### ISSUE TITLE
Harita kütüphanesi?

### ISSUE THREAD

**Issue by ozcanzaferayan** [acikkaynak/deprem-yardim-frontend#1]
Iki farkli çözüm var isteginize gore birini secebiliriz
Sadece Google haritalar için şunun gibi bir kütüphane var:
https://www.npmjs.com/package/google-map-react

Birden fazla harita desteklemek istiyorsak şunu kullanabiliriz:
https://react-leaflet.js.org/

**Comment by originalai** [comment]
Tasarimlar leaflet uzerinden ilerliyor.

**Comment by khnbzkrt** [comment]
https://leafletjs.com/download.html
