### ISSUE TITLE
storybook entegrasyonu

### ISSUE THREAD

**Issue by ozcanzaferayan** [acikkaynak/deprem-yardim-frontend#10]

**Comment by ozcanzaferayan** [comment]
https://github.com/muum/storybook-for-component-library

**Comment by 0fatihyildiz** [comment]
Gerek varmı ?

**Comment by SafaElmali** [comment]
Zaman kaybı olarak geliyor bana. Bir UI Library entegre edilip geçilebilir.

**Comment by serhhan** [comment]
bu kadar acil ve hızlı reaksiyon alınması gereken bir şey durumda storybook taskı oluşturmaya vakit harcamaya bile gerek yok...

**Comment by ozcanzaferayan** [comment]
Tamamdır close ediyorum
