### ISSUE TITLE
bug:  AfetHarita - Javascript Error on "Found } that I can't handle at line 0:350"

### ISSUE THREAD

**Issue by utkubenli** [acikkaynak/deprem-yardim-frontend#1004]
## Bug Definition
A Javascript error with no apparent visible impact is seen on the console. Does not directly have a functional error tied to it. 

-- Please add discord contact information
** discord username: @utkubenli#4662 **

## Severity
Low

## Bug environment
rc.afetharita.com
afetharita.com

## Describe how you are producing the bug step by step

1. Go to 'https://afetharita.com/en' on Google Chrome
2. Open Developer Tools and check the console in order to observe the javascript error.

full log: 
Error: Found } that I can't handle at line 0:350
    at e (519-8ef9091c3e409173.js:28:111912)
    at e.exports.parse (519-8ef9091c3e409173.js:28:112203)
    at e.exports.parse (519-8ef9091c3e409173.js:28:105951)
    at index-5ffc70b3840e754d.js:1:41987
    at Array.map (<anonymous>)
    at Object.onSuccess (index-5ffc70b3840e754d.js:1:41950)
    at 519-8ef9091c3e409173.js:28:177712

## Expected Behaviour
We should not have any Javascript errors on the Console

## Screen shots
https://prnt.sc/afvX2F0Wesnk 

## Desktop Information
- Operating System: Windows 10
- Browser Google Chrome
- Version 109.0.5414.120

## Mobile Phone Information
-

**Comment by puskuruk** [comment]
The problem is malformed data comes from backend.

**Comment by nejatcanunlu** [comment]
This was discussed with the backend team and the malformed data will be removed.

**Comment by utkubenli** [comment]
@nejatcanunlu Can you share the Issue ID on backend side so that we can track when the fix comes in. Checking RC environment I am still seeing this issue so I am guessing backend team has not deployed the fix yet.
