### ISSUE TITLE
bug: User can not interact with markers to the right and left of Disclosure Footer pop up until disclosure is dismissed

### ISSUE THREAD

**Issue by utkubenli** [acikkaynak/deprem-yardim-frontend#1005]
## Bug Definition
Red disclosure/disclaimer pop up appears when the user lands on afetharita.com. While this disclaimer is visible:

- User **can not** click and open pins right and left of the banner across the browser (y coordinates within the boundary height of the disclaimer box). You can clearly see the Disclosure box element `footer class="FooterBanner_footer__pXKYQ" ` extends to the edge of the browser.
- User **can** click and open pins above and below the banner at any x coordinate as long as the y is above or below the footer banner y coordinates.

Once the disclosure is dismissed user can interact with any markers

-- Please add discord contact information
** discord username: @utkubenli#4662**

## Severity
Medium

## Bug environment

Describe the environment produces the bug. For example:
rc.afetharita.com
afetharita.com
## Describe how you are producing the bug step by step

1. Go to 'afetharita.com'
2. Wait for the red disclaimer pop up to appear 
3. Hover over around the disclaimer and attempt to click on markers above, at same height and below the disclaimer either to the right or left of the Disclosure box.

## Expected Behaviour
User should not be obstructed from clicking around the Disclaimer banner. 

## Screen shots
https://www.hizliresim.com/byip8kl
https://www.hizliresim.com/802jwfy

## Desktop Information
- Operating System: Win10 
- Browser Google Chrome
- Version 110.0.5481.78

## Mobile Phone Information
Not tested 

## Additional Context
NA

**Comment by CyhnYldz** [comment]
Fixed in RC and Prod. 👍

**Comment by utkubenli** [comment]
Closing as fixed
