### ISSUE TITLE
bug: Wrong remaining time implementation on `ScanAreaButton.tsx`

### ISSUE THREAD

**Issue by puskuruk** [acikkaynak/deprem-yardim-frontend#1006]
## Bug Definition

https://user-images.githubusercontent.com/22892227/218948710-7f5c02cd-bf0d-4f28-ba78-437f0a56f80f.mov

The problem comes from the line  22. When you mount a react hook in multiple files/components they'll have independent states.
<img width="560" alt="Screenshot 2023-02-15 at 09 10 48" src="https://user-images.githubusercontent.com/22892227/218946853-52dd3c07-fcd2-4e72-87d6-c0c569e4fcc5.png">

-- Please add discord contact information
** discord username: @puskuruk  **

## Bug environment
rc.afetharita.com

**Comment by CyhnYldz** [comment]
We checked this;
When we click the scan button we sow that the timer do not rest but the system sends the request.
