### ISSUE TITLE
feat: make the reason category more visible on drawer

### ISSUE THREAD

**Issue by mucahitgurbuz** [acikkaynak/deprem-yardim-frontend#1010]
## Define your request
When I selected multiple categories on the top-right selector, I couldn't identify which category a specific pin belonged to. There is no indicator on the pin, drawer, etc. right now which makes the data meaningless.
We might display the `reason` data (erzak,barinma,giysi etc.) we received from the backend into the drawer. 

**discord username: justinhoyte#1478**

## Define the alternatives you have in mind
We can also show different pin images for different reason categories.

## Extra context
You can see in the ss below that after I clicked a pin, there is no info anywhere about the reason category.
<img width="1511" alt="Screenshot 2023-02-15 at 11 49 46" src="https://user-images.githubusercontent.com/22075688/219011376-edfa1637-002b-4874-b1ce-dcbec58ae653.png">

**Comment by usirin** [comment]
there will be a design refresh very soon, this will be addressed differently there.
