### ISSUE TITLE
refactor: EN translation doen't work for left pop-up menu

### ISSUE THREAD

**Issue by selman-keskin** [acikkaynak/deprem-yardim-frontend#1044]
### Refactor Request

** discord username: selmankeskin
EN tranlation doesn't work for left pop-up menu, it is useful for non-turkish speakers

afetharita.com

**Comment by akifunal** [comment]
![image](https://user-images.githubusercontent.com/37534146/219719628-7276135f-ff45-4256-9b15-ff46cd28315b.png)
![image](https://user-images.githubusercontent.com/37534146/219719739-019f71d7-9f54-4247-aae0-10f444ad3e81.png)

**Comment by oguzergul** [comment]
Feed contents are not entered manually. Therefore, we do not have a chance to add English versions of them. In addition, this data is currently not available in the system. So I'm closing this issue.
