### ISSUE TITLE
bug: Service clusters and aid clusters appear in the same shades of colour.

### ISSUE THREAD

**Issue by cenasis-ali-adiguzel** [acikkaynak/deprem-yardim-frontend#1047]
## Bug Definition
If, for example, hot meal layer enables when wreckage filter selected these clusters appear same shades of color.

-- **discord username: Exalted#4261**

## Bug environment
rc.afetharita.com
afetharita.com

## Describe how you are producing the bug step by step
1. Go to [afetharita.com](afetharita.com) or [rc.afetharita.com](rc.afetharita.com)
2. Select only wreckage filters and enable hot meal layer 
3. Zoom into an specific area 
4. Bug appears

## Expected Behaviour
Service clusters and aid clusters must appear in different shades of colour. The fact that they appear in different colours at first glance makes it easier to find the desired things.

## Screen shots
![image](https://user-images.githubusercontent.com/97669330/219447756-d106351d-099d-406f-acc0-ea2b6ba88873.png)
![image](https://user-images.githubusercontent.com/97669330/219447840-3864e05f-84b1-463b-8920-aeccb17946d9.png)

## Desktop Information
- Operating System: Windows 11
- Browser: Edge
- Version: 22H2

## Mobile Phone Information
- Devıce: OnePlus 5
- Operating System Android 9.0
- Browser: Opera

## Additional Context
Service clusters may appear shades of green or blue.

**Comment by Ogunk** [comment]
Bug also appeared in Google Chrome, Windows 10

I have a fix ready for this if interested

**Comment by oguzergul** [comment]
@handekaratas96 @senapalaa @sevilayerkan @canerakin111 is this a bug? 

We are setting clusters for the density of an area not to distinguish different layers. Also, the new design has not any different layers.

**Comment by handekaratas96** [comment]
@oguzergul yes, we can close this issue :)
