### ISSUE TITLE
bug: Left pane menu moves out of the screen and user cannot use the menu when the user slide the page at the bottom of the page

### ISSUE THREAD

**Issue by HarunRAltun** [acikkaynak/deprem-yardim-frontend#1058]
## Bug Definition
Left pane menu moves out of the screen and the user cannot use the menu when the user slide the page at the bottom of the page.

-- Please add discord contact information
** discord username: Aaron68#5600 **

## Bug environment
afetharita.com
## Describe how you are producing the bug step by step

1. Go to 'afetharita.com'
2. Slide the page up at the bottom of the page 
3. Bug appears

## Expected Behaviour
THe left pane menu should be visible when the user slide the page up from at the bottom of the page.

## Screen shots
![IMG_8307](https://user-images.githubusercontent.com/47951202/219709260-4f8b40bd-137c-4eb9-ac13-200a1b092472.jpg)

## Desktop Information
- Operating System: [for example iOS]
- Browser [for example, safari]
- Version [for example 22]

## Mobile Phone Information
- Devıce: iPhone13 Pro Max]
- Operating System (with the version): iOS 15.6.1
- Version Chrome
- Browser Version 110.0.5481.83

## Additional Context
Add any other context about the bug here

**Comment by myagizmaktav** [comment]
I don't think this is a bug, as I've tried it on other sites using Safari. It appears to be a feature added by Safari developers to provide additional sliding effects as feedback when a page has finished.

**Comment by HarunRAltun** [comment]
It is reproducible on Chrome as well and not looks like a feature coz user cannot use it any more after it moves up.
![image](https://user-images.githubusercontent.com/47951202/219765880-3b27ac8c-1224-4cc8-b66d-8658355677e7.png)

**Comment by myagizmaktav** [comment]
Errors video.

https://cdn.discordapp.com/attachments/1076220638068482048/1076221073886019676/VIDEO-2023-02-17-18-27-43.mov

**Comment by oguzergul** [comment]
PS: I have tried this issue and reproduced it on iPhone 11, It happens if you slide from the left bottom corner. Zoom "+" and "-" buttons are hiding. Not happened at Samsun A70 and iPhone 8 Plus.
