### ISSUE TITLE
bug: Notification Time Incorrect Calculation

### ISSUE THREAD

**Issue by canerakin111** [acikkaynak/deprem-yardim-frontend#1073]
## Bug Definition
Notify time calculation is completely incorrect. Also Notify time label should be notification time.

The script below should be fixed.
https://github.com/acikkaynak/deprem-yardim-frontend/blob/f4bec085f9387896d0dcf17dc0945b1b3cee1c32/utils/date.ts

-- Please add discord contact information
** discord username: @brokenbean**

## Bug environment
afetharita.com

## Describe how you are producing the bug step by step
![image](https://user-images.githubusercontent.com/35246326/218630987-e86a6a2e-2ceb-4175-b631-b47daf43c0af.png)

### **For Troubleshooting:**
https://apigo.afetharita.com/feeds/1592555
https://twitter.com/Yobazsol/status/1627380786935525383

## Expected Behaviour
- [ ] The date calculation is fixed and now displays the correct date.
- [ ] The label "Notify time" is changed to "Notification time" throughout the relevant system or documentation.
- [ ] The change is made in all applicable languages and translations.

## Screen shots
![image](https://user-images.githubusercontent.com/35246326/218630987-e86a6a2e-2ceb-4175-b631-b47daf43c0af.png)

**Comment by canerakin111** [comment]
@isaozler is reviewing to make sure that this issue exists for other examples.

**Comment by isaozler** [comment]
![image](https://user-images.githubusercontent.com/1378630/219983131-4f4fecf6-14d0-47e9-8345-bf4a0d9b9c3d.png)

I aligned with @oguzergul on this, but in case it's not clear, please do reach out 👍
