### ISSUE TITLE
refactor: petal map harita isteği

### ISSUE THREAD

**Issue by sercangoger** [acikkaynak/deprem-yardim-frontend#1074]
harita da herhangi bir pine tıklandıgında google harita,apple harita gibi seçenekler cıkmaktadır bunun yanında huawei telefonlar için

https://www.petalmaps.com/

petal map haritasınında koyulması gerekmektedir.
petal map huawei telefonların kullanmış olduğu bir navigasyon haritalama sistemidir.
huawei telefonlar için google servisleri problem olabilmekte ve sahada huawei telefonu olan bir kazazede için bu durumuda düşünülmesi gerekmektedir.
ekleme yapılması gerekmektedir.

**Comment by usirin** [comment]
Closing this as we are not taking in any feature requests from this repository. Please use https://github.com/acikkaynak/afetharita-roadmap for feature requests.
