### ISSUE TITLE
refactor:  yandex map seçeneği ekleme talebi

### ISSUE THREAD

**Issue by sercangoger** [acikkaynak/deprem-yardim-frontend#1075]
harita da bir pine tıklandıığında cıkan harita seçenekleri yanında yandex haritalama da konulması önemli olabilir. çünkü google navigasyon hizmetine alternatif olarak seçilmesi çok görülmektedir. bu yüzden ekleme yapılabilir:

https://yandex.com.tr/harita/115709/esenler/?ll=28.882174%2C41.038018&z=12

**Comment by usirin** [comment]
Closing this as we are not taking in any feature requests from this repository. Please use https://github.com/acikkaynak/afetharita-roadmap for feature requests.
