### ISSUE TITLE
feat: we need to manage our local-storage implementations.

### ISSUE THREAD

**Issue by oguzergul** [acikkaynak/deprem-yardim-frontend#1076]
## Define your request
Could you define the feature you're requesting clearly and briefly?

We need to know what should be stored at local storage. And how should it be?

-- fill in the line below:
** discord username: @afetharita#0001 **

## Define the alternatives you have in mind
Could you provide a clear and brief explanation to any alternative solution or feature you have in mind?

## Extra context
Could you add some extra context or screenshot about that feature request?

**Comment by usirin** [comment]
Let's reopen this as improvement again, but i am closing all improvements tickets for our emergency situation right now.
