### ISSUE TITLE
bug: Can't click scan field button when map layer window is open

### ISSUE THREAD

**Issue by CyhnYldz** [acikkaynak/deprem-yardim-frontend#1094]
## Bug Definition
Can't click scan field button when map layer window is open

-- Please add discord contact information
** discord username: @afetharita#0001 **

## Bug environment
Describe the environment produces the bug. For example:
rc.afetharita.com

## Describe how you are producing the bug step by step

1. Go to '..RC.'rc.afetharita.com
2. Click map layer button
3. Click to scan field button
4. Bug appears

## Expected Behaviour
map layers should be closed and scan layer shold be clickable

## Screen shots
If possible, add screenshots to describe your bug.

## Desktop Information
- Operating System: Windows 10
- Browser chrome
- Version 110.0.5481.97 (Resmi Derleme) (64 bit) Sürümü

## Mobile Phone Information
- Devıce: [for example iPhone6]
- Operating System (with the version): [for example iOS8.1]
- Version [for example default browser, safari]
- Browser Version [for example 22]

## Additional Context
Add any other context about the bug here

**Comment by dopplerDistortion** [comment]
on it
