### ISSUE TITLE
bug: 'Map details' can't be seen on mobile 

### ISSUE THREAD

**Issue by sevilayerkan** [acikkaynak/deprem-yardim-frontend#1096]
## Bug Definition
A clear and short text to decribe the bug.
'Map details' can't be seen on mobile, can not be scrolled as seen in screenshot.

-- Please add discord contact information
** discord username: `notDepresseDeveloper#0919` **

## Bug environment
rc.afetharita.com

## Describe how you are producing the bug step by step

1. Go to 'rc.afetharita.com' on mobile
2. Click to see Map details ' 
3. Bug appears

## Expected Behaviour
A clear and short text to decribe the expected behaviour.
Map details section should be scrollable and be seen

## Screen shots
If possible, add screenshots to describe your bug.
![image](https://user-images.githubusercontent.com/22706692/220208319-462f0e40-3438-4389-81b9-84a1b344b70b.png)

## Mobile Phone Information
- Devıce: iPhone 7plus 15.6.1
- Operating System (with the version): 15.6.1
- Version [for example default browser, safari]
- Browser Version [for example 22]

## Additional Context
Add any other context about the bug here

**Comment by dopplerDistortion** [comment]
on it
