### ISSUE TITLE
feat: grouping categories under reason filters 

### ISSUE THREAD

**Issue by eraygundogmus** [acikkaynak/deprem-yardim-frontend#1097]
It'd be great if we could group filters by category.

<img width="307" alt="Screen Shot 2023-02-21 at 01 39 28" src="https://user-images.githubusercontent.com/74984741/220208329-a55dd522-9321-4b1f-9bbd-9d2331604f00.png">

**Comment by nazdezar** [comment]
This was part of the original scope, so I am marking this as a bug/defect.

**Comment by usirin** [comment]
Let's reopen this as improvement again, but i am closing all improvements tickets for our emergency situation right now.
