### ISSUE TITLE
bug: Incorrect Filtering - Resource/Aid Markers show under "Enkaz" Filter

### ISSUE THREAD

**Issue by nazdezar** [acikkaynak/deprem-yardim-frontend#1098]
## Bug Definition
When "Enkaz" is the only selection on the map (rc.afetharita.com), other markers related to resource/aid are also present. Incorrect filtering.

-- Please add discord contact information
** discord username: @nazdezar  **

## Bug environment
rc.afetharita.com
https://rc.afetharita.com/?lat=36.26727971060079&lng=36.57910823822022&zoom=16&id=1592421&reasons=enkaz

See screenshot:

1. Go to ' Hizmetler > Select only ENKAZ', Go to Reyhanli/Hatay
See screenshot
![Reyhanli](https://user-images.githubusercontent.com/124920405/220209063-c1d3e906-4b19-439a-a6ab-7c7802db52ca.png)

## Expected Behaviour
A clear and short text to decribe the expected behaviour.

## Screen shots
If possible, add screenshots to describe your bug.

## Desktop Information
- Operating System: [for example iOS]
- Browser [for example, safari]
- Version [for example 22]

## Mobile Phone Information
- Devıce: [for example iPhone6]
- Operating System (with the version): [for example iOS8.1]
- Version [for example default browser, safari]
- Browser Version [for example 22]

## Additional Context
Add any other context about the bug here

**Comment by mertkaya1033** [comment]
#1095 Fixes this issue

**Comment by mertkaya1033** [comment]
Fixes:
- #1095 Fixes the issue where deselecting a filter did not update the map
- #1111 Fixes the issue where some of the data not being fetched (like enkaz)
