### ISSUE TITLE
bug: Unable to navigate to tweet sources

### ISSUE THREAD

**Issue by sevilayerkan** [acikkaynak/deprem-yardim-frontend#1099]
## Bug Definition
Unable to navigate to tweet sources. When we click on the source button, it redirects to the "https://twitter.com/anyuser/status/null" link.

-- Please add discord contact information
** discord username: `notDepresseDeveloper#0919` **

## Bug environment
rc.afetharita.com

## Describe how you are producing the bug step by step

1. Go to rc.afetharita.com
2. Click and look one of the pin details
3. Try to go one of the tweets
4. Bug appears

## Expected Behaviour
A clear and short text to decribe the expected behaviour.

## Screen shots
![image](https://user-images.githubusercontent.com/22706692/220209464-8d68252d-e65f-4063-a21d-20d9758227d9.png)

## Desktop Information
- Operating System: Windows 10
- Browser: Chrome
- Version [for example 22]

## Mobile Phone Information
- Devıce: [for example iPhone6]
- Operating System (with the version): [for example iOS8.1]
- Version [for example default browser, safari]
- Browser Version [for example 22]

## Additional Context
Add any other context about the bug here

**Comment by MaksuCode** [comment]
I believe the reason might be backend related since there is no twitter_id data on the response. Please check the screen shot below.

![image](https://user-images.githubusercontent.com/60291378/220210274-62ba1ae4-c0ac-4ab7-b5d3-3f0f7fa107f2.png)

**Comment by MaksuCode** [comment]
![image](https://user-images.githubusercontent.com/60291378/220211608-d0280dbe-ca89-4028-a2d2-cba00d82e3c6.png)

**Comment by usirin** [comment]
- [ ] TODO: don't show "source" button if `tweet_id` is null
