### ISSUE TITLE
bug: No data with custom filters when the browser refreshed

### ISSUE THREAD

**Issue by sercanerhan** [acikkaynak/deprem-yardim-frontend#1102]
## Bug Definition
> A clear and short text to decribe the bug.

When refreshing the browser or accessing a shared Afet Harita link with a custom filter, the locations of victims and heatmaps are not displayed.

> Please add discord contact information

** discord username: @sercanerhan#0543 **

## Bug environment
Describe the environment produces the bug. For example:
[x] rc.afetharita.com
[ ] afetharita.com
## Describe how you are producing the bug step by step

1. Go to the [link](https://rc.afetharita.com/?zoom=16&reasons=bar%C4%B1nma%2Cenkaz%2Cerzak&lat=36.2041913777133&lng=36.159278154373176)
2. Ensure the the Markers & Heatmap is enabled 
4. Bug appears

**Alternative method**
1. Go to RC
2. Zoom to a location where at least a clear `marker` is visible
3. Change filter for the `services` and enable only one of them
4. refresh the browser
5. bug appears

## Expected Behaviour
A clear and short text to decribe the expected behaviour.

## Screen shots
> If possible, add screenshots to describe your bug.
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/3420568/220209456-90409092-05f9-4353-843e-95b5fb8ca91b.png">

![ezgif com-resize](https://user-images.githubusercontent.com/3420568/220210424-68746c4e-227a-4f5f-aa3d-2e54867978be.gif)

## Desktop Information
- Operating System: MacOS
- Browser: Firefox
- Version: 110.0
 
## Mobile Phone Information
- Devıce: [for example iPhone6]
- Operating System (with the version): [for example iOS8.1]
- Version [for example default browser, safari]
- Browser Version [for example 22]

## Additional Context
Add any other context about the bug here

**Comment by fdemir** [comment]
it seems an expected behavior. Should be tested.

**Comment by usirin** [comment]
@sercanerhan can you retest this, i have a feeling this might be invalid after data fixes

**Comment by sercanerhan** [comment]
@usirin still same...

**Comment by usirin** [comment]
probably not fixed but, we made another deployment to rc with #1146

**Comment by oguzergul** [comment]
this works @sercanerhan approved. i am closing.
