### ISSUE TITLE
bug: Filter window problems

### ISSUE THREAD

**Issue by CyhnYldz** [acikkaynak/deprem-yardim-frontend#1103]
## Bug Definition
page starts default services window open. also if you don't close map layers or manual or service filters manulally they won't close

-- Please add discord contact information
** discord username: @afetharita#0001 **

## Bug environment
Describe the environment produces the bug. For example:
rc.afetharita.com

## Describe how you are producing the bug step by step

1. Go to '.RC.'rc.afetharita.com
2. Bug appears

1. Go to '.RC.'rc.afetharita.com
2. Open maplayers
3. open manual
4. open service filters
5. Bug appears

## Expected Behaviour
A clear and short text to decribe the expected behaviour.

## Screen shots
If possible, add screenshots to describe your bug.
![Ekran görüntüsü 2023-02-21 015420](https://user-images.githubusercontent.com/111140617/220210278-d9ca28e3-4147-4153-b64a-11482d429d0f.png)
## Desktop Information
- Operating System: Windows 10
- Browser chrome
- Version 110.0.5481.97 (Resmi Derleme) (64 bit) Sürümü

## Mobile Phone Information
- Devıce: [for example iPhone6]
- Operating System (with the version): [for example iOS8.1]
- Version [for example default browser, safari]
- Browser Version [for example 22]

## Additional Context
Add any other context about the bug here

**Comment by fdemir** [comment]
what is the excepted behaviour of this bug? i could not really understand it.

**Comment by CyhnYldz** [comment]
the filter windows should close automatically when you click toanother filter or button

**Comment by usirin** [comment]
this seems to be fixed, @CyhnYldz you can reopen if it still exists
