### ISSUE TITLE
bug: Filters not working without page refresh

### ISSUE THREAD

**Issue by CyhnYldz** [acikkaynak/deprem-yardim-frontend#1106]
## Bug Definition
Filters not working without page refresh

-- Please add discord contact information
** discord username: @afetharita#0001 **

## Bug environment
Describe the environment produces the bug. For example:
rc.afetharita.com

## Describe how you are producing the bug step by step

1. Go to 'RC...'rc.afetharita.com
2. change the service filters
3. close the filters even if you click scan area button 
4. Bug appears

## Expected Behaviour
map refresh according to new filter combination or selection

## Screen shots
If possible, add screenshots to describe your bug.

## Desktop Information
- Operating System: windows 10
- Browser chrome
- Version 110.0.5481.97 (Resmi Derleme) (64 bit) Sürümü

## Mobile Phone Information
- Devıce: [for example iPhone6]
- Operating System (with the version): [for example iOS8.1]
- Version [for example default browser, safari]
- Browser Version [for example 22]

## Additional Context
Add any other context about the bug here

**Comment by fdemir** [comment]
cannot reproduce?

**Comment by usirin** [comment]
cannot repro, please reopen if it exists. i validated it by turning off and on all reasons.
