### ISSUE TITLE
feat: User guide

### ISSUE THREAD

**Issue by eraygundogmus** [acikkaynak/deprem-yardim-frontend#1109]
### Discussed in https://github.com/acikkaynak/deprem-yardim-frontend/discussions/832

<div type='discussions-op-text'>

<sup>Originally posted by **maliksenpai** February  8, 2023</sup>
## Define your request
It seems like a small information box is needed so that users can navigate the page more easily and understand the application better. Therefore, this information box was designed and coded within the team for this.

## Define the alternatives you have evaluated
The best way to inform the user without disturbing can be the information box.

## Additional Context
Screenshot:

![image](https://user-images.githubusercontent.com/37189443/217599854-60fa825e-2edf-4eee-8f21-c0b061a32bf6.png)

</div>

**Comment by handekaratas96** [comment]
This document should be added as the user guide 
TR & EN texts are in the document 

https://docs.google.com/document/d/1RJ1rP2VEUGP6jBM_S1E1FijcGfWWgCGZ10eMQK4usSE/edit

@usirin

**Comment by usirin** [comment]
Fixed with #1128
