### ISSUE TITLE
bug: When Enkaz is selected, no Markers are Present on the Map

### ISSUE THREAD

**Issue by nazdezar** [acikkaynak/deprem-yardim-frontend#1112]
## Bug Definition
A clear and short text to decribe the bug.

-- Please add discord contact information
** discord username: @afetharita#0001 **

## Bug environment
Describe the environment produces the bug. For example:
rc.afetharita.com

1. Go to 'rc.afetharita.com'
2. Select Enkaz ONLY, Click on Scan
4. Bug appears

## Expected Behaviour
We should see the markers for Enkaz. 

## Screen shots
![image](https://user-images.githubusercontent.com/124920405/220212680-53eab3d4-15a6-41e2-8098-51d4b851e137.png)

## Desktop Information
- Operating System: [for example iOS]
- Browser [for example, safari]
- Version [for example 22]

## Mobile Phone Information
- Devıce: [for example iPhone6]
- Operating System (with the version): [for example iOS8.1]
- Version [for example default browser, safari]
- Browser Version [for example 22]

## Additional Context
Add any other context about the bug here

**Comment by nazdezar** [comment]
This is coming as "Kurtarma" instead of Enkaz. Should we remove this filter?

**Comment by usirin** [comment]
Gonna be fixed by #1124 

@nazdezar let's reopen this if it still happens after we send that change
