### ISSUE TITLE
bug: Duplicate in service filter

### ISSUE THREAD

**Issue by CyhnYldz** [acikkaynak/deprem-yardim-frontend#1113]
## Bug Definition
Duplicate in service filter -> "ISINMA"

-- Please add discord contact information
** discord username: @afetharita#0001 **

## Bug environment
Describe the environment produces the bug. For example:
rc.afetharita.com

## Describe how you are producing the bug step by step

1. Go to '.RC..'rc.afetharita.com
2. Open Service filters
3. you can see double ISINMA

## Expected Behaviour
A clear and short text to decribe the expected behaviour.

## Screen shots
If possible, add screenshots to describe your bug.

## Desktop Information
- Operating System: Windows 10
- Browser chrome
- Version 110.0.5481.97 (Resmi Derleme) (64 bit) Sürümü

## Mobile Phone Information
- Devıce: [for example iPhone6]
- Operating System (with the version): [for example iOS8.1]
- Version [for example default browser, safari]
- Browser Version [for example 22]

## Additional Context
Add any other context about the bug here

**Comment by nazdezar** [comment]
@CyhnYldz @usirin it looks like this is a duplicate #1142 which already has a PR. We can close this as duplicate.
