### ISSUE TITLE
bug: Incorrect request reason name

### ISSUE THREAD

**Issue by sevilayerkan** [acikkaynak/deprem-yardim-frontend#1115]
## Bug Definition
The reason name in the outgoing request is incorrect and does not return data. For example: barinma instead of barınma

Example for not working: https://rc.afetharita.com/en?zoom=15&id=1596464&reasons=bar%C4%B1nma&lat=36.26432709604922&lng=36.57073974609376

Working example: https://rc.afetharita.com/en?zoom=15&id=1596464&reasons=barinma&lat=36.26432709604922&lng=36.57073974609376

-- Please add discord contact information
** discord username: `notDepresseDeveloper#0919` **

## Bug environment
Describe the environment produces the bug. For example:
rc.afetharita.com

## Describe how you are producing the bug step by step

2. Click '....' 
3. Scroll to '....' 
4. Bug appears

## Expected Behaviour
A clear and short text to decribe the expected behaviour.

## Screen shots
![image](https://user-images.githubusercontent.com/22706692/220213686-a02f23e3-b7d4-43b4-854a-f6576d35ab0d.png)

## Desktop Information
- Operating System: [for example iOS]
- Browser [for example, safari]
- Version [for example 22]

## Mobile Phone Information
- Devıce: [for example iPhone6]
- Operating System (with the version): [for example iOS8.1]
- Version [for example default browser, safari]
- Browser Version [for example 22]

## Additional Context
Add any other context about the bug here

**Comment by sercanerhan** [comment]
here is the findings from @toooboring#1074
```
Hizmetlerdeki sorunlu parametreler:

barınma --> barinma olmalı
sağlık --> saglik olmalı

battaniye         --> apide karşılığı yok reason değil
elektrik          --> apide karşılığı yok reason değil
giyecek           --> apide karşılığı yok reason değil
giyim             --> apide karşılığı yok reason değil
gıda              --> apide karşılığı yok reason değil
hijyen            --> apide karşılığı yok reason değil
ilaç              --> apide karşılığı yok reason değil
ısınma            --> apide karşılığı yok reason değil
kefen             --> apide karşılığı yok reason değil
kişisel-bakım     --> apide karşılığı yok reason değil
kişisel-ihtiyaç   --> apide karşılığı yok reason değil
operatör          --> apide karşılığı yok reason değil
pet               --> apide karşılığı yok reason değil
teçhizat          --> apide karşılığı yok reason değil
ulaşım            --> apide karşılığı yok reason değil
yakıt             --> apide karşılığı yok reason değil
çadır             --> apide karşılığı yok reason değil
çocuk             --> apide karşılığı yok reason değil
çocuk ihtiyaçları --> apide karşılığı yok reason değil

Extralar:
Önemsiz --> Requestte ısınma parametresi 2 defa var.

Bulabildiğim çalışan tüm reason parametreleri:

kurtarma
alakasiz
barinma
elektronik
saglik
yemek
su
giysi
lojistik
yagma
enkaz
genel
yardim
guvenli-noktalar
hayvanlar-icin-tedavi
konaklama
erzak

```

**Comment by MaksuCode** [comment]
This is checked on feature branch. It looks good!
