### ISSUE TITLE
feat: Filter Categorization

### ISSUE THREAD

**Issue by sercanerhan** [acikkaynak/deprem-yardim-frontend#1124]
## Bug Definition
> A clear and short text to describe the bug.

I am sharing below how reasons should be positioned in filtering.

New data content is being sourced from social media, which contains either the location of the disaster victim or the location where aid is being requested. We will separate these into the following categories:

**Afetzede Bul**
* channel  -> teyit_enkaz
*reason -> enkaz ve / veya kurtarma ise Afetzede bul filtrelemesinde gelmeli 

**Yardım Talepleri**
* channel -> teyit_enkaz
* reason -> sağlık, hayvanlar için tedavi ise Yardım talepleri, sağlık filtrelemesinde gelmeli

* channel -> teyit_enkaz
* reason -> barınma, lojistik ise Yardım talepleri, barınma filtrelemesinde 

* channel -> teyit_enkaz
* reason -> yemek, su, erzak ise Yardım talepleri, yeme-içme filtrelemesinde 

* channel -> teyit_enkaz
* reason -> güvenli noktalar ise Yardım talepleri, güvenli noktalar filtrelemesinde 

* channel -> teyit_enkaz
* reason -> genel, yardım ise Yardım talepleri, genel filtrelemesinde 

Yardım taleplerinde "yağma" reason gelirse haritaya çekmeyelim

**Hizmetler**
* channel -> Hot Meal, Sahara Kitchen ve Ahbap 
* reason -> erzak, yemek ise Hizmetler yemek filtrelemesinde

* channel -> Hospitals, Eczane, Ahbap, Diyaliz merkezleri
* reason -> sağlık, yardım, hayvanlar için tedavi ise Hizmetler sağlık filtrelemesinde 

* channel -> Güvenli yerler ve oteller, Ahbap
*  reason -> barınma, konaklama ise Hizmetler barınma filtrelemesinde 

condition çok efor yüksek olursa yardım talepleri şu şekilde konumlandırılabilir: 
* channel -> teyit_enkaz
* reason -> enkaz ve kurtarma dışındakilerin tümü

**Other cases:**
## First Case
[EN] If the reason is teyit enkaz and a new reason is received (not present in the issue), help requests should be filtered based on the categorization in Figma under the 'Help Requests' section.
[TR]channel == teyit enkaz && yeni bir reason geliyorsa (bu issuedaki), yardım taleplerini altında figmadaki kategorizasyona göre filtelendirilmeli.   

## Second Case
[EN] If the channel is 'teyit enkaz' and a new reason is added that wasn't in the issues, it should be filtered under the services based on the categorization in Figma.
[TR] Eğer channel != teyit enkaz && yeni bir reason geliyorsa (bu issuedaki) figmadaki hizmetlere göre filtrelendirilmeli.

[Figma](https://www.figma.com/file/ndZkyLsSzpXtEbGGcBxyOa/Afetharita-filtre-yap%C4%B1s%C4%B1?node-id=1%3A121&t=r12Ia3xp8Re5Ev6H-4)

-- Please add discord contact information
** discord username: @Hande Karataş#6520**

## Desktop Information
- Operating System: [for example iOS]
- Browser [for example, safari]
- Version [for example 22]

## Mobile Phone Information
- Devıce: [for example iPhone6]
- Operating System (with the version): [for example iOS8.1]
- Version [for example default browser, safari]
- Browser Version [for example 22]

## Additional Context
Add any other context about the bug here

**Comment by handekaratas96** [comment]
Not to delay in filtering task, we can proceed without separating relief aid and services. Let's proceed as follows:

If the reason is wreckage (enkaz) or rescue (kurtarma) the content should be shown with the rescue help filter. Verified/social media should be discluded from the filter options

If the reason is not wreckage (enkaz) or rescue (kurtarma), then in the content should come under the filter "relief aid" in accordance with reason-category mapping in the figma-yardım talepleri part
relief aid use case: if I check "health" from the relief aid filter, I can see the tweets about needs for medicines and also the hospitals and vets...

@usirin @mertkaya1033
