### ISSUE TITLE
feat: showing the results for both wreckage & rescue together under the wreckage filter

### ISSUE THREAD

**Issue by handekaratas96** [acikkaynak/deprem-yardim-frontend#1125]
## Define your request
The results for both wreckage (enkaz) & rescue (kurtarma) should be shown together under the wreckage (enkaz) filter
It can also be at the top of the filters  

-- fill in the line below:
** discord username: @Hande Karataş#6520

**Comment by usirin** [comment]
Related to #1124, gonna be implemented with it.
