### ISSUE TITLE
bug: Previously viewed markers do not indicate viewed (grey marker)

### ISSUE THREAD

**Issue by utkubenli** [acikkaynak/deprem-yardim-frontend#1126]
## Bug Definition
Previously viewed markers used to become grey to indicate viewed

-- Please add discord contact information
** discord username: @utkubenli#4662**

## Bug environment
Describe the environment produces the bug. For example:
rc.afetharita.com

## Describe how you are producing the bug step by step

1. Go to 'rc.afetharita.com'
2. Click on one of the markers 
3. Click out of the marker and observe if the first selected marker changes color 

## Expected Behaviour
Markers should turn gray once user interacts with it once

## Desktop Information
- Operating System: Win 10
- Browser Chrome
- Version 109.0.5414.120

## Mobile Phone Information
- Devıce: iphone 7 plus
- Operating System (with the version): ios 15.6.1
- Version [for example default browser, safari]
- Browser Version [for example 22]

## Additional Context
Add any other context about the bug here

**Comment by sercanerhan** [comment]
verified in https://github.com/acikkaynak/deprem-yardim-frontend/pull/1165 👍
