### ISSUE TITLE
bug: The page remains blank when the map type is changed

### ISSUE THREAD

**Issue by sevilayerkan** [acikkaynak/deprem-yardim-frontend#1127]
## Bug Definition
The page remains blank when the map type is changed.

-- Please add discord contact information
** discord username: `notDepresseDeveloper#0919` **

## Bug environment
rc.afetharita.com

## Describe how you are producing the bug step by step

1. Go to rc.afetharita.com
2. Zoom out till you see whole Turkey (to about zoom 6.4)
3. Change map type 
4. Bug appears

## Expected Behaviour
A clear and short text to decribe the expected behaviour.

## Screen shots
If possible, add screenshots to describe your bug.
![image](https://user-images.githubusercontent.com/22706692/220215659-b4cfee8c-3006-4237-86fb-2e3b715a8a83.png)

## Desktop Information
- Operating System: [for example iOS]
- Browser [for example, safari]
- Version [for example 22]

## Mobile Phone Information
- Devıce: [for example iPhone6]
- Operating System (with the version): [for example iOS8.1]
- Version [for example default browser, safari]
- Browser Version [for example 22]

## Additional Context
Add any other context about the bug here

**Comment by MaksuCode** [comment]
**Steps to reproduce :** 

1 - Go to rc.afetharita with zoom=6.4 (The maximum zoom out)
2 - Change map type 

**Expected result :** Map is visible with the new map type
**Actual result :** Map is blank

**Comment by nazdezar** [comment]
The markers are present but the outline of the map is gone.
