### ISSUE TITLE
bug: Brave Phone mode breaks the map after zooming out

### ISSUE THREAD

**Issue by utkubenli** [acikkaynak/deprem-yardim-frontend#1132]
## Bug Definition
If user enables the mobile mode by ztrl+shift+m on brave browser map breaks and shows gray layout only

-- Please add discord contact information
** discord username: @utkubenli#4662**
 

## Bug environment
Describe the environment produces the bug. For example:
rc.afetharita.com

## Describe how you are producing the bug step by step

1. Go to 'rc.afetharita.com' on your brave browser
2. Zoom out to max
3. Start mobile mode by hitting ctrl+shift+m 
4. Bug appears

## Expected Behaviour
Mobile mode should function as normal on brave browser

## Screen shots
![image](https://user-images.githubusercontent.com/124810497/220217447-18d26448-bacb-419e-a1b7-cb33a82c0027.png)

## Desktop Information
- Operating System: Win10
- Browser Brave 
- Version  110.0.5481.104

**Comment by sercanerhan** [comment]
@utkubenli could you please retry this case? It should have been fixed.

**Comment by usirin** [comment]
Should be fixed by #1127 Please reopen if it exists.
