### ISSUE TITLE
bug: Double click on every element results in zoom in

### ISSUE THREAD

**Issue by MaksuCode** [acikkaynak/deprem-yardim-frontend#1136]
## Bug Definition
No matter where you click (be it a button, map type etc.) the page is zoomed in.

 discord username: Mustafa Aksu

## Bug environment

rc.afetharita.com

## Describe how you are producing the bug step by step

1. Go to rc.afetharita.com
2. Click a button TWICE (f.e : Scan button or literally anywhere on the page)

## Expected Behaviour
The page should NOT be zoomed in.

## Actual Behaviour
The page is zoomed in.

## Desktop Information
- Operating System : WINDOWS
- Browser : CHROME
- Version : latest

## Mobile Phone Information
- Devıce : [iPhone14
- Operating System (with the version): IOS v16.2
- Version :  SAFARI
- Browser Version :  latests

**Comment by fdemir** [comment]
expected behavior. did on purpose i think.

**Comment by usirin** [comment]
Fixed this issue for `scan area` button with #1162 

How important do we think the rest are?
