### ISSUE TITLE
bug: reason filter has some duplicate fields

### ISSUE THREAD

**Issue by andyanday33** [acikkaynak/deprem-yardim-frontend#1142]
## Bug Definition
Reason filter has some duplicate fields

-- Please add discord contact information
** discord username: @bumshaqalaqa#2973 **

## Bug environment
Describe the environment produces the bug. For example:
rc.afetharita.com
afetharita.com

## Screen shots
![Screenshot 2023-02-21 at 01 32 45](https://user-images.githubusercontent.com/31995815/220225393-71e96c44-50e0-4185-b9cf-79f4bd4149a7.png)

**Comment by nazdezar** [comment]
The duplicate entry (Isinma) is now removed. Currently, there is no data being returned which seems to be expected.

**Comment by andyanday33** [comment]
Resolved with #1140

**Comment by andyanday33** [comment]
Resolved with #1140
