### ISSUE TITLE
bug: language change control needs to include an icon and its text should disappear in mobile devices

### ISSUE THREAD

**Issue by mertkaya1033** [acikkaynak/deprem-yardim-frontend#1155]
## Bug Definition
Currently, the language change control component's text becomes unreadable in small devices in its closed state. It needs to include an icon and its text should disappear in small devices to fix this issue.

** discord username: Sertcast#8543**

## Bug environment
rc.afetharita.com

## Screen shots
How it is in RC:
![RC](https://user-images.githubusercontent.com/47050442/220269235-85924e21-5980-4abf-864f-ad315d8b16dc.png)

How the new design should look like:

- Mobile: ![mobile](https://user-images.githubusercontent.com/47050442/220269308-ad081e4f-9723-4fe6-b8f6-38051a0da202.png)
- Desktop: ![desktop](https://user-images.githubusercontent.com/47050442/220269311-ecbe754b-4761-42a3-ba45-62bb24333a10.png)

**Comment by usirin** [comment]
Fixed with #1171 ty so much @absolutezero13
