### ISSUE TITLE
refactor: replace default exports with named exports

### ISSUE THREAD

**Issue by usirin** [acikkaynak/deprem-yardim-frontend#1186]
This tweet says it all: https://twitter.com/eser/status/1628292587802054656

There is a eslint rule for this:

```
"rules": {
     "import/prefer-default-export": "off",
     ...
}
```

**Comment by absolutezero13** [comment]
Just curios, what is the reason behind this? I want to know if it's a the best practice.

Also I can take this, can you assign it to me?

**Comment by eraygundogmus** [comment]
@absolutezero13 it is because emir büyük yerden @eserozvataf
