### ISSUE TITLE
[Bug] safari web & mobile browserda harita görüntülenmiyor

### ISSUE THREAD

**Issue by bedirhanyildirim** [acikkaynak/deprem-yardim-frontend#119]
![image](https://user-images.githubusercontent.com/27918203/217099890-a47f81d0-289e-48c9-b419-d0bf96ea2948.png)

**Comment by muum** [comment]
@bedirhanyildirim tekrar test edebilir misin? Anlık bir şey gibi görünüyor. Chrome, Safari, Brave mobile / desktop testlerinde başarılı görünüyor.

**Comment by bedirhanyildirim** [comment]
Düzeldi @muum
