### ISSUE TITLE
bug: Legal attributes can't be seen on mobile

### ISSUE THREAD

**Issue by sevilayerkan** [acikkaynak/deprem-yardim-frontend#1193]
## Bug Definition
Legal attributes can't be seen on mobile devices. As we talked in pr #1172 

-- Please add discord contact information
** discord username: `notDepresseDeveloper#0919` **

## Bug environment
Describe the environment produces the bug. For example:
rc.afetharita.com
afetharita.com

## Describe how you are producing the bug step by step

1. Go to afetharita on mobile
2. Bug appears

## Expected Behaviour
A clear and short text to decribe the expected behaviour.

## Screen shots
If possible, add screenshots to describe your bug.

## Desktop Information
- Operating System: [for example iOS]
- Browser [for example, safari]
- Version [for example 22]

## Mobile Phone Information
- Devıce: [for example iPhone6]
- Operating System (with the version): [for example iOS8.1]
- Version [for example default browser, safari]
- Browser Version [for example 22]

## Additional Context
Add any other context about the bug here

**Comment by absolutezero13** [comment]
@sevilayerkan can you include a screenshot?
