### ISSUE TITLE
[Feature] Create TS Types for API Data

### ISSUE THREAD

**Issue by muum** [acikkaynak/deprem-yardim-frontend#120]

**Comment by ozcanzaferayan** [comment]
Abi selam vardı bu: 
https://github.com/acikkaynak/deprem-yardim-frontend/blob/main/mocks/types.ts

**Comment by onurkanbakirci** [comment]
Introduced in https://github.com/acikkaynak/deprem-yardim-frontend/pull/131/commits/473c077c86f79302e204d63cd8242392b235fbf3
