### ISSUE TITLE
[Bug] Cluster popup kapanmıyor

### ISSUE THREAD

**Issue by omer-ayhan** [acikkaynak/deprem-yardim-frontend#135]
<img width="524" alt="Screenshot 2023-02-07 at 02 51 48" src="https://user-images.githubusercontent.com/32736625/217113093-45388b6b-5368-492e-9dd1-f5ec99bfa04a.png">

**Comment by mucahitgurbuz** [comment]
@omer-ayhan sen mi ilgileniyorsun? yoksa ben bakayim mi?

**Comment by omer-ayhan** [comment]
> @omer-ayhan sen mi ilgileniyorsun? yoksa ben bakayim mi?

şu an ben ilgileniyorum

**Comment by ramazanyigit** [comment]
ClusterGroup'taki bugdan dolayi kapanmasini yapmamistim, eline saglik @omer-ayhan
