### ISSUE TITLE
Fix the Overlapping Issue on the CTA Button in Mobile

### ISSUE THREAD

**Issue by buraksakalli** [acikkaynak/deprem-yardim-frontend#156]
## Description

The issue at hand is that the banner component at the bottom is causing overlap with the call to action button, obstructing it from being properly visible and accessible to the user. The goal of this ticket is to resolve the overlap and ensure that the call to action button is clear and functional for all users.

### Device Details
Note 20
412x915

### Screenshot
![Screen Shot](https://user-images.githubusercontent.com/10114716/217173638-76d020c8-529c-4895-b731-9c243c0afef5.png)

**Comment by ysnbyzli** [comment]
I'm interested right away 🙋‍♂️

**Comment by buraksakalli** [comment]
@ysnbyzli,

Tesekkurler Yasin, biraz once PR olusturdum (https://github.com/acikkaynak/deprem-yardim-frontend/pull/159). Goz atabilir misin?
