### ISSUE TITLE
Evleri Yıkılanlar İçin Konaklama İmkanı Linki

### ISSUE THREAD

**Issue by coderserdar** [acikkaynak/deprem-yardim-frontend#158]
https://www.otelz.com/gecmisolsunturkiyem?fbclid=PAAaaBLy77gaam2hBFeWnuR8GOjOI7HOStgXmb7Hx-RsAFf9YJGcnYUr9tVCE

[Otelz.Com](https://www.otelz.com) yukarıdaki linki yayınlamış. Twitter üzerinden gördüm. AFAD Numaraları yazan bölümün altına ufak bir bölüm olarak bu link eklenebilirse, siteye giren evi oturulamayacak halde olan insanların en azından bir kısmının konaklama için böyle bir hizmet olduğunu görmeleri sağlanır diye düşünüyorum.
Sitede şehir şehir ücretsiz konaklama hizmeti veren otellerin iletişim bilgileri ve ne kadar oda ayrıldığının bilgileri mevcut

**Comment by ahmeterenodaci** [comment]
Konaklanabilir yerler, yemek dağıtımı yapılan yerler, sağlık müdahalesi yapılan yerler gibi konumlar direkt olarak harita üzerine eklenebilir belki. Bu sayede insanlar harita üzerinde kendisine en yakın olan yardım noktalarını görebilirler.

**Comment by coderserdar** [comment]
Ya da bunlar için ayrı bir site de hazırlanabilir. Vatandaşlarımızdan evsiz kalan depremzedeleri ağırlayabilecek olanlar da kendi adres vb. bilgilerini girerek katkıda bulunabilirler. Aslında üzerinde düşünürsek en faydalı yöntem hangisi olacaksa ona yönelebiliriz

**Comment by ismailgunayy** [comment]
Birkaç kişi böyle bir site hazırlamış: [afetbilgi.com](https://www.afetbilgi.com/)

[İlgili tweet](https://twitter.com/Keleesssss/status/1622855716410204160)
