### ISSUE TITLE
Toplanma alanları için

### ISSUE THREAD

**Issue by Xunders** [acikkaynak/deprem-yardim-frontend#162]
https://linkstap.com/toplanmaalanlari
Her ile özel toplanma alanları var.Bunu eklesek insanlar daha rahat ulaşır

**Comment by demirhancosku** [comment]
Bu bilgilerin güvenilirliği nedir @Xunders? Doğrulama yapmak ya da resmi kurumlardan talep etmek gerekiyor herhangi bir şekilde yaymaya başlamadan önce.

**Comment by Xunders** [comment]
@demirhancosku Kendine Müzisyenin drekt kendisi paylaşmış şekilde gördüm ben. Hatta komple paylaşım şekli bu ; https://linkstap.com/depremyardim
