### ISSUE TITLE
[Feature] All platform distributions

### ISSUE THREAD

**Issue by onurkanbakirci** [acikkaynak/deprem-yardim-frontend#167]
If this feature accepted, i can try to build ios and android app easily by using [capacitor](https://capacitorjs.com/) and mac, win, linux distributions by using [electron](https://www.electronjs.org/).

**Comment by eraygundogmus** [comment]
go for it :) let's try

**Comment by onurkanbakirci** [comment]
Can yo review [c75effa](https://github.com/acikkaynak/deprem-yardim-frontend/pull/181/commits/c75effa812434b67a12d293fa29b24f102b9d910)?

**Comment by onurkanbakirci** [comment]
Updates in [6cbc3d5](https://github.com/acikkaynak/deprem-yardim-frontend/pull/197/commits/6cbc3d514d082d3e61cb3c189e11b899751550d4)
