### ISSUE TITLE
[Bug] Sayfa açıldığında harita çok uzaktan gösteriyor

### ISSUE THREAD

**Issue by cihadturhan** [acikkaynak/deprem-yardim-frontend#170]
Sayfa açıldığında harita çok uzaktan gösteriyor. Onun yerine daha yakından başlatılabilir.
![image](https://user-images.githubusercontent.com/3739536/217219415-13cee7fc-647f-4389-9a6c-2813e3849bbf.png)

Leaflet'in initialZoom gibi bir parametresi vardı yanlış hatırlamıyorsam. Bulunca alta yorum olarak eklerim.

**Comment by cihadturhan** [comment]
Ok bu fix edilmiş. Kapatıyorum

**Comment by gokserpirik** [comment]
Ben farklı zamanlarda açışımda farklı sonuçlar alıyorum. İlk denememde zoom düzgünken ikincisinde çok uzakta olması gibi.
Kodda Map component için Zoom ./utils'de belirtilmiş. Sorun orada değil sanırım
