### ISSUE TITLE
[Bug] Footer overlapse with pins

### ISSUE THREAD

**Issue by bedirhanyildirim** [acikkaynak/deprem-yardim-frontend#175]
![image](https://user-images.githubusercontent.com/27918203/217233174-e5302aea-8ac4-46ef-865f-5f09a24b8ad8.png)

**Comment by bedirhanyildirim** [comment]
Üstünde çalışıyorum

**Comment by eraygundogmus** [comment]
@bedirhanyildirim mainin güncel halini çekebilir misin?

**Comment by bedirhanyildirim** [comment]
[pr 182](https://github.com/acikkaynak/deprem-yardim-frontend/pull/182)
