### ISSUE TITLE
Yardım butonu ekranın ortasına kayıyor, sağ altta olmalı

### ISSUE THREAD

**Issue by tyakar** [acikkaynak/deprem-yardim-frontend#178]
Iphone 13 
IOS 16.3
Chrome 

![WhatsApp Image 2023-02-07 at 14 40 22](https://user-images.githubusercontent.com/2902990/217235666-3df60f1f-c48f-4592-84a0-11bdb5edcaac.jpeg)

**Comment by krmyildizz** [comment]
Bütün mobillerde ortada gözüküyor bu bir problem değildir

**Comment by eraygundogmus** [comment]
issue approved.

**Comment by bedirhanyildirim** [comment]
düzelttim bunu [pr 182](https://github.com/acikkaynak/deprem-yardim-frontend/pull/182) ile

**Comment by bedirhanyildirim** [comment]
![Screenshot 2023-02-07 at 13 06 14](https://user-images.githubusercontent.com/27918203/217240541-411a8a16-b1cf-46df-b16b-1a8b25c7d666.png)
@eraygundogmus @tyakar

**Comment by krmyildizz** [comment]
Ben halletmiştim pr gönderdim

**Comment by krmyildizz** [comment]
Issue kapatabilirsiniz
