### ISSUE TITLE
"Google Haritaları ile Gör" butonuna tıkladığımızda "Google Map" uygulaması açılıyor ancak ilgili koordinata gitmiyor.

### ISSUE THREAD

**Issue by tyakar** [acikkaynak/deprem-yardim-frontend#179]
Iphone 13
IOS 16.3
Chrome

![WhatsApp Image 2023-02-07 at 14 40 54](https://user-images.githubusercontent.com/2902990/217235956-61f4e00e-5003-461b-b381-f7f6ce3a2bd1.jpeg)
![WhatsApp Image 2023-02-07 at 14 41 34](https://user-images.githubusercontent.com/2902990/217235986-2e35d933-f2ee-4503-9ad9-39b46aa6e722.jpeg)

**Comment by eraygundogmus** [comment]
![Uploading Screen Shot 2023-02-07 at 14.45.59.png…]()
gördüğüm kadarıyla yönlenmiş attığın fotoğrafta
