### ISSUE TITLE
Add date time to the drawer data 

### ISSUE THREAD

**Issue by cdagli** [acikkaynak/deprem-yardim-frontend#186]
<img width="333" alt="image" src="https://user-images.githubusercontent.com/7020369/217239472-d84a4f21-d947-4b37-bb90-a9fde5090f2d.png">

buraya bir date/time bilgisi eklemek faydali olacaktir diye dusunuyorum.

**Comment by T410** [comment]
Sanirim data/time datasinin backend tarafindan frontend'e iletilmesi lazim oncelikle

**Comment by alperencantez** [comment]
Component oluşturulurken date objesi oluşturulup kullanılabilir, uygunsa bu issue'u alabilirim.

**Comment by mertcanaltin** [comment]
> Component oluşturulurken date objesi oluşturulup kullanılabilir, uygunsa bu issue'u alabilirim.

burada datanın geliş zamanını almamız daha sağlıklı olucaktır

**Comment by cdagli** [comment]
@mertcanaltin backend tarafinda track edebilecegimiz bir issue var mi bunun icin? Nerede track ediyorlar bilmiyorum.

**Comment by T410** [comment]
sanirim https://github.com/acikkaynak/deprem-yardim-backend/issues

**Comment by mertcanaltin** [comment]
@cdagli @T410  Backend tarafında bir [issue](https://github.com/acikkaynak/deprem-yardim-backend/issues/60) oluşturdum

**Comment by eraygundogmus** [comment]
kapattım issue'yu, gerekirse tekrar açabilirsniz
