### ISSUE TITLE
[Feature] Drawer'a adres tarifi al butonu eklenmesi

### ISSUE THREAD

**Issue by mucahitgurbuz** [acikkaynak/deprem-yardim-frontend#188]
Bazı kullanıcılarımız bulunduğu güncel konumdan seçtiği marker'a adres tarifi almak isteyebilir. Bunun için gereken adımı ekstra bir buton ile kısaltabiliriz.

<img width="762" alt="Screenshot 2023-02-07 at 13 00 19" src="https://user-images.githubusercontent.com/22075688/217240297-a5b01757-f1fb-49e5-a70e-b0a3f16c2e5c.png">
<img width="1267" alt="Screenshot 2023-02-07 at 13 00 30" src="https://user-images.githubusercontent.com/22075688/217240362-21388e17-ef28-4b0f-8621-c2576c5848b4.png">

**Comment by mucahitgurbuz** [comment]
Kod hazır, makul bir iyileştirme ise PR açacağım.

**Comment by eraygundogmus** [comment]
@mucahitgurbuz mükemmel, açar mısın?

**Comment by eraygundogmus** [comment]
@mucahitgurbuz lütfen mobil görünümü de kontrol edersen güzel olur
