### ISSUE TITLE
Kahramanmaraş Merkez adresi girilirken seçilecek ilçe.

### ISSUE THREAD

**Issue by ossarac** [acikkaynak/deprem-yardim-frontend#192]
Selamlar. Söyle bir feedback geldi siteyi paylaştıklarımdan. Sayfadan 'Kahramanmaraş merkez' diye bildirilen yardım çağrılarını girmek istediklerinde ilçe listesinde 'Merkez' diye bir seçenek yok ve hangi ilçeyi seçmeleri gerektiğini bilemiyorlar.  Sanırım burası Kahramanmaraş için '12 Şubat' (Bunun doğruluğunu teyid etmek lazım).  Eğer doğruysa bu seçeneğin yanına parantez içinde (Merkez) yazılabilir mi kolaylık olması için.

**Comment by bedirhanyildirim** [comment]
@ossarac söylediğiniz issue bu proje ile alakalı değil ama gerekli arkadaşlara ilettim

**Comment by arzucaner** [comment]
Bu tespite katiliyorum. Ozellikle ilgili sehirde yasamayanlar icin bu ayrimi yapmak zor olabilir. 

Bu ornege ilaveten;

* Gaziantep icin (Sahinbey ve Sehitkamil) 
* Hatay (Antakya)
* Mersin (Akdeniz, Yenisehir, Toroslar, Mezitli)
* Adana (Cukurova, Seyhan, Yuregir)

Merkez adi altinda toplanabilir.

**Comment by ossarac** [comment]
> @ossarac söylediğiniz issue bu proje ile alakalı değil ama gerekli arkadaşlara ilettim

Çok teşekkürler

**Comment by ossarac** [comment]
Burada bunu kapatıp backend'de açıyorum.
