### ISSUE TITLE
Pin işlemleri

### ISSUE THREAD

**Issue by DavutDurgun** [acikkaynak/deprem-yardim-frontend#196]
Merhaba arkadaşlar,

**Pin**'lerin  ${\color{red}rengini}$  , item ${\color{orange}publis time }$'a göre belirleyebiliriz, bu vesileyle **öncelik** belirlemede yardımcı olur ekiplere.

**Yoğunluğu** ise, ${\color{green}background color}$ olarak ifade edebiliriz. Bu **daha anlaşılır** olacaktır. 

Bu fikir destek görürse bir an önce başlayabiliriz.

**Comment by eraygundogmus** [comment]
backendden publish time gelmiyor
