### ISSUE TITLE
Zoom butonu toolbar altinda kaliyor

### ISSUE THREAD

**Issue by cdagli** [acikkaynak/deprem-yardim-frontend#211]
Zoom + butonu toolbar altinda kaliyor 

Google chrome, IOS 

![image](https://user-images.githubusercontent.com/7020369/217273543-c23717e0-280f-475b-8036-078f2c9c74d3.png)

**Comment by ahmeterenodaci** [comment]
ben ilgileniyorum

**Comment by ahmeterenodaci** [comment]
düzeltildi kapanabilir

**Comment by ozcanzaferayan** [comment]
Düzelmiş kapatıyorum
![IMG_4867](https://user-images.githubusercontent.com/1326963/217332421-96513ee6-e416-4faa-8996-e51909902a5f.PNG)
