### ISSUE TITLE
Mobil kullanimda componentler kullanimi engelliyor

### ISSUE THREAD

**Issue by mtugrulesin** [acikkaynak/deprem-yardim-frontend#212]
Mobil kullanimda componentler kullanimi engelliyor. 

Zoom level arttirkca ihbarlari goremiyorum. Ekran ustu pop-up cok ortada. Bunun yerine bir ekran alti pop-menu olusturarak ihbar listesini ve tiklandiginda bilgilendirme pop-up' ini gosterebiliriz.

![afet](https://user-images.githubusercontent.com/24235691/217275142-bca84b06-7e99-494c-bf5e-7dee70a08a06.jpg)

**Comment by eraygundogmus** [comment]
ilgileniliyor, duplicate
