### ISSUE TITLE
Sayfa yuklenirken teknik aksaklik mesaji goruntuleniyor

### ISSUE THREAD

**Issue by cdagli** [acikkaynak/deprem-yardim-frontend#214]
Chrome 

<img width="533" alt="image" src="https://user-images.githubusercontent.com/7020369/217277858-ed60fdbf-6ca8-4527-a7fc-ed40c7993070.png">

**Comment by mtugrulesin** [comment]
Sistemi guncelliyorlar ara sira ondan kaynaklaniyor muhtemelen.

**Comment by cdagli** [comment]
Sebebi burada: https://github.com/acikkaynak/deprem-yardim-frontend/pull/209#issuecomment-1420905476 Muhtemelen bu PR ile fix edilir.
