### ISSUE TITLE
[Bug] Footer'daki duyuru kapandıktan sonra buton klonlanıyor.

### ISSUE THREAD

**Issue by uzanenis** [acikkaynak/deprem-yardim-frontend#217]
<img width="1440" alt="Screen Shot 2023-02-07 at 17 53 42" src="https://user-images.githubusercontent.com/73305571/217279653-da7ce6f4-d92f-4e2a-811c-fccce7751956.png">

**Comment by uzanenis** [comment]
Sanırım @hasanugr halletmiş

**Comment by canklot** [comment]
Production'da sorun devam ediyor. Fix deploy edildi mi?
