### ISSUE TITLE
Harita üzerindeki pinlerin konumları yanlış

### ISSUE THREAD

**Issue by can101** [acikkaynak/deprem-yardim-frontend#218]
Kontrol datası olup olmadığını belemiyorum ama harita üzerindeki bazı pinlerin konumları deprem bölgesinden farklı iller üzerinde yoğunlaşıyor gibi örnek olarak İstanbul olabilir.

[![image](https://user-images.githubusercontent.com/68447137/217279499-7453fb3c-64cb-4a28-adb1-eb117e725f77.png)](https://afetharita.com/)

Link üzerinden kontrol edebilirsiniz.

**Comment by can101** [comment]
yada tweet atan kullanıcın konumunu buluyoruz !

**Comment by cdagli** [comment]
Selam, backend kanalinda tartisiliyor bu konu: https://discord.com/channels/1072074800622739476/1072074897712492594 

Adresler OpenAI ile tespit edildigi icin hatali pinler mevcut.
