### ISSUE TITLE
Yardım butonu çift görünmesi

### ISSUE THREAD

**Issue by rgnyldz** [acikkaynak/deprem-yardim-frontend#223]
Kırmızı popup kapatıldıktan sonra yatayda yardım butonu çift görünüyor. 

Senaryo şöyle;
İlk açılışta buton dikeyde de yatayda da normal. Popup kapatıldığında dikeyde yine normal görünüyor ancak yataya geçildiğinde buton çift görünüyor. 

Cihaz: iphone 13

**Comment by shtwon** [comment]
![image](https://user-images.githubusercontent.com/98853577/217283818-c5486c8c-1a09-408d-b71f-5a1e571a398e.png)
![image](https://user-images.githubusercontent.com/98853577/217283874-9318fd21-5304-4516-b9ce-acc28bb1c483.png)
Masaüstünde de sorun aynı.

**Comment by rgnyldz** [comment]
https://user-images.githubusercontent.com/5630172/217284350-f27ab383-e81e-4acc-9fa3-ed022877c9de.MOV

**Comment by hasanugr** [comment]
Bu sorunu çözdük, bilginize. Kapatılabilir.
