### ISSUE TITLE
SEO - Search Engine Optimization

### ISSUE THREAD

**Issue by t3nGri** [acikkaynak/deprem-yardim-frontend#225]
İnsanların oluşturduğumuz datalara/sonuçlara Google'dan veya Arama motorlarından hızlıca ulaşabilmesi için SEO - Arama motoru optimizasyonu yapılması gerekiyor. Çalıştığım SEO şirketimle görüştüm tümüyle bu konuda destek vermeye hazırız.
Şirketim: holisticseo.digital

**Comment by cdagli** [comment]
Related: https://github.com/acikkaynak/deprem-yardim-projesi/issues/12

**Comment by eraygundogmus** [comment]
duplicate
