### ISSUE TITLE
Sayfanın ilk açılışındaki teknik uyarı

### ISSUE THREAD

**Issue by Ecancan** [acikkaynak/deprem-yardim-frontend#228]
Sayfa ilk açıldığında "Teknik bir aksaklık söz konusu. Sistem kısa zamanda devreye girecektir" şeklinde uyarı çıkmaktadır. Aslında loading süresi boyunca çıkıyor gibi gözükmekte. Api tarafından yanıt dönmektedir.

**Comment by cdagli** [comment]
@Ecancan  Sunun ile duplicate https://github.com/acikkaynak/deprem-yardim-frontend/issues/214 Anladigim kadariyla https://github.com/acikkaynak/deprem-yardim-frontend/pull/209#issuecomment-1420905476 ile cozuldu ama henuz deploy olmamis olabilir.
