### ISSUE TITLE
index.tsx FallbackComponent'ın ayrı bir yere taşınması / split

### ISSUE THREAD

**Issue by eraygundogmus** [acikkaynak/deprem-yardim-frontend#229]

**Comment by mscandan** [comment]
ben ilgilenebilirim bununla uzerine calisilmiyorsa @eraygundogmus

**Comment by eraygundogmus** [comment]
@mscandan tab ii

**Comment by cdagli** [comment]
https://github.com/acikkaynak/deprem-yardim-frontend/pull/236/files fixed?

**Comment by eraygundogmus** [comment]
çok pardon, @mscandan zafer zaten halletmiş prda
