### ISSUE TITLE
PHP Version

### ISSUE THREAD

**Issue by Kobemeka** [acikkaynak/deprem-yardim-frontend#231]
_Yardım istemek için tıkla_ butonu çalışıyor mu diye denedim ancak 
`Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 5.5.38. in /home/deprem/public_html/vendor/composer/platform_check.php on line 25`
hatası ile karşılaşıyorum.

Daha düşük versiyonları desteklemek daha mantıklı olacaktır diye düşünüyorum.
![image](https://user-images.githubusercontent.com/29002131/217288123-1b234aca-7e2e-4bf6-9267-845ff3a844c1.png)

**Comment by eraygundogmus** [comment]
unrelated
