### ISSUE TITLE
footer da bulunan uyarı popup ı kapatıldığında yardım iste butonu çiftliyor.

### ISSUE THREAD

**Issue by receptopalak** [acikkaynak/deprem-yardim-frontend#233]
Footer'da bulunan uyarı popup ı kapatıldığında yardım iste butonu çiftliyor.

![image](https://user-images.githubusercontent.com/45707433/217289359-422a2630-0eb9-4cff-aae2-1804519b8612.png)

![image](https://user-images.githubusercontent.com/45707433/217289516-a037d813-0124-4970-86bc-3375b49ae174.png)

**Comment by cdagli** [comment]
Sununla fix olmus olabilir https://github.com/acikkaynak/deprem-yardim-frontend/pull/221

**Comment by eraygundogmus** [comment]
fixed görünüyor

**Comment by cagriatalay** [comment]
Kodu localhost'da çalıştırdığında herhangi bir problem gözükmüyor.
