### ISSUE TITLE
harita yüklenirken loading spinner dönmesi

### ISSUE THREAD

**Issue by eraygundogmus** [acikkaynak/deprem-yardim-frontend#237]
BE isteğe göre yüzdelik oran çıkartabiliriz 

![image](https://user-images.githubusercontent.com/74984741/217294291-e2219e9d-9c80-476a-abb1-0375e07d16b0.png)

bu mantıkta

**Comment by hasanugr** [comment]
Kimse ilgilenmiyorsa, ben bakıyorum bu işe

**Comment by eraygundogmus** [comment]
@hasanugr tabii

**Comment by hasanugr** [comment]
@ezranbayantemur Leafletmap'i inceliyorum böyle bir desteğini görürsem kontrol içerisine eklerim bunu da 👍

**Comment by maliksenpai** [comment]
@hasanugr leaflet içerisinde whenReady fonksiyonu var onunla yapabiliriz gibi geldi ne dersin?

**Comment by batur** [comment]
Haritanın render durumu `<RenderIf/>` ile kontrol ediliyor gördüğüm kadarıyla, oraya da bakmakta yarar var

https://github.com/acikkaynak/deprem-yardim-frontend/blob/24e9a56c5511d101aac7187130cd582138ea48bf/components/UI/Common/RenderIf.tsx#L1-L23

**Comment by tunahandanis** [comment]
@hasanugr bu issueda bi update var mı? ben de bakabilirim

**Comment by ahmeterenodaci** [comment]
> @hasanugr leaflet içerisinde whenReady fonksiyonu var onunla yapabiliriz gibi geldi ne dersin?

Biraz araştırınca ben de aynı sonuca ulaştım. Sayfa yüklendiğinde bir spinner döndürüp whenReady fonksiyonu çağrıldığında o spinner'ın kaybolması sağlanırsa sorun çözülür gibi.
