### ISSUE TITLE
siteye girdikten sonra açıklama metnini okuyunca kullanıcı (çarpıya tıklayınca) cookie'ye set etme

### ISSUE THREAD

**Issue by eraygundogmus** [acikkaynak/deprem-yardim-frontend#240]

**Comment by ozcanzaferayan** [comment]
https://www.npmjs.com/package/cookies-next

**Comment by beysemi** [comment]
ben bakabilirim

**Comment by batur** [comment]
Ben de üstlenebilirim

**Comment by eraygundogmus** [comment]
@beysemi 
tabii

**Comment by ahmeterenodaci** [comment]
Cookie kullandığımıza yönelik bir uyarı da ekleyebiliriz açıklamaya.

**Comment by eraygundogmus** [comment]
@beysemi @ahmeterenodaci 'e katılıyorum. aynı şekilde local storage kullanımı da kaldırablirsin

**Comment by beysemi** [comment]
@eraygundogmus tabii, ilgileniyorum.

**Comment by ulassekerci** [comment]
Hocam bilmediğimden soruyorum açıklama metni için cookie'nin localstorage'a kıyasla ne gibi bir avantajı var?

**Comment by erenkulaksiz** [comment]
> Hocam bilmediğimden soruyorum açıklama metni için cookie'nin localstorage'a kıyasla ne gibi bir avantajı var?

+1

**Comment by ivanfuzuli** [comment]
@ulassekerci cookie'e set edersen her requestte o bilgi de sunucuya gider. Ve cookie'nin maksimum boyutu çok düşük.

httponly olarak etiketlersen cookie'ye browser erişemez. Sadece sunucu erişebilir.
