### ISSUE TITLE
max zoom out mobilde farklı işliyor desktop ekranına göre

### ISSUE THREAD

**Issue by eraygundogmus** [acikkaynak/deprem-yardim-frontend#241]

**Comment by eraygundogmus** [comment]
<img width="390" alt="Screen Shot 2023-02-07 at 18 58 41" src="https://user-images.githubusercontent.com/74984741/217296333-435c2289-126d-41c5-8469-44ebd0f4dc31.png">
daha fazla uzaklaşılmıyor. değer mobil uyumlu değil

**Comment by batur** [comment]
Ben halledebilirim

**Comment by eraygundogmus** [comment]
@batur

**Comment by eraygundogmus** [comment]
fixed #245
