### ISSUE TITLE
Discord Kanal Erişememe

### ISSUE THREAD

**Issue by hasanozdem1r** [acikkaynak/deprem-yardim-frontend#249]
Merhabalar, 

Normalde discord'dan yazmayı düşünüyordum ama link expire galiba. Girememedim.

Ben boun data yı fetch ettim ve mail subsription felan eklenebilir istenirse.
Proje linki burada https://github.com/turkiye-deprem/turkiye-deprem.github.io
Bilgilendirirseniz ayrıntıları görüşebilliriz.

**Comment by huseyinturkmenoglu** [comment]
Merhaba, Discord linki burası [https://discord.gg/itdepremyardim](https://discord.gg/itdepremyardim)
