### ISSUE TITLE
haritanın açıldığındaki zoom değerleri hatalı oluyor

### ISSUE THREAD

**Issue by eraygundogmus** [acikkaynak/deprem-yardim-frontend#252]

**Comment by alperencantez** [comment]
leaflet default zoom ile ilgili sanıyorum, boştaysa alabillirim

**Comment by maliksenpai** [comment]
Buna ben de bakacağım ama paralelde bakan varsa sıkıntı yok, kim yetiştirebilirse.

**Comment by maydemirx** [comment]
Merhaba ilgilenen var mı? Bakabilirim

**Comment by maliksenpai** [comment]
@maydemirx Üzerine birden fazla kişi çalışıyor ama bakabilirsiniz bence, şuan hala tam sonuç alamadık.

**Comment by alperencantez** [comment]
sorun çözüldü arkadaşlar PR attım ve merge'lendi kapatabiliriz burayı

**Comment by maydemirx** [comment]
Arkadaşlar elinize sağlık. Projeyi fork ettim ve paketlerin kurulumlarını yapmaya çalışıyorum. İnternetim pek stabil değil. Repoyu takibe aldım. Issue açıldıkça destek olmak isterim. Herkesin eline sağlık.
