### ISSUE TITLE
[Bug] Masaüstü yardım al butonu popup altında kalıyor

### ISSUE THREAD

**Issue by omer-ayhan** [acikkaynak/deprem-yardim-frontend#256]
<img width="524" alt="Screenshot 2023-02-07 at 19 59 39" src="https://user-images.githubusercontent.com/32736625/217312450-c2e09cde-4788-4fd0-9db2-8979a572b2c1.png">

**Comment by ramazanyigit** [comment]
O butonun islevi kaldirildi, sadece logo olarak duruyor.

**Comment by ramazanyigit** [comment]
Ona benzer ozellik #257 ile eklenecek.
