### ISSUE TITLE
ilk açılışta "yardıma ihtiyacın var mı" şeklinde soru çıkartılması

### ISSUE THREAD

**Issue by eraygundogmus** [acikkaynak/deprem-yardim-frontend#257]
bir modal açabiliriz ilk sayfa açılışında, bunu da cache mekanizmasında tutabiliriz. varsa direkt https://depremyardim.com/ yönlendiririz, yoksa ana sayfamız render olur

**Comment by tunahandanis** [comment]
buna ben bakabilirim

**Comment by akselsaatci** [comment]
bakan yoksa bakabilirim

**Comment by denizsult** [comment]
Ben yapabilirim

**Comment by ramazanyigit** [comment]
Gencler biriniz kararlastirip alin bu isi de ayni anda 3 kisi bakmasin

**Comment by akselsaatci** [comment]
Masaüstünde de gösterilecekmi ? mobili şuan bu şekilde
![image](https://user-images.githubusercontent.com/100696686/217330395-bebb70fe-9e02-4dae-b321-67f221ca33e9.png)

**Comment by cengizcmataraci** [comment]
Bu taskı kim aldı? @akselsaatci @denizsult @tunahandanis assign edip pr ekleyelim.

**Comment by ramazanyigit** [comment]
Bu issue yapildi kapatmayi unuttuk

**Comment by akselsaatci** [comment]
Diğer arkadaşlar aldımı bilmiyorum eğer yukarıdaki tema uygunsa pr açabilirim.
