### ISSUE TITLE
[Refactor] MarkerData verisinin mapStore'a taşınması

### ISSUE THREAD

**Issue by MetinArslanturk** [acikkaynak/deprem-yardim-frontend#259]
Map'e dair veriler mapStore zustand store'da tutulmakta. MarkerData'yı da bu store'a yazabiliriz böylece prop'larla elden ele iletmekten kurtuluruz. 

Öte yandan yine index'de create edilip prop olarak iletilen click handler'lar ayrı bir hook'a taşınabilir. Props drilling'i olabildiğince azaltıp daha temiz bir index dosyasına sahip olabiliriz.

**Comment by eraygundogmus** [comment]
assign edebilirim?

**Comment by MetinArslanturk** [comment]
Olur 👍🏻
