### ISSUE TITLE
Acil Wiki Gerekiyor.

### ISSUE THREAD

**Issue by volkantash** [acikkaynak/deprem-yardim-frontend#265]
Selamlar. Bir wiki yaratma yeri hemen açabilir misiniz? Belgeleri kılavuzları yazmada orayı da dolursak çok iyi olurdu.

**Comment by eraygundogmus** [comment]
https://github.com/acikkaynak/deprem-yardim-frontend/blob/main/.github/ISSUE_TEMPLATE/bug_report.md
