### ISSUE TITLE
Buton(?)'un yazıyla çakışması

### ISSUE THREAD

**Issue by mahmutgurbulak** [acikkaynak/deprem-yardim-frontend#266]
Sağ alttaki eskiden buton olan logo bilgilendirme yazısı ile çakışıyor. Chromium, 1920x1080, Windows 10
![image](https://user-images.githubusercontent.com/122745355/217319814-60fe5da7-4ecc-47e3-9dad-f5f291c4f0d8.png)

**Comment by eraygundogmus** [comment]
duplicate
