### ISSUE TITLE
afet_harita_kullanimi_telefon_gif

### ISSUE THREAD

**Issue by rukiyealimci** [acikkaynak/deprem-yardim-frontend#276]
afet harita kullanım kulavızu için gif
https://user-images.githubusercontent.com/79915194/217329564-7a29dcbc-08a8-4b1a-8c01-ac13ddfbe101.mp4

**Comment by EnginKARATAS** [comment]
ne isteniyor tam olarak? buraya bir info buttonu eklenebilir
![image](https://user-images.githubusercontent.com/43602725/217338458-c0199b70-8335-45ef-8b7a-77b354f20f6c.png)

**Comment by ozcanzaferayan** [comment]
Tweet bölümü glitch oluyor halledicem

**Comment by oznrozdmr** [comment]
o kısımda switch kapatılınca bir şey gelicek mi boş mu olucak?
