### ISSUE TITLE
heatmap'in production ortamında çalışmaması ancak localhostta çalışması

### ISSUE THREAD

**Issue by eraygundogmus** [acikkaynak/deprem-yardim-frontend#282]

**Comment by oznrozdmr** [comment]
NEXT_PUBLIC_API_MOCKING=disable yapılmış muhtemelen ondan çalışmıyor enable yaparsan açlışır diye düşünüyorum

**Comment by tunahandanis** [comment]
@oznrozdmr çözümünü localde denedim, proddaki sorunu çözecektir evet 🎉 onun dışında, localde karşılaşılan bi süre interaksiyondan sonra heatmap in kaybolma sorunu var, onun için hazırda bi PR açtım, senin çözümünü de o PR a ekleyeceğim

**Comment by oznrozdmr** [comment]
kaybolduğunda console da hata ne verdi?

**Comment by tunahandanis** [comment]
hata yok, markerlar için atılan 2. istek ile heatmap e yedirilen points updateleniyor, bu olunca heatmap kayboluyor nedense, useMemo dependency'sini boşa alınca sonradan kaybolma sorunu çözülüyor

**Comment by tunahandanis** [comment]
senin çözümün de prodda ilk açılışta heatmap i göstermedi gibi:
[preview](https://deprem-yardim-frontend-6va7bwomb-afetharita.vercel.app/)

**Comment by oznrozdmr** [comment]
Şuan heatmap geliyor görünüyor. ellerine sağlık

**Comment by tunahandanis** [comment]
benim PR'ım mergelenmedi bile 🤔 bende heatmap yine yok prodda

**Comment by oznrozdmr** [comment]
preview paylaştın ya az önce vercelde görünüyor ama console da hata vardı. şuan yine gitmiş heatmapler

**Comment by tunahandanis** [comment]
prodda marker requesti boş dönüyor nedense, sorun o

**Comment by myagizmaktav** [comment]
problem devam ediyor.
