### ISSUE TITLE
performans iyileştirmeleri

### ISSUE THREAD

**Issue by erenkulaksiz** [acikkaynak/deprem-yardim-frontend#287]
Bir arkadaşın yazdığını iletiyorum: 
`Selamlar arkadaşlar afetharita.com'u açtığımda aşırı CPU ve RAM tüketimi yapıyor buda mobil cihazlar için aslında yüksek enerji tüketimi anlamına gelmekte bu noktada bir geliştirme sağlanabilir mi ? mesela sadece harita değilde harita site içinde ayrı bir sayfa olsa kullanıcı il ilçe seçip ham datayı okuyabilse`
Performans iyileştirmeleri için potansiyel olarak neler yapabiliriz?

**Comment by absolutezero13** [comment]
uzun sürebilecek bi feature ama alabilirim, tasarım olarak nasıl ilerlememiz gerekir onu belirlememiz gerekecek tabi.

**Comment by maliksenpai** [comment]
https://depremyardim.com/# zaten bu işleve yaramıyor muydu? Sayfa açılışında oraya yönlendirme de yaptırabiliriz harita falan hazırlanmadan? Ne dersiniz?

**Comment by hamitaksln** [comment]
Heatmap'i devre dışı bıraktımda baya bir rahatlama oluyor. Belki o kısma bir şeyler yapabiliriz.

**Comment by onurkerimov** [comment]
Potansiyel olarak yapilabilecek bir sey: Lejant'ın arkasında `backdrop-filter: blur(5px);` kullanımı görüyorum. Ne boyutta etki ediyordur bilmiyorum, ancak cok gerekli gorunmuyor

**Comment by hamitaksln** [comment]
Sorun kullanıdığımız map kütüphanesi ile alakalı bence. map-gl performans açısından daha başarılı görünüyor:
https://visgl.github.io/react-map-gl/examples/clusters

**Comment by safakyavsan** [comment]
Haritanın default zoom halinde tüm dataları birden göndermeye gerek olmayabilir.Cluster'lar yaklaştırıldıkça detayları çekebilirsiniz.Tabi backendede buna göre bir ayarlama yapmanız gerekicek.

**Comment by justChargin** [comment]
Harita görünümü subdomaine taşınıp ham veri anasayfada filtrelenebilir şekilde görüntülenebilirse güzel olur. Ham veri üzerinden harita görünümüne geçilebilmesine olanak sağlanır. Benim naçizane fikrim bu.

**Comment by aerdemsenturk** [comment]
> Sorun kullanıdığımız map kütüphanesi ile alakalı bence. map-gl performans açısından daha başarılı görünüyor: https://visgl.github.io/react-map-gl/examples/clusters

Ben de onun açık kaynak forku olan maplibreGL öneriyorum ama sanırım geçiş çok büyük iş çıkaracak diye üzerinde durulmuyor. Ama 5000+ noktalı haritalar için Leaflet yanlış tercih. Maplibre ile denemem şurada dursun: https://aerdemsenturk.github.io/map/afetharita/

**Comment by sametcodes** [comment]
https://github.com/acikkaynak/deprem-yardim-frontend/issues/331

**Comment by erenkulaksiz** [comment]
> Harita görünümü subdomaine taşınıp ham veri anasayfada filtrelenebilir şekilde görüntülenebilirse güzel olur. Ham veri üzerinden harita görünümüne geçilebilmesine olanak sağlanır. Benim naçizane fikrim bu.

Böyle ayrı sayfada filtreleme olsa güzel olur. İl ilçe mahalle tarzı filtre ile kayıtları görüntüleyebilsek güzel olur. maplibreGL implementasyonu güzel olmuş bu arada. Ben afetharita'yı iphone 11 cihazda açtım cihaz ısındı resmen garip bir şekilde.
