### ISSUE TITLE
Affet harita yönlendirme kırmızı buton çalışmıyor

### ISSUE THREAD

**Issue by akarakus27** [acikkaynak/deprem-yardim-frontend#289]
https://prnt.sc/bHT1yIChtuAm burda buton çalışmıyor 
https://afetharita.com/ yönlendirdigi url degişmiş

**Comment by osmandlsmn** [comment]
kimse ilgilenmiyorsa ben yapabilirim

**Comment by ramazanyigit** [comment]
Su an bu butonun ozelligi kapatildi, sag ustteki butona aktarildi.
