### ISSUE TITLE
Aşağıda kalan kırmızı yazının daha okunulur/erişilebilir olması

### ISSUE THREAD

**Issue by iGoodie** [acikkaynak/deprem-yardim-frontend#292]
Sitenin altında kalan kırmızı şerit bazı ekran boyutlarında okunulur değil. Daha erişilebilir olması için yeni bir PR oluşturmaya çalışıyoruz

![image](https://user-images.githubusercontent.com/8591785/217337243-b092ac16-4c94-409b-b8eb-8c50ebf86258.png)

**Comment by denizsult** [comment]
ben pr açtım

**Comment by denizsult** [comment]
https://github.com/acikkaynak/deprem-yardim-frontend/pull/286

**Comment by eraygundogmus** [comment]
duplicate
