### ISSUE TITLE
afet_harita_pc_kullanim_gif

### ISSUE THREAD

**Issue by umttshnn24** [acikkaynak/deprem-yardim-frontend#296]
![afetharita_pc_kullanim](https://user-images.githubusercontent.com/36659429/217339007-44139eb2-9560-4130-8f55-52cea298ba02.gif)

**Comment by umttshnn24** [comment]
Kullanım kılavuzuna dahil edilmesi için eklenmiştir.

**Comment by fdemir** [comment]
selam. readme'ye eklemek icin pr acar misin?

**Comment by umttshnn24** [comment]
@fdemir selam, ben commit atamadım yetkim olmadığı için o yüzden pr açamadım :/

**Comment by umttshnn24** [comment]
![cabucak_kullan_mobil](https://user-images.githubusercontent.com/36659429/217357933-1d254a1a-feeb-43be-b76c-bb273e8d537d.gif)

**Comment by volkantash** [comment]
Hazırlanmış görüntüler [ÇABUCAK ÖĞREN belgesi](https://github.com/acikkaynak/deprem-yardim-frontend/blob/development/%C3%A7abucak-ogren.md) içinde kullanıldı. Emeği geçenlere teşekkür ederiz.

**Comment by bedirhanyildirim** [comment]
@usirin issue kapatılabilir
