### ISSUE TITLE
Renk lejantı basıldığında bir filtreleme sağlamıyor

### ISSUE THREAD

**Issue by iGoodie** [acikkaynak/deprem-yardim-frontend#298]
![image](https://user-images.githubusercontent.com/8591785/217340105-d05898c1-dc2d-448b-8b5a-c7f726a7e6b6.png)

Herhangi bir seçeneğe basıldığında bir filtreleme sağlanmıyor. Bu taski alıyoruz eğer üzerinde çalışan yoksa

**Comment by eraygundogmus** [comment]
böyle bir feature istenilmiyor
