### ISSUE TITLE
Toplanma Bölgelerini Gösteren Buton

### ISSUE THREAD

**Issue by esmanurkaragol** [acikkaynak/deprem-yardim-frontend#303]
Toplanma bölgelerini göster adı altında bir ikon (https://www.shutterstock.com/image-vector/muster-point-sign-on-ehite-background-1901705938) seçip, tıklanabilir formda "https://www.turkiye.gov.tr/afet-ve-acil-durum-yonetimi-acil-toplanma-alani-sorgulama" adresine yönlendirme yapabilir.

**Comment by osmandlsmn** [comment]
Kimse ilgilenmiyorsa isterseniz ben yapabilirim

**Comment by sametocak** [comment]
Tam olarak nereye konulacak ona göre ön tarafa yerleştiriyorum

**Comment by esmanurkaragol** [comment]
@sametocak olur

**Comment by atayizuf** [comment]
svg, png lazımsa yapabilirim.

**Comment by esmanurkaragol** [comment]
icon için bir link attım direkt onu bağlasak olmaz mı ?

**Comment by sametocak** [comment]
> svg, png lazımsa yapabilirim.

.svg gönderir misin güzel bi şekil

**Comment by sametocak** [comment]
> icon için bir link attım direkt onu bağlasak olmaz mı ?

Fazla iri, daha minimalist çalışılmalı ekranda yer kaplamasın @atayizuf  sen devam

**Comment by esmanurkaragol** [comment]
görünüm için oranlarını belirleyebiliriz, ancak daha kolay olacak derseniz .svg formu da olur tabi

**Comment by Mahmutcano** [comment]
![Frame 1 (22)](https://user-images.githubusercontent.com/91735041/217349409-55ec62fb-cc1f-484b-b662-1bb2304ca49f.png)

**Comment by Mahmutcano** [comment]
![Frame 1 (22)](https://user-images.githubusercontent.com/91735041/217349780-815cb2cb-187b-4d4a-9a14-f3e701e2a74a.png)

**Comment by Mahmutcano** [comment]
![Frame 1](https://user-images.githubusercontent.com/91735041/217350118-7e82ecef-33d0-43e3-b310-c17be5e54c65.svg)

**Comment by sametocak** [comment]
teşekkürler, birazdan ui-add dalı ile pr oluşturacağım bakıp içeri alabilirisniz

**Comment by atayizuf** [comment]
![toplanmaYeri](https://user-images.githubusercontent.com/54551321/217361800-77553db1-d178-4832-8b4f-e838b2f87a2e.svg)

Hangisi isine yararsa artik

**Comment by sametocak** [comment]
Pr oluşturamadım collab olarak ekli değilim @esmanurkaragol

**Comment by bedirhanyildirim** [comment]
> Pr oluşturamadım collab olarak ekli değilim @esmanurkaragol

projeyi fork edip pr açman lazım development branchine

**Comment by esmanurkaragol** [comment]
@bedirhanyildirim @sametocak Github da branch nasıl ekleniyor bunu bilmiyorum, discordan ekran paylaşayım yapalım beraber

**Comment by sametocak** [comment]
https://github.com/acikkaynak/deprem-yardim-frontend/pull/456 pr açıldı @bedirhanyildirim  @esmanurkaragol @Mahmutcano
