### ISSUE TITLE
En mantıklı simgeler, iconlar ile daha anlaşılır harita yapmak

### ISSUE THREAD

**Issue by volkantash** [acikkaynak/deprem-yardim-frontend#308]
Çalışma sırasında kullanılan renkli yuvarlakların ne anlama geldiği karmaşası ile karşılaştık. Bu yüzden o bölümün yeniden ele alınması düşüncesi doğdu. Yoğunluğu 3 düzeyde belirtmek yeterli olabilir.

Yoğunluk belirtmek için hazırladığımız " az - orta - çok " düzeylerindeki simgeleri renk körleri dahi anlasın diye **kara ve boz (gri)** renklerinde oluşturduk. 

Görüşlere göre daha başarılı bir sunuş ve kullanış elde edilebilir.

[icons8-full-and-excellent-phone-signal-reception-network-level-tal-revivo-duo(1).zip](https://github.com/acikkaynak/deprem-yardim-frontend/files/10678666/icons8-full-and-excellent-phone-signal-reception-network-level-tal-revivo-duo.1.zip)
[icons8-full-and-excellent-phone-signal-reception-network-level-tal-revivo-duo(2).zip](https://github.com/acikkaynak/deprem-yardim-frontend/files/10678667/icons8-full-and-excellent-phone-signal-reception-network-level-tal-revivo-duo.2.zip)
[icons8-full-and-excellent-phone-signal-reception-network-level-tal-revivo-duo.zip](https://github.com/acikkaynak/deprem-yardim-frontend/files/10678668/icons8-full-and-excellent-phone-signal-reception-network-level-tal-revivo-duo.zip)

**Comment by caginsucu** [comment]
Dediğin konuda haklısın ama heatmap kullanıldığı için yoğunlukları renge göre belirtilcek şekilde ayarlanmıştı bununla ilgili diğer arkadaşlar  da yorum yapacaktır illa ki. Ama tüm akışı değiştiri gibi geldi

**Comment by esmanurkaragol** [comment]
yayında da söylendiği gibi yeşil renk sanki hiçbir sorun yok, temiz bölge gibi anlaşılıyor bu nedenle renk skalasında güncellenme yapılması gerektiğini düşünüyorum bende .

**Comment by EnginKARATAS** [comment]
bana da öyle gelmişti. projeye yeni girdim. kırmızı bölgeye odaklanılıyor otomatik olarak. corona virüs haritası değil bu. custom çözüm iyi olabilir
> esmanurkaragol
