### ISSUE TITLE
Technical Error

### ISSUE THREAD

**Issue by justChargin** [acikkaynak/deprem-yardim-frontend#317]
Oppo Reno marka telefonum üzerinden siteye giriş yaptığımda aşağıdaki gibi bir ekranla karşılaşıyorum. Bilgisayardan siteye girmeyi denemedim.

![IMG_20230207_230703.jpg](https://user-images.githubusercontent.com/46795644/217353584-8915c3e4-82e1-4920-8cc7-445509d0322f.jpg)

**Comment by tunahandanis** [comment]
teknik hatalar için ufak bi ekran yazdım, dcden ss ini atıyorum

**Comment by justChargin** [comment]
> teknik hatalar için ufak bi ekran yazdım, dcden ss ini atıyorum

Discord link atar mısınız
