### ISSUE TITLE
Arama bölümü

### ISSUE THREAD

**Issue by maydemirx** [acikkaynak/deprem-yardim-frontend#318]
Merhaba, harita üzerinde zoom butonlarının altına "Arama" kutucuğu eklenebilir. Bu buton ile açılacak panelde adres, yardım içeriği, konum gibi değerler girilerek ilişkili veriler listelenebilir. Açılan panelde "Haritada Göster" butonuna tıklanarak sadece arama sonuçlarını içeren pinler gösterilerek belli bir konu özelinde harita özelleştirilebilir.

**Comment by murerkinn** [comment]
Selam, uygulamanın üst kısmına başta statik olarak deprem bölgelerinin adreslerini içeren bir dropdown eklemeyi düşünüyorum. Böylece oradan kolaylıkla seçerek haritada o bölgeye odaklanabilirler. Bir de "Konumumu kullan" butonu ile kullanıcının olduğu yere haritanın odaklanmasını ekleyebilirim. Daha sonrasında gerekirse bir autocomplete search de ekleyebiliriz. Bana assign edebilir misin? @usirin
