### ISSUE TITLE
Kayıplar Ve İletişim

### ISSUE THREAD

**Issue by esmanurkaragol** [acikkaynak/deprem-yardim-frontend#324]
Kayıp olan kişilerin bilgilerinin (ad, soyad, cinsiyet , yaş, adres...) girildiği bir ekran olabilir. Kvkk açısından sorun olur mu bilmiyorum ancak isteğe bağlı olarak resim ekleme butonu da koyabiliriz.  Kayıp olan kişinin tahmini bulunduğu konumuda girilmesi için il, ilçe, mah. Bilgileride kullanıcılardan alınmalı. 
Ardından girilen verileri adrese göre filtreleme yaparak, İlgili adresde bulunan kayıpların  resimleri büyük bir şekilde altında ise ad-soyad bilgisi verilecek şekilde ekrana bastırabilir. Aynı zamanda bulundu-bulundu ise konumunun vs girileceği bir alan oluşturulmalı.

**Comment by sarpkayature** [comment]
Çocuklar için bu askıya alındı galiba?

**Comment by esmanurkaragol** [comment]
Anlamadım, açıklayabilir misin
