### ISSUE TITLE
Viewport zoom zorunu

### ISSUE THREAD

**Issue by ogunbaysal** [acikkaynak/deprem-yardim-frontend#325]
Mobil cihazda kullanıcı yanlışlıkla marker detayının üzerinde zoom yaparsa ve marker'ı kapatırsa map'e focus olduğu için zoom'u geri alamıyor. Viewport ile zoom engellenerek çözülebilir.

**Comment by ogunbaysal** [comment]
Pull request açıldı. 
https://github.com/acikkaynak/deprem-yardim-frontend/pull/339

**Comment by ezranbayantemur** [comment]
Windows'da deneyemedim fakat;
`Drawer.tsx`'e ;
```js
  useEffect(() => {
    if (isOpen) {
      // Mac'de pinch to zoom engellemek için
      window.addEventListener(
        "wheel",
        (e) => {
          if (e.ctrlKey) {
            e.preventDefault();
          }
        },
        { passive: false }
      );

      // iPhone'da pinch to zoom engellemek için
      document.addEventListener(
        "touchmove",
        function (event) {
          if (event.scale !== 1) {
            event.preventDefault();
          }
        },
        { passive: false }
      );
    }
  }, [isOpen]);
```

Şeklinde geliştirme eklemek işe yarar gibi görünüyor. Senin PR'da eklediğin `meta`lar eğer Windows'da destek sağlıyorsa bunlar da ek olarak eklenebilir. Sonrasında bu listener return'da kaldırılabilir eğer drawer destruct oluyorsa
