### ISSUE TITLE
Dev ortamında kullanılan dependency'lerin temizlenerek bundle'ın küçültülmesi

### ISSUE THREAD

**Issue by akifunal** [acikkaynak/deprem-yardim-frontend#326]
İlk bakışta ts ve eslint paketlerinin devDependencies altına taşınması faydalı olacaktır.

**Comment by sarpkayature** [comment]
@akifunal ben alabilirim

**Comment by sarpkayature** [comment]
> @akifunal ben alabilirim

zaten bu dependency'ler devDependency

**Comment by akifunal** [comment]
@sarpkayature benim branch geride kalmış. 2 saat önce bir arkadaş paketleri düzenlemiş. Emeğine sağlık.
