### ISSUE TITLE
Mobil ekranlarda sadece zoomlanmış lokasyondaki markerların gösterilmesi

### ISSUE THREAD

**Issue by csgn** [acikkaynak/deprem-yardim-frontend#327]
Optimizasyon için özellikle mobil ekranlar için bütün markerları render etmek yerine sadece zoomlanmış alandaki markerlar render edilse?  

Bir deneme >>>

![1](https://user-images.githubusercontent.com/53083523/217361533-0fb42823-c20c-4264-a130-95f2ce1331a5.png)

![2](https://user-images.githubusercontent.com/53083523/217361535-529a34fc-764c-49d6-b9b0-76848deaaa71.png)

**Comment by ezranbayantemur** [comment]
Şu an bu durumla alakalı konuşuluyor, gelen data boyutu ile ilgili bir çalışma deneniyor

**Comment by csgn** [comment]
Anladım. Bilgi için teşekkürler.

**Comment by bedirhanyildirim** [comment]
@usirin issue kapatılabilir
