### ISSUE TITLE
Sözleşmelerin HTML olarak yeni tabta açılması

### ISSUE THREAD

**Issue by eraygundogmus** [acikkaynak/deprem-yardim-frontend#330]

**Comment by eraygundogmus** [comment]
<img width="849" alt="Screen Shot 2023-02-08 at 00 10 52" src="https://user-images.githubusercontent.com/74984741/217366357-74c78f2a-5a61-4f22-b371-0e80a18cb063.png">

**Comment by atayizuf** [comment]
Html sayfalarını ben hazırlıyorum.

**Comment by mehmetranas** [comment]
pdf convert edip static olarak serve edelim bence, bundle size buyumemis olur
pdf dosyasini browserda actirabiliriz sanki.

**Comment by atayizuf** [comment]
> 

Tamamdır. Nasıl uygunsa.

**Comment by atayizuf** [comment]
[gizlilik.pdf](https://github.com/acikkaynak/deprem-yardim-frontend/files/10679509/gizlilik.pdf)
[cerez.pdf](https://github.com/acikkaynak/deprem-yardim-frontend/files/10679510/cerez.pdf)

**Comment by eytanfb** [comment]
https://github.com/acikkaynak/deprem-yardim-frontend/pull/357
