### ISSUE TITLE
Apple Maps deep link

### ISSUE THREAD

**Issue by cemiluzunhasan** [acikkaynak/deprem-yardim-frontend#332]
iPhone & iPad cihazlarda Apple Maps'te konumlari acmak icin button koyulabilir. Bir button araciligi ile deep link koyulmasindan bahsediyorum google maps button'larinin oldugu yere. Eger hic kimse bakamayacaksa destek atabilirim. Sevgiler ve gecmis olsun 🙏🏼

**Comment by cemiluzunhasan** [comment]
Elimde kod hazir, eger istiyorsaniz PR acabilirim @canumay

**Comment by canumay** [comment]
Zaten hazirladiysan PR acabilirsin hocam, ilgili arkadaslar onaylacaktir.

**Comment by cemiluzunhasan** [comment]
Tamamdir hemen aciyorum, kolayliklar ve tesekkurler

**Comment by cemiluzunhasan** [comment]
Hocam selamlar, ilgili PR'i ekte birakiyorum. Herkesin emegine saglik. Olasi bir bug/hata durumunda ben de destek saglayabilirim. Iyi geceler dilerim

https://github.com/acikkaynak/deprem-yardim-frontend/pull/343
