### ISSUE TITLE
Warning: Cannot update a component (`LeafletMap`) while rendering a different component (`Home`). To locate the bad setState() call inside `Home`,

### ISSUE THREAD

**Issue by Nightvision53** [acikkaynak/deprem-yardim-frontend#335]
This error occurs because in pages/index.tsx we are rendering the Leaflet map even though the loading stage is not fulfilled.

**Comment by mehmetranas** [comment]
Bakiyorum

**Comment by Nightvision53** [comment]
@mehmetranas pull request oluşturdum https://github.com/acikkaynak/deprem-yardim-frontend/pull/336
