### ISSUE TITLE
 Düşük internet hızları için Progress Loader

### ISSUE THREAD

**Issue by atifsimsek** [acikkaynak/deprem-yardim-frontend#340]
Deprem bölgesinde internet hızları düşük olduğu için, kullanıcı uygulama yüklenmeden dondu sanıp uygulamadan çıkabilir. Ana Loader Progress  bar ile birlikte oluşturulup güncellenebilir.

**Comment by canumay** [comment]
#342

**Comment by JusticeBoi** [comment]
ben bakiyorum buna

**Comment by usirin** [comment]
#361 ile load uzadiginda text'i update ederek cozduk bunu
