### ISSUE TITLE
[feature] Yüklenmeyen tweetler için placeholder

### ISSUE THREAD

**Issue by ozcanzaferayan** [acikkaynak/deprem-yardim-frontend#348]

**Comment by ynsalc** [comment]
Api yanıt dönmemesi durumunda mı eklenecek ? Ve nasıl bir placeholder eklenecek detay verirseniz yapabilirim.

**Comment by mehmetranas** [comment]
Tasarrim ekibinden destek almak icin yazdim.

**Comment by ynsalc** [comment]
Tamamdır bekliyorum

**Comment by ynsalc** [comment]
Sanırım yetkim yok hiçbirşey göremiyorum mesajlar yüklenmiyor @mehmetranas

**Comment by ozcanzaferayan** [comment]
Selam ben yaptım bunu :)

**Comment by ynsalc** [comment]
Tamamadır abi eline sağlık. Ama discorda erişim yapamıyorum mesajlar yüklenmedi diyor @mehmetranas abi link verdi dc de varım ama birşey göremiyorum.

**Comment by ErgunErkan** [comment]
Discord üzerinde bir tasarım hazırladık. Figma'yı kontrol edebilirsiniz.
