### ISSUE TITLE
[proposal] - Kayıtların sosyal mecralarda paylaşılabilmesi için open graph edge function oluşturulması

### ISSUE THREAD

**Issue by dopplerDistortion** [acikkaynak/deprem-yardim-frontend#355]
Başlıkta geçen konu için bir fikir çalışmasına başladım. fyi

**Comment by dopplerDistortion** [comment]
Ben yapıyorum bunu

**Comment by dopplerDistortion** [comment]
Open graph için templateleri paylaşıyorum

https://www.figma.com/file/wjmuadG78Lu7Bgr1bSnD2B/Design?node-id=0%3A1&t=lgBnvs5aBVpfyosD-1

<img width="849" alt="Screenshot 2023-02-08 at 02 19 54" src="https://user-images.githubusercontent.com/1084392/217389166-2c63757d-09db-48ea-9d0d-744e87bde72a.png">

**Comment by dopplerDistortion** [comment]
İhtiyaç listesi:
1. Single entry (örn: id ile çağırılabilecek) çekebilmek için servis ihtiyacı
2. Sayfaların karşılanabilmesi için tekil item sayfası veya uygulama açıldığında direk oraya gönderebilecek bir query karşılaması

**Comment by usirin** [comment]
> Sayfaların karşılanabilmesi için tekil item sayfası veya uygulama açıldığında direk oraya gönderebilecek bir query karşılaması

Bu kismi direk drawer'i acacak sekilde ayarlayabiliriz, 1. ihtiyac icinse yanlis hatirlamiyorsam backend endpoint gelistiriliyor su an

**Comment by dopplerDistortion** [comment]
> > Sayfaların karşılanabilmesi için tekil item sayfası veya uygulama açıldığında direk oraya gönderebilecek bir query karşılaması
> 
> Bu kismi direk drawer'i acacak sekilde ayarlayabiliriz, 1. ihtiyac icinse yanlis hatirlamiyorsam backend endpoint gelistiriliyor su an

Tamamdır. Edge functionı bitirince tekrar yazarım.

**Comment by fdemir** [comment]
assigned.

**Comment by dopplerDistortion** [comment]
@fdemir edge function hazır. ancak bunun ayrı bir repo olması gerektiğini düşündüğüm için ayırdım. repoyu open olarak oluşturdum. readme.md güncel. detaylarını boş bir vaktinizde konuşalım. devamı için bu repoda metalar için bir kurulum yapıp oradan devam edeceğim. edge function için: 

https://github.com/thisiswunder/deprem-yardim-og-generator
