### ISSUE TITLE
Twitter embedler bozulmus durumda

### ISSUE THREAD

**Issue by usirin** [acikkaynak/deprem-yardim-frontend#366]
`tweet_id` undefined oldugu icin tweet widget'i dogru calismiyor.

**Comment by Kayra1** [comment]
Yeni data modelimizde `extra_parameters` in icinde olacak tweet_id. JSON.parse yapip bulabilirsiniz. Simdilik bu field bugli ve yazanlar AFK. yakin zamanda cozmeyi umuyoruz.

https://github.com/acikkaynak/deprem-yardim-backend/issues/105

**Comment by yamac-kurtulus** [comment]
Buna bakıyorum da yeni data çekerken problem yok gibi, düzeldi mi, yoksa eski datalar mı sıkıntılı, yoksa edge case'ler mi var?
