### ISSUE TITLE
[ISSUE] Pinler/yoğunkluk belirli bir yakınlaşmadan sonra kayboluyor

### ISSUE THREAD

**Issue by DodoBey** [acikkaynak/deprem-yardim-frontend#368]
![1](https://user-images.githubusercontent.com/77416196/217409838-75f18e22-fb06-444c-b3cc-bc5350f109c8.png)
![2](https://user-images.githubusercontent.com/77416196/217409841-aa3b0df7-1577-4586-9f62-8b0906880502.png)
![3](https://user-images.githubusercontent.com/77416196/217409847-3a291d74-f70c-45c9-90d3-022a9c7ca364.png)

Ekran resimleri 14 pro max, safari ye ait. Belirli bir oranda yakınlaştıktan sonra pinler/yoğunluk kayboluyor, ihbarların detayları ulaşılmaz oluyor maalesef.

**Comment by eytanfb** [comment]
buna bakan yoksa ben basladim bakmaya. sanirim desktop'ta da oluyor bu. aslinda goruntude olmasi gereken bir pin kayboluyor belli zoom seviyesinde

**Comment by eytanfb** [comment]
api'dan gelmiyor data.

ornegin su degerleri yolladigimizda:
```
ne_lat=36.71016769116917
ne_lng=37.142192213796086
sw_lat=36.7065379912661
sw_lng=37.14010009076447
```

`loc` bu olmasina ragmen data donmuyor:
```
loc : [36.7082893, 37.1409422]
```

buna backend baksa mantiklisi o olur. ya da belli bir zoom in levelina geldigimizde yine de biraz daha genis bir bound yollayacagiz.

**Comment by eytanfb** [comment]
> api'dan gelmiyor data.
> 
> ornegin su degerleri yolladigimizda:
> 
> ```
> ne_lat=36.71016769116917
> ne_lng=37.142192213796086
> sw_lat=36.7065379912661
> sw_lng=37.14010009076447
> ```
> 
> `loc` bu olmasina ragmen data donmuyor:
> 
> ```
> loc : [36.7082893, 37.1409422]
> ```
> 
> buna backend baksa mantiklisi o olur. ya da belli bir zoom in levelina geldigimizde yine de biraz daha genis bir bound yollayacagiz.

bahsettigim cozum icin PR (https://github.com/acikkaynak/deprem-yardim-frontend/pull/384)
