### ISSUE TITLE
[Feature] Harita layerında pinlerden uzaklaştıkça yoğunluk bilgisinin paylaşılması

### ISSUE THREAD

**Issue by muum** [acikkaynak/deprem-yardim-frontend#37]
[https://www.figma.com/file/sctw6xtcdoFOfmE0gC97Ft/Deprem-Yard%C4%B1m?node-id=0%3A1&t=1hg6ltcv5aURnh5N-0](https://www.figma.com/file/sctw6xtcdoFOfmE0gC97Ft/Deprem-Yard%C4%B1m?node-id=0%3A1&t=1hg6ltcv5aURnh5N-0)

**Comment by muum** [comment]
Harita layerında uzaklaştıkça pinlerin kaybolup onların yerine yoğunluk bilgilerinin gelmesi

**Comment by muum** [comment]
Düşük Yoğunluk: 0 Pin
Orta - Alt Yoğunluk: 1 - 5 Pin
Orta Yoğunluk: 6 - 25 Pin
Orta - Üst Yoğunluk: 26 - 100 Pin
Yoğun: +100

**Comment by ynsalc** [comment]
Kimse ilgilenmiyorsa ilgileniyorum

**Comment by muum** [comment]
@ynsalc ek bilgi gerekirse buradayım

**Comment by mehmetranas** [comment]
@ynsalc ben de localde biraz ilerletmistim, yardima ihtiyac olursa durtersim.

**Comment by ynsalc** [comment]
Ben ilgileniyorum fakat ilgilenen varsa yine ilerletsin benden hızlı bitiren geliştirmeyi tamamlasın daha iyi olur deprem bölgesindeyim  bazen bakamayabilirim

**Comment by mehmetranas** [comment]
ben alabilirim @ynsalc

**Comment by ynsalc** [comment]
Tamamdır @mehmetranas

**Comment by mehmetranas** [comment]
[PR](https://github.com/acikkaynak/deprem-yardim-frontend/pull/136) actim ama vercel de fail oluyor. ben yarin bakamayabilirm, biri buradan destek olabilir belki.

**Comment by denizsult** [comment]
@ynsalc  devam ediyor musun?

**Comment by duygu-korkmaz** [comment]
Ben de ilgilenmeye basladim fakat kendimi assignee olarak isaretlemiyorum, halen üzerinde calisan biri varsa yardimci olmak isterim

**Comment by denizsult** [comment]
Ben de ilgileniyorum
