### ISSUE TITLE
[BUG] Zoom out butonu calismiyor

### ISSUE THREAD

**Issue by eytanfb** [acikkaynak/deprem-yardim-frontend#372]
Haritada zoom out butonu calismiyor

**Comment by eytanfb** [comment]
https://github.com/acikkaynak/deprem-yardim-frontend/pull/376

**Comment by DodoBey** [comment]
ops yemeğe gidip geldim pr açtım görmedim çalışan olduğunu ama aslında bir tık daha iyi çözüm test ederseniz [#381 ](https://github.com/acikkaynak/deprem-yardim-frontend/pull/381)
