### ISSUE TITLE
[FEATURE] Subdomain ile şehir filtresi

### ISSUE THREAD

**Issue by onuralpyilkin** [acikkaynak/deprem-yardim-frontend#377]
Afet bölgesinde olan iller için subdomain oluşturarak haritayı direkt o şehrin merkezi veya en yoğun bölgesinden açabiliriz. Bu şekilde zoom yaptıkça harita yavaş yavaş yükleniyor, bekleme süresi çok fazla. Direkt şehir linklerini paylaşarak daha çabuk ulaşılması sağlanabilir.

**Comment by erenkulaksiz** [comment]
FYI @ozcanzaferayan @eserozvataf 
https://stackoverflow.com/questions/57469815/retrieving-sub-domain-in-next-js-page
https://github.com/vercel/static-fun/blob/master/pages/api/get-page.ts

vercel ile nasıl yapılır bilmiyorum ancak yapılabilir görünüyor

**Comment by candase** [comment]
@onuralpyilkin @erenkulaksiz Subdomain yerine query param de kullanilabilir
