### ISSUE TITLE
[bug] twitter paylaşımda open graph image gelmiyor

### ISSUE THREAD

**Issue by dopplerDistortion** [acikkaynak/deprem-yardim-frontend#382]
Örnek link
https://deprem-yardim-frontend-49pacp1fb-afetharita.vercel.app/

Output
![Screenshot 2023-02-08 at 07 08 30](https://user-images.githubusercontent.com/1084392/217431426-dde38554-995f-4155-92fd-98f010e766ce.png)

**Comment by didemkkaslan** [comment]
Kodda image kısımları boş kalmış

**Comment by dopplerDistortion** [comment]
@didemkkaslan evet diğer pagelerdeki head componentlarını yeni componentla replace etmediğimi fark ettim. İlgileniyorum.
