### ISSUE TITLE
[Bug] ClusterPopup's intensity badge color is not matching with legend.

### ISSUE THREAD

**Issue by ramazanyigit** [acikkaynak/deprem-yardim-frontend#390]
![image](https://user-images.githubusercontent.com/54190298/217448701-c1e4c2e3-a601-4e36-afe2-b9128bed4483.png)

**Comment by mertcanaltin** [comment]
ilgileniyorum @ramazanyigit

**Comment by mertcanaltin** [comment]
#401 @eraygundogmus
