### ISSUE TITLE
[Feature] Drawer içerisinde detay bilgilerinin gösterilmesi

### ISSUE THREAD

**Issue by muum** [acikkaynak/deprem-yardim-frontend#40]
- [x] Belirtilen adresin yoğunluğunun belirtilmesi
- [x] Pinin işaret ettiği açık adresin gösterimi (İl, ilçe, mahalle, cadde/sokak)
- [x] Pinin işaret ettiği açık adresin alt-lon bilgisinin (koordinat) gösterimi
- [x] Verilen lat-lon'a göre Google Harita'lara yönlendirme yapılacak buttonın yaratılması
- [x] Adres bağlantısının default geleceği text fildin yaratılması
- [x] Adre bağlantısının kopyalanabileceği buttonın yaratılması

**Comment by maliksenpai** [comment]
Pr'ını açtım: https://github.com/acikkaynak/deprem-yardim-frontend/pull/59

**Comment by maliksenpai** [comment]
" Adres bağlantısının default geleceği text fildin yaratılması" Hakkında bilgi verebilecek var mı acaba?

**Comment by maliksenpai** [comment]
2. madde hariç hepsi tamamlandı merge edildi @muum
