### ISSUE TITLE
ci/cd: activate dependabot for this repo.

### ISSUE THREAD

**Issue by cdagli** [acikkaynak/deprem-yardim-frontend#409]
## Define your request
Dependabot can help keeping the repo depencies contemporary. My guess, the app wil be in maintenance mode soon and there won't be as many as contributions like nowadays. At least if the PRs are created automatically, maintaining them would be easier in the long term.

## Define the alternatives you have evaluated
Dependabot is working with Yarn 3 right now (https://github.blog/changelog/2022-10-20-dependabot-can-now-generate-security-and-version-updates-for-yarn-v2-and-v3/) but if we experience any issue we can also try  [Renovate](https://github.com/renovatebot/renovate).

## Additional Context
-  Not an emergency need. We can even think for a few weeks later to keep the PR list clean.
- PR Creation frequency can be 1 per week.

**Comment by cdagli** [comment]
@eraygundogmus Sanirim bunun icin admin yetkisi gerekiyor bu arada, biz fanilerin yapabilecegi bir sey degil bildigim kadariyla. Ama acil degil,  sadece almaya niyetlenen birisi olursa belirtmek istedim.

**Comment by fdemir** [comment]
any updates?
