### ISSUE TITLE
feat: Request / payload optimizasyonu

### ISSUE THREAD

**Issue by cdagli** [acikkaynak/deprem-yardim-frontend#412]
## İsteğiniz şeyi tanımlayın 
Mobilde 20-30 px bile kaydirsak yeni request atiyoruz, bu da kullanici deneyimini negatif yonde etkiliyor. (Kisisel gorusum, herhangi bir veri yok elimde)

Fakat bu kadar spesifik lat/lng degerleri ile request atmak yerine birkac digit yuvarlayip request/payload oranini kullanici deneyimini gelistirebilecek sekilde ayarlamayi deneyebiliriz. 

https://api.afetharita.com/feeds/areas?ne_lat=37.596526894784134&ne_lng=36.900989384760535&sw_lat=37.57946070408204&sw_lng=36.89103751438192

ne_lng & ne_lat yukariya, 
sw_lat, sw_lng asagiya yuvarlanirsa request attigimiz rectangle buyumus olur 🤔 

## Değerlendirdiğiniz alternatifleri tanımlayın
Değerlendirdiğiniz herhangi bir alternatif çözüm veya özellik hakkında açık ve kısa bir açıklama.

## Ek Bağlam
Bu özellik isteği hakkında herhangi bir başka bağlam veya ekran görüntüsü ekleyin.

**Comment by cdagli** [comment]
Hemen implement etmeden once artilarini / eksilerini gercek bir problemi cozup cozmedigini tartismak isterim elbette.

**Comment by eraygundogmus** [comment]
Burada benim aklıma gelen kaygı şu yönde, burada digit yuvarlamak yerine, haritadaki pozisyonu track edip, çok ufak değişiklikler için belki istek atan fonksiyonu boş return etmek faydalı olabilir. 

Ama burada yeni bi concern ortaya çıkıyor: 

Ölçek.

**Comment by raxetul** [comment]
Ne kadar yuvarlayacağız, yuvarlama yaparsak ne kadar fayda sağlayacağı belirsiz sanki.

Aktif viewport ile zoom yapılan ya da kaydırılan yönde oluşan 2 fark dikdörtgeni için sorgu atılabilir.

- Siyah aktif viewport
- Kırmızı hedef viewport
- Yeşil ve mavi ise fark dikdörtgenleri

<img width="526" alt="image" src="https://user-images.githubusercontent.com/1366577/217483193-af1233b6-1945-42b2-8411-3e72bd4fba03.png">

Düzlemde yapılabilecek 4 farklı hareket var
- -X ve -Y
- -X ve Y
- X ve -Y
- X ve Y

X ya da Y değerlerinden herhangi birisi sıfır olduğunda tek eksenli olacak ve tek bir dikdörtgen hesaplanacak.

Backend de area-lite ile yalın nokta düzenlemesi şu an aktif çalıştırılamıyor ben bu mesajı yazarken.
Bu şekilde hesaplama ile 1500 nokta yerine 100-200 nokta sorgulaması gider diye düşünüyorum.

**Comment by eraygundogmus** [comment]
https://github.com/acikkaynak/deprem-yardim-frontend/discussions/426
