### ISSUE TITLE
feat: Test framework eklenmesi ve ornek bir testin yazilmasi 

### ISSUE THREAD

**Issue by cdagli** [acikkaynak/deprem-yardim-frontend#420]
## İsteğiniz şeyi tanımlayın 
Eger projeyi uzun soluklu maintain etmek istiyorsak bir sekilde CI uzerinde test etmemiz gerekiyor. Alacagimiz karara gore Jest, testing-library, Cypress, Playwright gibi araclardan faydalanabiliriz. 

## Değerlendirdiğiniz alternatifleri tanımlayın
-

## Ek Bağlam
-

**Comment by cdagli** [comment]
Burada tartisabiliriz oncelikle test stratejimiz ne olmalidir, hangi araclari kullanabiliriz.

**Comment by eraygundogmus** [comment]
önce mock api ile unit test yazmalıyız, imho.
