### ISSUE TITLE
feat: Kullanıcının mevcut konumunun bulunduğu alana yakınlaştırma

### ISSUE THREAD

**Issue by Ecancan** [acikkaynak/deprem-yardim-frontend#422]
## İstek
Uygulamayı kullanan kullanıcının bulunduğu konuma yakın yerlerdeki yardımları daha rahat görebilmesi için kullanıcı konumunu alarak yakınlaştırması, o bölgede bulunan yardım için uygulamayı kullanan kişinin işini kolaylaştıracağını düşünüyorum. 

## Değerlendirilen Alternatif
Otomatik olarak direkt lokasyon bilgisinin alınıp zoom işlemini değerlendirdim. Fakat bu aşamada ilk etapta aniden lokasyon bilgisinı otomatik olarak sorduğundan ve refleks olarak genellikle bu tip bilgiler onay verilmediğinden bu alternatifi gerçekleştirmedim. 

## Ekran Görüntüsü
<img width="1141" alt="Screenshot 2023-02-08 at 12 16 28" src="https://user-images.githubusercontent.com/22291337/217486804-b796131c-eef1-44a1-9145-1875c423ff43.png">

**Comment by eraygundogmus** [comment]
Ürün tarafından böyle bir istek olmadı. Danışmak gerek.

**Comment by krmyildizz** [comment]
Konu ile ilgili işlem yapılıp pr atanmıştır kapatılabilir
