### ISSUE TITLE
feat: Leaflet Hash'in kullanılması

### ISSUE THREAD

**Issue by aerdemsenturk** [acikkaynak/deprem-yardim-frontend#431]
## İsteğiniz şeyi tanımlayın 
URL sonuna dinamik olarak koordinat eklenirse, haritadaki bir alanın zoom level ile birlikte URL olarak paylaşılabilmesine olanak tanır.

## Değerlendirdiğiniz alternatifleri tanımlayın
Leaflet Hash kullanmak sanıyorum basit. 

örnek:
https://mlevans.com/leaflet-hash/map.html#12/37.7771/-122.4128

```
    // Assuming your map instance is in a variable called map
    var hash = new L.Hash(map);
```

https://www.npmjs.com/package/leaflet-hash

## Ek Bağlam
![resim](https://user-images.githubusercontent.com/25268260/217491025-d39a9c18-2ea7-4d9f-836b-2545f00f2e4c.png)

**Comment by eraygundogmus** [comment]
güzel düşünmüşsün. teşekkürler, bu konuda pr bekliyorum

**Comment by yuiji** [comment]
@eraygundogmus bu feature'ı ben alabilirim. Bitmek üzere eğer onaylarsan pull request açacağım biter bitmez.
