### ISSUE TITLE
feat: Leaflet clusterlarin okunulurlugu arttirilmali

### ISSUE THREAD

**Issue by AhmetEnesKCC** [acikkaynak/deprem-yardim-frontend#432]
## İsteğiniz şeyi tanımlayın 
Leaflet-clusterlarin okunulurlugu ui ux prensiplerine uygun olarak arttirilmali. Okunakli degiller. Shadow ozellikle kisilmali.

## Değerlendirdiğiniz alternatifleri tanımlayın
Fontlar gozden gecirildi. Renkler ve opacity duzenlenebilir

## Ek Bağlam

<img width="151" alt="Screen Shot 2023-02-08 at 12 37 13" src="https://user-images.githubusercontent.com/61010746/217491891-b8667e52-ffb1-43f4-998a-d5960358fdb7.png">

**Comment by eraygundogmus** [comment]
+1
