### ISSUE TITLE
feat: List view özelliği

### ISSUE THREAD

**Issue by erzenhaxhi** [acikkaynak/deprem-yardim-frontend#433]
---
name: List view
about: Tum adresleri liste halinde gorecegimiz bir view.
title: 'feat: List view'
labels: ''
assignees: ''

---

## İsteğiniz şeyi tanımlayın 
Uygulamaya list view modunu gelistirerek, map'te olan tum adresleri baska bir view'da listelemek. Bu view'a sehir filtresi gibi filtreler de gelistirilebilir.

## Değerlendirdiğiniz alternatifleri tanımlayın
_Bulunmamaktadır_

## Ek Bağlam
Uygulamin bas kismina bir switch buttonu eklenip map ve list view arasinda gecis yapilabilir.

**Comment by eraygundogmus** [comment]
daha descriptive olabilir misin?

**Comment by khnbzkrt** [comment]
@erzenhaxhi PR standartlara uygun değil rica etsem standart başlıklara göre güncelleyebilir misin?

https://github.com/acikkaynak/deprem-yardim-frontend/blob/development/.github/ISSUE_TEMPLATE/feature_request.md

**Comment by erzenhaxhi** [comment]
@khnbzkrt güncelledim.

**Comment by erzenhaxhi** [comment]
@khnbzkrt güncelledim.

**Comment by eraygundogmus** [comment]
yanlış olmuş yine. tekrar açabilirsin issue'yu
