### ISSUE TITLE
feat: seo meta tagler için yeni yapı oluşturulması

### ISSUE THREAD

**Issue by dopplerDistortion** [acikkaynak/deprem-yardim-frontend#435]
## İsteğiniz şeyi tanımlayın 
- <head> içerisinde bulunan meta taglerin dinamik hale getirilmesi
- sosyal mecralarda görünürlüğü arttırmak için paylaşım spesifik resimler üretilebilmesi
- üretilen resimlerin aynı şekilde image proplarının karşılığında gösterilmesinin sağlanması

## Değerlendirdiğiniz alternatifleri tanımlayın
- resim üretimi için gönderilen parametrelere göre sadece image outputu verebilecek bir edge function yaratılması

## Ek Bağlam
Hedef görüntü olarak tekil bir kaydın sosyal mecralarda paylaşımı sonucu aşağıdaki gibi görünüm sağlanabilmesi

<img width="849" alt="Screenshot 2023-02-08 at 02 19 54" src="https://user-images.githubusercontent.com/1084392/217389166-2c63757d-09db-48ea-9d0d-744e87bde72a.png">

**Comment by eraygundogmus** [comment]
thank you

**Comment by eraygundogmus** [comment]
@dopplerDistortion tekrar açtım issue'yu

**Comment by fdemir** [comment]
tekil kayit icin bir sey tutuyor muyuz? herhangi bir sey yapildi mi orayla alakli?

**Comment by fdemir** [comment]
@eraygundogmus dc

**Comment by berkayvuran** [comment]
@dopplerDistortion bu iş tamamlandı mı? closed görüyorum ama in progress'te, teyit etmek istiyorum.
