### ISSUE TITLE
bug: Tweet undefined geliyor ve loading ekranında kalıyor

### ISSUE THREAD

**Issue by dukeofsoftware** [acikkaynak/deprem-yardim-frontend#436]
## Hata Tanımı
Tweet undefined geliyor ve loading ekranında kalıyor

## Hatayı nasıl aldığınızı adım adım açıklayın

1. Bir lokasyona gidin
4. Hata görünüyor

## Beklenen Davranış
Tweet'in ekranda düzgün bir şekilde gözükmesi
## Ekran Görüntüleri
![image](https://user-images.githubusercontent.com/89215036/217498897-8fd7669d-d98b-472c-8f2b-753478a278e3.png)

## Masaüstü Bilgileri
- İşletim Sistemi: [ Kali Linux]
- Tarayıcı [ edge]

**Comment by canumay** [comment]
Backend API düzeltilene kadar sadece text verisini gösterecek şekilde düzenledik.

#416 (fyi @eraygundogmus )
