### ISSUE TITLE
[Feature] Leaflet ile Google Maps entegrasyonu

### ISSUE THREAD

**Issue by ozcanzaferayan** [acikkaynak/deprem-yardim-frontend#44]
Google Maps key ile birlikte OpenStreetMap yerine GoogleMaps entegre edilecek

**Comment by originalai** [comment]
https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant bundan mi bahsediyoruz?

**Comment by ozcanzaferayan** [comment]
Şu kütüphane aslında 
https://www.npmjs.com/package/react-leaflet-google-layer
