### ISSUE TITLE
bug: cluster pop padding bozukluğu, heading küçüklüğü ve gereğinde büyük butonlar

### ISSUE THREAD

**Issue by cagriatalay** [acikkaynak/deprem-yardim-frontend#444]
## Hata Tanımı
Cluster pop sol padding'de gözle görülebilir bozukluk, heading'in yeteri kadar büyük olmaması ve butonların gereğinden fazla büyük olması.

## Hatayı nasıl aldığınızı adım adım açıklayın

1. Cluster'a tıklayın
2. Hata görünüyor

## Beklenen Davranış
Daha oturaklı bir görünüş

## Ekran Görüntüleri
![aefaefa](https://user-images.githubusercontent.com/90172969/217517421-d174e3b8-5dd8-4d48-864b-26d8a5e23e54.JPG)

## Masaüstü Bilgileri
- Tarayıcı [Brave]
- Sürüm [ v1.48.158]

**Comment by eraygundogmus** [comment]
rc.afetharita.com adresinde kontrol ettin mi?

**Comment by cagriatalay** [comment]
> rc.afetharita.com adresinde kontrol ettin mi?

Rc şuan çalışmıyor
