### ISSUE TITLE
feat: Logo duzenlemesi

### ISSUE THREAD

**Issue by cdagli** [acikkaynak/deprem-yardim-frontend#445]
## İsteğiniz şeyi tanımlayın 
Mevcut logonun buton sanilip tiklanmaya calisildigi bir cok kullanici tarafindan bildirildi. 

<img width="411" alt="image" src="https://user-images.githubusercontent.com/7020369/217518993-d9f212f2-54ea-49e5-a83a-dc170fbbddb3.png">

Logo opacityisi azaltilip kafa karisikligi onune gecilebilir

## Değerlendirdiğiniz alternatifleri tanımlayın
Değerlendirdiğiniz herhangi bir alternatif çözüm veya özellik hakkında açık ve kısa bir açıklama.

## Ek Bağlam
Bu özellik isteği hakkında herhangi bir başka bağlam veya ekran görüntüsü ekleyin.

**Comment by nejatcanunlu** [comment]
Hallediyorum

**Comment by nejatcanunlu** [comment]
Geldi: https://github.com/acikkaynak/deprem-yardim-frontend/pull/449
