### ISSUE TITLE
feat: mock API data for development environment

### ISSUE THREAD

**Issue by mucahitgurbuz** [acikkaynak/deprem-yardim-frontend#450]
## İsteğiniz şeyi tanımlayın 
Gelistirme sirasinda real endpoint sorgularini beklemek ciddi blockerlar arasinda. Repoda static bir API return value belirleyip `process.env.NODE_ENV !== 'production'` durumunda bu datayi donebiliriz. Isimizi oldukca hizlandiracaktir.

## Değerlendirdiğiniz alternatifleri tanımlayın
-

## Ek Bağlam
-

**Comment by eraygundogmus** [comment]
@ozcanzaferayan böyle bi geliştirme yapmıştı sanki

**Comment by akifunal** [comment]
Mock api tarafında verilen url ile şu anda istek atılan url farklı olduğu için böyle bir sorun var. İlgileniyorum.
