### ISSUE TITLE
feat: Sağ üst köşeye diğer sitelerin iconları koyulacak.

### ISSUE THREAD

**Issue by myagizmaktav** [acikkaynak/deprem-yardim-frontend#451]
## Sağ üst köşeye diğer sitelerin iconları koyulacak.

Sağ üst köşeye 25x25px  yuvarlak olarak diğer sitelerimiz iconları koyulacak ve bu iconlar tıklandığında diğer siteleri yeni sayfada açıcak.
Ve eğer üstlerine gelindiğinde kısaca sitelerin ne konuda çözüm ürettiği hakkında açıklama çıkıcak.

açıklamayı mui popover ile yapabilirsiniz.
https://mui.com/material-ui/react-popover/

### Siteler
- Deprem.io
- Depremyardim.com
- discord.gg/itdepremyardim

**Comment by emirefek** [comment]
DC'de yetkim yok ama alabilirim. Diğer sitelerin linkleri nedir?

**Comment by cdagli** [comment]
Bence bunu yapmadan once bir tasarimi refactor etmek lazim. Yukarisi kalabalik zaten. 

<img width="393" alt="image" src="https://user-images.githubusercontent.com/7020369/217585594-05e6c6bb-7248-48a2-add0-a0db557c1e66.png">

**Comment by myagizmaktav** [comment]
çoğu bitti sol üste yapiyorum.

**Comment by OrhanOzkercin** [comment]
Bunu yapiyorum, fyi.

**Comment by eytanfb** [comment]
PR'a not dustum buraya da yazayim.

Soyle bir ekleme suggestion'im var eger degerlendirmek isterseniz. Yukleniyor yazisi ve otomatik yuklenme yazilarini ayni butonun icine alip alandan kazanabiliriz. Ozellikle mobil icin kazanc olacaktir bence.

**Desktop**
![Screenshot 2023-02-08 at 3 42 11 PM](https://user-images.githubusercontent.com/1498968/217677199-794efa48-faa8-4295-864e-5366918416d1.png)

![Screenshot 2023-02-08 at 3 41 57 PM](https://user-images.githubusercontent.com/1498968/217677201-62aebee5-d1be-4d10-8b40-f386d8133d29.png)

![Screenshot 2023-02-08 at 3 41 23 PM](https://user-images.githubusercontent.com/1498968/217677202-1cbaa865-6738-4320-87af-b4c79087d627.png)

**Mobil**
![Screenshot 2023-02-08 at 3 44 11 PM](https://user-images.githubusercontent.com/1498968/217677254-c34d29d0-ce8f-49c1-9414-6d8eaa191bb6.png)

![Screenshot 2023-02-08 at 3 43 56 PM](https://user-images.githubusercontent.com/1498968/217677257-86117664-9dab-46b9-a8f3-7474aa762014.png)

![Screenshot 2023-02-08 at 3 43 39 PM](https://user-images.githubusercontent.com/1498968/217677260-f1df02e7-5ebd-47d4-ad06-cf2fb7c9ad32.png)

Eger kabul edilirse kodu yazdim, PR'i acabilirim.

**Comment by OrhanOzkercin** [comment]
Pr acilmis o sebeple birakiyorum. fyi
