### ISSUE TITLE
bug: cluster pop-up responsivity problems and cannot use zoom/pan on the map when cluster popup is open

### ISSUE THREAD

**Issue by ramazanyigit** [acikkaynak/deprem-yardim-frontend#454]
## Hata Tanımı
Cluster popup acildiginda harita kontrollerini kullanamiyoruz. Ayrica cluster pop-up mobilde ekranin yarisini kapliyor gorsel guncelleme yapilacak.

## Hatayı nasıl aldığınızı adım adım açıklayın

1. Haritada herhangi bir cluster groupa tiklayin.
2. Haritadaki cluster popup acildiginda haritaya tekrar tiklanana kadar zoom/pan yapilmiyor.

## Beklenen Davranış
Cluster popup acikken haritada zoom/pan yapilabilmelidir.

## Ekran Goruntuleri
![image](https://user-images.githubusercontent.com/54190298/217589122-803764e8-44a5-4726-aeb7-f437da44e24d.png)

## Masaüstü Bilgileri
- İşletim Sistemi: Windows
- Tarayıcı: Brave
- Sürüm: 1.47.186 - Chromium: 109.0.5414.119

## Ek Bağlam
Sorun hakkında diğer herhangi bir bağlamı burada ekleyin.

**Comment by metinerdempat** [comment]
Koda baktığımda useEffect ile eventler engelleniyor, sebebi bu. Eğer bu engellemelerin başka bir işlevi yoksa kaldırabilirim.

**Comment by ramazanyigit** [comment]
Bu isle ben ilgileniyorum su anlik @metinerdempat

**Comment by ramazanyigit** [comment]
Yok yok oyle bir durum yok issue sahipli ondan dedim, tesekkurler tekrardan :)

**Comment by eraygundogmus** [comment]
Bu çözülmemiş miydi? @ramazanyigit

**Comment by ramazanyigit** [comment]
Bu is bendeydi; cozerken cluster pop-up'in gorunusunu de toparladim

**Comment by eraygundogmus** [comment]
1. conflict var, 
2. ben böyle bi sorun göremiyorum rc'de

**Comment by eraygundogmus** [comment]
@ramazanyigit

**Comment by ramazanyigit** [comment]
1. conflicti cozmustum pr alinmistir hallederim
2. cluster group sec sonra mapte pan yapmaya calis bosluga tiklamadan

**Comment by ramazanyigit** [comment]
Bir goz atabilir misin @eraygundogmus
