### ISSUE TITLE
Kayıt Sonrası Reload ve CTRL+F Bilgi Yazısı

### ISSUE THREAD

**Issue by mfc003** [acikkaynak/deprem-yardim-frontend#46]
https://www.depremyardim.com/ sitesine kayıt ekledikten sonra sitenin güncellenmesi için reload, refresh eklenirse yeni kayıtların da düşmesi sağlanabilir. Ayrıca aynı kayıtların girilmemesi için ctrl+F yapılması hakkında bilgi yazısı koyulabilir.

**Comment by alperencantez** [comment]
WebSockets implenetasyonu ile daha kolay olabilir sanki bu öneriniz.

**Comment by bedirhanyildirim** [comment]
O proje bu repo içerisinde yer almıyor.

**Comment by cengizcmataraci** [comment]
Bu repo ile alakasız bir konu, @eraygundogmus bunu kapatabiliriz sanırım.
