### ISSUE TITLE
feat: Belirli alanların ekran görüntüsünü alıp png/jpg şeklinde export alınması 

### ISSUE THREAD

**Issue by yakutozcan** [acikkaynak/deprem-yardim-frontend#461]
## İsteğiniz şeyi tanımlayın 
Yavaş internet sorunu olanlar için ve ekipler ile paylaşmayı kolaylaştırmak adına belirli alanların veya enkazların export alınması eklenebilir mi ?

**Comment by eraygundogmus** [comment]
@yakutozcan benzer bir çalışma yapılıyor abi, sevgiler <3
