### ISSUE TITLE
feat:  Konum arama input bar

### ISSUE THREAD

**Issue by ygzaydn** [acikkaynak/deprem-yardim-frontend#467]
App'in sağ veya sol üzerine konum aramak için bir input bar eklenir ise, belirli bir bölgeyi arayacak kişilerin hızlıca bölgeye ulaşması sağlanabilir. Girilen konum query edilerek koordinata çevirillip ekranın ortasına gösterilebilir.

**Comment by aerdemsenturk** [comment]
Adres arama kesinlikle çok faydalı olur.

Burada bir paket var:
https://www.npmjs.com/package/leaflet-search

Nominatim API adresler için kullanılabilir:
https://opengeo.tech/maps/leaflet-search/examples/geocoding-nominatim.html

Keşke ben yardımcı olabilsem ama teknik bilgim yeterli değil.

**Comment by emirefek** [comment]
Bu issue üzerinde uğraşıyorum. Daha hızlı çözüm üretebilmek adına bir sorum var.
map'i kontrol edebilecek hooklar var mı projede. setCoordinates adında bir hook buldum fakat nasıl kullanılacağını çözemedim. LngLat, verileri ile nasıl harita kontrolü sağlayabilirim ?

**Comment by aerdemsenturk** [comment]
Doğru anladıysam, flyTo işinizi görecektir. Adrese tıkladığında koordinata zıpla:

https://gis.stackexchange.com/questions/168687/fly-to-location-in-leaflet
https://leafletjs.com/reference.html#map-flyto

flyTo(<LatLng> latlng, <Number> zoom?, <Zoom/pan options> options?)

Example:

flyTo([13.87992, 45.9791], 12)

**Comment by emirefek** [comment]
> flyTo([13.87992, 45.9791], 12)

süper bu işime yarar. map method'larına bir komponentten nasıl erişmeliyim? Global bir context veya store var mı?

**Comment by JusticeBoi** [comment]
Previewa baktim suan ve bi önerim olucakti: Arama butonuna basildiginda direk yazmaya baslanabilse daha iyi olur mu acaba? Yani suan önce arama butonuna sonra da yer araya basmak gerekiyor. Tek hamlede yazmaya baslamak bana daha kullanici dostu geliyor.

**Comment by emirefek** [comment]
> Previewa baktim suan ve bi önerim olucakti: Arama butonuna basildiginda direk yazmaya baslanabilse daha iyi olur mu acaba? Yani suan önce arama butonuna sonra da yer araya basmak gerekiyor. Tek hamlede yazmaya baslamak bana daha kullanici dostu geliyor.
- @JusticeBoi 

Feedback için teşekkürler, dediğiniz şekilde AutoFocus ekledim. Teşekkürler. Artık PR otomatik focus oluyor.

**Comment by Ecancan** [comment]
> > flyTo([13.87992, 45.9791], 12)
> 
> süper bu işime yarar. map method'larına bir komponentten nasıl erişmeliyim? ~Global bir context veya store var mı?~ useMap hook'unu kullanıyorum.

useMap hookunu kullanıldığında context hatası alabilirsin. Sana yüklenen map instance değeri gerekir. Kullanıcı lokasyon bilgisini alıp zoomladığım pr vardı kapatıldı böyle bir istek yok diye. Dilersen oradaki map verisi üzerinden ilerleyebilirsin @emirefek 

https://github.com/acikkaynak/deprem-yardim-frontend/pull/425
