### ISSUE TITLE
bug: hata ekranında alanı tara butonu görünüyor

### ISSUE THREAD

**Issue by eraygundogmus** [acikkaynak/deprem-yardim-frontend#468]
## Hata Tanımı
Rc'deki sürümümüzde hata ekranında alanı tara butonu görünüyor

## Hatayı nasıl aldığınızı adım adım açıklayın

1. Backende atılan isteği blocklayın
2. Hata görünüyor

## Beklenen Davranış
Görünmemesi

## Ekran Görüntüleri
<img width="1438" alt="Screen Shot 2023-02-08 at 16 37 43" src="https://user-images.githubusercontent.com/74984741/217545497-0394af2b-6491-4ee6-9d2b-b8a125f3cebe.png">

**Comment by absolutezero13** [comment]
ben alabilirim uygunsa

**Comment by akifunal** [comment]
Maintenance aynı page içerisinde çalıştığı için button görünüyor. /maintenance gibi bir url'e alınması hızlı çözüm olur gibi. @absolutezero13

**Comment by eraygundogmus** [comment]
PR beklyorum.

**Comment by eraygundogmus** [comment]
@absolutezero13
