### ISSUE TITLE
bug: Title 

### ISSUE THREAD

**Issue by fferhan** [acikkaynak/deprem-yardim-frontend#470]
## Hata Tanımı
Hatanın ne olduğu hakkında açık ve kısa bir açıklama.

## Hatayı nasıl aldığınızı adım adım açıklayın

1. '...' a gidin
2. '....' ye tıklayın
3. '....' ye kaydırın
4. Hata görünüyor

## Beklenen Davranış
Beklediğiniz şeyin açık ve kısa bir açıklaması.

## Ekran Görüntüleri
Uygulanabilirse, sorununuzu açıklamak için ekran görüntüleri ekleyin.

## Masaüstü Bilgileri
- İşletim Sistemi: [örneğin iOS]
- Tarayıcı [örneğin chrome, safari]
- Sürüm [örneğin 22]

## Akıllı Telefon Bilgileri
- Cihaz: [örneğin iPhone6]
- İşletim Sistemi: [örneğin iOS8.1]
- Tarayıcı [örneğin varsayılan tarayıcı, safari]
- Sürüm [örneğin 22]

## Ek Bağlam
Sorun hakkında diğer herhangi bir bağlamı burada ekleyin.

**Comment by cdagli** [comment]
Yanlislikla acildi galiba, kapatiyorum.
