### ISSUE TITLE
feat: Yukleniyor mesaji ile "bu alani tara" butonu birlestirme

### ISSUE THREAD

**Issue by cdagli** [acikkaynak/deprem-yardim-frontend#472]
## İsteğiniz şeyi tanımlayın 
Bu ikisini birlestirebiliriz 

`isLoading`, `isValidating` oldugunda MUILoading button stateini set edebiliriz: 

https://mui.com/material-ui/api/loading-button/

Ya da sadece basitce butonu disable edip textini degistirebiliriz. 

<img width="416" alt="image" src="https://user-images.githubusercontent.com/7020369/217550030-f972ac71-33b2-478b-84ab-75bb11c15411.png">

## Değerlendirdiğiniz alternatifleri tanımlayın
Değerlendirdiğiniz herhangi bir alternatif çözüm veya özellik hakkında açık ve kısa bir açıklama.

## Ek Bağlam
Bu özellik isteği hakkında herhangi bir başka bağlam veya ekran görüntüsü ekleyin.

**Comment by cdagli** [comment]
@hasanugr bu iconlari kullanirsak attribute etmemiz gerekir, MUI icerisinden bir seyler kullanirsak daha kolay olacaktir diye dusunuyorum.

**Comment by hasanugr** [comment]
@cdagli Doğru söylüyorsun, önerim benzer bir şekilde farklı icon ile uygulanabilir. MUI içinden birşey seçip ekran kaplamasını azaltıp tek icon ile basitleştirebiliriz hala bu durumu.

**Comment by teomanofficial** [comment]
Butonu her halükarda disable etmemiz gerekiyor. Tekrarlayan isteklerden kaçınmak için. Bunun dışında

**Comment by denizsult** [comment]
Ben alıyorum

**Comment by usirin** [comment]
@denizsult PR acabilirsen bakalim

**Comment by eytanfb** [comment]
ben bunun issue'su oldugunu gormeden yaptim. @denizsult bir kac saattir yazmadigini gordugum icin aciyorum

**Comment by aliilhami** [comment]
@eytanfb bu ilerledi mi? ilerliyorsa issue'yu üstlenebilir misin?

**Comment by eytanfb** [comment]
@aliilhami bu issue kapanmis gorunuyor. eksik birsey mi var?

**Comment by berkayvuran** [comment]
@cdagli bu iş tamamlandı mı? closed görüyorum ama in progress'te, teyit etmek istiyorum.

**Comment by denizsult** [comment]
https://github.com/acikkaynak/deprem-yardim-frontend/pull/531 merge edilmiş
