### ISSUE TITLE
bug: "Bu alani tara" butonu bakim ekraninda goruntuleniyor

### ISSUE THREAD

**Issue by cdagli** [acikkaynak/deprem-yardim-frontend#477]
## Hata Tanımı
"Bu alani tara" butonu bakim ekraninda gorunuyor. 

Ayrica bakim ekrani Iphone SE ekranina sigmiyor. 

## Hatayı nasıl aldığınızı adım adım açıklayın

1. Bakim sayfasina gidin (requesti developer toolsdan blocklayabilirsiniz) 

## Beklenen Davranış
Bu alani tara butonu bakim ekraninda goruntulenmemeli 

## Ekran Görüntüleri
<img width="481" alt="image" src="https://user-images.githubusercontent.com/7020369/217566155-c4adf099-fc00-4aba-beef-a1cb82f93250.png">

## Masaüstü Bilgileri
- İşletim Sistemi:  Mac
- Tarayıcı Chrome
- Sürüm [örneğin 22]

## Akıllı Telefon Bilgileri
- Cihaz: [örneğin iPhone6]
- İşletim Sistemi: [örneğin iOS8.1]
- Tarayıcı [örneğin varsayılan tarayıcı, safari]
- Sürüm [örneğin 22]

## Ek Bağlam
Sorun hakkında diğer herhangi bir bağlamı burada ekleyin.

**Comment by eraygundogmus** [comment]
duplicate #468
