### ISSUE TITLE
bug:  Google Oturum açmış kullanıcı ile yol tarifi bilgisinin alınamaması

### ISSUE THREAD

**Issue by koraysaldere** [acikkaynak/deprem-yardim-frontend#478]
## Hata Tanımı
Google Oturum açmış kullanıcı ile yol tarifi bilgisinin alınamaması

## Hatayı nasıl aldığınızı adım adım açıklayın

1. https://afetharita.com gidin.
2. Açılan haritadan herhangi bir konum imi simgesine tıklayın.
3. Açılan sol menüde Yol Tarifi Al butonuna basın.
4. Açılan Google Maps sayfasında haritada yönlendirme yapılmadığı görünüyor.
5. Location alanında mevcut location bilgisi yerine "My Location ibaresi görünüyor . 
6. Altta kayıtlı location bilgilerinde biri seçildiğinde yine yönlendirme yapamıyor.

## Beklenen Davranış
Google Maps yönlendirmesi sonucunda location ve destiny location bilgilerinin doğru şekilde gelmesi ve yönlendrimenin direkt olarak yapılması.

## Ekran Görüntüleri
Uygulanabilirse, sorununuzu açıklamak için ekran görüntüleri ekleyin.

![image](https://user-images.githubusercontent.com/42040766/217566987-01fd66b3-70d5-4833-b8c5-55c6aef87fa8.png)

![image](https://user-images.githubusercontent.com/42040766/217566805-d5df72d3-e107-4aaf-a1f1-0455b2514953.png)

## Masaüstü Bilgileri
- İşletim Sistemi: [Windows]
- Tarayıcı [chrome, opera]
- Sürüm [109.0.5414.120]

## Akıllı Telefon Bilgileri
- Cihaz: [Mi 8 Lite android]
- İşletim Sistemi: [8.1.0]
- Tarayıcı [varsayılan tarayıcı, chrome]
- Sürüm []

## Ek Bağlam
Sorun hakkında diğer herhangi bir bağlamı burada ekleyin.

**Comment by aerdemsenturk** [comment]
Yol tarifi URL'sindeki parametreler sorunlu sanıyorum.
https://www.google.com/maps?saddr=My+Location&daddr=36.2027419,36.1548184
saddr=My+Location kısmı yanlış. Bunu metin olarak ele alıyor.

Yol tarifi url'sini şöyle dener misiniz:

https://www.google.com/maps/dir/?api=1&destination=36.2027419,36.1548184
@eraygundogmus

**Comment by aerdemsenturk** [comment]
https://www.google.com/maps?saddr=My+Location&daddr=36.2027419,36.1548184
Bu masaüstünde bende de çalışmıyor. Başlangıç noktasına My Location'u text olarak ekliyor o kadar.

Bu çalışıyor ama:
https://www.google.com/maps/dir/?api=1&destination=36.2027419,36.1548184

**Comment by koraysaldere** [comment]
Durumu şöyle özetliyeyim, Masaüstünde eğer bir Google hesabı ile login olunmamış ise konum ve yönlendirme bilgisi geliyor.
Login ise; issue ekran görüntüsündeki gibi My Location bilgisi dönüyor.
Mobilde ise zaten android cihazda halihazırda bir Google hesabı ile bağlı olduğundan, My Location ile Google haritalara imlenmiş Mekan bilgilerini getiriyor. 

@teomanofficial  konum servislerim açık.

![image](https://user-images.githubusercontent.com/42040766/217595775-b0fcfd06-dcf2-46e3-9c0a-670a7f8ffbbe.png)
