### ISSUE TITLE
feat: Google Maps Marker

### ISSUE THREAD

**Issue by cemiluzunhasan** [acikkaynak/deprem-yardim-frontend#479]
## İsteğiniz şeyi tanımlayın 
Google Maps yonlendirmesinde konuma marker koyma

## Değerlendirdiğiniz alternatifleri tanımlayın
Cozum olarak "google maps ile ac" yonlendirmesindeki linke gerekli lat lng parametreleri eklenerek bos bir alan yerine uzerine marker atilmis bir alan acilabilir.

Eger gelistirme yapilmadiysa daha oncesinde uygulamaya katkim mevcut. Bu gorevi de ustlenecek zamanim var seve seve de yapabilirim. Simdiden tekrar elinize saglik

## Ek Bağlam
Su anki koyacagim fotografta konum belli fakat bir marker'in koyulmasi gereken bazi konumlar cikabilir. Bence guzel bir gelistirme olur. 
<img width="1680" alt="Screenshot 2023-02-08 at 16 01 52" src="https://user-images.githubusercontent.com/29410269/217567316-76abfb8f-1265-492f-8ee7-8bbeed38b1bc.png">
<img width="1680" alt="Screenshot 2023-02-08 at 16 02 09" src="https://user-images.githubusercontent.com/29410269/217567365-a62eb96e-848e-4c51-8403-c70897740150.png">

**Comment by ytkimirti** [comment]
Maps dökümantasyonu şu şekilde https://developers.google.com/maps/documentation/urls/get-started#directions-action, doğru url'nin ne olması gerektiğine bakıyorum

**Comment by ytkimirti** [comment]
Url'nin `https://www.google.com/maps/dir/?api=1&destination=<konum>` şeklinde olması gerekiyormuş bir pr açıyorum

**Comment by cemiluzunhasan** [comment]
Oncelikle issue'nun onaylanip atanmasi gerekiyor @ytkimirti

**Comment by ytkimirti** [comment]
@cemiluzunhasan kusura bakmayın başka issue ile bunu karıştırmışım 🤦
