### ISSUE TITLE
bug: Bu Alani Tara buttonu iki defa request gonderiyor

### ISSUE THREAD

**Issue by kemalunal** [acikkaynak/deprem-yardim-frontend#481]
## Hata Tanımı
Bu Alani Tara buttonu'na tiklandigi zaman iki defa request atiliyor, data dogru gelmiyor

## Hatayı nasıl aldığınızı adım adım açıklayın
ilk acilan harita bolgesini degistirip "Bu Alani Tara" butonuna tiklayin

## Beklenen Davranış
"Bu Alani Tara" butonuna tiklandiginda tek request atilmasi ve markerlarin ekran icindeki bolgede gorunmesi

**Comment by gizemnkorkmaz** [comment]
Selamlar @kemalunal,
Issue title kısmını uygun şekilde düzenleyebilir misin?

https://github.com/acikkaynak/deprem-yardim-frontend/blob/development/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by eraygundogmus** [comment]
Kanıt ekleyebilir misin? @kemalunal

**Comment by kemalunal** [comment]
@cdagli aslind tam fixlemiyor sanki ama deploy ile kontrol edelim, deploy oldugunu nerden gorebilirim ?

**Comment by keislamoglu** [comment]
> @cdagli aslind tam fixlemiyor sanki ama deploy ile kontrol edelim, deploy oldugunu nerden gorebilirim ?

https://rc.afetharita.com/

buradan deneyebilirsin

**Comment by eraygundogmus** [comment]
closed
