### ISSUE TITLE
bug: UI'da halt/freeze sorunu söz konusu

### ISSUE THREAD

**Issue by denizsult** [acikkaynak/deprem-yardim-frontend#484]
## Hata Tanımı
Interval güncellendiğinde veya harita hareket ettirildiğinde donmalar yaşanıyor

## Hatayı nasıl aldığınızı adım adım açıklayın

1. https://rc.afetharita.com/ 'a gidin
2. Haritayı kaydırın
3. Ui kısmında drop'u fark edeceksiniz
 

## Beklenen Davranış
Donma olmaması

## Ekran Görüntüleri
Uygulanabilirse, sorununuzu açıklamak için ekran görüntüleri ekleyin.

## Masaüstü Bilgileri
- İşletim Sistemi: Mac OS
- Tarayıcı: Chrome 
- Sürüm: 110.0.5481.77 

## Ek Bağlam
Asenkron/await var ise bu soruna sebep olabilir veya callstack'i yoruyor olabilir.

**Comment by erenkulaksiz** [comment]
benim gözlemim ekranı kaydırırken üstteki sayaç 30 saniyeye geri dönerken ui dönüyor

**Comment by denizsult** [comment]
> benim gözlemim ekranı kaydırırken üstteki sayaç 30 saniyeye geri dönerken ui dönüyor

O sırada api isteği atıyor ve map render olurken kasma yaşanıyor sanırım

**Comment by erenkulaksiz** [comment]
> > benim gözlemim ekranı kaydırırken üstteki sayaç 30 saniyeye geri dönerken ui dönüyor
> 
> O sırada api isteği atıyor ve map render olurken kasma yaşanıyor sanırım

O sırada api isteği atmıyor. Network ile ilgili bir sorun değil.

**Comment by kemalunal** [comment]
ilk 30sn den sonra sure sekildeki gibi oluyor sonra tekrar butona tiklandiginda 30sn tekrar basliyor 

![Screenshot 2023-02-08 at 17 18 02](https://user-images.githubusercontent.com/3184435/217589097-170be751-2150-4893-8ef9-5de0fe0a04c6.png)

**Comment by erenkulaksiz** [comment]
sorun router olabilir mi? 
![Screenshot_22](https://user-images.githubusercontent.com/44942737/217591874-1da1aca5-420a-4122-a267-344e5e901a79.png)
dev de boyle bir exception geliyor?

**Comment by erenkulaksiz** [comment]
> sorun router olabilir mi? ![Screenshot_22](https://user-images.githubusercontent.com/44942737/217591874-1da1aca5-420a-4122-a267-344e5e901a79.png) dev de boyle bir exception geliyor?

sorun router'da. push yerine replace kullanabiliriz. bu issue'yi devralabilirim FYI @eraygundogmus

**Comment by yuiji** [comment]
> > sorun router olabilir mi? ![Screenshot_22](https://user-images.githubusercontent.com/44942737/217591874-1da1aca5-420a-4122-a267-344e5e901a79.png) dev de boyle bir exception geliyor?
> 
> sorun router'da. push yerine replace kullanabiliriz. bu issue'yi devralabilirim FYI @eraygundogmus

router.push() yerine window.history.replaceState() kullanmak sorunu çözüyor sanırım. router.replace() ile aynı sorunu yaşadım local'de.

**Comment by denizsult** [comment]
> > > sorun router olabilir mi? ![Screenshot_22](https://user-images.githubusercontent.com/44942737/217591874-1da1aca5-420a-4122-a267-344e5e901a79.png) dev de boyle bir exception geliyor?
> > 
> > 
> > sorun router'da. push yerine replace kullanabiliriz. bu issue'yi devralabilirim FYI @eraygundogmus
> 
> router.push() yerine window.history.replaceState() kullanmak sorunu çözüyor sanırım. router.replace() ile aynı sorunu yaşadım local'de.
> 
> [vercel/next.js#18072 (comment)](https://github.com/vercel/next.js/discussions/18072#discussioncomment-109059)

o şekilde çalışabilir ben de denedim oldu

**Comment by yuiji** [comment]
Şu an bu bug üzerine çalışan birisi yoksa ben alabilirim.

**Comment by usirin** [comment]
@yuiji baslayabilirsin
