### ISSUE TITLE
feat: improving lighthouse scores

### ISSUE THREAD

**Issue by eraygundogmus** [acikkaynak/deprem-yardim-frontend#486]
## Define your request
We should aim to get high scores from tools that test accessibility, seo and performance, such as Google Page Insights and Lighthouse, and work in this direction.

**Comment by EmirBoyaci** [comment]
Gece test ettiğimde lighthouse performansı 93+ geliyordu, şu an dışarıda olduğum için test etme şansım yok. Ayrıca, performans kısmı önemli ama erişilebilirlik kısmına da önem vermemiz gerektiğini düşünüyorum. Aynı şekilde, dün gece baktığımda erişilebilirlik 100 geliyordu. Yine kontrol etmek gerekebilir.

**Comment by quatronostro** [comment]
![image](https://user-images.githubusercontent.com/93223660/217599957-b5cd6f98-36bc-4d4e-8990-ac6e22ba2ec4.png)

Google page insights bu şekilde

**Comment by fdemir** [comment]
@quatronostro mobil icin test eder misin?

**Comment by EmirBoyaci** [comment]
> @quatronostro mobil icin test eder misin?

rc icin mi prod icin mi?

**Comment by EmirBoyaci** [comment]
## ! Bakılması mantıklı olan RC çünkü develop'tan main'e merge olacak.

## RC Desktop
![rc-desktop](https://user-images.githubusercontent.com/59085992/217622860-e5b8e5f6-e45b-4ecb-99a4-2a5ce5661240.png)

## RC Mobil
![rc-mobil](https://user-images.githubusercontent.com/59085992/217622882-2b592e4b-c30e-4703-ab44-5dac26498578.png)

<br />

## PROD Desktop
![prod-desktop](https://user-images.githubusercontent.com/59085992/217622976-8ce4a7c5-080c-4706-99d9-d1796567bd12.png)

## PROD Mobil
![prod-mobil](https://user-images.githubusercontent.com/59085992/217623002-3146d910-eea8-4a59-bf35-60be268fe1c6.png)

**Comment by EmirBoyaci** [comment]
Lighthouse testleri için mutlaka Misafir profili (veya boş profil açıp) kullanılması gerekiyor. Gizli sekme yeterli değil, tarayıcı eklentileri sayfaya müdahale edebiliyor eğer gizli sekmede izin verildi ise.

**Comment by canerakin111** [comment]
@eraygundogmus Projeyi unutmayalim.
