### ISSUE TITLE
feat: Google haritalara yönlenildiğinde, konumu marker ile gösterme

### ISSUE THREAD

**Issue by absolutezero13** [acikkaynak/deprem-yardim-frontend#490]
## İsteğiniz şeyi tanımlayın 
Google haritalar yönlendirmesi doğru bir şekilde yapılıyor fakat konum şu anda haritada herhangi bir marker vs. ile gösterilmiyor. 

## Değerlendirdiğiniz alternatifleri tanımlayın
Google maps'in alternatif bir url'i var, denedim ve başarılı bir şekilde konumu marker ile gösterdim. 

Approve olduğunda pr açabilirim.

## Ek Bağlam
Marker ile birlikte sol tarafta konum ile ilgili resim, bilgi vs. de çıkıyor. Bu da ekstra bir fayda sağlayabilir.

**Comment by cdagli** [comment]
Duplicate https://github.com/acikkaynak/deprem-yardim-frontend/issues/479 ?

**Comment by absolutezero13** [comment]
> Duplicate #479 ?

doğru görmemişim
