### ISSUE TITLE
feat: User guide

### ISSUE THREAD

**Issue by maliksenpai** [acikkaynak/deprem-yardim-frontend#491]
## Define your request
It seems like a small information box is needed so that users can navigate the page more easily and understand the application better. Therefore, this information box was designed and coded within the team for this.

## Define the alternatives you have evaluated
The best way to inform the user without disturbing can be the information box.

## Additional Context
Screenshot:

![image](https://user-images.githubusercontent.com/37189443/217599854-60fa825e-2edf-4eee-8f21-c0b061a32bf6.png)

**Comment by maliksenpai** [comment]
Ayrıca geliştirilmesi tamamlanmıştır.

**Comment by aerdemsenturk** [comment]
Metodoloji açıklaması da bu bilgi kutusuna dahil edilebilir.

https://github.com/acikkaynak/deprem-yardim-frontend/issues/465

**Comment by maliksenpai** [comment]
İleride onu de ekleyebiliriz ben de buradaki açıklamaları zaten "çabucak-ogren.md" dosyasından aldım.

**Comment by khnbzkrt** [comment]
approve olması durumunda ben üstlenebilirim 👍

**Comment by maliksenpai** [comment]
@khnbzkrt kodlamayı yaptım bile, sadece onaylanmasını bekliyorum da.

**Comment by maliksenpai** [comment]
pr'ını açtım, onaylanırsa merge edilebilir pr: https://github.com/acikkaynak/deprem-yardim-frontend/pull/514

**Comment by maliksenpai** [comment]
3. kez açıklamasız closed yedim, pes ediyorum. @khnbzkrt eğer isterseniz siz yapabilirsiniz.

**Comment by maliksenpai** [comment]
Buraya bakan birileri var mı?

**Comment by maliksenpai** [comment]
Buraya bakabilir misiniz? @eraygundogmus kod hazır tasarım hazır, onaylanır onaylanmaz pr açılabilir bir issue. Eğer istenmiyorsa kapatalım.

**Comment by EmirBoyaci** [comment]
cc: @usirin

**Comment by ozcanzaferayan** [comment]
Selam bence güzel approve ediyorum

**Comment by handekaratas96** [comment]
@canerakin111 @eraygundogmus bunu Canerle konuştuk, haritada yeni eklenenlerle birlikte kullanım zorluğu yaratıyor olabiliriz, daha açıklayıcı olmak adına bu taskı geri açmamız gerekli @Batuhandgenc @senapalaa beraber çalışabilir misiniz gerektiğinde ben de destek olurum

**Comment by maliksenpai** [comment]
@handekaratas96 eğer yazıyı görüşebilirsek güncelleyebilirim. Kodu hazır sadece text hazırlanırsa tekrardan güncelleyebilirim.

**Comment by maliksenpai** [comment]
Discord ismim: MalikSenpai#8572

**Comment by maliksenpai** [comment]
Design kısmı zaten ekip tarafından tasarlandı ayrıca, refactore gerek var mı bilmiyorum

**Comment by handekaratas96** [comment]
selam aynen o zaman bence de ama mobilde pop up mı bu arada? @maliksenpai isterseniz şöyle yapalım: @senapalaa sen texti hazırlattığında hazır geliştirmeyle nasıl göründüğüne test ortamında bakar karar veririz ne dersiniz? @eraygundogmus

**Comment by maliksenpai** [comment]
@handekaratas96 evet mobilde de aynı şekilde. Buttona tıklanır ve popup üzerinde bilgi verilir. Mobil için ekranda daha büyük yer kaplıyor anlaşılır olması için.

**Comment by berkaydesign** [comment]
Design is done for this issue. You can check it out on Figma. @maliksenpai 

![image](https://user-images.githubusercontent.com/65855467/218264014-1ce8c076-c469-447e-aa55-7076679a3e28.png)

**Comment by maliksenpai** [comment]
@berkaydesign good work, I will work on it, thank you.

**Comment by fdemir** [comment]
@maliksenpai do u have any update?

**Comment by maliksenpai** [comment]
@fdemir I worked a little but I'm busy right now. But i will finish as soon as I can, probably tonight will finish.
