### ISSUE TITLE
bug: False position statement in similar addresses

### ISSUE THREAD

**Issue by quatronostro** [acikkaynak/deprem-yardim-frontend#494]
## Bug definition
A clear and short description about the bug.
I saw a few pins near Mersin, i clicked one of those and i determined there is a false position statement via the source message.
## Describe how you are producing the bug step by step

1. Go to 'https://afetharita.com/#lat=36.806171760853076&lng=34.6024773598815&zoom=12'
2. Click to 'Pin that is slight over the Mersin text'
3. You will understand if you compare those "Çağdaşkent" text in "Yardim Icerigi" address is not Mersin, is Elbistan 

## Expected Behaviour
I have no idea how to fix the situation that such places with the same name are in other provinces and districts.

## Screenshots
![image](https://user-images.githubusercontent.com/93223660/217604675-c844a46f-d821-45cd-86e2-3718976c8345.png)
Displayed address

![image](https://user-images.githubusercontent.com/93223660/217604798-5e24fa6e-cc11-4447-803e-b420499d7574.png)
Exprected address

## Desktop Information
- Operating System: windows
- Browser: Chrome
- Version109.0.5414.121 (Official compilation) (64 bit) Version

## Additional Context
Add any other context about the bug here

**Comment by can101** [comment]
bu olay haritanin genelinde bulunuyor galiba tweet atmis olan kullanicin adresinimi buluyoruz.

**Comment by hasanugr** [comment]
Data ekibine iletilmesi gerekiyor bunun, birçok adreste bu durum mevcut.

**Comment by JusticeBoi** [comment]
Acaba hatali adresleri raporlama gibi bi sistem kullanisli olur mu, konuma basinca acilan Drawer'a bir buton gibi. Hatali olanlari da data ekibi inceleyebilir.

**Comment by quatronostro** [comment]
Aynen ya da "kaynak ile yardım içeriği uyuşmuyor" gibi bir buton da iş görebilir

**Comment by canerakin111** [comment]
Data ekibi hali hazirda bunun uzerinde calisiyor. Bu issue'yu da yonlendiriyorum.

**Comment by younver** [comment]
Bu problemle alakalı bulunan adreslerden yoğun olan bölgeye yakın olanın seçilmesini sağlayan bir algoritma yazdım. Backend tarafında bir [PR](https://github.com/acikkaynak/deprem-yardim-backend/pull/135)'im mevcut.

**Comment by cdagli** [comment]
@canerakin111 Approved eklemissiniz ama bu FE tarafinda fix edilebilecek bir sey degil, kapatalim mi?

**Comment by agitrubard** [comment]
Konumun yanlış olduğunu veya doğru olduğunu bildirebilmek üzerine bir yapı da oluşturulabilir, geçici olarak bu bildiriler üzerine buradaki konum bildirisi kaldırılabilir, örnek olarak ben bulunduğum yerde yanlış bir konum gördüm fakat yanlış olduğunu belirtemedim.

**Comment by nazdezar** [comment]
@JusticeBoi @canerakin111 @quatronostro  - I am leaning towards closing this ticket as **won't fix/do**. To my understanding, the #veri-kontrol team is actively working on updating/correcting these locations. I can pass this on to them and have them review it. Please confirm.

https://deprem-adres-kontrolleri.vercel.app/

**Comment by JusticeBoi** [comment]
Solving the issue from its roots is a better idea =]. Feel free to close from my side.

**Comment by fdemir** [comment]
BE RELATED CLOSED
