### ISSUE TITLE
feat: default seo

### ISSUE THREAD

**Issue by fdemir** [acikkaynak/deprem-yardim-frontend#497]
## İsteğiniz şeyi tanımlayın 
default seo. title, meta tags etc. eklenmeli.

## Değerlendirdiğiniz alternatifleri tanımlayın
next-seo kullanbilabir. ama onermiyorum.

**Comment by khnbzkrt** [comment]
@fdemir buna benzer bir issue mevcut. Lütfen issue oluşturmadan önce arama yapabilirseniz duplice sorunların önüne geçmiş oluruz 👍

https://github.com/acikkaynak/deprem-yardim-frontend/issues/435

**Comment by dopplerDistortion** [comment]
@fdemir #516 'da head spesifik constantlar için ne olur ne olamaz yer açtım. fyi

https://github.com/acikkaynak/deprem-yardim-frontend/blob/71e11db6d441d3843646aa8547330f7d3f8e5a56/components/base/HeadWithMeta/HeadWithMeta.constants.tsx
