### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by eakpinar** [acikkaynak/deprem-yardim-frontend#498]
## Hata Tanımı
"30sn sonra otomatik taranacak" geri sayımı bittiğinde otomatik taramıyor ve 900sn'den geri sayıma devam ediyor.

## Hatayı nasıl aldığınızı adım adım açıklayın

1. Haritada herhangi bir yere git, 30 saniye geri sayım dolmasını bekle
2. Yeni konum işaretlerinin yüklenmediğini görmek için "Bu Alanı Tara" butonuna bas
3. 30 saniye sonunda olması gereken sonucun olmadigini görmüş ol.

## Beklenen Davranış
Geri sayım bittiğinde yeni datanın yüklenmesi gerekir ve sayım resetlenir.

## Ekran Görüntüleri
30 saniyelik video kaydı büyük dosya olacağı için eklenmedi.

## Masaüstü Bilgileri
- İşletim Sistemi: MacOS Intel
- safari
- Sürüm 16.2

**Comment by khnbzkrt** [comment]
@eakpinar Bu bir bug değil bilinçli olarak böyle tasarlandı.

**Comment by eakpinar** [comment]
Bu geri sayımın amacı ne olmuş oluyor? Bu bir beklenti oluşturmuyor mu? Alınan son veri üzerinden ne kadar süre geçtiğini saysa daha iyi olur mu?
