### ISSUE TITLE
feat: Sag alttaki logonun kaldirilmasi

### ISSUE THREAD

**Issue by cdagli** [acikkaynak/deprem-yardim-frontend#499]
## İsteğiniz şeyi tanımlayın 
Her ne kadar opacity'si dusurulse de hala kullanicilarda bir buton intibasi olusturuyor bu nedenle bu logoyu kaldirmayi teklif ediyorum. 

## Değerlendirdiğiniz alternatifleri tanımlayın
Ya da illa logo olsun dersek, Gizlilik politikasi yanina daha kucuk bir seyler eklenebilir. 

## Ek Bağlam
<img width="408" alt="image" src="https://user-images.githubusercontent.com/7020369/217620044-eb50514b-e074-4fc0-82a7-f47d3ab3a0f6.png">

**Comment by EmirBoyaci** [comment]
Bence bu logonun uygulamaya bir katkısı yok, dolayısıyla kaldırılmasında herhangi bir problem olmadığını düşünüyorum.

**Comment by can101** [comment]
bunu ben yapa bilirim istenirse

**Comment by canerakin111** [comment]
@can101 task'i ustlenebilirsin.

**Comment by berkayvuran** [comment]
@cdagli bu iş tamamlandı mı? closed görüyorum ama in progress'te, teyit etmek istiyorum
