### ISSUE TITLE
[Feature] Farklı harita providerlarıyla çalışabilme Google Maps, KGM, Bing vs

### ISSUE THREAD

**Issue by zaferayan** [acikkaynak/deprem-yardim-frontend#50]

**Comment by ozcanzaferayan** [comment]
Google: http://mt0.google.com/vt/lyrs=m&hl=en&x={x}&y={y}&z={z}
KGM:  http://yol.kgm.gov.tr/wmts/kar_muc/gm_grid/{z}/{x}/{y}.png

**Comment by eraygundogmus** [comment]
@end-y ilgileniyor, kendime assign ettim

**Comment by end-y** [comment]
@ozcanzaferayan  abi bu son attıkların hata veriyor

**Comment by ozcanzaferayan** [comment]
KGM ve Google ekleyebilirsin şimdilik
