### ISSUE TITLE
bug:"Adres Bildirim Formu zorunlu alanlar girilmeden  kayıt edilebilmesi" 

### ISSUE THREAD

**Issue by ilyastunch** [acikkaynak/deprem-yardim-frontend#500]
## Hata Tanımı
Adres Bildirim Formu zorunlu alanlar girilmeden 
kayıt edilebilmesi

## Hatayı nasıl aldığınızı adım adım açıklayın

1.  Deprem Yardım Anasayfasına gidin
2. Adres Bildirim Formunda Sehir alanını girin
3.İlçe/Mahalle zorunlu alanlarını boş bırakın
4. Diğer zorunlu alanları girin
5. Kaydet butonına basın

## Beklenen Davranış
Kaydetmenin gerçekleşmemesi ve zorunlu alanları doldurun uyarısının gelmesi

##Olan Davranış
Kaydetme işlemini gerçekleştiriyor.  Yardım isteyenler listesinde görünüyor.

## Masaüstü Bilgileri
- İşletim Sistemi: Windows 10 x64
- Tarayıcı: Chrome
- Sürüm: Version 109.0.5414.120 (Official Build) (64-bit)

**Comment by denizsult** [comment]
Sanırım yanlış repoya yazdın

**Comment by ilyastunch** [comment]
Hangi repoya yazmam gerekiyor. 
Issue UI issuesu gibi duruyor .
Test kanalına ulaşamıyorum discordda.

**Comment by denizsult** [comment]
https://github.com/acikkaynak/deprem-yardimi

**Comment by denizsult** [comment]
@ilyastunch dostum issue'yı kapatır mısın?
