### ISSUE TITLE
bug: "Bu alani tara butonu" Drawer uzerinde kaliyor

### ISSUE THREAD

**Issue by cdagli** [acikkaynak/deprem-yardim-frontend#502]
## Hata Tanımı
Hatanın ne olduğu hakkında açık ve kısa bir açıklama.
<img width="507" alt="image" src="https://user-images.githubusercontent.com/7020369/217626080-985323b1-28ba-4a34-a20e-b3c4d0444bfb.png">

## Hatayı nasıl aldığınızı adım adım açıklayın

1. Chrome developer tools'dan cihaz olarak Iphone SE secin
2. Herhangi bir pini acin
3. Hata görünüyor

## Beklenen Davranış
Butonlar drawerin uzerinde kalmamali. 

## Ekran Görüntüleri
Uygulanabilirse, sorununuzu açıklamak için ekran görüntüleri ekleyin.

## Masaüstü Bilgileri
- İşletim Sistemi: OSX
- Tarayıcı Chrome
- Sürüm 109

## Akıllı Telefon Bilgileri
- Cihaz: [örneğin iPhone6]
- İşletim Sistemi: [örneğin iOS8.1]
- Tarayıcı [örneğin varsayılan tarayıcı, safari]
- Sürüm [örneğin 22]

## Ek Bağlam
Sorun hakkında diğer herhangi bir bağlamı burada ekleyin.

**Comment by CreatorX64** [comment]
MuiDrawer'a verilecek bir `z-index` değeri ile çözülebilir. Henüz kimseye atanmadıysa PR gönderebilirim.

**Comment by JusticeBoi** [comment]
@CreatorX64 Ben de bakiyordum, ve ayni fikirdeyim z-index konusunda. Ben direk [bu containerin z-indexini kücülterek](https://github.com/acikkaynak/deprem-yardim-frontend/blob/development/pages/index.tsx#L99) de sorun halledilebilir, belki yardimci olur size. Kolay gelsin.

**Comment by CreatorX64** [comment]
@JusticeBoi Teşekkürler.

> Ben direk [bu containerin z-indexini kücülterek](https://github.com/acikkaynak/deprem-yardim-frontend/blob/development/pages/index.tsx#L99) de sorun halledilebilir diye düsündüm

UI içerisinde diğer DOM birimleri, bahsettiğiniz containerın `z-index` değerine coupled bir şekilde style edilmiş olabilir. Kimi componentlar `sx` değeri verilerek inline şekilde style edildiği için tüm componentları gözden geçirip test etmeden emin olamıyorum. Bu yüzden bahsettiğiniz containerın güncel `z-index` değerini değiştirmek yerine `MuiDrawer` component'ına daha yüksek bir `z-index` değeri vermek daha güvenli seçenek olabilir.

**Comment by JusticeBoi** [comment]
@CreatorX64 Teşekkürler aciklama icin, haklisiniz.

**Comment by emirefek** [comment]
Selamlar, projede zIndex'ler çok ciddi sıkıntılı. Bununla alakalı bir issue açtım. Bence oradan devam etmek en doğrusu olacaktır. zIndex'ler düzensiz olarak kafadan sallanmış. ilgili issue: #507

**Comment by CreatorX64** [comment]
@emirefek Katılıyorum, fakat @cdagli'nin açtığı güncel issue'da bahsedilen problem uygulamanın kullanılabilirliğine ciddi etki yapıyor. Bu problemin ivedi bir şekilde çözülmesi, toplu bir refactordan daha öncelikli gibi.

Bunun için `MuiDrawer` component'ına "99999" değerinde bir `z-index` verilip merge edilirse en azından kötü etkilenen UX bu scope'ta düzelecektir (approved olmasını bekliyorum PR atmak için).

Bu problem hızlıca aradan çıkarıldıktan sonra önerdiğiniz refactor kesinlikle yapılmalıdır.

**Comment by ramazanyigit** [comment]
Production'da bu çözüldü #454 ile birlikte. https://afetharita.com ve https://rc.afetharita.com adresinde bu sorun görünmüyor.

**Comment by cdagli** [comment]
rc'de reproduce edemedim, kapatiyorum o yuzden.
