### ISSUE TITLE
bug: Kaynak linkleri çalışmıyor

### ISSUE THREAD

**Issue by yuiji** [acikkaynak/deprem-yardim-frontend#504]
## Hata Tanımı
Kaynak butonun'a basıldığında "https://twitter.com/anyuser/status/undefined" bu linke gidiyor. Her link'i tek tek deneyemedim ancak. Denediğim bütün linklerde aynı sorunla karşılaştım

## Hatayı nasıl aldığınızı adım adım açıklayın

1. Herhangi bir marker'a tıklayın.
2. Kaynak butonu'a tıklayın.
3. Açılan link hatalı.

## Beklenen Davranış
Kaynak link'inin bozuk olmaması. 

## Masaüstü Bilgileri
- İşletim Sistemi: windows
- Tarayıcı chrome, opera

**Comment by absolutezero13** [comment]
muhtemel duplicate https://github.com/acikkaynak/deprem-yardim-frontend/issues/482
