### ISSUE TITLE
refactor: tagleri daha type safe yapmak

### ISSUE THREAD

**Issue by frankie303** [acikkaynak/deprem-yardim-frontend#506]
issue acmadigim icin pr'im kapatildi: [pr](https://github.com/acikkaynak/deprem-yardim-frontend/pull/503
) zaten yapmak istedigim seyi anlatiyor ama ben yine de anlatayim:

Su anki haliyle `Tags`'i (`TAGS_CONFIG` olarak degistirdim) manual type'lamak yerine [const assertion](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions) kullanabiliriz, boylece literal type'i alabiliriz. Onun disinda `findTagByClusterCount`'i bu degisiklik ile refactor ettim. 

Bir öneri: refactorlerde issue acmak zorunlu tutulmasa? pr mantikliysa alinsa, degilse alinmasa (veya reviewda tartisilabilir) nasil olur? Cunku pr'da [faydali denmesine ragmen](https://github.com/acikkaynak/deprem-yardim-frontend/pull/503#issuecomment-1423126963) pr direk kapatildi, bu bana biraz garip geldi.

**Comment by frankie303** [comment]
@erdemkarakas neden `invalid` olarak tagledigini aciklayaibilir misin?

**Comment by erdemkarakas** [comment]
https://github.com/acikkaynak/deprem-yardim-frontend/blob/development/.github/ISSUE_TEMPLATE/

Uygun issue tamplate'inde açmadığı için kapatıyoruz, yukarıdaki bağlantıdan uygun template'i bulabilirsin.

**Comment by emr3rden** [comment]
Kusura bakmayın buna uygun template olmadığı için haklsıınız tekrardan açıyoruz. Issue onaylandıktan sonra tekrar PR gönderir misiniz?

**Comment by eraygundogmus** [comment]
Şu an yeteri kadar descriptive ve düzenli değil issue. Template hazırlandı.

**Comment by frankie303** [comment]
> Şu an yeteri kadar descriptive ve düzenli değil issue. Template hazırlandı.

Tam olarak neden 'yeteri kadar' descriptive degil ve hangi kismini anlamadin? Issue'yu kapatmak yerine bu sorulari sorabilirsin.
