### ISSUE TITLE
bug: zIndex's are bloated and conflicts MUI

### ISSUE THREAD

**Issue by emirefek** [acikkaynak/deprem-yardim-frontend#507]
## Hata Tanımı
zIndex values are not really making any sense, and they are broking MUI's popper components.
Popper component is needed for MUI's components with Pop-up UX purpose. They needed to get lower then 100z.

## Hata Ortamı
I noticed this problem while developing feature with MUI's Autocomplete component.  PR: #495
When you add MUI's Autocomplete component the component stays under Header.

## Hatayı nasıl aldığınızı adım adım açıklayın
1. Checkout the PR: #495
2. Don't forget to add GCloud api-key as env variable. It's needed for feature.
3. Type something to search box and you'll see it stays under header.
4. Don't try to manipulate zIndex because you shouldn't bypass MUI's default values like this if you don't really need.

## Beklenen Davranış
It should be on top and when I look source code. These are the all zIndex values in whole project:
[9999, 99999, 1000, 998, 999, 1000, 999, 999, 1000, 2, -1, -1, 1, 1, 9999, 999]
I think we needed to get away from this bloated stuff. And manage zIndex properly.

## Ekran Görüntüleri
<img width="251" alt="ss" src="https://user-images.githubusercontent.com/6191145/217640450-9acf341a-1f6e-4e25-8505-d8e0d57c56df.png">

## Masaüstü Bilgileri
- İşletim Sistemi: [Windows 11]
- Tarayıcı [Chrome]
- Sürüm [stable@latest]

## Akıllı Telefon Bilgileri
- Cihaz: [S21]
- İşletim Sistemi: [A13]
- Tarayıcı [Chrome]
- Sürüm [stable@latest]

## Ek Bağlam
It's easy to fix problem. If you assign me the issue I can coordinate the zIndexes and order them properly.

**Comment by emirefek** [comment]
Also #502 numbered issue has same problem. That's a quite global problem about MUI and zIndex'es.

**Comment by canerakin111** [comment]
@eraygundogmus @usirin request for attention.

**Comment by lyketia** [comment]
Be my guest and fix it.

**Comment by emirefek** [comment]
> Be my guest and fix it.

So I fixed it in my fork, waiting for approved status to create PR.

**Comment by emirefek** [comment]
May I ask why it's closed?
