### ISSUE TITLE
refactor: kullanilamayan react importlarini sil

### ISSUE THREAD

**Issue by fdemir** [acikkaynak/deprem-yardim-frontend#508]
### Refactor İsteği
Next.JS otomatik olarak React'i import ediyor. Gerek yok.

### Çözüm Önerisi

```
import React from "react"
```

olan importlari silebiliriz. Hook import olanlari silmemeliyiz.

### Ek Bağlam

Editor icerisinden direkt olarak search edilebilir.

**Comment by puskuruk** [comment]
Evet, gerek yok fakat bu issue ile su an ugrasmanin marjinal faydasını göremiyorum.

**Comment by fdemir** [comment]
@puskuruk belki out bundlea bi faydasi olur diye acmistim. belki degerlendirilebilir

**Comment by puskuruk** [comment]
Iki versiyon ile build edip ciktilarin boyutlarini karsilastirabilirsin 🙏

**Comment by usirin** [comment]
kapatiyorum simdilik, kesinlikle `p0` degil
