### ISSUE TITLE
bug: yuksek varsayilan zoomout

### ISSUE THREAD

**Issue by fdemir** [acikkaynak/deprem-yardim-frontend#510]
## Hata Tanımı
First load yaparken girdiginizde haritanin cok yuksek bir zoom levelinden baslamasi.

## Hata Ortamı
rc.afetharita.com

## Hatayı nasıl aldığınızı adım adım açıklayın

1. cache silin
2. rc.afetharita.com'a gidin

## Beklenen Davranış
zoom levelinin ilk basta yuksek olmasi gerekiyor. bu sayede atilan ilk requestin payloadi dusuk olacaktir. ve sayfa daha hizli yuklenir.

## Ekran Görüntüleri
![image](https://user-images.githubusercontent.com/48316033/217644579-3c47bee9-8719-4ef9-b334-93fa6e7d4754.png)

## Masaüstü Bilgileri

Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Mobile Safari/537.36

## Akıllı Telefon Bilgileri
Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Mobile Safari/537.36

## Ek Bağlam
 atilan her request kulalnicinin gorus alani ile birlikte gidiyo ve buna gore request getiriliyor.

**Comment by puskuruk** [comment]
Zoom levelini daha önce arttirmistik. "Zoom levelinin ilk basta yuksek olmasi gerekiyor." derken ne kadar "yüksek" olması gerektiğini düşünüyorsun?

**Comment by turkerdev** [comment]
> Zoom levelini daha önce arttirmistik. "Zoom levelinin ilk basta yuksek olmasi gerekiyor." derken ne kadar "yüksek" olması gerektiğini düşünüyorsun?

Saniyorum ki "dusuk" demek istedi.

**Comment by EmirBoyaci** [comment]
İlk açılışta bunun yeterli olduğunu düşünüyorum: @usirin @fdemir 

![image](https://user-images.githubusercontent.com/59085992/217646673-41d4e483-b9d7-4e2d-aca4-25b32efd3c8b.png)

**Comment by fdemir** [comment]
zoom yukseltmek -> yakinlasmak
evet yeterli. @EmirBoyaci 
calisan birini assign edebilirim.

**Comment by EmirBoyaci** [comment]
@canerakin111 approve pls
