### ISSUE TITLE
refactor: duplicate type refactor

### ISSUE THREAD

**Issue by absolutezero13** [acikkaynak/deprem-yardim-frontend#518]
### Refactor İsteği

bazı typelar çok tekrar ediyor, örnek;
`  device: "mobile" | "desktop"; `

### Çözüm Önerisi

Ortak bir type yazılabilir.

### Ek Bağlam

approved olduğu takdirde çok fazla dosyada olmayacak şekilde bazı typeları güncelleyebilirim.

**Comment by buraksaraloglu** [comment]
bakiyorum

**Comment by berkayvuran** [comment]
@absolutezero13 bu iş tamamlandı mı? closed görüyorum ama in progress'te, teyit etmek istiyorum.

**Comment by absolutezero13** [comment]
@berkayvuran #539 'da halledildi, merged.
