### ISSUE TITLE
refactor: overfetchin onune gecerek response timei hizlandirma - areas lite

### ISSUE THREAD

**Issue by fdemir** [acikkaynak/deprem-yardim-frontend#521]
### Refactor İsteği
Su an ekranda gozukmesini istedigimiz pointleri /feeds/areas adli bir endpoint uzerinden atiyoruz. Burada BE projesi bir guncelleme cikti. Bu guncelleme ile birlikte transfer edilecek payloadi dusurmeyi planliyoruz.

### Çözüm Önerisi
Yeni yazilmis iki endpointi implemente ederek bu soruna cozum getirebilirz.

/locations/{point-id} - Ilgili pointin detayini al
/areas/lite - Pointlerid asagidaki struct ile dondurur

```
[
  {
   id: number, 
   loc: [lat, lon]
  }
]
```

Bu iki endpoint implemente edilerek sorunlarin onune gecirilebilir.

### Ek Bağlam

API spesifikasyonu - https://api.afetharita.com/feeds/

**Comment by altankurt** [comment]
#488 duplicate
