### ISSUE TITLE
bug: ClusterPopup zoom problem

### ISSUE THREAD

**Issue by ezranbayantemur** [acikkaynak/deprem-yardim-frontend#523]
## Bug Definition
In the mobile device and also the browser, in the cluster popup on zoom action it does not work well. Can not zoom out

## Describe how you are producing the bug step by step

1. Go to 'afetharita.com' 
2. Click to any cluster
3. Zoom in to PopUp
3. Zoom out in PopUp
4. There is an wrong displayed

## Expected behaviour
Cluster PopUp should not be zoomable

## Screenshots
![IMG_9971](https://user-images.githubusercontent.com/42299721/217662272-f323bc78-e790-4f7b-9503-52fa6251767e.PNG)

## Desktop Information
- Operating System: Mac
- Browser: Chrome

## Mobile Phone Information
- Devıce: iPhone 13 Pro Max
- Operating System : 16.2
- Browser: Chrome

**Comment by ezranbayantemur** [comment]
Bu problem ile ben ilgileniyorum, PR'ı açacağım

**Comment by emirefek** [comment]
Ek olarak şu aşağıdaki kırmızı pop-up'da da aynı problem var.

<img width="248" alt="zoomProblem" src="https://user-images.githubusercontent.com/6191145/217668722-af4e9506-2664-41a0-92af-425dfa11ac43.png">

**Comment by ezranbayantemur** [comment]
güncelleyeyim orayı da

**Comment by canerakin111** [comment]
@usirin suan bu issue testing temi?

**Comment by CyhnYldz** [comment]
@canerakin111 @usirin test ekibine iletildi

**Comment by CyhnYldz** [comment]
Günaydın tüm ekibe pop-up açıkken mobil chrome browser üzerinde zoom-in zoom-out fotoğraflardaki sıkıntıya yol açmakta. daha derinlemesine test edip bilgilendireceğiz.


![Image](https://user-images.githubusercontent.com/111140617/218032487-83264a82-3354-41cc-a3a2-525882dee217.jpg)
![Image](https://user-images.githubusercontent.com/111140617/218032488-a84bc938-d649-4909-891a-b427b31950ed.jpg)

Kolay gelsin

**Comment by CyhnYldz** [comment]
merhaba farklı cihazlarda denemeler yaptık hata tekrar etmekte. özellik ilk açılışlarda cache temizliği yapıldığında reproduce edilebiliyor.
kolay gelsin.

iphone 13 promax ios 16.3
browser safari

![IMG_5024](https://user-images.githubusercontent.com/111140617/218040187-b8a195d9-da59-4a35-8776-0f3593dfdc28.jpeg)
![IMG_5023](https://user-images.githubusercontent.com/111140617/218040205-4a537409-80e3-409d-8f7e-7a2569de6a04.jpeg)
![IMG_5025](https://user-images.githubusercontent.com/111140617/218040217-49013812-0d4b-4467-9003-cef601a24351.jpeg)

**Comment by emr3rden** [comment]
TR: Issue'ların bundan sonra ingilizce olarak gönderilmesi gerekiyor ve halihazırda açık olanlara da bu talebimizi iletiyoruz. O nedenle sizden ricamız bu issue'yu ingilizce olarak düzenlemeniz. Lütfen ingilizce olarak düzenler misiniz?

EN: "Issues" must be sent in English from now on, and we forward this request to those who are already open. Therefore, we request you to edit this "issue" in English. Could you please edit it in english?
