### ISSUE TITLE
feat: UI development for density map

### ISSUE THREAD

**Issue by sefadegirmenci** [acikkaynak/deprem-yardim-frontend#525]
## Define your request
There are 2 deficieny in heatmap clusters on map:

1- When zooming in/out those areas are not changing dynamically consequently while zooming in/out those clusters remain stable and creates a bad display

Video: https://youtube.com/shorts/6tY4IMNq7jc?feature=share

2- Heatmap colors interfere with the pinpoint colors, both of them are red/orange.

** discord username: @sefadegirmenci#6360 **

## Define the alternatives you have in mind

1- If heatmap clusters turned dynamic it would create a more professional appearance.
2- Pinpoint color should be changed.

**Comment by aerdemsenturk** [comment]
1_- Yoğunluk kümeleri dinamik hale getirilebiliyorsa daha profesyonel bir görünüm olacaktır._

Bunun Leaflet ile bir çözümü yok. maplibreGL için bu mümkün idi ama proje leaflet ile ilerlediği için leaflet'den vazgeçilemiyor şu anda.

**Comment by canerakin111** [comment]
Kullandigin telefon modeli, OS system ve tarayici bilgisi verir misin? Bir delay goruluyor ama kumelenmede bir problem gozukmuyor.

**Comment by fdemir** [comment]
video atar misin? reproduce edemiyorum.

**Comment by sefadegirmenci** [comment]
> Kullandigin telefon modeli, OS system ve tarayici bilgisi verir misin? Bir delay goruluyor ama kumelenmede bir problem gozukmuyor.

Iphone X, Safari, ios 16.1.1 

Video çekiyorum şimdi

**Comment by sefadegirmenci** [comment]
> video atar misin? reproduce edemiyorum.

https://youtube.com/shorts/6tY4IMNq7jc?feature=share

**Comment by fdemir** [comment]
Beklenen davranis nasil olmali?  @sefadegirmenci Eger swipe ettikce kume ve heatmapin guncellenmesini istiyorsan. Bu animasyona girecektir. Ve gereksiz yere cihazi zorlariz.

**Comment by sefadegirmenci** [comment]
> Beklenen davranis nasil olmali?  @sefadegirmenci Eger swipe ettikce kume ve heatmapin guncellenmesini istiyorsan. Bu animasyona girecektir. Ve gereksiz yere cihazi zorlariz. 

Eğer dinamik bir şekilde güncelleyemiyorsak bile en azından yoğunluk kümelerini haritadaki yerlerine sabitleyebiliriz ve sadece pinch hareketi sonlanınca bunları güncelleyebiliriz. Örneğin şu an yakınlaştırırken Kahramanmaraş üstündeki küme aşağı kayıp Antep'te görülebiliyor. Videoda görüldüğü gibi ekranda serbest hareket ediyor kümeler. Bunun yerine hesaplamanın yapıldığı bölgeye koordinat bazında sabitlenebilir.

**Comment by ramazanyigit** [comment]
Kümelerin konumlandırılmasında herhangi bir yanlışlık göremiyorum. Ayrıca https://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.388.html bu adresteki örnekle de davranış aynı görünüyor. Hatta bunun yanında heatmaplerin görüntülenmesinde zoom sırasında kayma oluyor onu ayrı issue açmalıyız yoksa.

**Comment by aerdemsenturk** [comment]
> > video atar misin? reproduce edemiyorum.
> 
> https://youtube.com/shorts/6tY4IMNq7jc?feature=share

Şimdi anlıyorum bunun önüne belki şöyle geçilebilir:
harita hareket ettirildiğinde heatmap'ı invisible yap. Hareket bittiğinde tekrar visible yap. Şöyle eventler var sanırım leaflet'te:

zoomstart, zoomend, movestart, moveend.

https://www.syncfusion.com/succinctly-free-ebooks/leafletjs/handling-events

```
map.on("movestart", function () {
  //heatmap'i gizle
});

map.on("moveend", function () {
  //heatmap'i göster
});
```

**Comment by egemenu** [comment]
Kontrol ettiğim kadarıyla yoğunluk haritasına transition eklenme şansı yok gibi. En mantıklı çözüm headmap'i gizleyip göstermek gibi gözükyor.

**Comment by sefadegirmenci** [comment]
> > > video atar misin? reproduce edemiyorum.
> 
> > 
> 
> > https://youtube.com/shorts/6tY4IMNq7jc?feature=share
> 
> 
> 
> Şimdi anlıyorum bunun önüne belki şöyle geçilebilir:
> 
> harita hareket ettirildiğinde heatmap'ı gizle. Hareket bittiğinde tekrar göster. Şöyle eventler var sanırım leaflet'te:
> 
> 
> 
> zoomstart, zoomend, movestart, moveend.
> 
> 
> 
> https://www.syncfusion.com/succinctly-free-ebooks/leafletjs/handling-events
> 
> 
> 
> ```
> 
> map.on("movestart", function () {
> 
>   //heatmap'i gizle
> 
> });
> 
> 
> 
> map.on("moveend", function () {
> 
>   //heatmap'i göster
> 
> });
> 
> ```

Leaflet hakkında pek bir bilgim yok ancak bu heatmap clusterlarını sabitlemek için bir yol yok mu latitude, longitude şeklinde? Mesela bir cluster Hatay üstündeyse zoom sırasında da Hatay üzerinde kalsa?

Bu şekilde daha smooth bir geçiş olabilir, eğer böyle olmuyorsa dediğiniz gibi zoom sırasında gizlenebilir.

**Comment by egemenu** [comment]
https://user-images.githubusercontent.com/16397775/217787540-f8a79436-4a29-4270-a4c5-f761a9bdb489.mp4

Lokal olarak çözüm uyguladım ve zoom sırasında gizlemenin pratikte o kadar da iyi bir çözüm olmadığına kanaat getirdim.

**Comment by aerdemsenturk** [comment]
Smooth çözümü sanıyorum ki leaflet ile yok. Leaflet eskiden kullanıyordum galiba doğası gereği böyle. maplibreGL ile bir deneme yapmıştım. Intensity orada çok iyi çalışıyor. Çok sayıda noktayla da iyi başa çıkabiliyor: 

https://aerdemsenturk.github.io/map/afetharita/#7/37.28/37.28

**Comment by sefadegirmenci** [comment]
Peki movestart ve moveend eventleri durumunda `heatmap.redraw()` gibi bir fonksiyon çağırabilir miyiz? 
MaplibreGL linkini telefonda denedim gerçekten güzel çalışıyor.

@egemenu Evet tamamen katılıyorum

**Comment by aerdemsenturk** [comment]
> Peki movestart ve moveend eventleri durumunda `heatmap.redraw()` gibi bir fonksiyon çağırabilir miyiz? MaplibreGL linkini telefonda denedim gerçekten güzel çalışıyor.
> 
@egemenu nun örneğinde zaten redraw ediyor dimi? 

Aslnıda tek sorun heatmap değil. Bir çok farklı kişiden hep aynı geribildirimi aldım. Telefonda ilk açılış OK ama biraz gezinince hemen takılmalar başlıyor. Başından beri bu haritadaki takılmaların Leaflet kaynaklı olduğunu düşünüyorum. 

Ben vakit bulursam, maplibreGL örneğini geliştirip belki bir issue açacağım, maplibreGL'ye geçiş için motavisyon olur belki.

**Comment by sefadegirmenci** [comment]
> > Peki movestart ve moveend eventleri durumunda `heatmap.redraw()` gibi bir fonksiyon çağırabilir miyiz? MaplibreGL linkini telefonda denedim gerçekten güzel çalışıyor.
> 
> > 
> 
> @egemenu nun örneğinde zaten redraw ediyor dimi? 
> 
> 
> 
> Aslında tek sorun heatmap değil. Bir çok farklı kişiden hep aynı geribildirimi aldım. Telefonda ilk açılış OK ama biraz gezinince hemen takılmalar başlıyor. Başından beri bu haritadaki takılmaların Leaflet kaynaklı olduğunu düşünüyorum. 
> 
> 
> 
> Ben vakit bulursam, maplibreGL örneğini geliştirip belki bir issue açacağım, maplibreGL'ye geçiş için motavisyon olur belki. 
> 
> 
> 
> 
> 
> 
> 
> 

Aslında afet bölgesindeki insanların büyük çoğunluğu telefondan giriyor. Sanmıyorum yanlarında bilgisayar taşıdıklarını. Eğer Leaflet'ten kaynaklı mobilde böyle sorunlar oluyorsa bunu düzeltmek çok faydalı olur.

**Comment by aerdemsenturk** [comment]
Telefon için demiştim zaten.

**Comment by sefadegirmenci** [comment]
> Mobil için demiştim zaten.

Evet evet anladım. Yazdıklarınıza katılıyorum anlamında cevaplamıştım.

**Comment by budancamanak** [comment]
https://stackoverflow.com/a/18613197/1444788 burdaki şekilde map'e eventhandler ekleyebiliriz sanki. 
https://leafletjs.com/reference.html#map-zoomend api'de zoom eventi varmış ve tekrarlı bi şekilde çağrılıyormuş.

**Comment by sefadegirmenci** [comment]
Bahsettiğiniz bu değil mi? 
![Screen Shot 2023-02-10 at 00 59 39](https://user-images.githubusercontent.com/56880835/217948972-2e85ff09-5e20-48fe-97e1-8527bcea80b4.png)

Tam da işe yarayacak bir şey gibi, her zoom level change'de `heatmap.redraw()` yapabiliriz. Ne kadar sıklıkla bu eventi çağırıyor, lag yapıyor mu vs test edilebilir.

**Comment by eraygundogmus** [comment]
Hala buna ihtiyaç varsa PR çalışılıp PR açıldıktan sonra değerlendirilebilir FE teknik ekip tarafından

**Comment by sefadegirmenci** [comment]
Ben backend kısmında destek sağlamaya çalışıyorum frontend bilgim pek yok. Pr açılırsa test edebilirim.

**Comment by khnbzkrt** [comment]
Ben ilgileniyorum fyi.

**Comment by budancamanak** [comment]
> Bahsettiğiniz bu değil mi? ![Screen Shot 2023-02-10 at 00 59 39](https://user-images.githubusercontent.com/56880835/217948972-2e85ff09-5e20-48fe-97e1-8527bcea80b4.png)
> 
> Tam da işe yarayacak bir şey gibi, her zoom level change'de `heatmap.redraw()` yapabiliriz. Ne kadar sıklıkla bu eventi çağırıyor, lag yapıyor mu vs test edilebilir.

evet bir ufaktan deneme yaptım. heatmap.redraw çağırdım ancak yine bi laglıyor. onun dışında tile istekleri zoomend event fonksiyonunda çağrıldığı için hareket sonlandığında map kendini yeniliyor diye anladım. orası da problemin diğer kaynağı olabilir. mobilde pinch hareketinin tamamlanması da yani parmağın kaldırılması zoomend tetikliyo ondan dolayı heatmap gecikmeli update oluyo olabilir. bi de zoomSnap 0 a setlenebilir. snap şu an 0.25 her level arasında 4 tane zoom eventi fırlatıyor olacak. daha smooth bişey için [zoomanim](https://leafletjs.com/reference.html#map-zoomanim) diye bi event vardı sanırım zoomanimasyonu esnasında çok daha çağrılıyor o da denenebilir. tecrübelerim bunlar. kolay gelsin.

**Comment by CyhnYldz** [comment]
merhaba aynı hatayı test ekibi olarak bizde aldık bilgilerinize. buraya da comment göndermemin sebebi takip edebilmek.
sizlere kolay gelsin arkadaşlar

**Comment by selensr** [comment]
bu sorunla ilgileniyorum

**Comment by selensr** [comment]
> Ben ilgileniyorum fyi.

bu sorunla ben de ilgileniyorum

**Comment by emr3rden** [comment]
TR: Issue'ların bundan sonra ingilizce olarak gönderilmesi gerekiyor ve halihazırda açık olanlara da bu talebimizi iletiyoruz. O nedenle sizden ricamız bu issue'yu ingilizce olarak düzenlemeniz. Lütfen ingilizce olarak düzenler misiniz?

EN: "Issues" must be sent in English from now on, and we forward this request to those who are already open. Therefore, we request you to edit this "issue" in English. Could you please edit it in english?

**Comment by khnbzkrt** [comment]
I can reproduce this issue in development environment but we can make new performance issues for this issue resolves. For this reason i think, we can remove approved tag and we can close this issue.

You can use this guide for reroducing : https://developer.chrome.com/docs/devtools/remote-debugging/

**Comment by sefadegirmenci** [comment]
> I can reproduce this issue in development environment but we can make new performance issues for this issue resolves. For this reason i think, we can remove approved tag and we can close this issue.
> 
> 
> 
> You can use this guide for reroducing : https://developer.chrome.com/docs/devtools/remote-debugging/

Sorry but I couldn't understand. Do you mean it is resolved and should be closed?

**Comment by selensr** [comment]
> > I can reproduce this issue in development environment but we can make new performance issues for this issue resolves. For this reason i think, we can remove approved tag and we can close this issue.
> > You can use this guide for reroducing : https://developer.chrome.com/docs/devtools/remote-debugging/
> 
> Sorry but I couldn't understand. Do you mean it is resolved and should be closed?

This issue is related to the bug from the library that we use to show the heatmap. The error applies to mobile devices; you can check this example below. This issue is not blocking the user, and we need more time and understanding to solve it. It is better to close this pr or decrease the priority.

Here is the example of the issue:
[https://observablehq.com/@gpachera/leaflet-heatmap-example](https://l.facebook.com/l.php?u=https%3A%2F%2Fobservablehq.com%2F%40gpachera%2Fleaflet-heatmap-example%3Ffbclid%3DIwAR18QG0CZWpgACLdmcZWTBQR3px7WXC--vqIPN1wU0R6o3PGhOIAxySLOFo&h=AT2X4gQxehIJKQe_3gPB1g-tilCmb4plcJnH8M0dhI44pmpO-u_KdduiyVQaypNxB0jyd4KpXOYg7rEqG_YxgEtbSjXIhO9NV9lW9vgZchrC5skycMaxP1Fri5BXY7a1dzUFN4Mh)

**Comment by sefadegirmenci** [comment]
> > > I can reproduce this issue in development environment but we can make new performance issues for this issue resolves. For this reason i think, we can remove approved tag and we can close this issue.
> 
> > > You can use this guide for reroducing : https://developer.chrome.com/docs/devtools/remote-debugging/
> 
> > 
> 
> > Sorry but I couldn't understand. Do you mean it is resolved and should be closed?
> 
> 
> 
> This issue is related to the bug from the library that we use to show the heatmap. The error applies to mobile devices; you can check this example below. This issue is not blocking the user, and we need more time and understanding to solve it. It is better to close this pr or decrease the priority.
> 
> 
> 
> Here is the example of the issue:
> 
> [https://observablehq.com/@gpachera/leaflet-heatmap-example](https://l.facebook.com/l.php?u=https%3A%2F%2Fobservablehq.com%2F%40gpachera%2Fleaflet-heatmap-example%3Ffbclid%3DIwAR18QG0CZWpgACLdmcZWTBQR3px7WXC--vqIPN1wU0R6o3PGhOIAxySLOFo&h=AT2X4gQxehIJKQe_3gPB1g-tilCmb4plcJnH8M0dhI44pmpO-u_KdduiyVQaypNxB0jyd4KpXOYg7rEqG_YxgEtbSjXIhO9NV9lW9vgZchrC5skycMaxP1Fri5BXY7a1dzUFN4Mh)
> 
> 
> 
> 

Yes it stems from the library, that's why we tried to find a workaround. The decision of closing/decreasing the priority is all yours. It would just be better to solve this issue at some point.
