### ISSUE TITLE
feat: Discord Forum & Github update feed channel

### ISSUE THREAD

**Issue by siniradam** [acikkaynak/deprem-yardim-frontend#526]
## İsteğiniz şeyi tanımlayın 

# Discord'a 2 farkli Forum Kanali;
- SSS => (Read only, content supplied by contributors)
- - Yeni katilanlar icin sorabilecekleri sorularin cevaplari
- - Surece araliklarla dahil olanlar icin icin olan bitenler
- - Proje isimleri, ekipleri, ve hangi kullanicilarin hangi kaynaklara erisebildigine dair bilgiler ( <- Bu farkli saatlerde gelen katki sahipleri icin inanilmaz buyuk bir onem tasiyor.)

- Inquries
- - Projeye dahil olmak isteyenlerin listesi
- - Diger talepleri olanlar. 

Her iki forum icinde gerekli tag sistemi yapilmali. Boylece icerikler filterelenebilir, 

# GitHub Kanali (event feed);
- Github'da yeni gelen issue'larin ve guncellenen issue'larin otomatk olarak aktarilabilecegi read-only kanal.

Duruma gore, ilgili discord yetkileri verilirse yardimci olabilirim veya yetki sahibi kisinin ulasmadi durumunda yardimci olabilirim.

-- bu bilgiyi ekleyiniz
** discord kullanıcı adı: @tinman#7219 **

**Comment by birkaany** [comment]
Repodan bağımsız bir issue olduğundan ötürü kapatıyoruz, bilginiz olsun. Discord kanalı üstünden ilgili birimle iletişime geçebilirseniz seviniriz.
