### ISSUE TITLE
bug: https://rc.afetharita.com/ sayfası Yol Haritası sekmesi açıldığında kişi konumu konumlandırılamıyor.

### ISSUE THREAD

**Issue by darklordens** [acikkaynak/deprem-yardim-frontend#528]
## Hata Tanımı
Yol Konumlandırma seçeneği seçildiğin de haritaya yönlendirme yapılıyor. gidilecek konum doğrulanırken. Gidecek kişinin konumunu My Locaiton şeklinde gösterip yol tarifi çıkartamamaktadır.

-- bu bilgiyi ekleyiniz
** discord kullanıcı adı: @Kaan ARSLAN#1025 **

## Hata Ortamı
Hatanın ortaya çıktığı ortamı açıklayın. Örneğin:
https://rc.afetharita.com/#lat=37.5184934366135&lng=36.05300903320313&zoom=10         
## Hatayı nasıl aldığınızı adım adım açıklayın

1.https://rc.afetharita.com/#lat=37.5184934366135&lng=36.05300903320313&zoom=10 SAYFAYA GİDİLİR.
2. Sol alt sekmeden YOL TARİFİ AL tıklanır.
3. Açılan google harita da Gidecek yolcu alanı MY LOCATİON olarak kalır.

## Beklenen Davranış
Gidecek kişinin konumu direk aktarıp yol güzergahı rota oluşturulmalıdır.

## Ekran Görüntüleri
Uygulanabilirse, sorununuzu açıklamak için ekran görüntüleri ekleyin.
![Yol Bulma - My Location ataması hatası](https://user-images.githubusercontent.com/61864210/217670850-68883fa1-dbf8-4762-98ac-a0f1dccc2b34.png)

## Masaüstü Bilgileri
- İşletim Sistemi: windovs
- Tarayıcı chrome
- Sürüm 109.0.5414.120
![yol tarifi al butonu haritada my locatin ataması](https://user-images.githubusercontent.com/61864210/217670860-98b736ea-aeaa-4182-8e85-c931d2cd6085.png)
![Yol Bulma - My Location ataması hatası](https://user-images.githubusercontent.com/61864210/217671019-7916b9d7-7293-4f40-adfd-0b8ea151a627.png)

## Akıllı Telefon Bilgileri
- Cihaz: [örneğin iPhone6]
- İşletim Sistemi: [örneğin iOS8.1]
- Tarayıcı [örneğin varsayılan tarayıcı, safari]
- Sürüm [örneğin 22]

## Ek Bağlam
Sorun hakkında diğer herhangi bir bağlamı burada ekleyin.

**Comment by aerdemsenturk** [comment]
Bununla aynı sorun:

https://github.com/acikkaynak/deprem-yardim-frontend/issues/478#issuecomment-1422857951

**Comment by altankurt** [comment]
duplicate
#478

**Comment by darklordens** [comment]
Selamlar, Net konum vermemektedir. Re-Test yaptığımda bir düzelmenin olduğu My Location yazısının kalktığını ama konumlandırma yaparken net bir konumlandırma yapmadığını görüyorum. Örneğin Ben İstanbul\Ümraniye -sarıgazideyim ancak konum otomatik beni Ataşehir / İstanbul olarak gösteriyor. Destek Pls. Ayrıca bu sorunun başlangıc seviyesinden itibaren Chromede de karşılaşıyorum.
