### ISSUE TITLE
bug:  Microsoft EDGE ----- https://rc.afetharita.com/ sayfasına gidilip dil değişimi (eng) sonrası SAYAÇ hatası.

### ISSUE THREAD

**Issue by darklordens** [acikkaynak/deprem-yardim-frontend#532]
## Hata Tanımı
https://rc.afetharita.com/ ilgili sayfaya edge üzerinden gidilir. Sağ üst tabdan dil değişimi ENG olarak seçilir. Sayaç da donma yaşanır. 

-- bu bilgiyi ekleyiniz
** discord kullanıcı adı: @Kaan ARSLAN#1025 **

## Hata Ortamı
Hatanın ortaya çıktığı ortamı açıklayın. Örneğin:
rc.afetharita.com

## Hatayı nasıl aldığınızı adım adım açıklayın

1. 'Microsoft EDGE a gidin
2. (https://rc.afetharita.com/) ye tıklayın
3. Sağ üst tab dan sayfa dilini ENG olarak ayarlayın.
4. 30 saniye sayacı donmaya başlar.

## Beklenen Davranış
Sayaç dil değişiminden etkilenmeden SCAN işlemine devam etmeli geriye sayımını yapmalıdır.

## Ekran Görüntüleri
![translate eng 30s will error](https://user-images.githubusercontent.com/61864210/217680415-aba59061-c370-4396-b1dc-5334f0169367.png)

## Masaüstü Bilgileri
- İşletim Sistemi: windovs
- Tarayıcı microsoft edge
- Sürüm 110.0.5481.78

## Akıllı Telefon Bilgileri
- Cihaz: [örneğin iPhone6]
- İşletim Sistemi: [örneğin iOS8.1]
- Tarayıcı [örneğin varsayılan tarayıcı, safari]
- Sürüm [örneğin 22]

## Ek Bağlam
Sorun hakkında diğer herhangi bir bağlamı burada ekleyin.

**Comment by sevilayerkan** [comment]
Test ekibi olarak bu hatayı biz de inceledik Edge ile birlikte Chrome ve Firefox'ta da browserdaki çeviri fonksiyonunu açarak reproduce ettiğimizde sitenin hiç çalışmadığını ve Application Error alındığını gördük. Chrome 109.0.5414.121 deki test için ekran görüntüsü ve console çıktısı görseldeki gibi olmaktadır. 
![image](https://user-images.githubusercontent.com/22706692/217826802-44ceb411-beb6-4a99-adca-f453121ea62e.png)

**Comment by darklordens** [comment]
Selamlar, Net konum vermemektedir. Re-Test yaptığımda bir düzelmenin olduğu My Location yazısının kalktığını ama konumlandırma yaparken net bir konumlandırma yapmadığını görüyorum. Örneğin Ben İstanbul\Ümraniye -sarıgazideyim ancak konum otomatik beni Ataşehir / İstanbul olarak gösteriyor. Destek Pls. Ayrıca bu sorunun başlangıc seviyesinden itibaren Chromede de karşılaşıyorum.

**Comment by Kibyra** [comment]
Bu aslında bir chrome bugı: https://bugs.chromium.org/p/chromium/issues/detail?id=872770

2 çeşit çirkin şekilde çözülebilir:
a- Translate fonksiyonunu kapatacağız
b- Site içerisinde ki her dinamik text - {printMe} - span tagı ile wraplanacak <span>{printMe}</span>

Nasıl ilerleyelim?

**Comment by Kibyra** [comment]
> > Bu aslında bir chrome bugı: https://bugs.chromium.org/p/chromium/issues/detail?id=872770
> > 2 çeşit çirkin şekilde çözülebilir: a- Translate fonksiyonunu kapatacağız b- Site içerisinde ki her dinamik text - {printMe} - span tagı ile wraplanacak `<span>{printMe}</span>`
> > Nasıl ilerleyelim?
> 
> ek olarak -> translate kapatılıp #587 feat'i uygulanabilir.

bir arkadaş #587 için pr açmıştı (https://github.com/acikkaynak/deprem-yardim-frontend/pull/588) #587 approve olursa yanlışlarını düzeltip tekrar açabilir. Feature approve olmazsa ona göre tekrar bakarız.

**Comment by efegurkan** [comment]
Selamlar, #592 translate ozelligi kapatilarak cozuldu. Bu issue kapatilabilir ya da enhancement olarak degistirilebilir su an.

**Comment by ahmettulutas** [comment]
> #587

Bu konuyla kim ilgileniyor, prosedür nasıl işliyor? Ben pr'ı uygun hale getirip, gerekli düzenlemeleri yapabilirim. Böyle bir uygulamanın dil desteğini kapamak çok doğru olmaz. Bu konuda kim yardımcı oluyor?

**Comment by efegurkan** [comment]
Geri eklendi diye dil destegi biliyorum.
