### ISSUE TITLE
bug: EDGE Browser da https://rc.afetharita.com/ sayfası üzerinde ki deprem.io iconunda ki metnin düzeltilmesi hakkında.

### ISSUE THREAD

**Issue by darklordens** [acikkaynak/deprem-yardim-frontend#536]
## Hata Tanımı
https://rc.afetharita.com/ sayfasında yeni getirilen deprem.io iconun da belirtilen tanım metni anlaşılır hale getirilmelidir.

-- bu bilgiyi ekleyiniz
** discord kullanıcı adı: @Kaan ARSLAN#1025 **

## Hata Ortamı
Hatanın ortaya çıktığı ortamı açıklayın. Örneğin:
rc.afetharita.com

## Hatayı nasıl aldığınızı adım adım açıklayın

1. Microsoft EDGE browserına gidin
2. (https://rc.afetharita.com/)  tıklayın
3. Sağ üst alanda ki deprem.io iconuna tıklayın. 
4. Tanım metni daha anlaşılır olmalıdır.

## Beklenen Davranış
İlgili metin de fazlalık kelimeler çıkartılmalı sayfa hakkında özet daha anlaşılır bir tanımlama sağlanmalıdır.

## Ekran Görüntüleri
![Metinde düzenleme gerekiyor](https://user-images.githubusercontent.com/61864210/217684057-5b4a59d4-2bfc-4395-afaa-6140a7ad0d85.png)

## Masaüstü Bilgileri
- İşletim Sistemi: windovs
- Tarayıcı microsoft edge
- Sürüm 110.0.5481.78

**Comment by canerakin111** [comment]
Bu istekte calismaya baslayan arkadas varsa yazsin, in Progress'e cekelim.

**Comment by mertcanaltin** [comment]
@canerakin111  Deprem İmece Platformu  metni yeterli olurmu ? @darklordens

**Comment by absolutezero13** [comment]
ben bi fix yolluyorum @canerakin111

**Comment by EmirBoyaci** [comment]
closed via #562

**Comment by canerakin111** [comment]
@eraygundogmus merge sonrasi projeyi bir sonraki seviye'ye tasiyalim.
