### ISSUE TITLE
feat: ne kadar zaman gecti bilgisini goster

### ISSUE THREAD

**Issue by usirin** [acikkaynak/deprem-yardim-frontend#538]
## İsteğiniz şeyi tanımlayın 
Gelen timestamp verisine gore relative time gosterelim (ornek: 20 dakika once)

-- bu bilgiyi ekleyiniz
** discord kullanıcı adı: @umut#3072 **

cc @eraygundogmus

**Comment by sametcodes** [comment]
Bunu alabilirim.
