### ISSUE TITLE
bug: google maps yonlendirme

### ISSUE THREAD

**Issue by cemiluzunhasan** [acikkaynak/deprem-yardim-frontend#541]
## Hata Tanımı
Onceki google maps marker PR'im merge'lenmisti. Fakat ben testlerimi bilgisayar uzerinden yurutmustum. Mobilde su anda gereksiz bir parametre haritaya paslandigi icin konuma marker atilamiyor. Bu parametre bilgisayarda calisirken mobilde calismiyor, bu parametrenin hic gonderilmemesi de sorunu cozuyor.

-- bu bilgiyi ekleyiniz
** discord kullanıcı adı: @cemiluzunhasan#5776 **

## Hata Ortamı
afetharita.com

## Hatayı nasıl aldığınızı adım adım açıklayın
1. Mobil cihazdan siteye giris saglayin (Telefonda Google Maps uygulamasi kurulu olmali)
2. Haritada cikan marker'lardan herhangi birine tiklayin
3. Cikan modal' da "Google Haritalarda Ac" button'una tiklayin
4. Karsiniza uyari cikacak

## Beklenen Davranış
1. Mobil cihazdan siteye giris saglayin (Telefonda Google Maps uygulamasi kurulu olmali)
2. Haritada cikan marker'lardan herhangi birine tiklayin
3. Cikan modal' da "Google Haritalarda Ac" button'una tiklayin
4. Marker atilmis sekilde istenen konumu Google Maps uzerinden gorun

## Akıllı Telefon Bilgileri
- Cihaz: iPhone12
- İşletim Sistemi: iOS
- Tarayıcı safari
- Uygulama Google Maps App

## Ek Bağlam
Cozum: `generateGoogleMapsUrl` methodunda bulunan `loc` keyword'u kaldirilmali. Bu kaldirilinca haritada hem marker atilacak hem de sistem mobilde sorunsuz calisacaktir.

**Comment by usirin** [comment]
gonder gelsin

**Comment by cemiluzunhasan** [comment]
Hemen hallediyorum, kolayliklar 👍🏼

**Comment by aliilhami** [comment]
@cemiluzunhasan issue'yu aldıysan üstlenebilir misin?

**Comment by CyhnYldz** [comment]
@aliilhami @cemiluzunhasan sorun afetharita.com üzerinden bazı cihazlarda devam etmekte. Yukarıda ortam prod olarak yazıldığı için prod üzerinden test edildi nasıl bir yol izleyelim.
düzeltme prod'a alındımı RC üzerinden mi test edelim

**Comment by cemiluzunhasan** [comment]
Selamlar,
Bu cihazlarin herhangi bir ortak ozelligi var mi test asamasinda? (Ikisinde de chrome kullanildi, ikisinde de Google Maps uygulamasi var vs gibisinden?)

Su anda elimdeki cihazlardan test yaptigimda calisir vaziyette oldugunu goruyorum cunku. Aklima ilk gelen sey cache sorunu gibi geldi su asamada. Browser ayarlarini test yapilan herhangi bir cihazda bu site icin reset'leyip tekrar deneyebilir misiniz?

Referans olmasi acisindan ekte video birakacagim. Bana cihaz ozelinde fark yaratacak bir implementasyon degil gibi geliyor cunku. Herhangi bir gorusu olan varsa ve aydinlatirsa da cok sevinirim.

Ayrica hangi konum acildiysa acilan konumda belki bir problem olabilir. Haritadaki hangi konuma tikladiniz? (Enlem ve boylam gozukecek sekilde atabilir misiniz?)

Tesekkurler elinize saglik simdiden @CyhnYldz 

https://user-images.githubusercontent.com/29410269/217956074-92859a2b-59b9-4ab0-8c1a-408bc0bfc079.mp4

**Comment by CyhnYldz** [comment]
@cemiluzunhasan 5 ayrı cihaz üzerinden test yapıldı . farklı browserlarda 2 fail aldık olanların açıklamalarını yolluyorum ikisi de chrome'da fail verdi.

1--Android mobil cihazda Chrome uygulaması üzerinden siteye giriş yaptım
-Haritadaki marker'lardan herhangibirine tıkladım
-çıkan ekranda "Google Haritalarda Aç" butonuna tıkladım
**_-Google Maps uygulaması açıldı ancak sadece uygulama açıldı, konuma gitme veya işaretleme olmadı_**
!-"Yol tarifi al" butonuna tıkladığımda ise o koordinatlara istenilen şekilde en uygun yolu gösterdi
!-Aynı aşamalar samsung mobile browser da istenildiği şekilde çalışıyor, google maps browser üzerinde açılıp, açıldığı gibi haritadaki işaretli konuma gidiyor/Aynı şekilde "yol tarifi al" istenildiği şekilde çalışıyor.

2-Android cihazda google chrome acılır, herhangi bir konuma dokunulur, acılan pencere "google haritalarda ac" a dokunulur. expected result : ilgili konumun acılması . 
actural result: google maps acılır ve mevcut(suanki) konum goruntulenir. 

yarın sabahtan tekrar dediğiniz gibi testlerin tekrarını isteyeceğim ekran görüntüleri ile. iyi geceler

**Comment by CyhnYldz** [comment]
@cemiluzunhasan sorun chrome üzerinden  Google Maps uygulaması açıldığında reproduce edilebiliyor. uygulama kullanıcının o anki konumuyla açılıyor. Chrome dışında kullanılan browserlarda hatayı reproduce edemedik. 

Bu arada ek bilgi olarak : yol tarifi al denildiğinde konuma yol tarifi sorunsuz çalışmakta.
Kolay Gelsin

**Comment by eraygundogmus** [comment]
Hata hala bozuk olduğu için reopen yaptım!

**Comment by cemiluzunhasan** [comment]
Selam tekrardan, ayrintili aciklama icin @CyhnYldz ve tekrar re-open icin @eraygundogmus tesekkurler. Su an guncel dokumantasyonda yazan linklerin ayni implementasyonlarini gecirdim. Tekrardan PR actim.

Kolayliklar 👍🏼

**Comment by CyhnYldz** [comment]
@cemiluzunhasan hazır olduğunuzda bilgi verirseniz re-test yaparız hızlı bir şekilde

**Comment by nazdezar** [comment]
@cemiluzunhasan have we fixed this issue?

**Comment by CyhnYldz** [comment]
@cemiluzunhasan @nazdezar 
As we re-test this issue. 
if you click on a pin it works fine and fixed.  
if you click on an cluster when verified filter is active it shows some place in Istanbul. when you go on and work your way to a single pin it works as expected. but I think it is showing babala location for verified clusters.
I will plece Test-Fail just for reminder so you can check this later when you are available.

**Comment by cemiluzunhasan** [comment]
I'm on it right now. It seems like one of the markers is coming with a location which is in Istanbul but I'll check again

**Comment by cemiluzunhasan** [comment]
This issue should be closed since the problem is in a different scope. Let me explain:

BE is giving a cluster data and this cluster data includes a location based on Istanbul.
But on the other hand, when you click another cluster in the map, you'll see that the `lat,lng` data of the cluster will not change, it will remain the same.

The reason that I'm saying we should close this issue is: Taking a data including Istanbul is wrong, also not updating the drawer data is another problem. But it's out of the scope of map redirections. 

I know that it's a long explanation :) Please ping me if you have some missing points 👍🏼 @akarakus27 @CyhnYldz

**Comment by CyhnYldz** [comment]
We re-tested it. It is fixed. Congrats.

**Comment by CyhnYldz** [comment]
@cemiluzunhasan sorry but problem comes back. when you click open in google maps button while a cluster is selected it shows "Şişli" on goole maps. :(

**Comment by absolutezero13** [comment]
@CyhnYldz can you checkout my PR about this?

**Comment by CyhnYldz** [comment]
@absolutezero13 on my device problem is solved but we are checking with multiple devices to be sure. I will inform you as soon as possible

**Comment by CyhnYldz** [comment]
@absolutezero13 problem solved. 👍

**Comment by oguzergul** [comment]
@senapalaa @CyhnYldz @handekaratas96 @cemiluzunhasan is this issue solved? We need to fix this if it is not fixed yet.
