### ISSUE TITLE
bug: Açıklama modalının estetiksizliği ve haritayı bloklaması

### ISSUE THREAD

**Issue by Kakcil** [acikkaynak/deprem-yardim-frontend#542]
## Hata Tanımı
Mobilde açıklama kısmı oldukça fazla yer kaplıyor biraz daha gereksiz boşluklar silinerek yer kazanılabilir. Masaüstünde ise daralmış estetik olmayan bir görüntü gözüküyor.

** discord kullanıcı adı: @kemdetroit#4551 **

## Hata Ortamı
rc.afetharita.com
afetharita.com
## Hatayı nasıl aldığınızı adım adım açıklayın

1. Siteye mobilden ya da masaüstünden girin.
2. En altta saydamlığı azaltılmış kırmızı backgrounda sahip açıklama yazısını göreceksiniz. Heightı oldukça fazla yer kaplıyor.

## Beklenen Davranış
Haritayı mümkün olduğunca daha az yer kaplaması.

## Ekran Görüntüleri
![image](https://user-images.githubusercontent.com/55282653/217697342-54568991-ba0c-4322-8b90-4062891046e2.png)
![image](https://user-images.githubusercontent.com/55282653/217698101-8b0abb67-86cb-450d-a494-b8d0be57d430.png)

**Comment by absolutezero13** [comment]
Hepsini gör vb. bir şey yapıp kısaltabilir miyiz? Çünkü çok önemli değil gibi. Ben alırım eğer müsaitse

**Comment by berkayvuran** [comment]
@Kakcil bu iş tamamlandı mı? closed görüyorum ama in progress'te, teyit etmek istiyorum
