### ISSUE TITLE
feat: (Button) En yakınımdaki yardım çağrısına git butonu

### ISSUE THREAD

**Issue by kaganbuzcu** [acikkaynak/deprem-yardim-frontend#545]
## İsteğiniz şeyi tanımlayın 
Kullanıcı konumunu yardım çağrısı verileri ile karşılaştırıp en yakındaki yardım çağrısının tespit edilmesi ve harita merkezinin ilgili konuma taşınması işi. 

** discord kullanıcı adı: @kaganbu#7797 **

## Değerlendirdiğiniz alternatifleri tanımlayın
Afet bölgesinde kurtarma faaliyetleri yürüten ekipleri en yakınlarındaki çağrıya kolayca yönlendirebilmek için,

* Sağ üste(mesela), "En Yakınımdaki Yardım Çağrısına Git" görevini uygulayacak bir button eklenmesi 
* Kullanıcı konumunu dönen bir helper yazılması
* Alınan kullanıcı konumu verisinin points ile kıyaslanması ve en yakındaki yardım çağrısı koordinatlarının state'e yazılması
* Tespit edilen en yakın koordinata map center'ın set edilmesi

## Ek Bağlam

Konum verisi talep etmenin yasal yükümlülükleri hakkında bilgim yok, problem yaratabilecek bir konu değilse veya feature'ın kullanışsız olduğu düşünülmüyorsa aşağıdaki gereksinimlere ihtiyaç doğacaktır.

* Wording, buton görünümü ve konumu konularında UI/UX desteği
* Yazılmış kodun revizesi için biraz zaman

![afet-harita-nearest-button](https://user-images.githubusercontent.com/63363182/217695062-728b98a1-d5c7-48e6-804a-d2bc64cc8cd4.gif)

**Comment by canerakin111** [comment]
@kaganbuzcu Google Maps yol tarifini yol verisi uzerinden saglar. Deprem sirasinda hangi yollar da bozulacagi icin kullanisli bir feature olmaz. Onun yerine en yakin 5 noktayi isaretle olabilir. Bu konuyu discussion'a tasiyalim.
