### ISSUE TITLE
feat: Son koordinatlarin local storage'da tutulmasi

### ISSUE THREAD

**Issue by cdagli** [acikkaynak/deprem-yardim-frontend#556]
## İsteğiniz şeyi tanımlayın 
En son koordinatlari local storageda tutarsak ve acilista once onu kontrol edersek kullanici sayfayi her actiginda en son kaldigi yerden devam edebilir. 

Surekli bizim hard code ettigimiz koordinatlardan baslayip kendi bolgene scroll etmek sinir bozucu biraz. 

-- bu bilgiyi ekleyiniz
** discord kullanıcı adı: @Caner dagli#1251 **

## Değerlendirdiğiniz alternatifleri tanımlayın
Değerlendirdiğiniz herhangi bir alternatif çözüm veya özellik hakkında açık ve kısa bir açıklama.

## Ek Bağlam
Bu özellik isteği hakkında herhangi bir başka bağlam veya ekran görüntüsü ekleyin.

**Comment by emirefek** [comment]
Haritayı ilk renderlar hard-coded kordinatlar nasıl alınıyor? Eğer codebase'de nasıl çalıştığınız açıklarsanız bu issue'yu ben alabilirim.

**Comment by cdagli** [comment]
Suradan takip edebilirsiniz: https://github.com/acikkaynak/deprem-yardim-frontend/blob/development/components/UI/Map/utils.ts#L3 

Approved olmasini bekleyelim.

**Comment by ercumentlacin** [comment]
Bu taski alabilir miyim assign edilmediyse

**Comment by aerdemsenturk** [comment]
Burada şöyle bir ayrıntı var. Şu anda Haritada belli bir konumu ve zoom seviyesi hash olarak URL ye ekleniyor link paylaşımı kolaylığı için. 
Localstore'da koordinat tutulacaksa, url'de hash olduğu takdirde store'dan koordinat almaktan vazgeçmesi gerekecek.

**Comment by eraygundogmus** [comment]
@aerdemsenturk bu yorumu pr altına yapar mısın? arkadaş pr açmış

**Comment by ercumentlacin** [comment]
> Burada şöyle bir ayrıntı var. Şu anda Haritada belli bir konumu ve zoom seviyesi hash olarak URL ye ekleniyor link paylaşımı kolaylığı için. Localstore'da koordinat tutulacaksa, url'de hash olduğu takdirde store'dan koordinat almaktan vazgeçmesi gerekecek.

Aslında öncelikle hash bilgisi var mı diye kontrol ediyor eğer yoksa localStorage bakıyor varsa onu getiriyor eğer o da yoksa son olarak default değere gidiyor.

**Comment by aerdemsenturk** [comment]
> > Burada şöyle bir ayrıntı var. Şu anda Haritada belli bir konumu ve zoom seviyesi hash olarak URL ye ekleniyor link paylaşımı kolaylığı için. Localstore'da koordinat tutulacaksa, url'de hash olduğu takdirde store'dan koordinat almaktan vazgeçmesi gerekecek.
> 
> Aslında öncelikle hash bilgisi var mı diye kontrol ediyor eğer yoksa localStorage bakıyor varsa onu getiriyor eğer o da yoksa son olarak default değere gidiyor.

Hah farkettim şimdi, eline sağlık.
