### ISSUE TITLE
feat: Redirect to e.afetharita.com for areas with low connectivity and mobile devices

### ISSUE THREAD

**Issue by denizsult** [acikkaynak/deprem-yardim-frontend#557]
## Define your request
Redirect to e.afetharita.com for areas with low connectivity and mobile devices. It loads faster and we can get details more quickly.

** discord username: Denizsl#2537 **

## Define the alternatives you have in mind
--

## Additional context
Current performance is not enough. Getting the data rapidly is very important in times like these.

**Comment by denizsult** [comment]
@fdemir Dostum repo yetkisi var mı sende?

**Comment by eraygundogmus** [comment]
Şöyle yapalım: loading state 5 saniyenin üzerine çıkarsa kullanıcıya modal çıkartıp, seni daha az verinin olduğu light versiyona taşımamızı ister misin diye soralım. Evet derse yönlendirelim

**Comment by canerakin111** [comment]
@eraygundogmus projeyi unutmayalim.

**Comment by denizsult** [comment]
Ben üstlenebilirim

**Comment by furknozg** [comment]
Ben potansiyel bir impl bulmuş olabilirim de şu an modal yerine confirm çıkartıyor.

**Comment by fdemir** [comment]
update olunca comment atarsaniz sevinirim. orasi active maintain edilen bir yer degil. direkt almamaliyiz.

**Comment by denizsult** [comment]
@fdemir  tamamdır zaten p1 akşam bakacağım. Bu arada rol almama rağmen dc'ye giremiyorum sebebi nedir?

**Comment by fdemir** [comment]
gökata#6419 yazabilir misin? @denizsult

**Comment by denizsult** [comment]
> gökata#6419

yazdım dostum

**Comment by emr3rden** [comment]
TR: Issue'ların bundan sonra ingilizce olarak gönderilmesi gerekiyor ve halihazırda açık olanlara da bu talebimizi iletiyoruz. O nedenle sizden ricamız bu issue'yu ingilizce olarak düzenlemeniz. Lütfen ingilizce olarak düzenler misiniz?

EN: "Issues" must be sent in English from now on, and we forward this request to those who are already open. Therefore, we request you to edit this "issue" in English. Could you please edit it in english?

**Comment by fdemir** [comment]
embed version is not actively maintained. Let me know if u want to make a couple of refactoring. i needed to make a couple adjustments to make sure everything is alright. thanks.
