### ISSUE TITLE
feat: taraniyor yazisi yeniden tasarlanmali. taraniyor kismi cihazlarda ortada gozukmuyor.

### ISSUE THREAD

**Issue by AhmetEnesKCC** [acikkaynak/deprem-yardim-frontend#566]
## İsteğiniz şeyi tanımlayın 

x saniye icerisinde taranacak kismi ortalanmamis.

-- bu bilgiyi ekleyiniz
AHMETenes#9745

## Değerlendirdiğiniz alternatifleri tanımlayın
css ile ilgili duzenlemeler yapildi

## Ek Bağlam
Yeni Tasarim
<img width="431" alt="Screen Shot 2023-02-09 at 13 00 48" src="https://user-images.githubusercontent.com/61010746/217780802-c8b6e8cb-8b57-4863-aa8e-efa1b4bf5f57.png">

**Comment by AhmetEnesKCC** [comment]
bunun pr i hazir. approve bekliyorum

**Comment by AhmetEnesKCC** [comment]
pr i approvedan sonra acabildigimiz icin bekliyorum

**Comment by usirin** [comment]
@AhmetEnesKCC pr hazirsa gonder gelsin, yoksa kapatalim cok da acil bi issue degil cunku.

**Comment by umutincek** [comment]
https://github.com/acikkaynak/deprem-yardim-frontend/pull/608 pr açıldı
