### ISSUE TITLE
bug: Web tarayıcıda haritaya zoom in-out yapıldığında sayaç baştan başlıyor.

### ISSUE THREAD

**Issue by SebahattinDemir** [acikkaynak/deprem-yardim-frontend#568]
Web tarayıcıda haritaya zoom in-out yapıldığında otomatik sayfa yenileme için görünen sayaç, süreyi doldurmadan baştan başlıyor.

discord kullanıcı adı: @Sebahattin#4863

Hata Ortamı
rc.afetharita.com
afetharita.com

## Hatayı nasıl aldığınızı adım adım açıklayın

1. 'rc.afetharita.com' a gidin
2. açılan haritada zoom in - zoom out yapın
3. otomatik tarama için 30 sn. den geri saymaya başlayan sayacın zoom geçişlerinde süre dolamdan tekrar 30 saniyeden başladığını görebilirsiniz

## Beklenen Davranış
Sayfada yapılan hareketlerde sayacın süresinin yenilenmemesi. 30 saniye dolana kadar sayacın çalışması.

## Masaüstü Bilgileri
- İşletim Sistemi: windows 10
- Tarayıcı chrome

## Ek Bağlam
Açılan harita sayfasında herhangi bir işlem yapmadan sayacın 30 saniye dolmasını beklediğinizde sayfa otomatik olarak yenileniyor ve sayaç 900 saniyeden geriye saymaya başlıyor.

**Comment by DodoBey** [comment]
Buradaki coordinate event lerini takip etmemizin spesifik bir nedeni var mı? Bu sebep oluyor buna. Ya da dependecy i kaldırıp her event değişiminde event ı tetiklemesini kesebiliriz fakat event type ı takip etmenin pek bir gerekliliği yok gibi geldi.

<img width="522" alt="Ekran Resmi 2023-02-09 02 27 26" src="https://user-images.githubusercontent.com/77416196/217786920-f9849909-ea20-4c84-b44b-930507241043.png">

**Comment by SebahattinDemir** [comment]
Selam, Açılan harita sayfasında herhangi bir işlem yapmadan sayacın 30 saniye dolmasını beklediğinizde sayfa otomatik olarak yenileniyor ve sayaç 900 saniyeden geriye saymaya başlıyor. Buda bilinçli olarak mı yapıldı

**Comment by usirin** [comment]
@SebahattinDemir aynen bunlarin hepsi bilincli kararlar request bomb yapmamak icin. herhangi bi sekilde haritayi hareket ettirdiginde yeni request yapilacak.
