### ISSUE TITLE
feat: sag uste afetbilgi.com eklenmesi

### ISSUE THREAD

**Issue by fdemir** [acikkaynak/deprem-yardim-frontend#570]
## İsteğiniz şeyi tanımlayın 
Ekranin sag ust kosesine veya musait bir yerine afetbilgi.com linki eklenmeli.
-- bu bilgiyi ekleyiniz  discord kullanıcı adı: gökata#6419
## Değerlendirdiğiniz alternatifleri tanımlayın
tasarimcilara basvurulsa iyi olur.

## Ek Bağlam
url: https://afetbilgi.com

**Comment by AhmetEnesKCC** [comment]
tasarım konıusunda destek olabılırım

**Comment by rgnyldz** [comment]
Fgma dosyası varsa ben hem tasarım hem buton ekleme kısmında yardımcı olabilirim.

**Comment by cdagli** [comment]
Merge edilmis gorunuyor, kapatiyorum 👍
