### ISSUE TITLE
https://deprem.io/ 'da eczane bilgi 

### ISSUE THREAD

**Issue by buraktuzlutas** [acikkaynak/deprem-yardim-frontend#572]
## İsteğiniz şeyi tanımlayın 
Bu alanda bölgeden sürekli girip çıkan ekiplerin kronik rahatsızlığı olan insanlara ilaç tedariğinde yardımcı olması amaçlı bi kısım uygun görülmesi halinde eklenebilir.

buraktuzlutas#4581

## Değerlendirdiğiniz alternatifleri tanımlayın
Yardım Listeleri kısmına İlaç ihtiyacı olanlar bölge yakınlarından ilaç tedariği konusunda iletişime geçebilmeli

## Ek Bağlam

![ilaceczane](https://user-images.githubusercontent.com/7132788/217790756-86d90af1-696d-4480-ad1a-3ce7c2620ca7.png)

**Comment by DodoBey** [comment]
Bunun kendi reposu yok muydu orada açmak daha sağlıklı olur sanki? @buraktuzlutas

**Comment by buraktuzlutas** [comment]
Oraya erişim yetkim sanırım yok, yeni katıldım. ilgili linki discord'dan yollar mısın ?  @DodoBey

**Comment by birkaany** [comment]
https://github.com/acikkaynak/deprem-io-frontend/issues

Buraya açabilirsiniz, buradakini kapatıyorum bilginize.
