### ISSUE TITLE
refactor: pop up ın sağa katman iconun altına hizalanıp küçültülmesi

### ISSUE THREAD

**Issue by DodoBey** [acikkaynak/deprem-yardim-frontend#573]
### Refactor İsteği
Yeni eklenen katman seçeneği ile birlikte pop up tamamen alan tara butonunun üstüne binmekte, pop up ı sağa hizalayıp biraz küçültsek tasarım açısından daha iyi olacak gibi. Zaten sadece masaüstü sürümünde görünür şu anda, biraz küçültmek sorun oluşturmayacak diye düşünüyorum.

-- bu bilgiyi ekleyiniz
** discord kullanıcı adı: @Dodo Bey#7116 **

Refactor isteğiniz bir sorunla ilgili mi? Lütfen açıklayın.

Açık ve öz bir şekilde sorunun ne olduğunu açıklayın. Örneğin, kodu okumakta zorluk çekiyorum çünkü [...]

### Çözüm Önerisi

Pop up sağa, katman menüsü altına hizalayıp küçültme.

### Ek Bağlam
<img width="874" alt="Ekran Resmi 2023-02-09 02 41 03" src="https://user-images.githubusercontent.com/77416196/217791203-31cab28b-669a-430d-a1c1-1eb07ed9c495.png">

**Comment by absolutezero13** [comment]
ben alabilirim, bi kaç refactor edilmesi gereken yerler de var. Onu da issue'ya belirtebilir miyiz? Mesela bu linkler maplenebilir

**Comment by absolutezero13** [comment]
@eraygundogmus buraya bi bakabilir miyiz, sorun yoksa pr atıcam

**Comment by canerakin111** [comment]
Bu konu #595 te tartisiliyor.

**Comment by absolutezero13** [comment]
@canerakin111 bana pek alakalı gibi gelmedi, diğer iş approve olsa bile baya uzun sürerdi. Bunun pr'ında ileride muhtemelen kullanacağımız bir yapı da var.
