### ISSUE TITLE
feat: merhaba site içerisinde stored HTML enjeksiyon açığı bulunmaktadır bu da siyeyi oltalama saldırılarına açık hale getirmektedir.

### ISSUE THREAD

**Issue by eglarestN** [acikkaynak/deprem-yardim-frontend#575]
## İsteğiniz şeyi tanımlayın 
Açık ve kısa bir şekilde istediğiniz feature'ın ne olduğunu tanımlayın.

-- bu bilgiyi ekleyiniz
** discord kullanıcı adı: @afetharita#0001 **

## Değerlendirdiğiniz alternatifleri tanımlayın
Değerlendirdiğiniz herhangi bir alternatif çözüm veya özellik hakkında açık ve kısa bir açıklama.

## Ek Bağlam
Bu özellik isteği hakkında herhangi bir başka bağlam veya ekran görüntüsü ekleyin.

**Comment by canumay** [comment]
Detay verebilir misiniz? Birdde issueyu kurallara uygun hale getirebilir misiniz?

**Comment by eglarestN** [comment]
Site içerisinde kayıt ekle seçeneğine script eklendiğinde html enjeksiyonu yapılabiliyor. Kurallara uygun hale nasıl getirebilirim yardımcı olur musunuz

**Comment by birkaany** [comment]
> Site içerisinde kayıt ekle seçeneğine script eklendiğinde html enjeksiyonu yapılabiliyor. Kurallara uygun hale nasıl getirebilirim yardımcı olur musunuz

https://github.com/acikkaynak/deprem-yardim-frontend/blob/development/.github/ISSUE_TEMPLATE/feature_request.md

Bu template'i kullanarak içeriği ve başlığı düzenleyebilirsiniz

**Comment by EmirBoyaci** [comment]
@eglarestN afetharita.com üzerinde mi bu?

**Comment by eglarestN** [comment]
Deprem.io

**Comment by EmirBoyaci** [comment]
Doğru repository değil burası

**Comment by eglarestN** [comment]
Siteye zarar vermemek için pentest yapamıyorum siteyle iletişim kısmına mesaj gönderdim fakat geri dönüş alamadım

**Comment by eglarestN** [comment]
Bugbounty linki buraya yönlendirdi ama yanlışsa tamamdır
