### ISSUE TITLE
bug: Otomatik tarama guncel koordinatlari request de eklemiyor.

### ISSUE THREAD

**Issue by emresandikci** [acikkaynak/deprem-yardim-frontend#578]
## Hata Tanımı
Otomatik alan tarama, suresi doldugunda, donen response haritaya yansitilmiyor.

Discord kullanıcı adı: @emresandikci#9746

## Hata Ortamı

rc.afetharita.com

## Hatayı nasıl aldığınızı adım adım açıklayın

1. rc.afetharita.com'a gidin
2. ilk haritada pinlenen noktalar yuklenmesini bekleyin
3. Biraz zoom out yapin ve otomatik tarama suresinin dolmasini bekleyin
4. Sure dolduktan sonra atilan request de zoom out yapildiktan sonra latitude ve longitude guncel olarak requeste dahil edilmiyor.
5. Alani tara button tiklandiginda guncel  latitude ve longitude gonderiliyor.

## Beklenen Davranış
 Sure dolduktan sonra atilan request de zoom out yapildiktan sonra latitude ve longitude guncel olarak requeste dahil edilmeli ve ilgili alanlar haritada guncel olarak gosterilmeli.

## Ekran Görüntüleri
 
 Ilk sayfa yuklendiginde gosterilen konumlar

<img width="1436" alt="1" src="https://user-images.githubusercontent.com/7765958/217800744-ecb08a9e-87bb-4216-9f2c-36c1d3881843.png">

 Harita zoomout yapildiginda

<img width="1303" alt="1.1" src="https://user-images.githubusercontent.com/7765958/217799739-94807e88-56f4-4013-b9a5-cbaba4e964ba.png">

Otomatik tarama basladi

<img width="1302" alt="2" src="https://user-images.githubusercontent.com/7765958/217799757-87bcb39a-c0ec-4019-a857-598028f289ed.png">

Otomatik tarama bitti ve haritaya yansitilmadi

<img width="1306" alt="3" src="https://user-images.githubusercontent.com/7765958/217799780-00ebd54e-55bb-4d7f-8778-bad4231cae0b.png">

Alani Tara button tiklantikdan sonra dogru koordinatlara gore harita guncelendi

<img width="1305" alt="4" src="https://user-images.githubusercontent.com/7765958/217800004-1ec9c12b-0dd9-475f-814f-502217394f2d.png">

## Masaüstü Bilgileri
- İşletim Sistemi: MacOS Catalina v10.15.7
- Tarayıcı Chrome
- Sürüm Version 109.0.5414.119 (Official Build) (x86_64)

**Comment by eraygundogmus** [comment]
macOs monterey 12.6
brave browser test edildi, aynı hataya rastlandı

**Comment by Kibyra** [comment]
Bunu aldım ben, pr açacağım.
