### ISSUE TITLE
feat: Directions to a location via Apple Maps

### ISSUE THREAD

**Issue by alperencantez** [acikkaynak/deprem-yardim-frontend#579]
## İsteğiniz şeyi tanımlayın 
Henüz hali hazırda bir tane Yol Tarifi Al butonu var ve bu Google Maps'e gidiyor. Telefonuna Google Maps kurmamış iOS kullanıcıları için aynı butonun Apple Maps'e giden versiyonun eklenmesi.

-- bu bilgiyi ekleyiniz
** discord kullanıcı adı: @canadianclublove#2188 **

## Ek Bağlam
Screenshot: 
![Screen Shot 2023-02-09 at 15 41 21](https://user-images.githubusercontent.com/80427016/217816326-9a2efa24-6d1a-4662-b892-2f15fd5b2893.png)

**Comment by poiu694** [comment]
I will open pr when approve

**Comment by alperencantez** [comment]
> I will open pr when approve

I've already made the changes locally. I'll use them when approved. Thank you for your interest.

**Comment by canerakin111** [comment]
This creates additional unnecessary complexity. Let's go with removing all get direction buttons. Once the user clicks on the Google or Apple option, they just need to click "direct" in the next app.
