### ISSUE TITLE
Detaylı Filtreleme

### ISSUE THREAD

**Issue by coderserdar** [acikkaynak/deprem-yardim-frontend#58]
Filtreleme kısmında
Sadece il-ilçe yerine tek bir textbox olsa ve il, ilçe, adres, ad soyad, kaynak alanlarından yüzdeli sorgulama yapsa, daha hızlı bir şekilde aranan kayıtlara ulaşılabilir diye düşünüyorum.
Python ile yazıldığı için çok fazla dahil olamıyorum koda. 
Ama yine de elimden geleni yapmaya hazırım

**Comment by eraygundogmus** [comment]
Yanlış repoya yazıyorsunuz sanırım

**Comment by coderserdar** [comment]
Backend tarafına mı taşıyayım hocam?
