### ISSUE TITLE
feat: Fay hatlarının görüntülenmesi 

### ISSUE THREAD

**Issue by ozcanzaferayan** [acikkaynak/deprem-yardim-frontend#580]
## Fay hatlarının harita üzerinde görüntülenmesi için geoJson katmanınin eklenmesi

** discord kullanıcı adı: @zaferayan#5143**

## Ekran görüntüsü
<img width="957" alt="image" src="https://user-images.githubusercontent.com/1326963/217818726-198ee5c3-6c5e-4453-9415-04795910187d.png">

## Geojson data
Data içeriği aşağıdan alınıp sadece Türkiye hatlarını görüntüleyecek şekilde temizlenmiştir: 
https://github.com/fraxen/tectonicplates/blob/master/GeoJSON/PB2002_plates.json

**Comment by puskuruk** [comment]
Bu özelliğin ürüne nasıl bir deger katacagini düşünüyorsun? @ozcanzaferayan

**Comment by aerdemsenturk** [comment]
Yıkık binalar ve fay hatları arasındaki ilişkiyi görmek ilginç olurdu ama bu haritanın amacının dışına çıkıyor bence.

**Comment by ozcanzaferayan** [comment]
@puskuruk korelasyonu görmek adına. For example:
https://twitter.com/fkadev/status/1623593030291791872

**Comment by puskuruk** [comment]
Ilginc olacagina katılıyorum fakat sence bundle sizeimizi arttırmak uygulamayı kullanarak aksiyon alacak kisilerin daha fazla data kullanmasına değecek mi? Bu güzel bir side project olabilir veya baska bir yerde serve edilebilir fakat uygulamanın su anki haline dahil edilmesini desteklemiyorum.

**Comment by vsabah** [comment]
Fay hattı verilerine nereden ulaştınız öğrenebilir miyim acaba?
