### ISSUE TITLE
bug:  İlk Açılış ekranı Map Zoom -> Kahramanmaraş

### ISSUE THREAD

**Issue by CyhnYldz** [acikkaynak/deprem-yardim-frontend#583]
## Hata Tanımı
Hatanın ne olduğu hakkında açık ve kısa bir açıklama.

App yüklendiğinde Web ve Mobilde Kahramanmaraş Odaklanmış olarak açılmakta

-- bu bilgiyi ekleyiniz

@Ceyhun Yıldız#6679

## Hata Ortamı

rc.afetharita.com
afetharita.com
## Hatayı nasıl aldığınızı adım adım açıklayın

1. 'https://afetharita.com/' a gidin
2. Hata görünüyor

1. 'https://rc.afetharita.com/' a gidin
2. Hata görünüyor

## Beklenen Davranış

ilk açılışta Kahramanmaraş yerine, yoğunluğun olduğu bölgenin genelinin gösterilmesi.
Hatay'da uygulamayı kullanan birinin önce zoom-out yapması sonrasında tekrak zoom-in yapması gerekmekte. özellikle mobil kullanımda bu sıkıntı yaratmakta.

## Ekran Görüntüleri
![Ekran görüntüsü 2023-02-09 170144](https://user-images.githubusercontent.com/111140617/217833738-8fd3af86-13b7-407f-80fb-ecd0b32246b0.png)

## Masaüstü Bilgileri
- İşletim Sistemi: [Windows]
- Tarayıcı [chrome, FireFox, Edge]
- Sürüm [chrome 109.0.5414.120 (Resmi Derleme) (64 bit) Sürümü]

## Akıllı Telefon Bilgileri
- Cihaz: [Samsung S21]
- İşletim Sistemi: [Android 13]
- Tarayıcı [Samsung Internet]
- Sürüm [19.0.6.3]

## Ek Bağlam
Bu uygulamanın yazılımında emek veren herkesin ellerine, emeğine sağlık. çok kısa bir zamanda efsane işler yaptınız ve yapmaya devam ediyorsunuz. bir canın bile kurtulmasına vesile olabildiysek ne mutlu. hepinize kolaylıklar diliyorum.

**Comment by yunusunver** [comment]
alabilirim bu taskı

**Comment by puskuruk** [comment]
Anladigim kadariyla veriyi çektikten sonra markerlarin en cok yogunlasacagi yer bulunup sonrasında haritada o bölgeyi göstermek istiyorsunuz fakat markerlarin en yogun olacağı yeri bulmayi nasıl planlıyorsunuz?

Aklıma gelen çözüm: Bize gelen datanın içerisindeki datayı sehir isimlerine gore sort etmek ve sonrasında ilk siradaki sehri alıp haritayı elimizde tuttuğumuz sehirlerin statik koordinatları datası ile hareket ettirmek.

Aklınıza daha iyi bir çözüm geliyor mu?

**Comment by yunusunver** [comment]
Burada default zoomu 14 ten 9 a çekmek yeterlidir. Default koordinat zaten deprem bölgesini gösteriyor. Default zoomu ayarlayınca sorun çözülüyor.
![Screenshot 2023-02-09 at 17 36 43](https://user-images.githubusercontent.com/24482512/217842976-137dc58b-fe20-4c12-927a-1b0a807607dd.png)

**Comment by younver** [comment]
@puskuruk backend tarafına (address api) en yoğun bölgenin bulunması ile ilgili bir algoritma yazmıştım https://github.com/acikkaynak/deprem-yardim-backend/pull/135

belki backend tarafına bunun için ayrı bir endpoint yapılabilir, böylece hem frontend hem de sistemin diğer elemanları kendi içerisinde bu sort'lamayı yapmak zorunda kalmayabilir, tam olarak çözümü bilemiyorum.

**Comment by hasanugr** [comment]
Default zoom'u geri çekmek (tüm alnı gösterecek şekilde), ilk girişte çok fazla data yüklenmesine ve yavaşlamaya sebebiyet verir.
Buna en makul çözüm kanaatimce location bilgisini cihazdan alıp ona göre ilk yüklemeyi yapmak olacaktır. 
Eğer location paylaşımına izin vermediyse de BE'den @younver 'da bahsettiği gibi yoğun bölgenin bilgilerini isteyebiliriz.

Bu iş için lead'lerden makul bir çözüm önerisi isteyelim derim, bunlar kişisel önerilerimdir.

**Comment by puskuruk** [comment]
Kulaga cok guzel geliyor @younver. Eline sağlık 🍻

Öyleyse once bu bahsettigin endpointe istek atıp sonrasında haritayı oraya hareket ettirebiliriz. Harita hareketini tamamladiginda ise su an kullandigimiz endpoint ile veriyi alabiliriz 🙏

**Comment by younver** [comment]
Backend'de bu konu üzerine çalışıp PR açıyorum. Gerekli bilgilendirmeleri buradan paylaşırım.

**Comment by canerakin111** [comment]
Bu issue test ekibi tarafindan olusturulmus. Test ekibinin olusturdugu issue'lar Test-failed ile isaretlenecek.

**Comment by canerakin111** [comment]
@oguzergul backend'e de baglayabilir miyiz?

**Comment by cdagli** [comment]
Suna bakalim derim https://github.com/acikkaynak/deprem-yardim-frontend/issues/556  En azindan bunu kullanici sadece 1 kere yapar, ondan sonra surekli en son biraktigi yeri gorur. 

Maras'a center edildi deprem merkezi oldugu icin. Zoom seviyesini de ozellikle azaltmiyoruz, bounding box kucuk kalsin ve ilk data boyutu az olsun diye.

**Comment by canerakin111** [comment]
@usirin konustugumuz gibi fix extend gidelim. Deprem anabolgelerini hepsini gosterebilecek bir zoom seviyesine cekelim.

**Comment by eytanfb** [comment]
aldim bunu

**Comment by canerakin111** [comment]
@usirin Is this in testing? Can we confirm?

**Comment by CyhnYldz** [comment]
@canerakin111 @usirin test ekibine iletildi

**Comment by CyhnYldz** [comment]
@canerakin111 @usirin size ve tüm ekibe günaydınlar diliyorum. Test Pass. 
Herkesin eline sağlık.
Kolay gelsin.
