### ISSUE TITLE
bug: Chrome bazında Twitter içeriklerini Share etmek istediğimizde butonlar anlık çalışmamazlık durumu oluşuyor. Genel bir kontrol gerekiyor.

### ISSUE THREAD

**Issue by darklordens** [acikkaynak/deprem-yardim-frontend#585]
## Hata Tanımı
Chrome de Twitlere ulaşıldığın da alt da gelen SHARE basıldığın da share çalışmıyor. Edge de ulaşıldığı görüldü.

-- bu bilgiyi ekleyiniz
** discord kullanıcı adı: @Kaan ARSLAN#1025 **

## Hata Ortamı

rc.afetharita.com

## Hatayı nasıl aldığınızı adım adım açıklayın

1. (https://rc.afetharita.com/) a gidin
2. Haritadan herhangi bir konum iconuna tıklayın. (Twitter paylaşımı aktif duranlar olacak ve Share butonu aktif gözüküyor olmalıdır.)
3. Kayıtlı verileri göster kapalı konumlandırılacak.
4. Share butonu çalışmıyor.

## Beklenen Davranış
Farklı kullanıcı ve ekipmanda farklılık gösterdiği için genel bir kontrol yapılması gerekiyor. Share butonu aktif olup paylaşım yapılabilir olmalıdır.

## Ekran Görüntüleri
![Share butonu çalışmıyor](https://user-images.githubusercontent.com/61864210/217840799-39c608d1-8129-48bf-9f45-1ab04ea9e2cf.png)

## Masaüstü Bilgileri
- İşletim Sistemi: Windovs
- Tarayıcı Chrome
- Sürüm 110.0.5481.78

**Comment by hasanugr** [comment]
@darklordens Chrome ve Edge üzerinde test ettiğimde çalışmayan paylaş butonuna denk gelemedim.
Resim ile ilettiğin id'li datayı da özellikle test ettim ama çalışmadığı duruma yine de denk gelemedim.
Çalışmadığında nasıl bir tepki alıyorsun ekranda, hata mı veriyor veya hiç bir etkileşim olmuyor mu? Biraz daha detay verebilir misin?

**Comment by darklordens** [comment]
Hasan selamlar, locationlarda twitter linkleri bazen boş unknown olabiliyor. Haritadan bilakis bir twitter paylaşımı olan ayrıca ekstradan Share butonu aktif olarak cıkan paylaşımları bulmalıyız. Sol alttan. Anca o şekilde bu durumu görüntüleyebilirsiniz.
Harita üzerinde herkes de farklı durum oluşuyor. Bazılarımızda tüm twitter içerikleri görüntülenirken. Bazılarımız da görüntülenmiyor. Burada bir stabilazasyon sorunu var gibi. Location iconlarından yönlenerek gidebiliyoruz dediğimi gibi.
Kolay gelsin.

**Comment by hasanugr** [comment]
@darklordens  Kontrol ettiğimde çalışıyor dediğim durumda Chrome'ın 109.xxx sürümünde test etmiştim ve çlışıyordu.
Senin notta belirttiğin 110.xxx sürümüne geçtikten sonra paylşım sorunu ile karşılaşmaya başladım. 
Fakat bu buton IFrame içinde geldiği için müdahle etmemiz çok zor, bu konuda başka arkadaşlara da danışıp fikir alabiliriz. 
Burası approve edildiğinde konuyu içeride toplu bir şekilde inceleriz.

**Comment by darklordens** [comment]
Tamamdır. Teşekkürler

**Comment by muhammedikinci** [comment]
Selamlar, bu Share butonundan bahsediyorsak, iframe içerisinde twitframe kendi yüklüyor bir düzenleme olabileceğini düşünmüyorum 🤔 twitframe bu proje ile yazılmadı sanırım. Ayrıca şimdi çalışıyor gibi
![image](https://user-images.githubusercontent.com/11901620/217851246-682ab9a3-10ce-4275-acf9-daef3e3141b3.png)

Ancak dediğiniz gibi bir sorun var. Undefined olarak çekmeye çalışıyoruz bu noktada büyük ihtimalle kaynak twitter olmayabilir.
https://twitframe.com/show?url=https://twitter.com/undefined/status/undefined

**Comment by dopplerDistortion** [comment]
Share butonu ile ilgili farklı bir davranış ile karşılaşıldı. 
- Windows chrome 110+ cihazlar Share butonu geldiği  share butonu tepki vermiyor.
- Windows chrome 110 altındaki cihazlar Share butonu geldiği ve çalıştığı gözlemlendi.
- Mac cihazlarda Share butonu yerine Copy butonu gözükmektedir. 
- Mobil cihazlarda Share butonu geldiği ve çalıştığı gözlemlendi.

**Comment by usirin** [comment]
Simdilik kapatiyorum cunku external API problemi fix etmekle ugrasacagimiz bi case gibi durmuyo
