### ISSUE TITLE
refactor: change time format for api request on frontend

### ISSUE THREAD

**Issue by oguzergul** [acikkaynak/deprem-yardim-frontend#586]
### Refactor İsteği

-- bu bilgiyi ekleyiniz
** discord kullanıcı adı: @oguzergul#9634**

Refactor isteğiniz bir sorunla ilgili mi? Lütfen açıklayın.

Açık ve öz bir şekilde sorunun ne olduğunu açıklayın. Örneğin, kodu okumakta zorluk çekiyorum çünkü [...]

Time formats should be  ```utc unix milis ``` format

### Çözüm Önerisi

Kafanızda bir çözüm varsa, lütfen açıklayın.

### Ek Bağlam

Lütfen ek bağlamı buraya ekleyin.

**Comment by hasanugr** [comment]
@oguzergul Tam olarak hangi request için bu isteği yaptın acaba, ben herhangi bir request içerisinde time bilgisi yolladığımızı göremedim. 🤔 
Response içerisindeki time format'dan bahsediyorsan eğer bu data BE tarafından handle ediliyor oraya issue açmak gerekir.

**Comment by canerakin111** [comment]
Frontend'de halledilecek bir issue.
