### ISSUE TITLE
bug: Konum detaylarının sayfa sınırlarını aştığı kısımlar görüntülenemiyor

### ISSUE THREAD

**Issue by sevilayerkan** [acikkaynak/deprem-yardim-frontend#591]
## Hata Tanımı
Konum detaylarının sayfa sınırlarını aştığı kısımlar görüntülenemiyor. Web üzerinde Edge, Opera, Chrome, Mobilde Safari ve Chrome'da hata reproduce edildi. Özellikle mobilde ciddi sorun oluşturduğu gözlemlenmiştir. 

-- bu bilgiyi ekleyiniz
notDepresseDeveloper#0919

## Hata Ortamı
rc.afetharita.com
afetharita.com
## Hatayı nasıl aldığınızı adım adım açıklayın
1. Bir lokasyondaki içerik kontol edilmeye çalışılır.
2. Yardım içeriğinin tamamının son satıra kadar görüntülenip görüntülenmediği kontrol edilir.
3. Uzun içerikler için de 2. işlem kontrol edilir.

## Beklenen Davranış
Beklediğiniz şeyin açık ve kısa bir açıklaması.
Yardım içeriğinin tamamının Twitter fonksiyonlarıyla birlikte (paylaş butonu vs.) görüntülenebilmesi/scrollanabilmesi.

## Ekran Görüntüleri
![image](https://user-images.githubusercontent.com/22706692/217843742-57e467ec-b307-4e1c-addc-645e00fdf0e1.png)

## Masaüstü Bilgileri
- İşletim Sistemi: Windows
- Tarayıcı : Edge, Opera, Chrome
- Sürüm : En güncel sürümler

## Akıllı Telefon Bilgileri
- Cihaz: iOS (Ipad 6th Gen), Android 
- İşletim Sistemi: iOS 14.2
- Tarayıcı : IOS'ta Safari ve Chrome, Android'de Chrome
- Sürüm : En güncel sürümler

**Comment by emirefek** [comment]
+1 reproduce edebildim. Soldaki div scroll etmeye izin vermiyor.

![Ekran görüntüsü_20230209_203024](https://user-images.githubusercontent.com/6191145/217891855-6e03f6eb-af34-4544-bd2f-5a67c8ef8048.png)

**Comment by ogzavc** [comment]
assign beklemek mi gerekiyor? gönderelim mi yoksa hemen?

**Comment by usirin** [comment]
Gonderin gelsin abi @nejatcanunlu @ogzavc

**Comment by nejatcanunlu** [comment]
hemen geliyor

**Comment by nejatcanunlu** [comment]
geldi: https://github.com/acikkaynak/deprem-yardim-frontend/pull/599

**Comment by berkayvuran** [comment]
@sevilayerkan bu iş tamamlandı mı? closed görüyorum ama in progress'te, teyit etmek istiyorum.

**Comment by sevilayerkan** [comment]
@berkayvuran Testleri tekrarladık özellikle küçük ekran boyutlu mobil cihazlarda hata hala devam ediyor. Durumla ilgili ekran görüntüsü şu şekilde. Tekrarlayamazsanız hatayı tekrar yazabilirsiniz.
![image](https://user-images.githubusercontent.com/22706692/218084841-73f2d85c-bbf4-4590-80a9-1439acd8d2a8.png)

**Comment by nejatcanunlu** [comment]
@sevilayerkan burada drawer scroll etmiyor mu? Şu an rc'de drawer'ı dolduran data backendden gelmiyor, geldiğinde kontrol edeceğim.
