### ISSUE TITLE
bug:  Edge ve Chrome'da çeviri fonksiyonları kullanıldığındaki Application Error hatası

### ISSUE THREAD

**Issue by sevilayerkan** [acikkaynak/deprem-yardim-frontend#592]
## Hata Tanımı
Edge ve Chrome'da üzerindeki Çeviri fonksiyonları kullanıldığında uygulama Application Error veriyor. Github'dan kontrol edildiğinde bu konuyla ilgili issue #532 açıldığı görüldü ancak bu issue'nun sorunu açıklamadığı görüldüğünden yeni bir issue açılması kararlaştırıldı.

Edge ile birlikte Chrome'da da browserdaki çeviri fonksiyonunu açarak bu hatayı reproduce ettiğimizde rc de yenileme butonunun çalışmadığını prodda ise sitenin hiç çalışmadığını ve Application Error alındığını gördük. 

-- bu bilgiyi ekleyiniz
notDepresseDeveloper#0919 

## Hata Ortamı
Hatanın ortaya çıktığı ortamı açıklayın. Örneğin:
rc.afetharita.com (sadece güncelleme hatası #532 )
afetharita.com 
## Hatayı nasıl aldığınızı adım adım açıklayın

1.  afetharita.com sitesine gidin
2.  Browser üzerinden çeviri için ilgili özelliği aktifleştirin

## Beklenen Davranış
Uygulamadaki Türkçe olan bölümlerin çeviri özelliği yardımıyla İngilizce veya diğer dillerde de görüntülenebilmesi

## Ekran Görüntüleri
Chrome 109.0.5414.121 deki test için ekran görüntüsü ve console çıktısı görseldeki gibi olmaktadır.
![image](https://user-images.githubusercontent.com/22706692/217878607-8faba1db-a9f3-4194-ba89-366e8b9ceee7.png)

## Masaüstü Bilgileri
- İşletim Sistemi: Windows
- Tarayıcı: Chrome
- Sürüm: 109.0.5414.121

**Comment by efegurkan** [comment]
Selamlar,

Discordda triaj ettik durumu. Kullanilan kutuphanelerle alakali ve cabukca cozulemeyen bir sorun oldugu icin ilk etapta translation ozelligini kapatacagiz. PR acilacak birazdan.

ilgili linkler:
https://github.com/facebook/react/issues/11538
https://bugs.chromium.org/p/chromium/issues/detail?id=872770

**Comment by tolgakisin** [comment]
Selamlar, şimdi pr açıyorum ilgili konuyla ilgili. Yapılan güncelleme @efegurkan'ın yazdığı gibi translation özelliğini kapatma ile ilgili.

**Comment by absolutezero13** [comment]
@usirin @canerakin111 Bu issue'yu tekrar açabilir miyiz? Translate kapatılmış fakat bu çözüm değil, Alanı tara butonu ile ilgili bir fix lazım bunun için, şu anda fixini yaptım pr'ını açabilirim

**Comment by canerakin111** [comment]
@usirin kontrol edebilir misin?

**Comment by absolutezero13** [comment]
@canerakin111 #603
