### ISSUE TITLE
feat: Eklenme tarihi filtresi

### ISSUE THREAD

**Issue by aliilhami** [acikkaynak/deprem-yardim-frontend#594]
### Discussed in https://github.com/acikkaynak/deprem-yardim-frontend/discussions/552

<div type='discussions-op-text'>

<sup>Originally posted by **furrki** February  8, 2023</sup>
## İsteğiniz şeyi tanımlayın 
Ekranın sağ üst köşesinde bir datepicker olup, seçilen tarihten sonra yapılan çağrıların filtrelenmesi özelliği.

## Değerlendirdiğiniz alternatifleri tanımlayın
Direkt olarak son 1 gün, son 24 saat gibi bir buton kümesi olabilir.

## Ek Bağlam
Afetin ilk 3 günü çok kritik. Ancak sonrasında hayatta kalma oranı çok düşük. Bu süreçte bir şekilde uzun süre hayatta kalabilmiş olanlar için bir filtreleme yaparak, sağ kalmış olan afetzedeyi bulmayı kolaylaştırabilir.
</div>

**Comment by aliilhami** [comment]
@berkaydesign bunun tasarımını tamamladı Figma burada https://www.figma.com/file/sctw6xtcdoFOfmE0gC97Ft/Afetharita.com?node-id=2349%3A8093&t=vQfzb1258VlyQMC6-1

**Comment by emirefek** [comment]
backend'den bu datayı alabiliyor muyuz? Request ile filtering yapılabiliyor mu?

**Comment by cdagli** [comment]
Ben aldim, pair olmak isteyen olursa konusabiliriz Discorddan.

**Comment by aliilhami** [comment]
@cdagli alttaki legand kısmı mobilde nasıl çalışıyorsa desktop'ta da öyle olacak, ufak bir iş diye bunun içerisinde düzeltti design ekibi. Desktop'ta komple açmak yerine her bir item'ın üzerine tıklandığında o item'ın adının ne olduğunu tooltip'te yazacağız

**Comment by handekaratas96** [comment]
ek not: default ekran açıldığında gösterilecek değer 6 saat olmalı

**Comment by eraygundogmus** [comment]
@handekaratas96 backend tarafında bu çalışma ile ilgili issue açtırabilir misin backend tarafındaki pm ile senkronize olup, naçizane fikrim bu filtreleme işinin backend tarafında yapılması, yani bu 6 saatlik veya 12 saatlik istenen data'nın filtrelenip verilmesi backend üstündeki yükü de azaltacaktır.

sevgiler

**Comment by cdagli** [comment]
@eraygundogmus Backend destegi mevcut, surada README'de kisaca dokumante ettiler: https://github.com/acikkaynak/deprem-yardim-backend-go#endpointler

**Comment by cccececcc** [comment]
@eraygundogmus selam, @cdagli nin ilettiği servis yeterli olması lazım. Farklı bir ihtiyaç olursa iletir misiniz?

**Comment by hamitaksln** [comment]
> Ben aldim, pair olmak isteyen olursa konusabiliriz Discorddan.
Yardımcı olabilirim bende.

**Comment by cemiluzunhasan** [comment]
Selamlar @cdagli ihtiyac halinde destek olabilirim. Kolayliklar

**Comment by handekaratas96** [comment]
selamm @eraygundogmus @cdagli bu işin ilerlemesine engelimiz var mıdır son durumda Ece'nin yorumu ile birlikte ok miyiz?

**Comment by canerakin111** [comment]
backend tarafina issue acildi.

**Comment by berkayvuran** [comment]
arkadaşlar be tarafındaki issueyı göremedim, bu iş ne durumda?

**Comment by handekaratas96** [comment]
selamlar, BE tarafında bu iş yapılmış, öncelikli olarak FE tarafında da bu işi yapabilir miyiz?
