### ISSUE TITLE
bug: Google maps adresi kopyalarken geolocation info ekranının kapanması 

### ISSUE THREAD

**Issue by furknozg** [acikkaynak/deprem-yardim-frontend#598]
## Hata Tanımı
Konum görüntülerken maps konum linki çift tıklayarak kopyalamaya çalışıldığında info ekranı kapanmakta. First order issue olmayabilir ama UX tarafından kafa karıştırıcı olabilir bundan dolayı bu issue'yu açıyorum

discord kullanıcı adı: @Andslash#1898

## Hata Ortamı
afetharita.com

## Hatayı nasıl aldığınızı adım adım açıklayın
1. afetharita.com'a gidin
2. Herhangi bir konuma bilgisi için tıklayın
3. Google maps linkine çift tıklayın
4. Ctrl tuşuna basın (Ctrl+c amaçlı olarak)
5. Konum bilgisinin kapandığını görebilirsiniz

## Beklenen Davranış
Konum bilgisinin kopyalanmaya çalışılmasına engel olmaktadır, konum bilgisinin ekranda kalması daha uygun olabilir.

## Masaüstü Bilgileri
- İşletim Sistemi: Ubuntu ^22.4
- Tarayıcı: Chrome
- Sürüm: 22

**Comment by yuiji** [comment]
Soruna Drawer component'inde 160. satırda bulunan onKeyDown eventi sebep oluyor. Sadece ctrl değil herhangi bir tuşa basıldığında drawer'ı kapatıyor. Bu eventin kullanım amacı tam olarak nedir anlamadım. Eğer esc'ye basıldığında kapanmasını istiyorsak o şekilde düzenleyebilirim. Aproved olduğunda pr açabilirim.

**Comment by yunusunver** [comment]
TextField componentini disable hale getirdiğimizde sorun çözülüyor. Kopyalama işlemide yapılabiliyor. 

https://user-images.githubusercontent.com/24482512/217917117-69ca6a44-62e0-46ea-bc11-643e9c18d029.mov
