### ISSUE TITLE
feat: Google translate özelliğinin geri eklenmesi

### ISSUE THREAD

**Issue by absolutezero13** [acikkaynak/deprem-yardim-frontend#601]
## İsteğiniz şeyi tanımlayın 
Translate özelliği https://github.com/acikkaynak/deprem-yardim-frontend/issues/592 şurada belirtildiği üzere kapatılmıştı, crashe sebep olduğu gerekçesiyle. Fakat şu an crashin "Alanı tara" butonuyla ilgili olduğunu keşfettim, gerekli fixleri yaptığımda sorunsuz çalıştığını gözlemledim. 

-- bu bilgiyi ekleyiniz
** discord kullanıcı adı: İlker Sarıca#7138 **

## Değerlendirdiğiniz alternatifleri tanımlayın
Değerlendirdiğiniz herhangi bir alternatif çözüm veya özellik hakkında açık ve kısa bir açıklama.

## Ek Bağlam
Pr içerisinde detaylı açıklama olacaktır.

**Comment by usirin** [comment]
@absolutezero13 ne tarz bi problem bu?

**Comment by absolutezero13** [comment]
@usirin 
https://guoyunhe.me/en/2019/06/02/fix-react-issues-with-google-translate/
şurada detaylı bir açıklama var, kısacası "Alanı tara" kısmını bir span'e sarmamız olayı çözüyor.

**Comment by usirin** [comment]
@absolutezero13 tamamdir, approved'a aliyorum, pr gonderirsin

**Comment by selensr** [comment]
bu issueyu alabilirim

**Comment by absolutezero13** [comment]
@selensr pr'ı açıldı

**Comment by efegurkan** [comment]
selamlar, Acaba eslint/tslint plugin'i var midir bu konuyla ilgili daha sonra olmasini engellemek icin bilginiz var mi ?

**Comment by canerakin111** [comment]
@usirin Proje'yi isaretledikten sonra backlog yada in Progress (gelistirici varsa) secelim abi.
