### ISSUE TITLE
bug: Haritanın yarısının gelmemesi

### ISSUE THREAD

**Issue by Yusufbmuhtar** [acikkaynak/deprem-yardim-frontend#602]
## Hata Tanımı
Harita ilk açıldığı zaman internet hızım iyi olmasına rağmen harita yarım çıkmakta (Tarayıcı sürüm)

yusuf#9239

rc.afetharita.com

![resim](https://user-images.githubusercontent.com/59209207/217922374-eda4fe15-bee9-4e83-b445-979a2939d3c4.png)

Tarayıcı: Mozilla Firefox (Sürüm: 109.0.1)

**Comment by emr3rden** [comment]
Bu bende de yaşanıyor ilk açışımda. Ama ardından F5 yapınca düzeliyor. Her iki linkte de yapıyor bunu. - "Windows 10 / Firefox - Version 109.0.1 (64-bit)"

**Comment by Yusufbmuhtar** [comment]
> Bu bende de yaşanıyor ilk açışımda. Ama ardından F5 yapınca düzeliyor. Her iki linkte de yapıyor bunu. - "Windows 10 / Firefox - Version 109.0.1 (64-bit)"

Bir sorun yoksa issue kapatabiliriz

**Comment by senapalaa** [comment]
Chrome üzerinden her iki linki açtığımda da ilgili sorunla karşılaşmadım. Her iki linkte hızlı bir şekilde açılıyor.

**Comment by Yusufbmuhtar** [comment]
Çerezler ile alakalı olabilir edge üzerinden denedim şimdi gene aynı hata ile karşılaştım

**Comment by nejatcanunlu** [comment]
> Çerezler ile alakalı olabilir edge üzerinden denedim şimdi gene aynı hata ile karşılaştım

Farklı bir bağlantıyla deneme şansın var mı, yine aynı sorun oluyor mu?

**Comment by Yusufbmuhtar** [comment]
Deneme sağladım, mobil üzerinden giriş sağladığım zaman daha kısa sürelide olsa aynı hatayı alıyorum, belki benden kaynaklı olabilir. Çok büyük bir sorun değilse es geçebiliriz

**Comment by ozcanzaferayan** [comment]
Ben de karşılaşıyorum ilk girişte.  Aşağıdaki gibi width heigth 100% verilebilir
https://stackoverflow.com/a/65964730/2537972

**Comment by Yusufbmuhtar** [comment]
Alım yapacak olan var mı? şu an çok müsait değilim approved olursa pr açılabilir

**Comment by canerakin111** [comment]
Approved ready to take.

**Comment by nejatcanunlu** [comment]
Ben hala reproduce edemiyorum bunu, şahit olabilen biri alabilir mi?

**Comment by eraygundogmus** [comment]
ben test etmedim. sadece bug varsa ilgilenebilir tech leadler. testerları yönlendirelim eğer yoksa kapatalım issue'yu

**Comment by nejatcanunlu** [comment]
Şimdi reproduce edebildik, bakıyoruz. 👍

**Comment by nejatcanunlu** [comment]
@Yusufbmuhtar şu linkten bakınca aynı sorunu yaşıyor musun?

https://deprem-yardim-frontend-git-test-grayed-tiles-afet.vercel.app

**Comment by Yusufbmuhtar** [comment]
Bu sefer ne yazık ki hiç yüklenmedi

**Comment by nejatcanunlu** [comment]
Sayfa komple mi hiç yüklenmedi, harita mı? Yeniden bakabilir misin, deploy preview olduğu için olabilir. @Yusufbmuhtar

**Comment by Yusufbmuhtar** [comment]
Tamamdır şu an geldi ![Screenshot_2023-02-10-03-03-32-229_org.mozilla.firefox.jpg](https://user-images.githubusercontent.com/59209207/217966731-a6a83522-39d0-4f24-a3cf-3b476342cd06.jpg)
