### ISSUE TITLE
bug: Zoom in/outtan sonra geri sayım bittiğinde harita güncellenmiyor

### ISSUE THREAD

**Issue by selensr** [acikkaynak/deprem-yardim-frontend#606]
## Hata Tanımı
Zoom in ve zoom out olduğunda gerisayım sıfırlanıyor. Gerisayım bittiğinde ise URLdeki parametreler güncellenmediği için haritadaki taralı alanlar güncellenmiyor.

** discord kullanıcı adı: @Selen#9858 **

## Hata Ortamı
rc.afetharita.com
afetharita.com

## Hatayı nasıl aldığınızı adım adım açıklayın

1. rc.afetharita.com a gidin
2. zoom +/- ye tıklayın
3. geri sayımın bitmesini bekleyin
4. taralı alan güncellenmiyor

## Beklenen Davranış
Taralı alan güncellenmeli

## Ekran Görüntüleri
![Screen Shot 2023-02-09 at 23 28 44](https://user-images.githubusercontent.com/45594532/217929745-bd705d93-3a9e-48ce-94e4-931628a868c8.png)

## Masaüstü Bilgileri
- İşletim Sistemi: MacOS
- Tarayıcı: chrome
- Sürüm: 109.0.5414.119

**Comment by Kibyra** [comment]
bu issue #578 in aynısı değil mi eğer öyleyse bu pr ile fixlendi https://github.com/acikkaynak/deprem-yardim-frontend/pull/582

**Comment by EmirBoyaci** [comment]
> bu issue #578 in aynısı değil mi eğer öyleyse bu pr ile fixlendi #582

hala aynı problem devam ediyor, valide edebilir misin?

**Comment by Kibyra** [comment]
sanırım prod, rc mergelenmedi henüz o yüzden yayında göremiyorsunuz fix dev branchte var

**Comment by selensr** [comment]
dev ortamında da devam ediyor

**Comment by akselsaatci** [comment]
evet rc de de devam ediyor

**Comment by Kibyra** [comment]
> dev ortamında da devam ediyor

devin linki var mı? repoyu çekip mi denedin?

**Comment by selensr** [comment]
> > dev ortamında da devam ediyor
> 
> devin linki var mı? repoyu çekip mi denedin?

evet direkt repoyu çekip development branchinde denedim

**Comment by EmirBoyaci** [comment]
> > > dev ortamında da devam ediyor
> > 
> > 
> > devin linki var mı? repoyu çekip mi denedin?
> 
> evet direkt repoyu çekip development branchinde denedim

haritaya datayı basıyor ama urldeki değerler değişmiyor değil mi?

**Comment by syndrakes** [comment]
> > > > dev ortamında da devam ediyor
> > > 
> > > 
> > > devin linki var mı? repoyu çekip mi denedin?
> > 
> > 
> > evet direkt repoyu çekip development branchinde denedim
> 
> haritaya datayı basıyor ama urldeki değerler değişmiyor değil mi?

evet tam olarak böyle şu an

**Comment by canerakin111** [comment]
@eraygundogmus approved tan sonra projeye ekleyin abi, takip icin.

**Comment by Kibyra** [comment]
@selensr   @EmirBoyaci @syndrakes müsait olduğunuzda dc den bir konuşalım

**Comment by selensr** [comment]
Bu issue #578 ile fixlenmiş, issueyu kapatıyorum
