### ISSUE TITLE
bug: Süre bitiminde süre artışı

### ISSUE THREAD

**Issue by Yusufbmuhtar** [acikkaynak/deprem-yardim-frontend#607]
## Hata Tanımı
Alanı tara butonuna basmadan süre bitimini beklediğimiz zaman 800 saniyeye çıkmakta

-- bu bilgiyi ekleyiniz
** discord kullanıcı adı: yusuf#9239**

## Hata Ortamı
Hatanın ortaya çıktığı ortamı açıklayın. Örneğin:
rc.afetharita.com
afetharita.com
## Hatayı nasıl aldığınızı adım adım açıklayın
Süreyi beklemek istedim bir önce olan issue'dan dolayı o zaman baktığımda gördüm.

1) Zoom out yapınız
2) Süreyi bekleyiniz
3) Hatayı gözlemleyiniz

## Beklenen Davranış
Beklediğiniz şeyin açık ve kısa bir açıklaması.
- İnternet olarak problem olmasın diye yapılmış olabilir ama en azından beklendiğinde 1.5 dakika gibi bir süre verilebilir. 800 saniye fazla
## Ekran Görüntüleri
Uygulanabilirse, sorununuzu açıklamak için ekran görüntüleri ekleyin.
![resim](https://user-images.githubusercontent.com/59209207/217934793-7582a3d2-66cf-4c26-9041-21dac2993eae.png)

## Masaüstü Bilgileri
- İşletim Sistemi: Windows 11
- Tarayıcı : Firefox
- Sürüm : 109.0.1

## Akıllı Telefon Bilgileri
- Cihaz: Redmi note 8 pro
- İşletim Sistemi: Android 11
- Tarayıcı: Firefox

**Comment by emr3rden** [comment]
Bununla ilgili daha önceden " issue: #529 " açılmıştı. Bilinçli olarak yapıldığı söylenmişti ekstra olarak. O nedenle bunu kapatıyorum.
