### ISSUE TITLE
refactor: Change tilelayer URL

### ISSUE THREAD

**Issue by EmirBoyaci** [acikkaynak/deprem-yardim-frontend#610]
### Refactor Request

** discord username: autoMagic#2912 **

Is your refactor request pertaining to a problem? Please elaborate.

We'd like to replace the tilelayer URL used from the start on, with a production ready tilelayer with a Google Maps API key (the key is incoming).

### Suggested solution

We'd like to replace the tilelayer URL used from the start on, with a production ready tilelayer with a Google Maps API key (the key is incoming).

### Additional context
None

**Comment by EmirBoyaci** [comment]
İlgili dokümantasyon: https://developers.google.com/maps/documentation/tile/request-tile?hl=tr#tile-request

**Comment by canerakin111** [comment]
@EmirBoyaci projeye ekleyin approval dan sonra.

**Comment by eytanfb** [comment]
is this still a valid issue? is it being worked on? if not i can take this. i would need the API key of course

**Comment by serhanelmali** [comment]
@EmirBoyaci

**Comment by EmirBoyaci** [comment]
We are currently waiting for API key. I will introduce PR after we get API key.
