### ISSUE TITLE
refactor: Human-readable kalan süre formatı

### ISSUE THREAD

**Issue by ozcanzaferayan** [acikkaynak/deprem-yardim-frontend#616]
### Refactor İsteği
** discord kullanıcı adı: @zaferayan#5143 **

Mevcut durumda kalan süre aşağıdaki gibi saniye cinsinden karmaşık bir halde görünüyor
<img width="126" alt="image" src="https://user-images.githubusercontent.com/1326963/217949562-3d11cb93-3948-4575-8b0f-8d18a2f737f4.png">

### Çözüm Önerisi
Aşağıdaki gibi bir pretty-ms kütüphanesi kullanıp türkçe karşılıkları ile replace edilebilir:
https://github.com/sindresorhus/pretty-ms

**Comment by birkaany** [comment]
#615 numaralı issue ile aynı olduğundan dolayı issue'yu kapatıyorum bilginize
