### ISSUE TITLE
feat: Bir lokasyonda birden fazla yardım bildirimi varsa bunlar gösterilmeli

### ISSUE THREAD

**Issue by arikan** [acikkaynak/deprem-yardim-frontend#618]
Bir lokasyonda birden fazla yardım bildirimi varsa bunlar gösterilmeli. Sahadakilere yardımcı yerelden bilgiler içereceğinden kurtarma ekiplerine faydası olacaktır.

Örneğin, bu ekran görüntüsündeki JSON veriye baktığımda bu noktada 16 adet yardim bildirimi olduğunu görülüyor.

![Screen Shot 2023-02-09 at 6 12 47 PM](https://user-images.githubusercontent.com/6969/217960270-0841f7b9-7145-4e67-8fc9-ce307fb4b4ed.png)

Discord: arikan#2136

**Comment by birkaany** [comment]
https://github.com/acikkaynak/deprem-yardim-frontend/blob/development/.github/ISSUE_TEMPLATE/feature_request.md
Selamlar, içeriği template'e uygun hale getirmeniz mümkün mü? sonrasında onaya göndereyim

**Comment by canerakin111** [comment]
@arikan 16 kere farkli yazilmis tweetler ayni noktayimi gosteriyor. Yoksa 16 ayni tweet ayni noktayi mi?
Eger 16 farkli tweet ayni noktadaysa, bu durum surekli olan bir durum mu? Ayni koordinata tweet dusmesi geocoding de sikinti oldugunu isaret ediyor.

**Comment by birkaany** [comment]
Issue kurallarına uygun şekilde açıldığında tekrardan açabiliriz, şimdilik kapatıyorum bilginize.

**Comment by arikan** [comment]
@birkaany template başlıklarını ekledim, tekrar açabilir misin.
