### ISSUE TITLE
Harita sağ üstte taglerin eklenmesi

### ISSUE THREAD

**Issue by eraygundogmus** [acikkaynak/deprem-yardim-frontend#62]

**Comment by efegurkan** [comment]
![Screenshot from 2023-02-06 19-11-15](https://user-images.githubusercontent.com/1410658/217051742-737c7273-54a7-488b-ad59-7f892625176d.png)

**Comment by kaanersoy** [comment]
ilgileniyorum. @eraygundogmus assign edebilirsin

**Comment by eraygundogmus** [comment]
@nejatcanunlu

**Comment by akselsaatci** [comment]
Merhaba yapılmıyorsa yapabilirim

**Comment by akselsaatci** [comment]
![image](https://user-images.githubusercontent.com/100696686/217071423-d21be86b-9250-47d9-93ba-e58636e87b33.png)
bu şekilde hazırladım eğer yapılmadıysa

**Comment by mehmetranas** [comment]
@akselsaatci eline saglik, yapilmamis gibi istersen hemen pr ac bakalim.

**Comment by akselsaatci** [comment]
tamamdır hemen açıyorum

**Comment by akselsaatci** [comment]
açtım
