### ISSUE TITLE
feat: Lokasyonların permalinkleri olmalı ki paylaşıldığında tekrar haritada açılabilsin

### ISSUE THREAD

**Issue by arikan** [acikkaynak/deprem-yardim-frontend#620]
## İsteğiniz şeyi tanımlayın 

Lokasyonların permalinkleri olmalı ki paylaşıldığında tekrar haritada açılabilsin. Şu anda adres bardan kopyalan URL (örn aşağıdaki) browser'a tekrar yapıştırıldığında aynı yer açılmıyor. 

Her lokasyon lat,lng degeri ile identify ediliyor, dolayisiyla içinde bu değerler olan URL browserdan gidildiğinde harita o noktada açılmalı ve bilgi kartı gösterilmeli.
```
https://afetharita.com/#lat=36.585656734527845&lng=36.17397129535676&zoom=17
```

![Screen Shot 2023-02-09 at 6 20 05 PM](https://user-images.githubusercontent.com/6969/217961051-b3c9f0c8-6a9e-449f-b3b9-8d44414a41b6.png)

Discord: **arikan#2136**

## Değerlendirdiğiniz alternatifleri tanımlayın

Yok.

## Ek Bağlam

Yok.

**Comment by giveerr** [comment]
Issue standartlara uygun değil rica etsem standart başlıklara göre güncelleyebilir misin?

https://github.com/acikkaynak/deprem-yardim-frontend/blob/development/.github/ISSUE_TEMPLATE/feature_request.md

**Comment by arikan** [comment]
@giveerr  başlıkları koydum, issue'u tekrar açar mısınız?

**Comment by giveerr** [comment]
Tabi. Katkılarınız için teşekkürler

**Comment by maliksenpai** [comment]
@arikan bu issue için çalışmaya başladın mı? hayırsa ben bakabilirim veya yardım gerekiyorsa pair çalışabiliriz?

**Comment by eraygundogmus** [comment]
fixed
