### ISSUE TITLE
bug: new added site anchor has mistaken behavior

### ISSUE THREAD

**Issue by eraygundogmus** [acikkaynak/deprem-yardim-frontend#622]
## Hata Tanımı
Diğerleri düşürmezken sağ üst kısımdaki site linklerinden yeni eklenen(afetbilgi.com) hover state'de arka plana opacity düşürüyor veya background rengi grileşiyor

# Hata ortamı
**rc.afetharita.com**

## Beklenen Davranış
Diğer 3 icon ile aynı davranışı sergilemeli

## Ekran Görüntüleri

<img width="863" alt="Screen Shot 2023-02-10 at 03 05 26" src="https://user-images.githubusercontent.com/74984741/217966950-c8e0bdda-9759-4240-a9ca-bef011c63347.png">

<img width="720" alt="Screen Shot 2023-02-10 at 03 05 36" src="https://user-images.githubusercontent.com/74984741/217966991-a42a2c28-9275-4326-8b54-67c6aef5970d.png">
## Cihaz Bilgisi
Tüm cihazlarda aynı şekildedir.

**Comment by EmirBoyaci** [comment]
aldım pr geliyor
