### ISSUE TITLE
feat: separate view for hospitals, veterinary clinics and assembly points

### ISSUE THREAD

**Issue by Kayra1** [acikkaynak/deprem-yardim-frontend#628]
## Define your request
New views are needed in order to display these misc points of interests gathered from other maps.

** discord username: Kayra#1872 **

## Define the alternatives you have in mind
There are two options; either a structure such as google maps' satellite vs traffic maps, or a combinable or non-combinable one such as restaurants/bars.

backend issue: https://github.com/acikkaynak/deprem-yardim-backend-go/issues/41

**Comment by usirin** [comment]
@oguzergul

**Comment by oguzergul** [comment]
@yemregundogmus @muhammedsedef  bunu ilerletmemiz iyi olacak. @Kayra1 geliştirme yaptı. Bu konuyu çözebilir miyiz ?

**Comment by emr3rden** [comment]
TR: Issue'ların bundan sonra ingilizce olarak gönderilmesi gerekiyor ve halihazırda açık olanlara da bu talebimizi iletiyoruz. O nedenle sizden ricamız bu issue'yu ingilizce olarak düzenlemeniz. Lütfen ingilizce olarak düzenler misiniz?

EN: "Issues" must be sent in English from now on, and we forward this request to those who are already open. Therefore, we request you to edit this "issue" in English. Could you please edit it in english?

**Comment by serhanelmali** [comment]
Any related PR on this issue?
