### ISSUE TITLE
bug: bazı kayıtlarda bildirim zamanı geleceği gösteriyor

### ISSUE THREAD

**Issue by sametcodes** [acikkaynak/deprem-yardim-frontend#629]
## Hata Tanımı

Bazı kayıtlarda bildirim zamanı geleceği gösteriyor.

**Discord kullanıcı adı: sametcodes#0001**

## Hata Ortamı
Hatanın ortaya çıktığı ortam:
- rc.afetharita.com
- afetharita.com

## Hatayı nasıl aldığınızı adım adım açıklayın

1. afetharita.com'a gidin: https://afetharita.com/#lat=37.576433262044254&lng=36.78917345097315&zoom=11.5
2. pinlere tıklayarak detay drawerı açın
3. bazı kayıtların bildirim zamanı geleceği gösteriyor

Request içeriğine baktığımda bu kayıtlar için timestamp değerinin `2023-02-10T01:00:00Z` olarak default bir değer döndürdüğünü görüyorum. Eğer kayıt 4 AM'den öncesinde görüntüleniyorsa fonksiyon geleceği gösteriyor.

```js
// URL: https://apigo.afetharita.com/feeds/552369
{
  "id": 552369,
  "full_text": "eşilyöre köyüTürkoğlu belediyesiTürkoğlu/kmaraş+ Kahramanmaraş",
  "is_resolved": false,
  "channel": "Babala",
  "timestamp": "2023-02-10T01:00:00Z", // <――― bazı kayıtlarda o günün tarihi ve saat UTC 1 AM şeklinde geliyor
  "extra_parameters": "{\"name_surname\": \"hilal gök\", \"tel\": \"0 534 208 56 88\", \"additional_notes\": \"acil gıda cocuk/ bebek ihtiyaçları hijyen battaniye kışkıkmeşya yardımna ihtiyaç var\", \"status\": \"Erzak\", \"manual_confirmation\": \"nan\"}",
  "formatted_address": "Sarıçukur, 46000 Merkez/Onikişubat/Kahramanmaraş, Türkiye"
}
```

## Beklenen Davranış

Frontend tarafında bir sorun olduğunu düşünmüyorum. **`timestamp` değeri bazı veriler için standard gelmiyor ve bu da bildirim zamanının yanlış gözükmesine sebep oluyor.**

## Ekran Görüntüleri

<img width="350" alt="Screenshot 2023-02-10 at 3 26 50 AM" src="https://user-images.githubusercontent.com/9467273/217969548-f391b207-098b-4237-a064-2fe04d9abd95.png">

## Masaüstü Bilgileri
- İşletim Sistemi: MacOS
- Tarayıcı: Chrome
- Sürüm 109

## Ek Bağlam
Crawl edilen veriler için tarih bilgisi bulunmadığı durumda default bir timestamp döndürülmüş olabilir.

**Comment by eytanfb** [comment]
almak istiyorum ama ornegini bulamiyorum afetharita'da. hala gecerli mi bu?

**Comment by absolutezero13** [comment]
baya gezdim ve ben de bi türlü karşılaşamadım.

**Comment by nejatcanunlu** [comment]
@sametcodes örnek spesifik pin veremiyorsan ya da başka reproduce edebilen yoksa kapatayım issue'yu şimdilik?

**Comment by CyhnYldz** [comment]
Merhaba Kolay gelsin. bizim ekipte aynı hatayı almakta. o nedenle bu issue altına eklemek istedim.

**Comment by hasanugr** [comment]
Bu durumu ben alıyorum, çözümü buldum PR çıkıcam yakında.
