### ISSUE TITLE
bug: <ClusterGroup /> render suresini cok uzatiyor

### ISSUE THREAD

**Issue by usirin** [acikkaynak/deprem-yardim-frontend#636]
## Hata Tanımı
Cluster group her requestten sonr renderingi fena bir sekilde blokluyor. #516 merge edildikten sonra iyice ortaya cikmaya basladi bu problem (direk #516 ile ilgili olmadigini confirm ettik)

discord kullanıcı adı: `umut#3072`

## Hata Ortamı
Hatanın ortaya çıktığı ortamı açıklayın. Örneğin:
rc.afetharita.com
afetharita.com

## Hatayı nasıl aldığınızı adım adım açıklayın

1. rc.afetharita.com'a git
2. request yapilirken haritayi kullanmaya calis
3. UI blocklandi kullanilamiyor.

## Beklenen Davranış
Request'in kullaniciyi bloklamamasi

## Ek Bağlam
- prod'da herhangi bir problem yok. 
- Prod ile rc arasindaki tek fark #516
- Her ne kadar supheli gozukse de 2 saatli valide sureci sonunda olayin #516 ile gelen bir sey ile alakali olmadigina karar verdik (yanlis olabiliriz saat baya gec 😅 )

**Comment by berkayvuran** [comment]
@usirin anladığım kadarıyla bu issue rc ile ilgili fakat prodda benim render sürem çok uzun, ilişkili mi?

**Comment by berkayvuran** [comment]
@usirin inprogresse çektim
