### ISSUE TITLE
bug: siteye girildiğinde gereksiz 2 adet request atılması

### ISSUE THREAD

**Issue by EmirBoyaci** [acikkaynak/deprem-yardim-frontend#639]
## Hata Tanımı
Site girildiğinde koordinatlar ve timestamp değerlerine bağlı olarak 2 adet gereksiz request atılıyor. Prod'a gitmeden önce fixlenmesi gerekiyor.

-- bu bilgiyi ekleyiniz
** discord kullanıcı adı: autoMagic#2912 **

## Hata Ortamı
Hatanın ortaya çıktığı ortamı açıklayın. Örneğin:
rc.afetharita.com
## Hatayı nasıl aldığınızı adım adım açıklayın

1. Tarayıcıda network tabını açın
2. 'rc.afetharita.com' ya gidin
3. Network tabında 2 adet gereksiz request atıldığını görebilirsiniz.

## Beklenen Davranış
Gereksiz request atılmaması

## Ekran Görüntüleri
![image](https://user-images.githubusercontent.com/59085992/218061241-5c0d3b55-9155-4c06-8b25-59b182401c01.png)

## Masaüstü Bilgileri
- İşletim Sistemi: [örneğin iOS]
- Tarayıcı [örneğin chrome, safari]
- Sürüm [örneğin 22]

## Akıllı Telefon Bilgileri
- Cihaz: MacBook
- İşletim Sistemi: macOS 13.2
- Tarayıcı: Google Chrome
- Sürüm: 110.0.5481.77

**Comment by absolutezero13** [comment]
![Screen Shot 2023-02-10 at 13 15 40](https://user-images.githubusercontent.com/68756641/218066187-c9d71f00-1ecb-4fe9-bf36-faaaa84dcc01.png)

Daha lat-lng setlenmeden istek atıyor sanırım, undefined gitmiş ikisi de. Benim networkte 3 request görünüyor, approve olursa ilgilenebilirim
