### ISSUE TITLE
feat: Drawer contentin channel'a gore render edilmesi

### ISSUE THREAD

**Issue by cdagli** [acikkaynak/deprem-yardim-frontend#642]
## İsteğiniz şeyi tanımlayın 
Farkli channellar farkli payloadlar iceriyor, bu nedenle Drawer contentinde bunu ayirt edip ona gore icerigi render etmemiz gerekiyor. Su anda Babala verileri duzgun bir sekilde render edilmiyor.

Babala data ornegi: https://apigo.afetharita.com/feeds/551410
Twitter data ornegi: https://apigo.afetharita.com/feeds/19629

-- bu bilgiyi ekleyiniz
** discord kullanıcı adı: @afetharita#0001 **

## Değerlendirdiğiniz alternatifleri tanımlayın
Değerlendirdiğiniz herhangi bir alternatif çözüm veya özellik hakkında açık ve kısa bir açıklama.

## Ek Bağlam
Bu özellik isteği hakkında herhangi bir başka bağlam veya ekran görüntüsü ekleyin.

**Comment by CyhnYldz** [comment]
Merhaba, Kolay gelsin öncelikle bizim ekipten aynı hata için bildirim geldi. o nedenle bu issue altına bilgi vermek istedik.

**Comment by ezranbayantemur** [comment]
Draft PR açacağım bununla ilgili
