### ISSUE TITLE
perf A/B: Is the map more performant with or without the `preferCanvas` property?

### ISSUE THREAD

**Issue by nejatcanunlu** [acikkaynak/deprem-yardim-frontend#645]
### Performance A/B test request

** discord username: nejatcanunlu | Coniun#5462 **

The `preferCanvas` property, forces the map to be drawn with canva
Let's test whether the render performance is better with or without the property. Currently, it is employed.

### Suggested solution
Test with and without the property.

### Additional context
N/A

cc: @eraygundogmus

**Comment by emr3rden** [comment]
Issue'nun etiketini düzenliyorum fakat başlığın formatı yanlış olmuş onu https://github.com/acikkaynak/deprem-yardim-frontend/blob/development/.github/ISSUE_TEMPLATE/feature_request.md buradaki template'e uygun bir şekilde düzenlemeni rica edeceğim.

**Comment by nejatcanunlu** [comment]
Söz konusu isteği üçüne de uyduramadığım için böyle açtım, uygun olduğunu düşündüğün biri varsa ona göre güncelleyebilirim issue'yu yeniden. @emr3rden
