### ISSUE TITLE
Ana Sayfada Çıkan Uyarı

### ISSUE THREAD

**Issue by coderserdar** [acikkaynak/deprem-yardim-frontend#65]
Sayfa yüklendiği zaman ekran görüntüsündeki gibi bir uyarı çıkıyor.
Art niyetli kişilerin siteye saldırması gibi bir durumda herhangi bir bilgi edinememeleri için kaldırılırsa daha güvenli olacağını düşünüyorum
Config dosyası ile ilgili bir uyarı
![Screenshot_4](https://user-images.githubusercontent.com/11051271/217051859-5c8705a2-9011-4bcf-af16-2dbe9e018709.png)

**Comment by bedirhanyildirim** [comment]
Bu repo ile alakalı değil. Issue kapatılabilir. @eraygundogmus
