### ISSUE TITLE
feat: Filtre bilgilerinin local storage'a kaydedilmesi

### ISSUE THREAD

**Issue by cdagli** [acikkaynak/deprem-yardim-frontend#651]
## İsteğiniz şeyi tanımlayın 
Zaman ve bildirim filtrelerini localstorage'a kaydedersek eger kullanici sayfayi yenilediginde ayni ayarlarla kullanmaya devam edebilir. 

-- bu bilgiyi ekleyiniz
** discord kullanıcı adı: @Caner Dagli#1251 **

## Değerlendirdiğiniz alternatifleri tanımlayın
Değerlendirdiğiniz herhangi bir alternatif çözüm veya özellik hakkında açık ve kısa bir açıklama.

## Ek Bağlam
Bu özellik isteği hakkında herhangi bir başka bağlam veya ekran görüntüsü ekleyin.

**Comment by ssibrahimbas** [comment]
localStorage'a kaydetmek çok verimli olmayacaktır. URL'de tutulması yeterli.

**Comment by cdagli** [comment]
https://github.com/acikkaynak/deprem-yardim-frontend/issues/692 uzerinden devam edelim bunu kapatiyorum. @ssibrahimbas onerin mantikli.
