### ISSUE TITLE
bug: Tüm feed idlerinnin boş gelmesi

### ISSUE THREAD

**Issue by sevilayerkan** [acikkaynak/deprem-yardim-frontend#653]
## Hata Tanımı
Data ekibinin ilettiği önemli bir hatayı aynen aktarıyorum: afet haritanın veri kontrol işlerini yürütüyoruz spam veya kaynak yoksa kaydını tutuyoruz. afet haritadaki adres ile kaynak tweet deki adres uyuşuyor mu onlara bakıyoruz fakat şu an deprem haritada hiçbir yardım içeriğini görüntüleyemiyoruz bu yüzden tıkandık gibi.

Prodda reproduce ettik hatayı açıklamalarda görüntüleri mevcut. Şu an bütün data ekibinin tıkanmış olduğu iletildi önceliklendirilebilirse seviniriz.

-- bu bilgiyi ekleyiniz
notDepresseDeveloper#0919

## Hata Ortamı
Hatanın ortaya çıktığı ortamı açıklayın. Örneğin:
[afetharita.com](https://afetharita.com/#lat=38.19021606402886&lng=36.74377441406251&zoom=11)
## Hatayı nasıl aldığınızı adım adım açıklayın

1. [Bu adrese gidin](https://afetharita.com/#lat=38.19021606402886&lng=36.74377441406251&zoom=11)
2. İlgili konuma tıklayın
4. Hata görünecektir

## Beklenen Davranış
Feed id'nin doğru gelmesi ve konum içeriklerinin doğru görüntülenmesi

## Ekran Görüntüleri
Uygulanabilirse, sorununuzu açıklamak için ekran görüntüleri ekleyin.
![image](https://user-images.githubusercontent.com/22706692/218087308-c4ddabb3-0b3d-4f4e-ab82-e64e21c489f9.png)
![image](https://user-images.githubusercontent.com/22706692/218087349-2b2c9914-992d-4615-b01e-b978b1557961.png)

## Masaüstü Bilgileri
- İşletim Sistemi: Windows 10 
- Tarayıcı: Google Chrome 109.0.5414.120 (Resmi Derleme) (64 bit)

- İşletim Sistemi: Fedora 37 
- Tarayıcı: Firefox 109.0.1 (64-bit)

- İşletim Sistemi: Windows 10 
- Tarayıcı: Microsoft Edge Sürüm 109.0.1518.78 (Resmi derleme) (64 bit)

**Comment by burcuozel227** [comment]
Saha ekiplerini etkileyen bir durum oluşabilir. PRD'ta tespit edildi, acil çözüm lütfen.

**Comment by MaksuCode** [comment]
Bunu backend'e gönderebiliriz frontendlik bir durum gibi durmuyor. 
https://github.com/acikkaynak/deprem-yardim-backend-go

**Comment by emr3rden** [comment]
Issue etiketini düzenledim fakat masaüstü bilgilerinde artı olarak sürüm bilgilerini de eklersen çok daha iyi olur. Onu düzenlemeni rica edeceğim. Ekstra olarak template'i ekliyorum. https://github.com/acikkaynak/deprem-yardim-frontend/blob/development/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by hackerone-yusuf** [comment]
Bu cihaza ya da sürüme göre değişecek bir şey değil ki, sorun datanın olmaması apiden gelen response boş.
Kısaca tüm cihazlar ve tüm sürümler.

**Comment by kemaltailor** [comment]
kesinlikle katılıyorum.

**Comment by sevilayerkan** [comment]
@emr3rden Masaüstü için ilgili bilgi güncellendi ancak arkadaşların dediği gibi çok daha genel hata söz konusu şu an.

**Comment by hackerone-yusuf** [comment]
Benimki de fedora 37 / firefox 109.0.1 (64-bit)

**Comment by sevilayerkan** [comment]
Ekstra güncelleme geldi: extra_parameters null geliyor ve frontend bunu parse edemiyor diye düşünüldü.
![image](https://user-images.githubusercontent.com/22706692/218093883-d0439c4e-f44a-402a-aab7-6d57b5ec4c31.png)

![image](https://user-images.githubusercontent.com/22706692/218093965-babac296-7b74-4e00-9870-809cb8f21f61.png)

**Comment by aerdemsenturk** [comment]
Bu sorun çözülmüş görünüyor.

https://apigo.afetharita.com/feeds/16757

**Comment by kemaltailor** [comment]
platformda halen yardım içeriği görünmeyen konumlar var. tek bende mi öyle bilmiyorum ama

**Comment by absolutezero13** [comment]
burası bende fyi

**Comment by absolutezero13** [comment]
burası dün bir pr'la çözülmüş, kapatılabilir. JSON.parse ile ilgili bir hataymış. Bulamadım şimdi pr'ı ama rc'de çözülmüş olması gerek

**Comment by cdagli** [comment]
@kemaltailor uzerine tikladiginda id'lerini gorebilirsin postlarin, eger paylasabilirsen investigate edelim. Fakat su an bunu kapatiyorum. Eger reproduce edilirse tekrar acalim @sevilayerkan
