### ISSUE TITLE
feat: Error boundary eklenmesi

### ISSUE THREAD

**Issue by cdagli** [acikkaynak/deprem-yardim-frontend#654]
## İsteğiniz şeyi tanımlayın 
Su anda bir exception throw ettigimizde default Nextjs sayfasini gosteriyoruz, ErrorBoundary ekleyerek generic bir error gosterebiliriz. (Reuse edebilirsek `components/UI/GenericError/GenericError.tsx`, edemezsek baska bir componentte "Teknik bir sorun oluştu. Lütfen daha sonra tekrar deneyiniz." mesaji goruntuleyebiliriz. 

Uygulama cokmesi durumunda bilgi alabilecekleri diger sitelerin linklerini ekleyebiliriz. 

<img width="1709" alt="image" src="https://user-images.githubusercontent.com/7020369/218090675-9fb793da-73d3-4f1d-a4f7-bd2aa67ba771.png">

-- bu bilgiyi ekleyiniz
** discord kullanıcı adı: @afetharita#0001 **

## Değerlendirdiğiniz alternatifleri tanımlayın
Değerlendirdiğiniz herhangi bir alternatif çözüm veya özellik hakkında açık ve kısa bir açıklama.

## Ek Bağlam
Bu özellik isteği hakkında herhangi bir başka bağlam veya ekran görüntüsü ekleyin.

**Comment by ramazanyigit** [comment]
Issue'yu ben alabilirim
