### ISSUE TITLE
bug: Mobil ekranlarda harita hareketinde isi haritasinin takilmasi

### ISSUE THREAD

**Issue by OrhanOzkercin** [acikkaynak/deprem-yardim-frontend#655]
## Hata Tanımı
Mobil cihazda harita uzerinde drag ettigimizde isi haritasi donuyor.

-- bu bilgiyi ekleyiniz
** discord kullanıcı adı: @orhanozercin#0001 **

## Hata Ortamı
Hatanın ortaya çıktığı ortamı açıklayın. Örneğin:
rc.afetharita.com
afetharita.com
## Hatayı nasıl aldığınızı adım adım açıklayın

1.  Web sitesini mobil ekranda acin gidin
2. Zoom in ya da zoom out ya da drag yapin.
3. Hata görünüyor

## Beklenen Davranış
Zoom ya da drag yaptigimiz anda isi haritasinin render olmasi

## Ekran Görüntüleri

https://user-images.githubusercontent.com/25130814/218092758-1c2ce47b-a7b8-4652-af8e-bd594bc5d555.MP4

## Ek Bağlam
@eraygundogmus tarafindan drag start ve zoom start eventlerinde isi haritasini guncelleme onerisi geldi.

**Comment by CyhnYldz** [comment]
merhaba aynı hatayı test ekibi olarak bizde aldık bilgilerinize.
kolay gelsin arkadaşlar

**Comment by aerdemsenturk** [comment]
Aynı konu:
https://github.com/acikkaynak/deprem-yardim-frontend/issues/525

**Comment by OrhanOzkercin** [comment]
@birkaany @altankurt Konu duplicate olmus close ediyorum, fyi.
