### ISSUE TITLE
bug: Layer filter icerisinde her cluster icin ayri ayri "noktalar" checkbox'i gorunuyor

### ISSUE THREAD

**Issue by cdagli** [acikkaynak/deprem-yardim-frontend#656]
## Hata Tanımı
Goruldugu kadariyla ekrandaki her cluster icin bir "noktalar" checkbox'i ekliyoruz. Hepsinin gruplanmasi gerekiyor. 

-- bu bilgiyi ekleyiniz
** discord kullanıcı adı: @Caner Dagli#1251 **

## Hata Ortamı
rc.afetharita.com
afetharita.com

## Hatayı nasıl aldığınızı adım adım açıklayın

1. Sol taraftaki layer filtere basin
4. Hata görünüyor

## Beklenen Davranış
Sadece 1 tane "Noktalar" secenegi olmali

## Ekran Görüntüleri
<img width="501" alt="image" src="https://user-images.githubusercontent.com/7020369/218091775-ccd8f9f9-b47f-4323-8dd6-baa474e130ff.png">

## Masaüstü Bilgileri
- İşletim Sistemi: OSX
- Tarayıcı [örneğin chrome, safari]
- Sürüm [örneğin 22]

## Akıllı Telefon Bilgileri
- Cihaz: [örneğin iPhone6]
- İşletim Sistemi: [örneğin iOS8.1]
- Tarayıcı [örneğin varsayılan tarayıcı, safari]
- Sürüm [örneğin 22]

## Ek Bağlam
Sorun hakkında diğer herhangi bir bağlamı burada ekleyin.

**Comment by CyhnYldz** [comment]
Merhaba Test ekibinden de aynı feed-back geldi 
kolay gelsin
