### ISSUE TITLE
Grid Üzerinde Yapılabilecek İşlemler

### ISSUE THREAD

**Issue by coderserdar** [acikkaynak/deprem-yardim-frontend#66]
Kayıtların gösterildiği grid üzerinde paging yapılamıyorsa bile
En azından kayıt tarihi, sıra no gibi bilgilerin gösterilmesi;
Kolonlara tıklandığı zaman ascending ve descending sıralama yapılabilmesi
Siteye girenlerin kendileri veya akraba arkadaşlarını ararken daha hızlı sonuç alabilmelerini sağlayacaktır diye düşünüyorum

**Comment by eraygundogmus** [comment]
Hangi gridden bahsediyorsunuz?

**Comment by coderserdar** [comment]
Yardım taleplerinin listelendiği;
Yani grid aslında lafın gelişi de, html table içerisinde satır satır tutulan verilerden bahsetmek istemiştim hocam.
Yanlış anlaşılma olduysa kusura bakmayın
