### ISSUE TITLE
bug: Son girdi tarihi olarak 30 dakika ve 1 saat girildiğinde sonuç vermiyor 

### ISSUE THREAD

**Issue by sinanguven87** [acikkaynak/deprem-yardim-frontend#660]
## Hata Tanımı
Hatanın ne olduğu hakkında açık ve kısa bir açıklama.
https://afetharita.com/?lat=37.830233863159215&lng=35.860253401702394&zoom=6.75 üzerinde son saatleri 30 dakika ve 1 saat olarak seçtiğimde haritaya noktalar gelmiyor.
-- bu bilgiyi ekleyiniz
** discord kullanıcı adı: @sinanguven **

## Hata Ortamı
Windows Edge Browser
https://afetharita.com/?lat=37.830233863159215&lng=35.860253401702394&zoom=6.75
afetharita.com
## Hatayı nasıl aldığınızı adım adım açıklayın
Harita üzerinde sağ köşede 30 dakika ve 1 saat seçtiğimde haritaya veri çizdirilmiyor. 3 saatte aynı şey geçerli değil. 3 saat seçildiğinde veriler geliyor.

## Beklenen Davranış
Harita üzerinde sağ köşede 30 dakika ve 1 saat seçtiğimde haritaya veri gelmesi ve çizdirilmesi

## Masaüstü Bilgileri
- İşletim Sistemi: Windows
- Tarayıcı :Edge 
- Sürüm :Version 109.0.1518.49 (Official build) (64-bit)

**Comment by cdagli** [comment]
Veri yeni gelmis olabilir, eger uretemiyorsak kapatalim: 
![2023-02-10 14 50 14](https://user-images.githubusercontent.com/7020369/218108152-a5e624c6-bdec-4d33-bb01-eef0674f28d7.gif)

**Comment by handekaratas96** [comment]
ben denediğimde 30 dk ve 1 saatte veriler geldi, birkaç kez denedim sorun yaşamadım

**Comment by sinanguven87** [comment]
@handekaratas96 tekrar olmadı. 
Problem geçti. Kolay gelsin. Ellerinize sağlık.
