### ISSUE TITLE
feat: changing the color of previously clicked pinpoints

### ISSUE THREAD

**Issue by muammerakca10** [acikkaynak/deprem-yardim-frontend#663]
While the data validation team is validating the data on aferharita;
Veri Kontrol Ekibi afetharita üzerinden verileri kontrol ederken; 
- Adding new data to system,
- The loose of pinpoints by the validator, 
- In backward validations

In this situations like this, there is an interfere which pin to look at. That situation slows down the control process.

discord username: @muammerakca10#2783

I think it will speed up the control process changing the clicked pin color interferes with the heatmap colors

**Comment by absolutezero13** [comment]
peki bu localStorage'a falan kaydedilmeli mi mesela? Refresh olması durumunda kaybedeceğiz çünkü

**Comment by senapalaa** [comment]
Tweetlerden daha önceden destek lazım denilip daha sonrasında bulundu kurtarıldı veya çalışma bitti gibi güncelleme atılan case'lerde pinpointlerin rengi değişse de iyi olabilir diye düşünüyorum.

**Comment by oguzergul** [comment]
@absolutezero13 bunun için local-forage kullansak daha iyi olabilir.çok fazla pin kayıt edersek local-storage over capacity olabilir. ne dersin ?

**Comment by usirin** [comment]
local-forage cok mantikli duruyor, lets go

**Comment by patateskafa** [comment]
I'm taking this one

**Comment by emr3rden** [comment]
TR: Issue'ların bundan sonra ingilizce olarak gönderilmesi gerekiyor ve halihazırda açık olanlara da bu talebimizi iletiyoruz. O nedenle sizden ricamız bu issue'yu ingilizce olarak düzenlemeniz. Lütfen ingilizce olarak düzenler misiniz?

EN: "Issues" must be sent in English from now on, and we forward this request to those who are already open. Therefore, we request you to edit this "issue" in English. Could you please edit it in english?

**Comment by patateskafa** [comment]
still working on it!

**Comment by sevilayerkan** [comment]
It seems like this issue will be fixed automatically after #785 had merged.

**Comment by muammerakca10** [comment]
Thank you for your good works
