### ISSUE TITLE
Logonun eklenmesi

### ISSUE THREAD

**Issue by eraygundogmus** [acikkaynak/deprem-yardim-frontend#67]

**Comment by efegurkan** [comment]
![6](https://user-images.githubusercontent.com/1410658/217055557-cc569dc3-b525-4931-84a4-05e5fde92f8b.svg)

**Comment by sametcayma** [comment]
Sayfaya eklenmesini de bu şekilde yapabilirsiniz:

![image](https://user-images.githubusercontent.com/16429643/217071467-1b472eb7-c483-4c7a-8be9-5bab61cd9833.png)
@efegurkan

**Comment by mertcanaltin** [comment]
@eraygundogmus @efegurkan  ilgilenebilir miyim abi bu konuyla

**Comment by efegurkan** [comment]
ilgileniyorum
