### ISSUE TITLE
feat: add other platform links for mobile devices

### ISSUE THREAD

**Issue by syndrakes** [acikkaynak/deprem-yardim-frontend#677]
## Define your request

** discord username: SynDrakes#8995

EN: The deprem.io & beniyiyim.com links show up on pc and tablets but not on mobile. They should be included on mobile UI too.

**Comment by handekaratas96** [comment]
@Batuhandgenc @berkaydesign bu konuya bir bakabilir miyizz birlikte

**Comment by emr3rden** [comment]
TR: Issue'ların bundan sonra ingilizce olarak gönderilmesi gerekiyor ve halihazırda açık olanlara da bu talebimizi iletiyoruz. O nedenle sizden ricamız bu issue'yu ingilizce olarak düzenlemeniz. Lütfen ingilizce olarak düzenler misiniz?

EN: "Issues" must be sent in English from now on, and we forward this request to those who are already open. Therefore, we request you to edit this "issue" in English. Could you please edit it in english?

**Comment by canerakin111** [comment]
@syndrakes I have edited your comment with English translation. Let's make sure to include English Translation for the next issues.

**Comment by syndrakes** [comment]
> @syndrakes I have edited your comment with English translation. Let's make sure to include English Translation for the next issues.

Much appreciated.

**Comment by eytanfb** [comment]
i can take this if no one is working on it. is there a design for it?

**Comment by cenarturkmen** [comment]
I am working but if you want we can pair

**Comment by eytanfb** [comment]
> I am working but if you want we can pair ( I don't have information about specs )

what is your discord name?

**Comment by usirin** [comment]
@canerakin111 we need a design for this

**Comment by serhanelmali** [comment]
https://github.com/acikkaynak/deprem-yardim-frontend/pull/745
https://github.com/acikkaynak/deprem-yardim-frontend/pull/767

We have two related PRs, who should own it? @usirin

**Comment by usirin** [comment]
I don't think this is ready for development yet, we need a proper design to how to implement this first.
