### ISSUE TITLE
bug: "Teyitli" ifadesinin bağlamı net değil

### ISSUE THREAD

**Issue by ali-adiguzel** [acikkaynak/deprem-yardim-frontend#680]
## Hata Tanımı
Bildirimler menüsündeki "Teyitli" ifadesinin bağlamı net değil gibi görünüyor. "Teyitli Depremzede" mi yoksa "Teyitli Erzak Yardımı" mı olduğu net değil.

-- discord kullanıcı adı: Exalted#4261

## Hata Ortamı
rc.afetharita.com
afetharita.com

## Hatayı nasıl aldığınızı adım adım açıklayın

1. [afetharita.com](https://afetharita.com) veya [rc.afetharita.com](https://rc.afetharita.com)'a gidin
2. 'Bildirimler' kısmından ilk fitredeki seçenekleri açın
3. 'Teyitli' ibaresi görünmekte

## Beklenen Davranış
"Teyitli" yerinde bağlamı daha net olan "Teyitli Depremzede" gibi bir ifadenin görünmesi.

## Ekran Görüntüleri
![image](https://user-images.githubusercontent.com/57965679/218127478-46de630a-882e-48d1-b663-87d9401c4b66.png)

## Masaüstü Bilgileri
- İşletim Sistemi: Windows 11
- Tarayıcı: Edge
- Sürüm: 22H2

## Akıllı Telefon Bilgileri
- Cihaz: OnePlus 5
- İşletim Sistemi: Android 9.0
- Tarayıcı: Opera

## Ek Bağlam
"Teyitli Depremzede" yerine daha iyi bir alternatif de bulunabilir.

**Comment by handekaratas96** [comment]
#491 bu task ile çözümlenecek
