### ISSUE TITLE
feat: ui improvements on the drawer, for babala content

### ISSUE THREAD

**Issue by ezranbayantemur** [acikkaynak/deprem-yardim-frontend#686]
## Define your request
UI improvements can be made while displaying the data received from BaBaLa on `FeedContent` within the `Drawer`.

** discord username: ezranbayantemur **

## Define the alternatives you have in mind
Provide a clear and brief explanation to any alternative solution or feature you have in mind.

## Additional context
Add some extra context or screenshot pertaining to said feature request.

**Comment by ezranbayantemur** [comment]
Bunun için ufak bir geliştirme yapacağım

**Comment by handekaratas96** [comment]
selam, @ezranbayantemur bunu biraz detaylandırabilir misin tam anlayamadım da

**Comment by ezranbayantemur** [comment]
Mevcut görüntü şu şekilde:
![Screenshot 2023-02-10 at 18 57 36](https://user-images.githubusercontent.com/42299721/218143527-6dc13b14-227d-4d8d-9198-2a36bc95f203.png)

Görünürlüğün daha iyi olması için şu şekilde bir tasarım yapılabilir.
![Screenshot 2023-02-10 at 19 25 42](https://user-images.githubusercontent.com/42299721/218143616-b38d8fb5-c295-4b7e-a8ca-5ace2663e1b5.png)

Bununla ilgili bir çalışma hazırladım, uygunsa PR göndereceğim

**Comment by hamitaksln** [comment]
> Mevcut görüntü şu şekilde: ![Screenshot 2023-02-10 at 18 57 36](https://user-images.githubusercontent.com/42299721/218143527-6dc13b14-227d-4d8d-9198-2a36bc95f203.png)
> 
> Görünürlüğün daha iyi olması için şu şekilde bir tasarım yapılabilir. ![Screenshot 2023-02-10 at 19 25 42](https://user-images.githubusercontent.com/42299721/218143616-b38d8fb5-c295-4b7e-a8ca-5ace2663e1b5.png)
> 
> Bununla ilgili bir çalışma hazırladım, uygunsa PR göndereceğim @OrhanOzkercin

Light theme hali daha iyi olur sanki tasarım tutarlılığı açısında.

**Comment by cdagli** [comment]
@handekaratas96 Bu yukaridaki ornek ne anlama geliyor? Bu adreste erzak mi var bu adrese erzak mi lazim? Bilginiz var mi acaba? 

+1 light theme devam etme taraftariyim. #tasarim-ux-ui kanalindan destek alabiliriz @ezranbayantemur

**Comment by ezranbayantemur** [comment]
İlk aklıma light tema geldi de babalanın rengi o renk olduğu için o şekil yapayım dedim, farklı renkli dursun diye. Değiştirebiliriz isterseniz

**Comment by oguzergul** [comment]
@ezranbayantemur burada tasarımı beklemeyelim bence bu saatte onlara ulaşmamız çok zor. Light them geçip ilerleyelim.

**Comment by ezranbayantemur** [comment]
Tamamdır. @OrhanOzkercin sen tooltip için ilgileniyordun, light tema kısmında da destek olabilir misin? Ben güncellersem conflict vs. çıkabilir senin codebasede, iyice çorba olmasın

**Comment by emr3rden** [comment]
TR: Issue'ların bundan sonra ingilizce olarak gönderilmesi gerekiyor ve halihazırda açık olanlara da bu talebimizi iletiyoruz. O nedenle sizden ricamız bu issue'yu ingilizce olarak düzenlemeniz. Lütfen ingilizce olarak düzenler misiniz?

EN: "Issues" must be sent in English from now on, and we forward this request to those who are already open. Therefore, we request you to edit this "issue" in English. Could you please edit it in english?

**Comment by oguzergul** [comment]
any update in here @OrhanOzkercin @ezranbayantemur ?

**Comment by OrhanOzkercin** [comment]
Yes, fixed it. Coming soon! @oguzergul
