### ISSUE TITLE
feat: internet data saving mode implementation

### ISSUE THREAD

**Issue by maliksenpai** [acikkaynak/deprem-yardim-frontend#689]
## Define your request
The scan interval to be customizable. This could be beneficial when internet connection is limited.

Instead of providing a number, presets such as `Frequent`, `Normal` and `Data Saving Mode` and an algorithm can be designed accordingly.

** discord username: MalikSenpai#8572

## Define the alternatives you have in mind
Instead of selecting from the `Bildirimler` (notifications) dropdown, a number could be typed in.

## Additional context
None

**Comment by maliksenpai** [comment]
Eğer onay gelirse geliştirmesini üstlenebilirim.

**Comment by cdagli** [comment]
@maliksenpai Guzel oneri fakat su an oradaki kod cok kompleks hale gelmeye basladi. Ben Discord uzerinde hatta o sureyi komple kaldirmayi teklif ettim tartisilmak uzere. Boylece sadece ilk acilista ve butona basildiginda veri cekilecek.

**Comment by cdagli** [comment]
Herhangi bir test yokken, o kisimlari daha da karisik hale getirmek uygulamanin kirilganligini arttiracaktir diye dusunuyorum.

**Comment by maliksenpai** [comment]
Anladım, o zaman eklememek de mantıklı olabilir. Ayrıca test gereken yerler var ise test kısmına da bakabilirim @cdagli

**Comment by maliksenpai** [comment]
@cdagli eğer yapılırsa veya farklı bir plan ile yapılmasına karar verilirse bakabilirim

**Comment by khnbzkrt** [comment]
I can reproduce this issue in development environment but we can make new performance issues for this issue resolves. For this reason i think, we can remove approved tag and  we can close this issue.

You can use this guide for reroducing : https://developer.chrome.com/docs/devtools/remote-debugging/

**Comment by cdagli** [comment]
I think this would be a bit early optimisation, that auto refresh already goes from 10 -> 100 -> 1000 .... so I don't think this would hurt anyone's data plan. So I suggest we either close this or move to discussions.

**Comment by maliksenpai** [comment]
@cdagli Don't think about only for saving mode. May user need frequently updated data. It's different situation but I'm not sure if it's not necessary we can close this issue.
