### ISSUE TITLE
bug: using markers (instead of circle markers) causes performance issues

### ISSUE THREAD

**Issue by savasalturk** [acikkaynak/deprem-yardim-frontend#691]
## Bug Definition

When we zoom in on the map, performance is low and freezes happen since markers are being used. Tested on Chrome and Firefox.

I suggest using circle markers. This would improve performance greatly. The shadows would not be calculated on render.

** discord username: Savaş Altürk#3292 **

## Bug environment

rc.afetharita.com
afetharita.com

## Describe how you are producing the bug step by step

1. Zoom in on the map
2. Wait till the markers are rendered
3. Since the number of markers displayed increase, performance drops and jank happens.

## Screen shots
![Capture](https://user-images.githubusercontent.com/60508433/218168417-c274b1a9-7907-428d-a31e-d30786046057.JPG)

## Desktop Information
- operating system(s): [windows 10]
- browser(s) [chrome, firefox]

**Comment by buraktuzlutas** [comment]
the problem does not persist. Problem solved for both browsers
