### ISSUE TITLE
bug: making notification selection persistent

### ISSUE THREAD

**Issue by ssibrahimbas** [acikkaynak/deprem-yardim-frontend#692]
## Bug Definition

The page resets when i change notification type and f5

** discord username: @ss.ibrahimbas#4990 **

## Bug environment
Web environment: rc.afetharita.com
rc.afetharita.com
afetharita.com
## Describe how you are producing the bug step by step

1. Click to 'Bildirimler/Notifications' dropdown
2. choose 'Erzak Yardımı / Vittles Support' option
3. F5
4. Data is resetted

## Expected Behaviour

My selection stay with me on page refresh
Sayfayı yenilediğimde tercihlerimin benimle kalması

## Screenshots
![image](https://user-images.githubusercontent.com/76786120/218168817-ee79c322-89bf-4f4e-862c-574ce6b1f3a6.png)

## Desktop Information
- Operating System : [Windows 11]
- Browser [chrome]
- Version[unknown]

**Comment by cdagli** [comment]
Benzer bir tane acmistim ama onu kapatiyorum, burasi ile devam edebiliriz. 

https://github.com/acikkaynak/deprem-yardim-frontend/issues/651

**Comment by emr3rden** [comment]
TR: Issue'ların bundan sonra ingilizce olarak gönderilmesi gerekiyor ve halihazırda açık olanlara da bu talebimizi iletiyoruz. O nedenle sizden ricamız bu issue'yu ingilizce olarak düzenlemeniz. Lütfen ingilizce olarak düzenler misiniz?

EN: "Issues" must be sent in English from now on, and we forward this request to those who are already open. Therefore, we request you to edit this "issue" in English. Could you please edit it in english?

**Comment by dgnydn** [comment]
Anyone working on this issue?

**Comment by batuhan** [comment]
I can take it. We can persist the selection in URL with `useRouter` hook.

**Comment by dgnydn** [comment]
> I can take it. We can persist the selection in URL with `useRouter` hook.
> 
> edit: someone asked if anyone took this and then sneakly removed their comment :P

it's me. I saw the pr and deleted my comment

**Comment by hamitaksln** [comment]
I believe we also put filters to url. We persist coordinates with url already so if we add also filters there you can share url with filters and we would have persistence.

**Comment by CyhnYldz** [comment]
this may be fixed by pr740 but it is still fail in rc.afetharita.com and afetharita.com
