### ISSUE TITLE
bug: supply assistance & confirmed locations appears as "nan" in address information 

### ISSUE THREAD

**Issue by sevilayerkan** [acikkaynak/deprem-yardim-frontend#693]
## Bug Definition
In address information section the expression 'nan' appears . This bug is happening mostly in the 'Confirmed' , 'Supply Assistance' sections. (There are also a few error for some locations in the earthquake-affected section.)

-- Please add discord contact information
** discord username: @notDepresseDeveloper#0919 **

## Bug environment
Describe the environment produces the bug. For example:
afetharita.com

## Describe how you are producing the bug step by step

1. Go to afetharita.com 
2. Choose one of the 'Supply Assistance' or 'Confirmed' options from right panel
3. View the details of any location.
4. Bug appears

## Expected Behaviour
A clear and short text to decribe the expected behaviour.
We expect a statement other than help details not to be displayed, but to be displayed correctly.

## Screen shots
![image](https://user-images.githubusercontent.com/22706692/218168161-c4cc8ee9-fab0-41ef-a33e-3b330479ad9d.png)

## Desktop Information
- Operating system: Win11
- Browser: Chrome
- Browser Version: 109.0.5414.120

**Comment by CyhnYldz** [comment]
@aysenur-aydin test-failed label'ı test ekibinden gelen issue'ları ayırt etmek için istediler. bilgilerinize
kolaylıklar diliyorum

**Comment by aysenur-aydin** [comment]
@CyhnYldz sanırım bir çakışma oldu label verirken, bilgilendirme için teşekkürler. İyi çalışmalar.

**Comment by sevilayerkan** [comment]
Selamlar, ufak bir ekleme "erzak yardımı" "son 3 gün" seçildiğinde bazı pinlerde de "nan" yerine "Teyit Edildi" olarak görünüyor. 

![image](https://user-images.githubusercontent.com/22706692/218175611-b700ea29-cf6f-4503-aa9a-268fc57632d1.png)

**Comment by usirin** [comment]
@sevilayerkan su an hala var mi bu issue?

**Comment by sevilayerkan** [comment]
@usirin Evet tekrar test ettik hem prodda hem rc de hala devam ediyor.

**Comment by emr3rden** [comment]
TR: Issue'ların bundan sonra ingilizce olarak gönderilmesi gerekiyor ve halihazırda açık olanlara da bu talebimizi iletiyoruz. O nedenle sizden ricamız bu issue'yu ingilizce olarak düzenlemeniz. Lütfen ingilizce olarak düzenler misiniz?

EN: "Issues" must be sent in English from now on, and we forward this request to those who are already open. Therefore, we request you to edit this "issue" in English. Could you please edit it in english?

**Comment by sevilayerkan** [comment]
@emr3rden Of course, we are translating immediately.

**Comment by cdagli** [comment]
Will be fixed with https://github.com/acikkaynak/deprem-yardim-frontend/pull/687

**Comment by sevilayerkan** [comment]
Issue had translated if there is any error in translation please let me know.

**Comment by cdagli** [comment]
https://github.com/acikkaynak/deprem-yardim-frontend/pull/687 is now merged. Please let us know if you see any nan values after the deployment, because there are a lot uncertainties around the data we get.

**Comment by sevilayerkan** [comment]
We tested in rc and this bug still occurs. Did you mean we should test after deployment to prod? @cdagli
