### ISSUE TITLE
bug/refactor: `BU ALANI TARA` (scan this area) button does not trigger a request

### ISSUE THREAD

**Issue by efegurkan** [acikkaynak/deprem-yardim-frontend#695]
## Bug Definition

The `BU ALANI TARA` (scan this area) button is not triggering a request. In the same vein, no request is performed after the countdown hits zero.

-- Please add discord contact information
** discord username: namcojoulder#1062**

## Bug environment
Describe the environment produces the bug. For example: rc.afetharita.com and/or afetharita.com
rc.afetharita.com

## Describe how you are producing the bug step by step
1. Navigate to rc.afetharita.com
3. Click the `BU ALANI TARA` (SCAN THIS AREA) button (top & center of the screen)
4. No request is made to the `/areas` endpoint

## Expected behavior
Even if the response is the same as the last one, a request must be made when the `BU ALANI TARA` (SCAN THIS AREA) button is clicked.

P.S: This might be expected behavior. (In theory, unless the REST GET URL changes, the same response will be returned, thus no benefit in making another request) In that case, it might make sense to remove the countdown completely, since we won't make a request when the countdown hits zero and the whole thing might become redundant.

## Screen shots
If applicable, add screen shots to elaborate the issue.

## Desktop Information
- Operating System: [for example iOS]
- Browser [for example, safari]
- Version [for example 22]

## Mobile Phone Information
- Devıce: [for example iPhone6]
- Operating System (with the version): [for example iOS8.1]
- Version [for example default browser, safari]
- Browser Version [for example 22]

## Additional Context
If we are sure that the response will be the same when unless the URL changes, the countdown becomes redundant. If the explained behavior is expected behavior, removing the countdown may be considered. Or this issue can be closed.

Thanks.

**Comment by efegurkan** [comment]
Beklenen davranistan emin olamadigim icin draft PR olusturdum bunlari kismen cozen. Ilgilenmek isteyen olursa uzerine alabilir https://github.com/acikkaynak/deprem-yardim-frontend/pull/698

**Comment by cdagli** [comment]
Right now we have 3 PRs that attempts to fix this issue: 

https://github.com/acikkaynak/deprem-yardim-frontend/pull/755
https://github.com/acikkaynak/deprem-yardim-frontend/pull/713
https://github.com/acikkaynak/deprem-yardim-frontend/pull/698

**Comment by birkaany** [comment]
@CyhnYldz could you please explain what test-failed means? 
If the bug couldn't be reproduced, I'll close this issue. Otherwise, there's a PR waiting for this issue to be tested. (#755)

**Comment by CyhnYldz** [comment]
> @CyhnYldz could you please explain what test-failed means? If the bug couldn't be reproduced, I'll close this issue. Otherwise, there's a PR waiting for this issue to be tested. (#755)

@birkaany the trigger works fine with the first 10 second count down but after that trigger is not working properly. 
if it is just about the trigger button there is no problem with that. 👍

**Comment by birkaany** [comment]
@efegurkan I close this issue cause test-failed, if you encounter this bug again, please feel free to open another issue.
