### ISSUE TITLE
bug: When scan at the same scale, the some data is gone

### ISSUE THREAD

**Issue by ssibrahimbas** [acikkaynak/deprem-yardim-frontend#699]
## Bug Definition
I zoom in a bit, the map is updating. Then I press the "scan area" button and some data is gone.

-- Please add discord contact information
** discord username: @ss.ibrahimbas#4990 **

## Bug environment
Web rc.afetharita.com

## Describe how you are producing the bug step by step

1. zoom any area
2. wait data changes
3. Click "scan area" without changing the scale after the data has changed
4. Bug appears

## Expected Behaviour
Data not going

## Screen shots

First zoom

![Screenshot_20230210_095143](https://user-images.githubusercontent.com/76786120/218174614-6dc00b60-53ac-461c-b520-27488f5f224c.png)

without changing the scale, after click "scan area"

![image](https://user-images.githubusercontent.com/76786120/218174572-45391cff-c3c5-4909-9400-769c586ebe95.png)

## Desktop Information
- Operating System: [Windows 11]
- Browser [Chrome]
- Version [unknown]

## Additional Context
Not have additional context

**Comment by oguzergul** [comment]
swr causing this ussue. cache should be disabled @usirin

**Comment by cdagli** [comment]
I am not sure if this is the cache issue. After the data refresh, if we get a different number of markers that might change the clustering and as a result it might look different. 

I'll see if I can reproduce 👍

**Comment by cdagli** [comment]
I tried a bit but I am not able to reproduce. (I had it in the past but not with the latest development branch) Please let me know if someone finds a way to reproduce it following the written steps, maybe I am missing something.

**Comment by erkutr-prog** [comment]
I have tried to clear all the cache before and after fetch with `mutate` but nothing seems to be changing.

**Comment by yusufeliacik** [comment]
I guess, I found a problem, this issue is not a zoom problem. when the map is moved, data does not refresh. @cdagli @ssibrahimbas  Can you re-check?

**Comment by yusufeliacik** [comment]
I fixed it. I'll send it.

**Comment by cdagli** [comment]
I am able to reproduce like that but i think it is expected: 

https://user-images.githubusercontent.com/7020369/218204774-c3c5a411-f393-406a-ae60-da8d9c6ea572.mov

**Comment by eraygundogmus** [comment]
prefer to say it is expected to save some resource, not a technical desicion, thx
