### ISSUE TITLE
Veri Düzenleme & Onaylama Ekranı

### ISSUE THREAD

**Issue by sercanerhan** [acikkaynak/deprem-yardim-frontend#703]
## İsteğiniz şeyi tanımlayın 
>Aşağıdaki maddeler çokca varsayım barındırmaktadır. Başta Data Lead'leri olmak üzere takım olarak incelenmesi gerekmektedir.
### WHY
Data ekibinin [örnek google sheet](https://docs.google.com/spreadsheets/d/1SKM5pMoA6m

![Image](https://user-images.githubusercontent.com/3420568/218178736-b5f3dfd3-beb5-4122-b7ff-e179623872c9.jpg)

vI00ia0nzNnxIkLgNsJMXlhO2jgrwWucc/edit#gid=975519625) üzerinden manuel kontroller ile yapmış olduğu veri düzenleme ve doğrulama işlemleri tamamlanmadan, veriler DB'ye alınamıyor ve uygulamada/canlıda bir gecikme ile gösterilmiş oluyor. Bu gecikmeyi en aza indirip; toplu data aktarımı haricinde, kontrol edilen data'nın anlık olarak uygulamaya yansıtabilecek bir çözüm arayışındayız.
### HOW
Veri kontrolünde ilgili satırın kontrolü için:
* Google Maps & Yandex Maps (ya da ihtiyaç olursa XXX websitesi) üzerinden adres araması 
* Twitter Araması
başta olmak üzere ilgil veri/olay üzerinde çeşitli aramalar yapmaktadır.

Tek bir bildirime özel, bu temel fonksiyonları aynı web sayfasında görüntüleyebilirse, çok daha hızlı veri kontrolü yapabileceği gibi, DB üzerinden servis edilen bu **ONAYLANMAMIŞ** verinin, çalışması akabinde yine DB üzerinden **ONAYLANMIŞ** olarak flaglanmesini sağlayabilecektir.

Bu da canlıdaki uygulamanın, onaylanmış veriyi anlık olarak gösterebilmesine olanak sağlayacaktır

### WHAT
Yapılacakları kısaca şu şekilde başlıklar altında toplanabilir:
* Veri düzenleme / Onaylama UI/UX
* Login & Yetki
    * Düzenleme & Onay yetkileri
* Get, Update Endpointleri
* O an editlenen bir kaydın başkasına düşmemesi (Yani birden fazla kişinin aynı kayıt ile çalışmaması. GET metodundan, şu an lock'lı olmayan bir kaydın döndürülmesi)
* ID ile arama
* Güncellenen verinin uygulamada görünebilir olması

### Risks
* GSheet üzerinde toplu düzenleme ihtiyaç duyulduğunda kolayca yapılabilecekken, şu an DB üzerinden güncellenmesi gerekir. Çalışmayı yapacak resource değişir.
* Veri kaybına karşı, veriyi veriyonlamak gerekebilir mi? Yani X kişisi onayladı ya da bir edit yaptı, akabinde **v1** oldu. Daha sonra **v0** 'a geri dönmek gerekir mi? 

-- bu bilgiyi ekleyiniz
** discord kullanıcı adı: @afetharita#0001 **

## Değerlendirdiğiniz alternatifleri tanımlayın
Yukarıdaki asıl problem için sunulan varsayım, kabul görürse, sağlanacak bu ekran ile, doğrulanmış veriler için anlık gösterim yeteneğine kavuşmuş olacağız ki, kıymetli bir kazanım olduğuna inanıyorum.

## Ek Bağlam
Vakit kaybeytmemek için çoook kötü bir şekilde çizdiğim draft mockup(!)'ı ekte paylaşıyorum.

**Comment by yusufgns** [comment]
https://github.com/acikkaynak/deprem-yardim-frontend/issues/705
