### ISSUE TITLE
feat: copy aid call details to clipboard 

### ISSUE THREAD

**Issue by alperencantez** [acikkaynak/deprem-yardim-frontend#712]
## Define your request
Other users might want to copy the aid calls and share them somewhere else. As sharing the whole link may not spread the data as fast as sharing the text itself, sharing the texts would be more practical.

** discord username: @canadianclublove **

## Define the alternatives you have in mind
This can be achieved by clicking on the text instead of an additional button. This way we can keep the UI same and add a little bit of more accessibility.

**Comment by aysenur-aydin** [comment]
"Issues" must be sent in English from now on, and we forward this request to those who are already open. Therefore, we request you to edit this "issue" in English. Could you please edit it in english?

https://github.com/acikkaynak/deprem-yardim-frontend/blob/development/.github/ISSUE_TEMPLATE/refactor-request.md

**Comment by nejatcanunlu** [comment]
I'm currently translating this issue and will remove pertaining comments when done. @aysenur-aydin

**Comment by canerakin111** [comment]
@nejatcanunlu approval'u bekleyelim calisamaya baslamadan once.

**Comment by nejatcanunlu** [comment]
@canerakin111 çeviriden mi bahsediyoruz, taskın kendisini kodlamaktan mı?

**Comment by canerakin111** [comment]
This issue has been edited by the author after approval. Doesnt align with the initial request. Please create a new issue with more details.
