### ISSUE TITLE
feat: ability to switch to a satellite map

### ISSUE THREAD

**Issue by el** [acikkaynak/deprem-yardim-frontend#724]
## Define your request
Currently there is no way to use a satellite map as a base layer.

**discord username: @el#9951**

## Define the alternatives you have in mind
Create a new base layer picker to switch between satellite and regular map.

## Extra context

<img width="525" alt="Screenshot 2023-02-11 at 00 57 36" src="https://user-images.githubusercontent.com/1488164/218206568-7086c349-e3d9-4268-8168-451221ba83eb.png">

**Comment by eraygundogmus** [comment]
it is possible technically. 

https://stackoverflow.com/questions/9394190/leaflet-map-api-with-google-satellite-layer

approved. i am not sure it is p0 or p1. @usirin can decide it.

**Comment by canerakin111** [comment]
Yes there should be an option for imagery basemap. @Batuhandgenc @gokceaydemir @maliksenpai adding you guys in for UX/UI

**Comment by el** [comment]
It is extremely easy, we just need to change the URL here
```
        <TileLayer
          url={`https://mt0.google.com/vt/lyrs=m&hl=en&x={x}&y={y}&z={z}&apistyle=s.e%3Al.i%7Cp.v%3Aoff%2Cs.t%3A3%7Cs.e%3Ag%7C`}
        />
        ```
        
        lyrs=m -> map
        lyrs=s -> satellite

**Comment by canerakin111** [comment]
@eraygundogmus @usirin let's pass it to UX/UI first. Their backlog is low.

**Comment by el** [comment]
@canerakin111 I think it can just be added here

<img width="241" alt="SCR-20230211-1ov" src="https://user-images.githubusercontent.com/1488164/218208659-f8949216-8524-4a02-b9f2-4827f52c9fe3.png">

**Comment by el** [comment]
@eraygundogmus can you please pass the below information to the UI/UX team


We have the ability to switch between multiple layer types, not just map and satellite.
<img width="268" alt="SCR-20230211-32o" src="https://user-images.githubusercontent.com/1488164/218219923-43e8c4af-3dc0-41e2-9810-1274bab23e0f.png">

**Comment by gokceaydemir** [comment]
> Yes there should be an option for imagery basemap. @Batuhandgenc @gokceaydemir @maliksenpai adding you guys in for UX/UI for the button

**Comment by berkaydesign** [comment]
Coming from UX team 👋 @canerakin111 , @el 

This satellite view option should be under that stack icon button, and I can see that you guys already handled that out.

P.S: Sometimes we really see these issues too late or we don't see them all. This doesn't mean that we are not checking here but we don't only support afetharita.com therefore sometimes issues for UX team get overlooked. Please ping me on discord as "wiser#1809" if we don't catch up with you.

**Comment by selensr** [comment]
If the UI decisions finalized I am taking the development of this issue

**Comment by cdagli** [comment]
@selensr Please notice there is an existing PR for this already https://github.com/acikkaynak/deprem-yardim-frontend/pull/731

**Comment by fdemir** [comment]
<img width="197" alt="image" src="https://user-images.githubusercontent.com/48316033/218257523-ddb63de9-3982-47ea-8d7d-8c6026ec3319.png">

**Comment by fdemir** [comment]
be careful while using mui components.
