### ISSUE TITLE
Market bakkal gibi ikonların haritadan gizlenmesi

### ISSUE THREAD

**Issue by ozcanzaferayan** [acikkaynak/deprem-yardim-frontend#73]

**Comment by mgurbuz-tr** [comment]
http://mt0.google.com/vt/lyrs=m&hl=null&x={x}&y={y}&z={z}&apistyle=s.e%3Al.i%7Cp.v%3Aoff%2Cs.t%3A3%7Cs.e%3Ag%7Cp.c%3A%23ffe0e0e0

**Comment by ozcanzaferayan** [comment]
Ben de tam attribute'leri araştırıyordum, Sağolasın
