### ISSUE TITLE
feat: localized contract pages

### ISSUE THREAD

**Issue by ssibrahimbas** [acikkaynak/deprem-yardim-frontend#734]
## Define your request
We added language support with the last rc, but there are some missing points. Our contract pages are only in Turkish.

Privacy policy and Cookie policy should also be provided for other supported languages.

-- fill in the line below:
** discord username: @ss.ibrahimbas#4990 **

## Define the alternatives you have in mind
Not have any alternatives

## Extra context
Not have extra content

**Comment by oguzergul** [comment]
@ssibrahimbas I have discussed this issue with @canerakin111 I will provide translated information.
