### ISSUE TITLE
feat: add i18n translations for error pages

### ISSUE THREAD

**Issue by ssibrahimbas** [acikkaynak/deprem-yardim-frontend#742]
## Define your request

i18n translations for error pages seem to be overlooked.

-- fill in the line below:
** discord username: @ss.ibrahimbas#4990 **

## Define the alternatives you have in mind
Not have alternatives

## Extra context
Not have extra content

**Comment by ssibrahimbas** [comment]
If you approve, I can take a look.

**Comment by oguzergul** [comment]
@ssibrahimbas approved, you can work on

**Comment by cdagli** [comment]
PR is merged, should we close this?

**Comment by khnbzkrt** [comment]
PR merged but vercel preview was not successful. This merge action generated a new error. This new error has been fixed with https://github.com/acikkaynak/deprem-yardim-frontend/pull/758/commits/45ebc8d9369c248896aa0942d64d3fdb0a6c6d5c commit
