### ISSUE TITLE
feat: display latest earthquakes as a bubble map layer

### ISSUE THREAD

**Issue by el** [acikkaynak/deprem-yardim-frontend#743]
## Define your request
We can have a layer to display the latest earthquakes.

-- fill in the line below:
** discord username: @el **

## Define the alternatives you have in mind
USGS has a GeoJSON source we can use. 
https://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php

This one includes 4.5+ earthquakes in the last month:
GeoJSON URL: https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/4.5_month.geojson

We can have a selection for: Last (month, week, day, hour) and 4.5+ or significant

<img width="689" alt="SCR-20230211-4a8" src="https://user-images.githubusercontent.com/1488164/218224386-55ad9605-a843-4a8e-8957-0e688d32965f.png">

**Comment by fdemir** [comment]
no need to do that now.
