### ISSUE TITLE
refactor: Set default zoom logic

### ISSUE THREAD

**Issue by puskuruk** [acikkaynak/deprem-yardim-frontend#746]
### Refactor Request

-- fill in the line below:
** discord username: @puskuruk  **

Is your refactor request pertaining to a problem? Please elaborate.
Our approach to setting the default zoom was unreadable, and we should make it more readable.

### Suggested solution
Remove the ternary and set default zoom with `useEffect`.

### Extra context

LeafletMap.tsx

**Comment by eytanfb** [comment]
@puskuruk what do you think about the `defaultCenter`? It looks unreadable as well

**Comment by puskuruk** [comment]
Yes, I refactored `defaultCenter` logic as well but I'll create a different pr for it 🙏

**Comment by puskuruk** [comment]
#707

**Comment by akifunal** [comment]
I can take this issue if it goes stale.

**Comment by puskuruk** [comment]
I already opened a pr for this issue @akifunal. You can check it if you want
