### ISSUE TITLE
bug: close dropdown on language change

### ISSUE THREAD

**Issue by ssibrahimbas** [acikkaynak/deprem-yardim-frontend#749]
## Bug Definition

Dropdown menu should close when language is changed

-- Please add discord contact information
** discord username: @ss.ibrahimbas#4990 **

## Bug environment
Describe the environment produces the bug. For example:
Both sites:
- rc.afetharita.com
- afetharita.com
## Describe how you are producing the bug step by step

1. Go to 'Main page'
2. Click switch language button 
3. Bug appears

## Expected Behaviour

Dropdown should closing on change

## Screen shots

![](https://media.discordapp.net/attachments/1072074878452240384/1073754178511437824/E3C3ABC8-F6FF-4DB2-8601-F0AD9DAABADB.png?width=418&height=905)

## Desktop Information
- Operating System: [for example iOS]
- Browser [for example, safari]
- Version [for example 22]

## Mobile Phone Information
- Devıce: [for example iPhone6]
- Operating System (with the version): [for example iOS8.1]
- Version [for example default browser, safari]
- Browser Version [for example 22]

## Additional Context
Add any other context about the bug here

**Comment by ssibrahimbas** [comment]
If you approve, I can take a look.

**Comment by eytanfb** [comment]
this is completed in https://github.com/acikkaynak/deprem-yardim-frontend/pull/745

**Comment by ssibrahimbas** [comment]
oo okay, good luck
