### ISSUE TITLE
Harita ile ilgili copyright iconlarinin gereksinimleri

### ISSUE THREAD

**Issue by efegurkan** [acikkaynak/deprem-yardim-frontend#75]
Haritada sag alta bulunan `leaflet/openstreetmap` yazisinin gorunurlugu konusundaki yasal gereksinimlerin incelenmesi ve tasarim secimleri dogrusunda silinip silinemeyeceginin belirlenmesi. 

1- kullandigimiz Google Maps linkinin gereksinimlerinin incelenmesi
2- kullanilan leaflet kutuphanesinin gereksinimlerinin incelenmesi
3- 1 ve 2. maddelerin sonuclari cercevesinde yasal olarak bu copyright metinlerinin kaldirilip kaldirilamayacaginin belgelendirilmesi gerekmektedir.

**Comment by demirtas91** [comment]
Map container içerisine şu şekilde modifikasyon yapılınca sağ alt taraftaki iconlar kaldırılabiliyor
```
   <MapContainer className={mapClassName} {...rest} attributionControl={false}>
      {children(ReactLeaflet, Leaflet)}
    </MapContainer>
```

**Comment by eraygundogmus** [comment]
Pr açar mısınız?
