### ISSUE TITLE
bug: notification type is "nan"

### ISSUE THREAD

**Issue by Kakcil** [acikkaynak/deprem-yardim-frontend#750]
## Bug Definition
In other notifications, a phrase like "enkaz" comes in, but "nan" comes up in the case I come across.

** discord username: @kemdetroit#4551 **

## Bug environment
afetharita.com

## Describe how you are producing the bug step by step

1. Go to ['this link'](https://afetharita.com/?lat=36.775729742227625&lng=36.52130126953126&zoom=10&id=706163)
2. Look left side
3. Focus on with blue clored label
4. Detect "nan" 

## Expected Behaviour
If nan is coming, it should not appear at all, or why "nan" is coming should be asked in the backend or a different solution.

## Screen shots
![image](https://user-images.githubusercontent.com/55282653/218227192-02a70b47-c8a1-4817-92c3-14912814d15a.png)

## Desktop Information
it doesn't matter

## Mobile Phone Information
it doesn't matter

## Additional Context
no more

**Comment by ssibrahimbas** [comment]
an api-related problem

![image](https://user-images.githubusercontent.com/76786120/218227837-f49e2681-2827-49f5-92c5-58732f6512b3.png)

**Comment by nazdezar** [comment]
I've also noticed this issue earlier in PROD so moving this directly to 'tested' for bug fix.

**Comment by eytanfb** [comment]
i'm working on this one

**Comment by sevilayerkan** [comment]
As a test team we had also come across this bug, you can also checkout #693 for more information.

**Comment by oguzergul** [comment]
@sevilayerkan @handekaratas96 we can close the issue if this issue is duplicated.
