### ISSUE TITLE
feat: scan my current location

### ISSUE THREAD

**Issue by ssibrahimbas** [acikkaynak/deprem-yardim-frontend#754]
## Define your request

People may want to see survivors where they are.  We can list the data at the current location of the user with a button called Scan location.

-- fill in the line below:
** discord username: @ss.ibrahimbas#4990 **

## Define the alternatives you have in mind
Not have an alternative
## Extra context
Not have extra context

**Comment by maliksenpai** [comment]
I think it's a good feature. If this issue will approve I can work on it.

**Comment by fdemir** [comment]
you can bring it to the discord server. closed. open if it is ok.
