### ISSUE TITLE
bug: After the drawer is closed, marker id is not removed from the url

### ISSUE THREAD

**Issue by puskuruk** [acikkaynak/deprem-yardim-frontend#760]
## Bug Definition

https://user-images.githubusercontent.com/22892227/218235830-6e82c8c6-52d2-4e2d-9492-b6e9304aa411.mov

-- Please add discord contact information
** discord username: @puskuruk  **

## Bug environment
rc.afetharita.com

## Describe how you are producing the bug step by step
1. Go to rc.afetharita.com
2. Click to a marker
3. See marker id on search parameters
4. Close the drawer
5. You'll still have `id`(marker id) on your url search parameters

## Expected Behaviour
We should remove marker id after user closed the drawer

## Desktop Information
Chrome 110

**Comment by eytanfb** [comment]
PR ready if approved

**Comment by canerakin111** [comment]
@eytanfb ben waiting-test ile waiting approval'u karistirdim o yuzden.

**Comment by CyhnYldz** [comment]
We are still getting the same URL with id marker after drawer closed unless we move the map.

**Comment by fdemir** [comment]
this is excepted behaviour.

**Comment by Rayberk** [comment]
It is expected because of;
The id data is already being deleted onMapMove action.

**Comment by cemiluzunhasan** [comment]
Related PR has been created
