### ISSUE TITLE
bug: legend values are not translated

### ISSUE THREAD

**Issue by eytanfb** [acikkaynak/deprem-yardim-frontend#763]
## Bug Definition
The legend values both on the marker, and the popup do not translate to english.

-- Please add discord contact information
** discord username: eytan#6012**

## Bug environment
Describe the environment produces the bug. For example:
rc.afetharita.com
afetharita.com

## Describe how you are producing the bug step by step

1. Go to afetharita.com/en
2. Click on the arrow to expand the markers on the bottom left

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/1498968/218238185-7681444f-3eb4-427b-9ee2-5d41d5084c95.png">

 
3. Click on any cluster marker

<img width="525" alt="image" src="https://user-images.githubusercontent.com/1498968/218238197-3ebc8896-5c54-46c5-9f62-38f1aa97b043.png">

## Expected Behaviour
The legend text should be in english

## Screen shots
See above

## Desktop Information
- Operating System: OSX
- Browser:  Chrome

**Comment by eytanfb** [comment]
PR ready if approved

**Comment by maliksenpai** [comment]
Is someone looking for this issue? If not, I can work on it.

**Comment by CyhnYldz** [comment]
Still has the same problem with the translation

**Comment by fdemir** [comment]
@eytanfb what is the pr? do u have updatE?
