### ISSUE TITLE
feat: Afetbilgi Icon needs to change.

### ISSUE THREAD

**Issue by myagizmaktav** [acikkaynak/deprem-yardim-frontend#769]
## Feat Definition
Afet Bilgi Icon can be changeable. On right bottom side.

** discord username: Yağız M.# 0539 ** (do not assign me pls)

## Feat environment

afetharita.com

## Describe how you are producing the bug step by step
<img src="https://user-images.githubusercontent.com/115627863/218254651-9c4c587e-db82-4415-bba8-87be49824c94.png" width=300>

## Expected Behaviour
Needs to show Afetbilgi site icon.

## Screenshots
<img src="https://user-images.githubusercontent.com/115627863/218254645-a40021a2-b04e-455b-93e4-513beb682165.png" width=300>

## Desktop Information
- Operating System: [Windows]
- Browser [Microsoft Edge]

**Comment by absolutezero13** [comment]
I'm taking this

**Comment by fdemir** [comment]
issue must be approved by product team. wait for approved label before started to work.

**Comment by absolutezero13** [comment]
This should be go in before the layout changes (filters etc.), there is also a refactor on related PR #774
