### ISSUE TITLE
Drawer açılırken yaşanan ui hatası

### ISSUE THREAD

**Issue by Bur0** [acikkaynak/deprem-yardim-frontend#77]
![Kapture 2023-02-06 at 22 46 53](https://user-images.githubusercontent.com/8000232/217070327-f9ed2585-e4f1-45fe-98ba-80a4bdbf35c3.gif)

**Comment by eraygundogmus** [comment]
hata nedir?

**Comment by Bur0** [comment]
@eraygundogmus drawer isOpen a değil de data ya bağlı olduğu için alt kısımda görüntü bozukluğu oluşuyor (açılırken)

**Comment by palaska** [comment]
Home daki state degistiginde harita tekrar renderlaniyor ve ilk haline donuyor.

**Comment by mehmetranas** [comment]
@Bur0 dedigi gibi render islemin ile open fonksiyonun akisindan kaynakliymis. fix cikiyorum ben

**Comment by Bur0** [comment]
@mehmetranas https://github.com/acikkaynak/deprem-yardim-frontend/pull/89 burada gönderdim hocam, kontrol edebilir misin ?

**Comment by palaska** [comment]
Map i memoize edince cozuluyor @mehmetranas

**Comment by mehmetranas** [comment]
Eline saglik @Bur0
