### ISSUE TITLE
feat: Adding Scale Control Proposal

### ISSUE THREAD

**Issue by selensr** [acikkaynak/deprem-yardim-frontend#776]
## Define your request
If there might be a need for it, we can bring scale control under layer control. This will make the scale visible to users for metric scale (m/km) and imperial scale (mi/ft).

-- fill in the line below:
** discord username: @selen#9858 **

## Extra context
Here is the video of the proposal

https://user-images.githubusercontent.com/45594532/218257652-e4d76b76-5c81-4f1c-a9e6-344b03ec6b76.mov

**Comment by fdemir** [comment]
no need to add. it does have no benefit for people who are using it. personally.
