### ISSUE TITLE
bug: Menu does not close after language selection

### ISSUE THREAD

**Issue by asknksk** [acikkaynak/deprem-yardim-frontend#777]
** discord username: Aşkın#1280 **

Main Page. When change language menu dosent close.  I added video.

- Devıce: on desktop
- Operating System (with the version): Apple M1 Pro
- Version Google Chrome
- Browser Version lastest

## Mobile Phone Information

https://user-images.githubusercontent.com/101400165/218258090-b2ee12ad-54b3-469a-a867-05233d792664.mov

## Additional Context
Add any other context about the bug here

**Comment by erkutr-prog** [comment]
Fixed it. can send a PR if approved.

**Comment by eytanfb** [comment]
this should be fixed by PR #677

**Comment by ilyastunch** [comment]
retested. fix validated

**Comment by CyhnYldz** [comment]
retested. fix validated

**Comment by hamitaksln** [comment]
@oguzergul Why #780 is reverted? Isn't it solved the problem?

**Comment by Rayberk** [comment]
Merge PR 817 after reopening this issue
