### ISSUE TITLE
feat: update notify time as 'X days Y hours' format

### ISSUE THREAD

**Issue by OrhanOzkercin** [acikkaynak/deprem-yardim-frontend#778]
## Define your request
Change notify time format as X days Y hours

<img width="395" alt="image" src="https://user-images.githubusercontent.com/25130814/218258633-bab1e756-7f6e-46a5-b65b-bd8c07ce0e0a.png">

This place

-- fill in the line below:
** discord username: #orhanozkercin0001 **

## Define the alternatives you have in mind
Provide a clear and brief explanation to any alternative solution or feature you have in mind.

## Extra context
Add some extra context or screenshot pertaining to said feature request.

**Comment by avatar-lavventura** [comment]
@OrhanOzkercin Wouldn't be better if `X days Y hours Z minutes` is used since single minute is important?
