### ISSUE TITLE
feat(refactor): removal of `SCAN FIELD` action and refactoring of refetch feature 

### ISSUE THREAD

**Issue by dopplerDistortion** [acikkaynak/deprem-yardim-frontend#783]
## Define your request
As discussed in #632 `SCAN FIELD` action is redundant. After its removal, refetching and throttling feature will require some refactoring to provide better UX for users.

-- fill in the line below:
** discord username: Göksenin#7758 **

## Define the alternatives you have in mind
- 'SCAN FIELD' action and throttling info section will be removed
![Screenshot 2023-02-11 at 16 30 43](https://user-images.githubusercontent.com/1084392/218260639-1441437c-1cf0-4d55-ade1-ecd009840546.png)
- Fetching new dataset will be integrated to `moveend` action of map
 
## Extra context
Add some extra context or screenshot pertaining to said feature request.

**Comment by absolutezero13** [comment]
can take this once approved
