### ISSUE TITLE
refactor: update the layer selection on desktop

### ISSUE THREAD

**Issue by el** [acikkaynak/deprem-yardim-frontend#790]
## Bug Definition

The layer selection drawer needs to be updated on the desktop according to the UI/UX team's design. 

-- Please add discord contact information
**discord username: @el**

Here is the design:

<img width="390" alt="SCR-20230211-r1b" src="https://user-images.githubusercontent.com/1488164/218269414-97d33cf0-317c-4fc4-bc2a-7b24a28d1fca.png">

**Comment by el** [comment]
I am reporting this here to keep a record of it. I will pick up this issue.

**Comment by fdemir** [comment]
it is not urgent.  not necessary, wil look at later. design is not first intent right now. please text from dc text channel so we can discuess it.
