### ISSUE TITLE
feat: Displaying verified and unverified data

### ISSUE THREAD

**Issue by eraygundogmus** [acikkaynak/deprem-yardim-frontend#796]
Discord kanalımızda Merve Noyan ve diğer arkadaşların collect edip, yapay zeka ml gibi teknolojilerle otomasyon haline getirdiği datayı şu anlık güvensiz buluyoruz. 

The data collected and automated with ai, ml technologies by Merve Noyan and other friends are right now being unsecured.

Çünkü güçlü bir onay mekanızmasına giren datalar toplanıyor: Örnek: BabalaTV tek tek telefonla arıyor, AHBAP organizasyonu, vs vs. 

Because of the data is gathered with a strong confirmation mechanism. Example: BabalaTV is making phone calls one by one, Ahbap Organization etc.

Haritada initial ve default olarak, onaylanmış şeyleri göstermeliyiz. bir multiselect altında 
Under a multiselect; we have to display verified data by default and initial on the map.

https://mui.com/material-ui/react-select/
Verified: True
Unverified: False

**Comment by a-nyx** [comment]
bunu ben alabilirim. `verification` parametresi ve menüye diğerlerinin benzeri bir dropdown ekleyebilirim.

**Comment by oguzergul** [comment]
@a-nyx this issue is currently in development by me and @OrhanOzkercin

**Comment by sercanerhan** [comment]
As described in [the issue](https://github.com/acikkaynak/deprem-yardim-frontend/issues/796) the default value should be **Verified** cases. [Preview Link](https://deprem-yardim-frontend-git-fork-cdagli-feat-796-caner-afet.vercel.app/) opens with null selection.

The expectation is, on the initial default page load, only the **Verified** locations should be visible and  new multi-select filter should be selected as ** Verified**

**Comment by naimyurek** [comment]
I have completed the development to be approved as the default value.

**Comment by nazdezar** [comment]
@sercanerhan @naimyurek it looks like this has been released to production. right?
