### ISSUE TITLE
bug: translation error clustergroups and map.layer.markers

### ISSUE THREAD

**Issue by emirhnergn** [acikkaynak/deprem-yardim-frontend#806]
## Bug Definition
A clear and short text to decribe the bug.

No translations for view controls (top left)
Translation error for clusterTags
map.layer.markers translation is not consistent with both english and reason filter

-- Please add discord contact information
** discord username: @RedCore#6872**

## Bug environment
Describe the environment produces the bug. For example:
afetharita.com
## Describe how you are producing the bug step by step

1. Go to 'afetharita.com'
2. Click 'switch language button' 
3. Switch to 'EN' 
4. Bug appears

## Expected Behaviour
![image](https://user-images.githubusercontent.com/42092152/218275114-37fca622-ab43-4afe-b7ca-207b5b68e550.png)

## Screen shots
If possible, add screenshots to describe your bug.
![image](https://user-images.githubusercontent.com/42092152/218275123-a3efd54c-b517-4e73-a87b-b4e10301e3ee.png)

## Desktop Information
- Operating System: Windows
- Browser: Chrome
- Version: 109

## Mobile Phone Information
- Devıce: [for example iPhone6]
- Operating System (with the version): [for example iOS8.1]
- Version [for example default browser, safari]
- Browser Version [for example 22]

## Additional Context
Add any other context about the bug here

**Comment by ssibrahimbas** [comment]
If you mark it as assigned, I can send it quickly.

**Comment by buraktuzlutas** [comment]
Error status still exists.

**Comment by aysenur-aydin** [comment]
@emirhnergn  We are appreciated your work but currently our team decided to accept team's issues, your sincerely.
