### ISSUE TITLE
bug: snackbar z index problem

### ISSUE THREAD

**Issue by vnylbscr** [acikkaynak/deprem-yardim-frontend#822]
## Bug Definition
Snackbars does not appears on front of drawer screen. It must be front of the drawer screen.

**discord username: mertolala#9076**

## Bug environment

rc.afetharita.com
afetharita.com
## Describe how you are producing the bug step by step

1. Trigger any snackbar on screen while drawer is opened, it would shown behind the drawer screen

## Expected Behaviour
It must be front of the drawer screen 
## Screen shots

![Screen Shot 2023-02-12 at 02 39 06](https://user-images.githubusercontent.com/24382252/218285953-10327c62-4888-43a2-8945-fb794287c5e5.png)

## Desktop Information
- Operating System: macos 12.6
- Browser: Google Chrome
- Version: any

**Comment by sevilayerkan** [comment]
Hello, It seems like pr #824 solves this issue perfectly. After merge the bug will solved. Also we could not reproduce this issue in nor prod or rc. So `waiting-test` can be removed.  If there you need more test please let us know.
