### ISSUE TITLE
bug: Points disappear on zoom

### ISSUE THREAD

**Issue by emincanoguz11** [acikkaynak/deprem-yardim-frontend#845]
## Bug Definition
 https://afetharita.com/?lat=37.54559044559978&lng=36.80883407592774&zoom=14
In this link when you zoom in the marker disappears. Ther is a problem with the zoom value. Can you check? (After zoom level 18)

-- Please add discord contact information
** discord username: @emincanoguz#1867 **

## Bug environment
https://discord.com/channels/1072074800622739476/1072074878452240384/1074344702918279198 
the bug video here
afetharita.com

**Comment by absolutezero13** [comment]
Might be a backend problem

this is the request that returns 4 points;

ne_lat: 37.54516899939234
ne_lng: 36.796176267623906
sw_lat: 37.5366355518261
sw_lng: 36.7840160598755
channel: babala

When I zoom, it returns 0 points and this is the request;

ne_lat: 37.543671801558915
ne_lng: 36.793445778846745
sw_lat: 37.53840508373894
sw_lng: 36.786365674972544
channel: babala

**Comment by selensr** [comment]
In these coordinates, it returns 6 points
lat=37.5437532785641
lng=36.7934274673462
zoom=14

In these coordinates, it returns 4 points
lat=37.543758826410155
lng=36.79344892501832
zoom=15

It should return 5 points; one is disappearing
and it doesn't appear after scanning the field

**Comment by selensr** [comment]
![Screen Shot 2023-02-12 at 20 27 13](https://user-images.githubusercontent.com/45594532/218326777-afb5091a-098e-4eed-a0e9-6f05032c2b8b.png)

Something similar happens here too. When the marker/marker cluster is close to the frame, they disappear

![Screen Shot 2023-02-12 at 20 26 51](https://user-images.githubusercontent.com/45594532/218326817-059100f4-fe39-499b-8620-3453bf84388b.png)

**Comment by selensr** [comment]
the data returns an empty array

**Comment by serdarozturk** [comment]
It seems that this issue is not originating from the frontend. The data is not being returned from the API endpoint. It could be due to the location values in the database table or the float precision value in the API code.
