### ISSUE TITLE
bug: saglik menu item gorunmuyoe

### ISSUE THREAD

**Issue by OrhanOzkercin** [acikkaynak/deprem-yardim-frontend#850]
## Bug Definition
Filtrede saglik menu item gorunmuyor

-- Please add discord contact information
** discord username: orhanozkercin#0001 **

## Bug environment
Describe the environment produces the bug. For example:
rc.afetharita.com
afetharita.com
## Describe how you are producing the bug step by step

2. Click '....' 
3. Scroll to '....' 
4. Bug appears

## Expected Behaviour
A clear and short text to decribe the expected behaviour.

## Screen shots
If possible, add screenshots to describe your bug.

## Desktop Information
- Operating System: [for example iOS]
- Browser [for example, safari]
- Version [for example 22]

## Mobile Phone Information
- Devıce: [for example iPhone6]
- Operating System (with the version): [for example iOS8.1]
- Version [for example default browser, safari]
- Browser Version [for example 22]

## Additional Context
Add any other context about the bug here
@oguzergul

**Comment by nejatcanunlu** [comment]
Took this on, PR is on the way.

**Comment by nejatcanunlu** [comment]
Just found out this must be removed, closing this issue and opening a more appropriate one for consistency.
