### ISSUE TITLE
feat: Data Sources text-button

### ISSUE THREAD

**Issue by sercanerhan** [acikkaynak/deprem-yardim-frontend#855]
## Define your request
Currently we have an information model which is visible only for first time visitors to explain our data sources to them.
Within this exercise, we will allow user to to access that information anytime via a new link named (en: Date Sources; tr: Veri Kaynakları)
on the bottom left as a new (3rd) text-button.

![image](https://user-images.githubusercontent.com/3420568/218322528-a1211807-4bb1-401f-904b-93494fd1c35f.png)
![image](https://user-images.githubusercontent.com/3420568/218322664-7e2ea1a5-f350-4981-8fc3-992f2e069ffd.png)

We also need to update existing text in that modal as below:

**[TR]** Açıklama: Sosyal medya ve haberleşme platformları, web siteleri, sivil toplum kuruluşları, dernekler, yardım kuruluşları, basın ve medya kuruluşları ile kamu kurum ve kuruluşları tarafından paylaşılan/yapılan/yayınlanan yardım, destek ve arama kurtarma çağlarılarını topluyoruz ve bu veriyi sahada kullanılmak üzere anlamlı, rafine hale getiriyoruz. Amacımız bilgi teknolojilerini kullanarak ilgili kurum ve STK'lara yardımcı olmak ve afet zamanlarında açık bir veri platformu sağlamaktır.

**[EN]** Disclosure: We gather information on relief efforts, support requests, search and rescue requests that are shared by social media platforms, websites, civil society organizations, associations, aid organizations, the media, public institutions and organizations. We process this data to make it usable in the field. Our aim is to support relevant institutions and NGOs using information technology and to provide a clear and accessible data platform during times of disaster

### Default Behavior
Same as existing live version.
* Open: Only the first time visitors automatically see that information.
* Close: modal close button (manually).

### Re-Access the information
* Open: Since we will have the new (3rd) **Data Sources** text-button, whenever a user clicks that button, the same existing modal pops-up.
* Close: modal close button (manually).

** discord username: @sercanerhan#0543 **

## Define the alternatives you have in mind
> Provide a clear and brief explanation to any alternative solution or feature you have in mind.

**Comment by absolutezero13** [comment]
You can assign this to me if it's not taken @oguzergul

**Comment by utkuonursahin** [comment]
I'm available for this issue and wanting to work on it.

**Comment by sercanerhan** [comment]
@oguzergul text information has been updated in the issue as below:

**[TR]** Açıklama: Sosyal medya ve haberleşme platformları, web siteleri, sivil toplum kuruluşları, dernekler, yardım kuruluşları, basın ve medya kuruluşları ile kamu kurum ve kuruluşları tarafından paylaşılan/yapılan/yayınlanan yardım, destek ve arama kurtarma çağlarılarını topluyoruz ve bu veriyi sahada kullanılmak üzere anlamlı, rafine hale getiriyoruz. Amacımız bilgi teknolojilerini kullanarak ilgili kurum ve STK'lara yardımcı olmak ve afet zamanlarında açık bir veri platformu sağlamaktır.

**[EN]** Disclosure: We gather information on relief efforts, support requests, search and rescue requests that are shared by social media platforms, websites, civil society organizations, associations, aid organizations, the media, public institutions and organizations. We process this data to make it usable in the field. Our aim is to support relevant institutions and NGOs using information technology and to provide a clear and accessible data platform during times of disaster

**Comment by sercanerhan** [comment]
@usirin looks like we have lost this feature in  #1195. That's why I'm moving this issue to `open` again.

**Comment by sercanerhan** [comment]
tested in RC and this issue is still valid.
