### ISSUE TITLE
bug: language selection dropdown is not closing after selection

### ISSUE THREAD

**Issue by BerkanSezer** [acikkaynak/deprem-yardim-frontend#858]
## Bug Definition
- After language selection vie dropdown on bottom of the page, Menu is not closing immediately.
- Language dropdown should located to top of selection button for better experience.

-- Please add discord contact information
** discord username: @solaksolcu#3512 **

## Bug environment
afetharita.com
## Describe how you are producing the bug step by step

1. Open language dropdown
2. Change Application language
3. Bug appears

**Comment by Rayberk** [comment]
#777 duplicate
