### ISSUE TITLE
bug: Chips without reason are visible

### ISSUE THREAD

**Issue by isaozler** [acikkaynak/deprem-yardim-frontend#866]
## Bug Definition
The Tweet placeholder chips are not filtering empty reasons

-- Please add discord contact information
** discord username: @isaozler#4498 **

## Bug environment
Describe the environment produces the bug:
afetharita.com

## Describe how you are producing the bug step by step

1. Select a social media event in the filters
2. Click event with ID 769353
3. Bug appears, you can see the empty chip

## Expected Behaviour
The expected behavior here is to hide the chip

## Screenshots
![image](https://user-images.githubusercontent.com/1378630/218326701-a381b8b8-0e7c-479b-a0af-72cb553c5220.png)

**Comment by oguzergul** [comment]
i will handle this issue

**Comment by isaozler** [comment]
components/UI/Drawer/components/channels/twitter/PlaceholderTweet.tsx

![image](https://user-images.githubusercontent.com/1378630/218327264-560b1683-7a25-4c5c-a432-ca1d5f653dbd.png)

**Comment by sevilayerkan** [comment]
We tested we didn't encounter any problem you have mentioned. Also both prod and rc seem just fine. Congrats 👏
