### ISSUE TITLE
bug: Phone Number is in incorrect format

### ISSUE THREAD

**Issue by aybekckaya** [acikkaynak/deprem-yardim-frontend#879]
## Bug Definition
Phone Number is in incorrect format

** discord username: @aybekcankaya#6847 **

## Bug environment
1- Select one of the "enkaz" places. You can see that phone number is in incorrect format. 
 Endpoint: https://apigo.afetharita.com/feeds/707461
(I have seen this bug in only one place)

## Expected Behaviour
Phone number should be like : "05432345465"

## Screen shots
![Ekran Resmi 2023-02-12 21 46 12](https://user-images.githubusercontent.com/4394343/218331407-39611f4b-cc8f-48a5-bd1a-3dd6565ec2bb.png)

## Desktop Information
- Browser [Opera macOS Sürüm 13.0.1]

**Comment by CyhnYldz** [comment]
We also got the same error. With the phone number data

**Comment by zntemel** [comment]
Isn't it a backend bug?

**Comment by el** [comment]
This is a backend issue
