### ISSUE TITLE
feat: Disaster Pharmacy Map 

### ISSUE THREAD

**Issue by savasdenli** [acikkaynak/deprem-yardim-frontend#881]
## Define your request
There is a disaster pharmacies map created by Türk Eczacılar Birliği. Map contains truck and container pharmacies.

-- fill in the line below:
** discord username: @Savaş Denli#2570 **

## Define the alternatives you have in mind
This map can be added like Hospital Map.

## Extra context
Map provided by TEB: https://maps.app.goo.gl/bog7Zqi4KbyjAJWK6?g_st=ic

**Comment by ssibrahimbas** [comment]
A friend of mine from the earthquake zone just asked if there is such a feature. I think it will work, its priority can be increased.

**Comment by oguzergul** [comment]
we have already have this data. thank for info.
