### ISSUE TITLE
bug: Ahbap data description value data type

### ISSUE THREAD

**Issue by absolutezero13** [acikkaynak/deprem-yardim-frontend#883]
## Bug Definition

Data from Ahbap sometimes has description property and it can be object or string. This sometimes cause "Objects are not valid child" error.

-- Please add discord contact information
** discord username: İlker Sarica#7138 **

## Bug environment
Describe the environment produces the bug. For example:
rc.afetharita.com
afetharita.com
## Describe how you are producing the bug step by step

1. Go to [Diyarbakır on the map](https://rc.afetharita.com/en?lat=37.926325689039984&lng=40.14752984046937&zoom=16)
2. Click icon
3. Bug appears

## Expected Behaviour
A clear and short text to decribe the expected behaviour.

## Screen shots
If possible, add screenshots to describe your bug.

## Desktop Information
- Operating System: [for example iOS]
- Browser [for example, safari]
- Version [for example 22]

## Mobile Phone Information
- Devıce: [for example iPhone6]
- Operating System (with the version): [for example iOS8.1]
- Version [for example default browser, safari]
- Browser Version [for example 22]

## Additional Context
Add any other context about the bug here

**Comment by absolutezero13** [comment]
pr ready if approved.

**Comment by el** [comment]
The issue seems to continue

**Comment by nazdezar** [comment]
@el can you please provide screenshots or examples of this issue?

**Comment by usirin** [comment]
Fixed with #924
