### ISSUE TITLE
bug: Back button click leading to an error message

### ISSUE THREAD

**Issue by CyhnYldz** [acikkaynak/deprem-yardim-frontend#886]
## Bug Definition
after clicking back button you got error message

-- Please add discord contact information
Ceyhun Yıldız#6679

## Bug environment

rc.afetharita.com
afetharita.com
## Describe how you are producing the bug step by step

1- Open rc.afetharita.com or afetharita.com
2- Move the map 
3- Clikck the back button
4- You will see the error message.

## Expected Behaviour
there wont be an error message. 

## Screen shots

https://user-images.githubusercontent.com/111140617/218333524-b69122ba-21f2-4775-8589-ddc8e139b443.mp4

## Desktop Information
- Operating System: Windows 10
- Browser Chrome
- Version 109.054 / 110.0

- Operating System: Windows 10
- Browser Opera
- Version 108

- Operating System: Windows 10
- Browser FireFox
- Version 109.01

## Mobile Phone Information

- Devıce: note 10+
- Operating System (with the version): android 12
- Version 
- Browser Version brave browser 1.48

- Devıce: Samsun S21
- Operating System Android 13
- Version android 13
- Browser Version Samsung Internet 20.0.0.65

- Devıce: Ipad 6
- Operating IOS 
- Version 14.2
- Browser Version Ipad Safari

## Additional Context
Add any other context about the bug here

**Comment by akselsaatci** [comment]
This bug happens in desktop too. It happens because of "?" from query dissapers.  It's hard to reproduce the bug.

Normal query : `http://localhost:3000/?lat=37.04957695185612&lng=35.52199602127076&zoom=16`

When the bug happens :  `http://localhost:3000/lat=37.04957695185612&lng=35.52199602127076&zoom=16`

**Comment by CyhnYldz** [comment]
@akselsaatci it is tested on desktop  in 3 different browsers as you can see above. Also it is pretty easy to reproduce the bug.

**Comment by akifunal** [comment]
I might find the problem. I can this issue.
