### ISSUE TITLE
refactor: Disclosure text readability problem

### ISSUE THREAD

**Issue by denizhacisalihoglu** [acikkaynak/deprem-yardim-frontend#887]
### Refactor Request

As .6rem the disclosure text in footer is too small.

** discord username: denizhcs **

<img width="1498" alt="Screen Shot 2023-02-12 at 22 04 36" src="https://user-images.githubusercontent.com/4246313/218334494-488fb4d4-74ad-43af-8707-d482ba2cd29c.png">

### Suggested solution

 Please update font-size in FooterBanner.module.css at least 12px/.75rem.

**Comment by khnbzkrt** [comment]
I developed this issue, if approved i can make or ican share the code with you @denizhacisalihoglu 
![image](https://user-images.githubusercontent.com/67371416/218335928-e0df06d4-d9b8-49c6-9172-557be942dc5a.png)
![image](https://user-images.githubusercontent.com/67371416/218335978-02eb28c6-acff-424d-969b-824143d0fa54.png)

**Comment by khnbzkrt** [comment]
@denizhacisalihoglu There is a general design change in the components on this screen and this problem will be solved there, so I'm closing the issue.
