### ISSUE TITLE
bug: Localization string is missing

### ISSUE THREAD

**Issue by denizhacisalihoglu** [acikkaynak/deprem-yardim-frontend#888]
## Bug Definition
Localization string for filter.reasons.saglik is missing.
** discord username: @denizhcs **

## Bug environment
[afetharita.com](https://afetharita.com/)
## Describe how you are producing the bug step by step
1. Go to [afetharita.com](https://afetharita.com/)
2. Click to All Reasons in filter menu
3. Scroll to last item in the list
4. Missing item will be shown here in all languages

## Expected Behaviour
Text should be set for English and Turkish.

## Screen shots
<img width="937" alt="image" src="https://user-images.githubusercontent.com/4246313/218334715-e70e5e02-8810-4888-b91e-4531a0d06c1c.png">

## Desktop Information
- Operating System: macOS
- Browser Chrome
- Version 110.0.5481.77

**Comment by akselsaatci** [comment]
I think it fixed in https://rc.afetharita.com/en
![image](https://user-images.githubusercontent.com/100696686/218335013-88480057-b758-4933-8023-780a88fa0559.png)

**Comment by nejatcanunlu** [comment]
This is already fixed on rc and will be deployed to prod eventually, closing issue for cleanup. Thanks for the report @denizhacisalihoglu!
