### ISSUE TITLE
bug: Show language-dependent time information in drawer

### ISSUE THREAD

**Issue by nikneym** [acikkaynak/deprem-yardim-frontend#889]
## Bug Definition
The time information that's shown in drawer only supports turkish output.

-- Please add discord contact information
** discord username: @nikneym#7666 **

## Bug environment
afetharita.com
## Describe how you are producing the bug step by step

1. Click 'on some marker'
3. Open 'drawer'
4. Bug appears

## Expected Behaviour
It should be translated to other languages and showed as such.

## Screen shots
![image](https://user-images.githubusercontent.com/4337696/218336992-c78b954e-46b5-4b09-9c1c-638fd26dc4de.png)

## Desktop Information
- Operating System: [for example iOS]
- Browser [for example, safari]
- Version [for example 22]

## Mobile Phone Information
- Devıce: [for example iPhone6]
- Operating System (with the version): [for example iOS8.1]
- Version [for example default browser, safari]
- Browser Version [for example 22]

## Additional Context
Add any other context about the bug here

**Comment by nazdezar** [comment]
Currently it says: "Notify Time: 3 gün 5 saat 39 dakika önce" for the English page.

Let's update this to : 

"Last Notification 3 **days** 5 **hours** 39 **minutes** ago" <<< thoughts on this @handekaratas96 @canerakin111 ?

**Comment by canerakin111** [comment]
@nazdezar my understanding is that notify time is notification time. Are you suggesting that we should cap the tweet based on publish date?
