### ISSUE TITLE
bug: Filters do not work properly

### ISSUE THREAD

**Issue by sevilayerkan** [acikkaynak/deprem-yardim-frontend#890]
## Bug Definition
Filters on the right do not work properly. For example when user selects Ahbap map filter on the left then the filters on the right does not make any sense. Or it is also the case for 'Hospital' map filter. So there is no conenction between right and left filters. We suspect there are more problems like these. 

-- Please add discord contact information
** discord username: @notDepresseDeveloper#0919 **

## Bug environment
Describe the environment produces the bug. For example:
rc.afetharita.com
afetharita.com

## Describe how you are producing the bug step by step

1. Go to afetharita.com
2. Click `Map type` filter on the left
3. Select `Ahbap locations`
4. Select something from right filter
5. Bug will appear

## Expected Behaviour
A clear and short text to decribe the expected behaviour.
We should have seen the map/locations based on filters we choose.

## Screen shots
Here is ss for the one of the problems we have mention.
![image](https://user-images.githubusercontent.com/22706692/218336886-62b2e0d5-868e-4692-b44a-d89bda1b6b98.png)

## Desktop Information
- Operating System: Windows 10, 11
- Browser: Chrome, Safari

## Mobile Phone Information
- Operating System (with the version): Android, IOS 
- Browser : Chrome, Safari (for IOS), Samsung Browser (Android)

**Comment by nazdezar** [comment]
@sevilayerkan we are working on removing "Ahbap" from the layers so I am inclined not to work on this for now.

**Comment by sevilayerkan** [comment]
We are not getting the error not just for Ahbap (reported it as a example), we're experiencing same problem with all the filters actually.  We encountered and suspected there are more problems like these. As a test team since this it is actively used by the people in field we are really concerned this might cause problem for them. So i highly recomend you should change your decision about `wontfix.`

**Comment by sevilayerkan** [comment]
We are not getting the error not just for Ahbap (reported it as a example), we're experiencing same problem with all the filters actually. We encountered and suspected there are more problems like these. As a test team since this it is actively used by the people in field we are really concerned this might cause problem for them. So i highly recomend you should change your decision about `wontfix`. @nazdezar

**Comment by CyhnYldz** [comment]
We re evaluate the issue

**Comment by usirin** [comment]
@sevilayerkan do we know if this still exists?

**Comment by usirin** [comment]
Gonna be gone fixed with new design, thanks for the report.

**Comment by sevilayerkan** [comment]
Hi, we tested again (in prod and rc) filters work in all filters other than Ahbap and Teleteyit. Thanks for your efforts in new design ❤️ @usirin
