### ISSUE TITLE
bug: Page performance issue when all data filters selected

### ISSUE THREAD

**Issue by sevilayerkan** [acikkaynak/deprem-yardim-frontend#892]
## Bug Definition
When all filters are active (including map, channel etc) the page speed decreases drastically. In near future we want to add more data layers to this map thats why we have to consider fixing it beforehand. 

-- Please add discord contact information
** discord username: @notDepresseDeveloper#0919 **

## Bug environment
Describe the environment produces the bug. For example:
rc.afetharita.com
afetharita.com
## Describe how you are producing the bug step by step

1. Go to afetharita.com or rc.afetharita.com
2. Select all filters both left and right

## Expected Behaviour
A clear and short text to decribe the expected behaviour.
We expect seamless system even works in the weak devices or networks.

## Screen shots
If possible, add screenshots to describe your bug.
![image](https://user-images.githubusercontent.com/22706692/218337444-0234c89d-8104-402c-862b-20db54194538.png)

## Desktop Information
- Operating System: Windows 10, 11
- Browser: Chrome, Safari

## Mobile Phone Information
- Operating System (with the version): Android, IOS 
- Browser : Chrome, Safari (for IOS), Samsung Browser (Android)

**Comment by mertkaya1033** [comment]
I am working on fixing this issue.

**Comment by usirin** [comment]
- update `AhbapClusterGroup` and TeleteyitClusterGroup` components to have radius: 10 value for supercluster

**Comment by mertkaya1033** [comment]
It is very confusing for the users when marker cluster group icon and the ahbap/teleteyit cluster icon are the same. Here are some of my suggestions to handle this issue:

- Use a different icon for each of the cluster types (i.e. ahbap and teleteyit)
- Add a specific border to the already existing icon and represent the cluster size by icon size. In other words. the larger the cluster, the larger it is displayed.
