### ISSUE TITLE
feat: implement satellite channel to map layers

### ISSUE THREAD

**Issue by oguzergul** [acikkaynak/deprem-yardim-frontend#910]
## Define your request
Define the feature you're requesting clearly and briefly.

-- fill in the line below:
** discord username: @oguzergul#9634 **

## Define the alternatives you have in mind
Provide a clear and brief explanation of any alternative solution or feature you have in mind.

## Extra context
Add some extra context or screenshots pertaining to said feature request.

**Comment by nazdezar** [comment]
@oguzergul this seems to be already in production. can you please confirm this is what you are referring?

**Comment by usirin** [comment]
@nazdezar this is "uydu" as source of markers, not satellite mode for the map terrain.
