### ISSUE TITLE
bug: Locations' detail title error

### ISSUE THREAD

**Issue by sevilayerkan** [acikkaynak/deprem-yardim-frontend#913]
## Bug Definition
A clear and short text to decribe the bug.
In locations title looks like this  <**l>

-- Please add discord contact information
** discord username: @notDepresseDeveloper#0919 **

## Bug environment
Describe the environment produces the bug. For example:
For pr #908 
rc.afetharita.com
afetharita.com

## Describe how you are producing the bug step by step

1. Go to pr deployment preview
2. Look one of the locations
4. Bug appears

## Expected Behaviour
Title should be seen right

## Screen shots
![image](https://user-images.githubusercontent.com/22706692/218350219-1cf722b7-c999-4eaf-a969-f78635da77b9.png)
![image](https://user-images.githubusercontent.com/22706692/218350291-86243a19-8b41-4db2-832f-4d42b82e73d6.png)

## Desktop Information
- Operating System: Windows
- Browser Chrome
- Version 110

## Mobile Phone Information
- Operating System (with the version): Android
- Browser Version: Chrome 110

**Comment by sevilayerkan** [comment]
Update similar error occurs titles for other locations too

![image](https://user-images.githubusercontent.com/22706692/218351481-a9807511-b38a-4360-838d-0449ba15bc8a.png)

**Comment by dopplerDistortion** [comment]
@nazdezar seems like this issue is fixed at latest RC deploy https://rc.afetharita.com/ you can check it again.
