### ISSUE TITLE
bug: Layers drawer not showing in Safari Desktop (min-width 768px)

### ISSUE THREAD

**Issue by isaozler** [acikkaynak/deprem-yardim-frontend#914]
## Bug Definition
The Layers Drawer is not showing when the page is visited in Safari Desktop with a viewport of min-width 768px

-- Please add discord contact information
** discord username: @isaozler#4498 **

## Bug environment
rc.afetharita.com
afetharita.com

## Describe how you are producing the bug step by step

1. Go to afetharita.com
2. Click on layers
3. Bug appears by not showing the "Layers Drawer"

## Expected Behaviour
A clear and short text to decribe the expected behaviour.

## Screen shots
![image](https://user-images.githubusercontent.com/1378630/218354368-fdff1f28-4f0b-471c-8f85-f8bade8bb9a7.png)

## Desktop Information
- Operating System: MacOS
- Browser Safari
- Viewport: Desktop

**Comment by sevilayerkan** [comment]
In addition to Ceyhun here is video regarding to test: 

https://user-images.githubusercontent.com/22706692/218440676-de00f00b-4cf9-4188-8f50-ffc696fa8579.mov

**Comment by oguzergul** [comment]
i ve tested this but it works on my machine @isaozler @sevilayerkan

**Comment by absolutezero13** [comment]
> In addition to Ceyhun here is video regarding to test: (it tested with safari-ipad)
> 
>  RPReplay_Final1676285873.mov

I also could reproduce just like this

**Comment by iremuguztemur** [comment]
This issue has been tried on safari desktop and specified environments. The same error continues.

**Comment by iremuguztemur** [comment]
This issue has been tried on safari desktop and specified environments. The same bug continues.

**Comment by iremuguztemur** [comment]
This issue has been tried on safari desktop and specified environments. The same problem continues.

**Comment by CyhnYldz** [comment]
fixed in PR #915
