### ISSUE TITLE
refactor: use zustand's persist middleware to store data on local storage

### ISSUE THREAD

**Issue by usirin** [acikkaynak/deprem-yardim-frontend#919]
## Refactor Request

** discord username: umut#3072 **

We shouldn't need to work with local storage inside components

### Suggested solution

Use zustand persist middleware so we can add the code to work with local storage over there.

### Related Issues
#917 
#893 

cc @puskuruk can you please post the links you have.

**Comment by sarpremziaksu** [comment]
https://github.com/pmndrs/zustand/blob/main/docs/integrations/persisting-store-data.md

For further contributions, this documentation needs to be checked over.

**Comment by sevilayerkan** [comment]
Note for the github team because of my discord username has the same id here (0919) whenever i opened a new issue there will be tagged here. Maybe we should consider to review issue template. Sorry for disturbance 😞
