### ISSUE TITLE
bug: fix error page

### ISSUE THREAD

**Issue by usirin** [acikkaynak/deprem-yardim-frontend#921]
## Bug Definition
Messages & strings need to be updated

-- Please add discord contact information
** discord username: umut#3270 **

![image](https://user-images.githubusercontent.com/1783869/218364380-23dd283a-b10d-465b-b344-dc4a3487be55.png)

**Comment by nazdezar** [comment]
@usirin we can show something like this. @sercanerhan could you please review these tomorrow? And if the team agrees, we can update the error messages to be generic for now.

TR: "Bir sorunla karsilastik. Lutfen tekrar deneyiniz".

Text on the links.
<Ana Sayfaya Geri Don>
<Depremyardim.com'a Git>

EN: "Something went wrong. Please try again."

Text on the links.
<Return to Homepage>
<Go to Depremyardim.com>

**Comment by usirin** [comment]
> <Depremyardim.com'a Git>

This needs to be <afetharita.com'a git>

**Comment by oguzergul** [comment]
i will handle this

**Comment by absolutezero13** [comment]
seems like it's really hard to do translation on next.js _error page https://github.com/i18next/next-i18next/issues/1020

I've tried several times and failed, should we just maybe hardcode or import json directly?

**Comment by akifunal** [comment]
@absolutezero13 i might find a solution to translate in error page. [withTranslation](https://github.com/i18next/next-i18next/issues/1020#issuecomment-1054896437)

**Comment by akifunal** [comment]
We need to update our language files for errors. I'm opening a pr to show how we can use translation on error page.

**Comment by usirin** [comment]
fixed
