### ISSUE TITLE
bug: capital letter of 'i' in English displayed as İ

### ISSUE THREAD

**Issue by mertkaya1033** [acikkaynak/deprem-yardim-frontend#926]
## Bug Definition
In the English translation, when the lower case letter 'i' is capitalized, it uses the Turkish letter İ.

-- Please add discord contact information
** discord username: Sertcast#8543 **

## Describe how you are producing the bug step by step
Choose the English language option from the right bottom of the screen.

## Expected Behaviour
The letter "I" should be used instead of "İ". For example, "VERİFİED" should be displayed as "VERIFIED"

## Screen shots
![Screenshot 2023-02-12 at 23 34 18](https://user-images.githubusercontent.com/47050442/218371446-eede80b4-e0c4-47a2-99fa-862c5af574dc.jpg)

**Comment by mertkaya1033** [comment]
This issue is caused by auto-capitalization of MUI. We can do a [global theme overwrite](https://mui.com/material-ui/customization/theme-components/#global-style-overrides) and manually convert text into uppercase letters via `.toLocaleUpperCase()`. Even though we will need to check every component where it was assumed that MUI would take care of the capitalization after implementing a global change in the codebase, we should not run into such problems  in the future. Let me know if you want me to implement this change @usirin

**Comment by CyhnYldz** [comment]
Fixed with #933. Verified displayed as expected "VERIFIED".
