### ISSUE TITLE
bug: lat=&lng= query strings are being removed when drawer closed 

### ISSUE THREAD

**Issue by siniradam** [acikkaynak/deprem-yardim-frontend#930]
## Bug Definition
Once the drawer is closed lat & lng values from url is being removed

-- Please add discord contact information
** discord username: tinman#7219 **

## Bug environment
prod: afetharita.com
## Describe how you are producing the bug step by step

Zoom in to any location, click/pick a pin (open drawer) then click on map and close it.
Once the drawer is closed lat & lng values from url is beng removed

## Expected Behaviour
Lat & Lng should consist.

## Desktop Information
- Browser Chrome

## Additional Context
Add any other context about the bug here

**Comment by mertkaya1033** [comment]
I am working on this issue.

**Comment by usirin** [comment]
i am also gonna take a look at this

**Comment by CyhnYldz** [comment]
issue still persists.

**Comment by Rayberk** [comment]
it is expected and caused by #884 
All of the queries are being removed to remove the id when drawer is closed.
Lat lng string are already stored in localstorage because of this they are being deleted
