### ISSUE TITLE
bug: Some pin locations displays an object that each character is a new line.

### ISSUE THREAD

**Issue by siniradam** [acikkaynak/deprem-yardim-frontend#931]
## Bug Definition
Some pins displays a JSON object that each characters splitted into new line.

-- Please add discord contact information
** discord username: @tinman#7219 **

## Bug environment
afetharita.com
rc.afetharita.com

## Describe how you are producing the bug step by step
Sample urls;

https://afetharita.com/en?id=707631
https://rc.afetharita.com/en?id=707622
https://rc.afetharita.com/en?id=552624
https://rc.afetharita.com/en?id=552626

## Expected Behaviour
Should show data, or none.

## Screen shots
<img width="405" alt="Screenshot 2023-02-12 at 9 10 08 PM" src="https://user-images.githubusercontent.com/3178435/218375713-6a989c33-036e-47cd-9a8a-c7c5b14f9e95.png">

## Desktop Information
- Operating System: osx
- Browser chrome

**Comment by CyhnYldz** [comment]
Fixed with #927
