### ISSUE TITLE
feat: Enhancements on Map Layers and Filters

### ISSUE THREAD

**Issue by nazdezar** [acikkaynak/deprem-yardim-frontend#932]
We have a growing number of reasons and channels from various sources and we need to re-design the map layers and filters to improve the user experience by simplifying the map layers and making the map filters easier to navigate between data type, channel, and reason.

** discord username: @nazdezar @handekaratas96 **

[FIGMA Design
](https://www.figma.com/file/sctw6xtcdoFOfmE0gC97Ft/Afet-Harita---Afetharita.com?node-id=5383%3A11182&t=453ihQvDDpYAOPkT-0)

[The FIGMA Data Filter Mapping](https://www.figma.com/file/sctw6xtcdoFOfmE0gC97Ft/Afet-Harita---Afetharita.com?node-id=5383%3A11182&t=453ihQvDDpYAOPkT-0)
reach out to @handekaratas96 for questions.

There are three main filters on the Map Filters: 
- Hizmetler / Services
- Yardim Talebi / Relief Aid
- Afetzede Bul / Rescue Help

**Requirements:** 
- If the underlying data is not present, do not show the data category to the user as a selection (for Yardim and Hizmet). 
- All selections should be multi-selection; allowing users to select more than one filter input. 
- "Hizmet ve Yardim Talep" categories should have ALL or NONE in the dropdown selection.
- When the Filter Menu is closed (X), the filter criteria should not change.

**Comment by usirin** [comment]
gonna be fixed with new filter ui
