### ISSUE TITLE
bug: In some detail data, the content comes as stringified json

### ISSUE THREAD

**Issue by ssibrahimbas** [acikkaynak/deprem-yardim-frontend#936]
## Bug Definition
In some location details the content comes as a stringified json. Still, the view is not very good.

-- Please add discord contact information
** discord username: @ss.ibrahimbas#4990 **

## Bug environment
Describe the environment produces the bug. For example:
rc.afetharita.com
afetharita.com
## Describe how you are producing the bug step by step

1. Go to [this url](https://rc.afetharita.com/en?id=706439)
2. Look at sidebar content

## Expected Behaviour
content should be parsed and meaningful data should be displayed

## Screen shots
![image](https://user-images.githubusercontent.com/76786120/218390554-5da9164c-1ff6-4dc3-916d-36ef14805188.png)

## Desktop Information
- Operating System: [Windows 11]
- Browser [chrome]
- Version [unknown]

## Additional Context
Not have additional context

**Comment by fdemir** [comment]
duplicates  #931
