### ISSUE TITLE
bug: ReturnHome button in error page does not work

### ISSUE THREAD

**Issue by selensr** [acikkaynak/deprem-yardim-frontend#941]
## Bug Definition
The returnHome button on the error page does not work

-- Please add discord contact information
** discord username: @selen#9858 **

## Bug environment
rc.afetharita.com
afetharita.com
## Describe how you are producing the bug step by step

1. afetharita.com
2. go error page
3. click returnHome
4. no action

## Expected Behaviour
should return home page

## Screen shots

https://user-images.githubusercontent.com/45594532/218432568-76a135b2-ed82-4257-b283-ffe37b50c015.mov

## Desktop Information
- Operating System: macos
- Browser : chrome
- Version : latest

**Comment by oguzergul** [comment]
i will handle this.
