### ISSUE TITLE
bug : notice type dropdown does not apply filter on the map

### ISSUE THREAD

**Issue by emre-turhan-ty** [acikkaynak/deprem-yardim-frontend#944]
## Bug Definition
When you choose the 3rd notice type on the left 3 filters on the map it does not apply any filter on the map.
![image](https://user-images.githubusercontent.com/121560069/218439172-481d7281-de45-4e5d-92b6-57f229b0c5ea.png)

** discord username: @meturhan#9926 **

## Bug environment
rc.afetharita.com
afetharita.com
## Describe how you are producing the bug step by step

1. Go to 'afetharita.com'
2. Click 'notice dropdown filter' 
3. Map is not updated
4. Bug appears

## Expected Behaviour
The map should be updated depending on the filters.

## Screen shots
![image](https://user-images.githubusercontent.com/121560069/218439943-3a44db54-f228-430d-9116-3edcc153b303.png)

## Desktop Information
- Operating System: macOS
- Browser safari, chrome

**Comment by Rayberk** [comment]
The issues should opened in English i have translated your issue to English.

**Comment by CyhnYldz** [comment]
Have the same result

**Comment by el** [comment]
Currently it does not filter the results when "Verified" channel is selected. We are in the process of changing whole filter structure, it can be tested after that
