### ISSUE TITLE
bug: Url id is not being changed when you choose another record at the same location

### ISSUE THREAD

**Issue by sevilayerkan** [acikkaynak/deprem-yardim-frontend#947]
## Bug Definition
A clear and short text to decribe the bug.

-- Please add discord contact information
** discord username: @notDepresseDeveloper#0919 **

## Bug environment
Describe the environment produces the bug. For example:
rc.afetharita.com
afetharita.com

## Describe how you are producing the bug step by step

1. Go to afetharita.com
2. Find and Click to a location includes multiple records at the same location
3. Click on one of the buttons in 'other records' section
4. The id on the url is expected to change
5. You should have seen the bug 

## Expected Behaviour
Urls should be dynamically changed regarding to selected record.

**Comment by absolutezero13** [comment]
I have a fix for this, I'll make a pr after it's approved. @sevilayerkan

**Comment by Rayberk** [comment]
I have edited your issue a bit to make it more brief and clear.
But i think this is expected behaviour @el coded this feature and it works fine i think the id should stay static
