### ISSUE TITLE
bug: Missing content details on locations

### ISSUE THREAD

**Issue by sercanerhan** [acikkaynak/deprem-yardim-frontend#955]
## Bug Definition
There are som locations which cannot show the details about the relief request.

> -- Please add discord contact information
** discord username: @sercannerhan#0543 **

## Bug environment
> Describe the environment produces the bug. For example:
afetharita.com
## Describe how you are producing the bug step by step

1. Go to prod
2. Filter **Verified**  
3. Search for the `id:707477` by zooming in `Gaziantep`
4. Click on the location to open the drawer
5. Find the details.
6. Only the adresss information is visible and there is no  details about the request.
7. When you checked the API response, you can find the expected information in `additional_notes` (acil ısıtıcı kıyafet, battaniye ve eşofman altı lazım 14 have nar ACİL!!!)  

## Expected Behaviour
When a users clicks on the location to see the detail on relief requests, the detail abou the request should be visible with the address information (not only the address information).

## Screen shots
> If possible, add screenshots to describe your bug.
![image](https://user-images.githubusercontent.com/3420568/218486744-cc16d396-35f1-4b3f-9fc7-bd6227123070.jpeg)
![image](https://user-images.githubusercontent.com/3420568/218486803-04155303-919f-4687-b776-9b0db4ae9e1a.jpeg)

## Desktop Information
- Operating System: [for example iOS]
- Browser [for example, safari]
- Version [for example 22]

## Mobile Phone Information
- Devıce: [for example iPhone6]
- Operating System (with the version): [for example iOS8.1]
- Version [for example default browser, safari]
- Browser Version [for example 22]

## Additional Context
Add any other context about the bug here

**Comment by el** [comment]
Fixed
