### ISSUE TITLE
bug: seems like fix pushed for #931 is caused to another error

### ISSUE THREAD

**Issue by siniradam** [acikkaynak/deprem-yardim-frontend#960]
## Bug Definition
May or may not be related, sample urls provided for [bug 931](https://github.com/acikkaynak/deprem-yardim-frontend/issues/931) does not load at all, displays maintenance page.

-- Please add discord contact information
** discord username: tinman#7219 **

## Bug environment
rc.afetharita.com
afetharita.com

## Describe how you are producing the bug step by step
![Screen Recording 2023-02-13 at 9 46 23 AM](https://user-images.githubusercontent.com/3178435/218534010-e95ebafb-c1db-4e97-9cf0-9c3ef8ba80c0.gif)

## Expected Behaviour
Run

## Desktop Information
- Operating System: osx
- Browser: chrome
- Version: [for example 22]

**Comment by el** [comment]
That was a backend issue, it is fixed now
