### ISSUE TITLE
bug: When backend sends empty response frontend fails

### ISSUE THREAD

**Issue by efegurkan** [acikkaynak/deprem-yardim-frontend#963]
## Bug Definition
When we get some data from backend calls, with no response, frontend fails and renders error page. We should fix the error handling by adding better error handlers and show data even when some requests are failed.

-- Please add discord contact information
** discord username: namcojoulder#1062 **

## Bug environment
Describe the environment produces the bug. For example:
rc.afetharita.com
afetharita.com

## Describe how you are producing the bug step by step

When backend returns no response or a failed response, (we had some time period today this happened)
1. Go to "afetharita.com"
2. Wait until requests are finished 
3. You should see error page. 

## Expected Behaviour
When we have some data missing, we should show what we have instead of showing error page. We should handle error cases more gracefully and show data that are available. 

## Screen shots
If possible, add screenshots to describe your bug.

## Desktop Information
- Operating System: Debian 11
- Browser all
- Version up-to-date

## Mobile Phone Information
- Devıce: [for example iPhone6]
- Operating System (with the version): [for example iOS8.1]
- Version [for example default browser, safari]
- Browser Version [for example 22]

## Additional Context
It is not an easy to test issue, if I come up with a test plan I will add that to the issue.

**Comment by sarpremziaksu** [comment]
https://stackoverflow.com/questions/11746894/what-is-the-proper-rest-response-code-for-a-valid-request-but-an-empty-data

The error code must've been seen "204" on the screen because that means there is no content to be shown for. But if there IS a problem with the cache of our data, we will have a different discussion about that.

**Comment by utkubenli** [comment]
I was able to mock this with intercepting the calls https://prnt.sc/ed5eKRC3xYO5 Page does work and not crash
