### ISSUE TITLE
bug: Map Pinpoints Are Not Displayed 

### ISSUE THREAD

**Issue by sefadegirmenci** [acikkaynak/deprem-yardim-frontend#968]
## Bug Definition
Map on the website not showing pinpoints for any of the element other than rescue (just like the inital versions of the map). The bug is observed both in desktop and mobile. 
discord username: @sefadegirmenci#6360

## Bug environment
It is encountered in afetharita.com and rc.afetharita.com

## Describe how you are producing the bug step by step

1. Visit www.afetharita.com
2. Observe that the pinpoints are not present

## Expected Behaviour
The map should be able to display all the pinpoints.

## Screen shots
![image](https://user-images.githubusercontent.com/56880835/218579227-9da392db-7be4-47bd-9241-99d176be0413.png)

## Desktop Information
- Operating System: Windows 10
- Browser Chrome
- Version 109.0.5414.120

## Mobile Phone Information
- Devıce: Iphone X
- Operating System (with the version): IOS 15
- Browser: Safari
- Browser Version: I can check if needed

**Comment by utkubenli** [comment]
@sefadegirmenci Can you provide further information, Which pinpoints are your referring to? Screenshot is showing markers and retesting this showed that I can get markers, teleteyit, etc on the map

**Comment by sefadegirmenci** [comment]
> @sefadegirmenci Can you provide further information, Which pinpoints are your referring to? Screenshot is showing markers and retesting this showed that I can get markers, teleteyit, etc on the map

On the screenshots it only shows the heatmap for rescue calls. As far as I remember couple of days ago it was showing pinpoints for food, hospitals, accomodations, etc. Moreover, nothing changes when i select/deselect elements on the filter tab.
