### ISSUE TITLE
feat: Enhancement on Drawer

### ISSUE THREAD

**Issue by sercanerhan** [acikkaynak/deprem-yardim-frontend#969]
### User Story
As a user, I want to easily identify the type of a clicked map pin by viewing the filter type information in the drawer, so that I can quickly understand the purpose of the location I've selected on the map.

### Background

The current map drawer displays various details about the selected location, but it does not show the filter type information. This can make it difficult for users to understand the purpose of the selected location. To improve the user experience, we need to update the drawer to display the filter type information, so that users can easily identify the type of a clicked map pin and understand its purpose. This will enhance the overall usability of our application and help users to access relevant information more quickly and efficiently.
<img width="817" alt="image" src="https://user-images.githubusercontent.com/3420568/220127716-641b437c-44a0-499f-be90-f2949c4f7f77.png">

** discord username: @sercanerhan#0543 **

## Acceptance Criteria
1. The filter type information should accurately reflect the type of location represented by the map pin (e.g., if the map pin represents a hospital, the filter type should show "hospital")
2. The drawer should be able to display multiple filter types for a single map pin if necessary (e.g., if the map pin multiple reasons/filter, relief aid both, then "hospital" and "relief aid" should be displayed in the drawer).

## Extra context
> Add some extra context or screenshot pertaining to said feature request.
[Figma Design](https://www.figma.com/file/sctw6xtcdoFOfmE0gC97Ft/Afet-Harita---Afetharita.com?node-id=6207%3A36060&t=zXYtFZ71TBeO6phr-4)

**Comment by sercanerhan** [comment]
this is also related with #932

**Comment by bali-ibrahim** [comment]
- Can you aid the request with images? I think the distinction between current map details, filters, reasons are vague in your description.
- Does this require backend development?

**Comment by sercanerhan** [comment]
@oguzergul [ss from the figma design](https://www.figma.com/file/sctw6xtcdoFOfmE0gC97Ft/Afet-Harita---Afetharita.com?node-id=6362%3A32390&t=UASYdJ0WJ20HFXDu-4) has been added.

**Comment by usirin** [comment]
Let's reopen this as improvement again, but i am closing all improvements tickets for our emergency situation right now.
