### ISSUE TITLE
feat: Enhancement on map layer

### ISSUE THREAD

**Issue by senapalaa** [acikkaynak/deprem-yardim-frontend#970]
## Define your request
- Relocating the map layer button.
- In our new map design, the map layer button is expected to be at the bottom left corner of the map. 
- Some areas (Ahbap Konumları, Hastaneler, Sıcak Yemek and Teleteyit) are expected to be removed from map details. 
- Map type will stay constant.
- Map details( markers and locations) are going to be enabled by default.
 

-- fill in the line below:
**discord username: @senapalaa#6815**

## Extra context

![image](https://user-images.githubusercontent.com/124930686/218594849-a972883e-45d2-49f4-9878-b121697dbd7d.png)

![image](https://user-images.githubusercontent.com/124930686/218594896-57748760-93eb-4a86-bc82-4b4ceb15d33b.png)

**Comment by myagizmaktav** [comment]
I can take this.

**Comment by usirin** [comment]
Done with #1045
