### ISSUE TITLE
bug: Unknown error occurs when teliteyit point is clicked upon

### ISSUE THREAD

**Issue by CyhnYldz** [acikkaynak/deprem-yardim-frontend#972]
## Bug Definition
A clear and short text to decribe the bug.

-- Please add discord contact information
** discord username: Ceyhun Yıldız#6679

## Bug environment
afetharita.com
## Describe how you are producing the bug step by step

1. Go to ['.Reyhanli..'](https://afetharita.com/en?lat=36.264803180755294&lng=36.549711227417&zoom=13)
2. Open teleteyit filter yo will see two teleteyit icons
3. Click on the left one of two teleteyit icons
4. Bug appears
![Ekran görüntüsü 2023-02-14 105324](https://user-images.githubusercontent.com/111140617/218673391-aea58e3a-6c26-46bd-ad8f-60c871b3e07a.png)

## Expected Behaviour
teleteyit info opens in the drawer

## Screen shots
![Ekran görüntüsü 2023-02-14 104955](https://user-images.githubusercontent.com/111140617/218672663-5aefd162-b3d0-41fe-b1a4-dfac3f56ca48.png)

## Desktop Information
- Operating System: Windows 10
- Browser Chrome, FireFox, Edge, Brave
- Version Chrome:110.0.5481.97

## Mobile Phone Information
- Devıce: [for example iPhone6]
- Operating System (with the version): [for example iOS8.1]
- Version [for example default browser, safari]
- Browser Version [for example 22]

## Additional Context
The URL mostly opens that specific location once so make sure you get the location. if you can't reproduce the defect clear cookies or  try with other browsers.

**Comment by CyhnYldz** [comment]
Error message on console : TypeError: e.charAt is not a function
    at ef (index-9f5ec3480558e93e.js:1:11529)
    at eF (index-9f5ec3480558e93e.js:1:17769)
    at ab (framework-2c79e2a64abdb08b.js:1:61008)
    at i (framework-2c79e2a64abdb08b.js:1:119565)
    at oO (framework-2c79e2a64abdb08b.js:1:99204)
    at framework-2c79e2a64abdb08b.js:1:99071
    at oF (framework-2c79e2a64abdb08b.js:1:99078)
    at ox (framework-2c79e2a64abdb08b.js:1:95830)
    at oC (framework-2c79e2a64abdb08b.js:1:96219)
    at r4 (framework-2c79e2a64abdb08b.js:1:44869)

**Comment by absolutezero13** [comment]
this should be fixed by #967, can you test it on this pr ? @CyhnYldz

**Comment by CyhnYldz** [comment]
Fixed by #967. thanks for the update @absolutezero13

**Comment by CyhnYldz** [comment]
Will re-test after deploy.

**Comment by usirin** [comment]
Closed this as we don't wait any development on this.
