### ISSUE TITLE
bug: Can not zoom/look western and eastern side borders

### ISSUE THREAD

**Issue by sevilayerkan** [acikkaynak/deprem-yardim-frontend#974]
## Bug Definition
Can not zoom or look eastern or western side of Turkey. For the east side when zooming we can not see the europian side of Istanbul and easter than the Bursa. For the west side we can't see Van region. Also in mobile  it is the same for Blacksea.

Its not an urgent issue but it should be resolved for further emergencies.

-- Please add discord contact information
** discord username: @notdepressedeveloper# 0919 **

## Bug environment
Describe the environment produces the bug. For example:
rc.afetharita.com
afetharita.com

## Describe how you are producing the bug step by step

1. Go to map
2. Zoom in
3. Try going to most eastern or most western side 
5. Bug appears

## Expected Behaviour
We could be looking or zooming any part of the map.

## Screen shots
![8](https://user-images.githubusercontent.com/22706692/218705291-8e63efa1-9b76-488b-8288-c980ff08913b.png)
![7](https://user-images.githubusercontent.com/22706692/218705306-35a22fd4-dde1-4f5a-ba20-c20eb34ddfb0.png)

## Desktop Information
- Operating System: Windows 
- Browser Chrome, Firefox

## Mobile Phone Information
- Devıce: Android, IOS
- Version: Chrome, Safari

## Additional Context
Its not an urgent issue but it should be resolved for further emergencies.

**Comment by absolutezero13** [comment]
tested, I also experienced same thing, can start working after approval.

**Comment by absolutezero13** [comment]
@sevilayerkan after looking around a little while I see that almost all of the points in Istanbul are pointing different cities (Hatay, Adıyaman etc.) and addresses are irrelevant . I'm not sure if we should even include it @sevilayerkan

**Comment by sevilayerkan** [comment]
@absolutezero13 I assumed we are developing this app to be available when ever our country needs it. if it is specific just to this disaster you are right. but if it will be in use for future disasters this app will be useless.

**Comment by sevilayerkan** [comment]
Hello, I glad you have the fix for that. There are also many pins for helping the people in need (for example you can check out the physiotherapy pin in Artvin). 
In additon please don't get attached to current pins. we all know there will be new pins in the next event and our map won't be able to show them. my concern isn't for today. it is for future uses. @absolutezero13

**Comment by sevilayerkan** [comment]
As test team we checked your last pr in vercel. We really liked and appreciate your efforts. Thank you all ❤️

**Comment by sevilayerkan** [comment]
Will be fixed by deploy of #985. Issue can be closed now
