### ISSUE TITLE
[Feature] canlı yayın akışını takip etmek

### ISSUE THREAD

**Issue by mertcanaltin** [acikkaynak/deprem-yardim-frontend#98]
merhaba bu dataların yanı sıra canlı yayın akışının da olduğu bir sağ sidebar veya ayrı bir yapı iyi bir özellik olur mu ? @ozcanzaferayan @eraygundogmus  demo : https://emergency-tv.vercel.app/

**Comment by mehmetranas** [comment]
Guzel bir fikir ama pil optimizasyonu bakimindan sorun olmaz mi?

**Comment by eraygundogmus** [comment]
discord genel kanallardan ürün tarafıyla konuşsak?
