### ISSUE TITLE
bug: In pharmacy pin numbers is coming wrong 

### ISSUE THREAD

**Issue by sevilayerkan** [acikkaynak/deprem-yardim-frontend#984]
## Bug Definition
While checking pharmacies pin number looks wrong. When if there is even only one pharmacy on that spot we are seeing 4 or even more in number tag.

-- Please add discord contact information
** discord username: `notDepresseDeveloper#0919` **

## Bug environment
rc.afetharita.com

## Describe how you are producing the bug step by step

1. Go to rc.afetharita.com
2. Filter pharmacies
3. Look for pharmacy regions
4. Zoom in to see real pharmacy size in that spot

## Expected Behaviour
Pin count tag should be seen correctly

## Screen shots
![image](https://user-images.githubusercontent.com/22706692/218783613-2dbede07-ca5f-4803-a7f9-c5232480833a.png)

## Desktop Information
- Operating System: [for example iOS]
- Browser [for example, safari]
- Version [for example 22]

## Mobile Phone Information
- Devıce: [for example iPhone6]
- Operating System (with the version): [for example iOS8.1]
- Version [for example default browser, safari]
- Browser Version [for example 22]

## Additional Context
Add any other context about the bug here

**Comment by CyhnYldz** [comment]
![Ekran görüntüsü 2023-02-14 182608](https://user-images.githubusercontent.com/111140617/218783769-cf39d4cd-5952-47b1-8992-e7bf274278b8.png)
![Ekran görüntüsü 2023-02-14 182631](https://user-images.githubusercontent.com/111140617/218783784-6bb922e1-8fa9-429e-9898-c2f2f98adc48.png)

**Comment by oguzergul** [comment]
I have tested this issue. this is not a bug and not happening in every location. some pharmacy locations have the exact same locations. so they are overlapping. @sevilayerkan @CyhnYldz
