### ISSUE TITLE
feat: Map Screenshot. To implement maps.afetbilgi.com to afetharita.com

### ISSUE THREAD

**Issue by isaozler** [acikkaynak/deprem-yardim-frontend#989]
## Define your request
As we have discussed with @usirin, the screenshot feature is crucial to replace the maps.afetbilgi.com map with afetharita.com. This is an important feature that the users are currently using.

-- fill in the line below:
** discord username: @isaozler#4498 **

## Define the alternatives you have in mind
We have agreed (with afetbilgi and the front-end) to add a camera icon in the toolbar where we also have the zoom and help buttons.

This feature will be based on the native Web Screen Capture API.  

## Extra context
![image](https://user-images.githubusercontent.com/1378630/218816942-29e58a8e-01bb-45df-87e4-050faf003439.png)

into

![image](https://user-images.githubusercontent.com/1378630/218817268-6dc947bd-0c84-49cd-a848-1a43cc207fc5.png)

**Comment by absolutezero13** [comment]
I'll start working on it

**Comment by oguzergul** [comment]
We have discussed this issue and decided to not implement this.
