### ISSUE TITLE
bug: Safe places and hotels button is not visible

### ISSUE THREAD

**Issue by sevilayerkan** [acikkaynak/deprem-yardim-frontend#995]
## Bug Definition
Safe places and hotels button is not visible. When left drawer menu is open, there is an extra icon button that can't be seen in viewport.

-- Please add discord contact information
** discord username: `notDepresseDeveloper#0919` **

## Bug environment
For pr #983
https://deprem-yardim-frontend-6wyrwo0i7-afet.vercel.app/

## Describe how you are producing the bug step by step

1. Go to ['...'](https://deprem-yardim-frontend-6wyrwo0i7-afet.vercel.app/)
2. Click layer button
3. Bug appears

## Expected Behaviour
Safe places and hotels button should be seen

## Screen shots
![image](https://user-images.githubusercontent.com/22706692/218861911-0f1a7d53-6757-4b56-9ad2-d07673ff1920.png)

## Desktop Information
- Operating System: [for example iOS]
- Browser [for example, safari]
- Version [for example 22]

## Mobile Phone Information
- Devıce: [for example iPhone6]
- Operating System (with the version): [for example iOS8.1]
- Version [for example default browser, safari]
- Browser Version [for example 22]

## Additional Context
Add any other context about the bug here

**Comment by absolutezero13** [comment]
I don't think this is related to https://github.com/acikkaynak/deprem-yardim-frontend/pull/985, is there a mistake @sevilayerkan

**Comment by sevilayerkan** [comment]
@absolutezero13 I'm really sorry for disturbance it should be #983

**Comment by senapalaa** [comment]
When I check from https://afetharita.com eveything seem fine to me, I'll add the ss below.

![image](https://user-images.githubusercontent.com/124930686/219484643-dd70b709-5040-4946-974a-82f1f105c98e.png)

**Comment by absolutezero13** [comment]
@senapalaa because satellite layer is removed, it was adding one more row.

**Comment by senapalaa** [comment]
@absolutezero13 so I will add the label "wontfix". Is it okay?

**Comment by oguzergul** [comment]
I am closing this issue. because our new design will fix this. we don't set different layers anymore.
